-- Migration 031b — seed the editorial_queue with curated vibe-check polls.
-- 12 per language × 8 languages. publish_daily_editorial() drips one per
-- language per day (cron, 09:00 UTC). Idempotent: only seeds when empty.

insert into public.editorial_queue (lang, question, options, topics, sort)
select v.lang, v.question, v.options, v.topics, v.sort
from (values
  ('fr','Pizza ou tacos ?',ARRAY['Pizza','Tacos'],ARRAY['food'],1),
  ('fr','L''ananas sur la pizza : crime ou génie ?',ARRAY['Crime','Génie'],ARRAY['food','debat'],2),
  ('fr','Ton crush like la story de son ex. Tu fais quoi ?',ARRAY['Je zappe','Je stalke','Je confronte'],ARRAY['couple','drama'],3),
  ('fr','Premier date : qui paie ?',ARRAY['Celui qui invite','On partage','Pile ou face'],ARRAY['couple','money'],4),
  ('fr','Perdre ton tel 1 semaine ou tes potes te ghostent 1 semaine ?',ARRAY['Le tel','Les potes'],ARRAY['tech','ado'],5),
  ('fr','La soirée parfaite un vendredi ?',ARRAY['Sortir en boîte','Ciné canapé','Resto entre potes'],ARRAY['lifestyle'],6),
  ('fr','Snap streak cassée : c''est grave ?',ARRAY['Méga grave','Osef total'],ARRAY['tech','ado'],7),
  ('fr','La meilleure saison, sans débat ?',ARRAY['Été','Hiver','Automne'],ARRAY['debat','lifestyle'],8),
  ('fr','Tu gagnes 1000 balles maintenant. Tu fais quoi ?',ARRAY['Je claque tout','J''épargne','Moitié-moitié'],ARRAY['money'],9),
  ('fr','Texto laissé en vu pendant 3h. Ta réaction ?',ARRAY['Tranquille','Un peu vexé','Fin du monde'],ARRAY['couple','drama'],10),
  ('fr','Le matin, ton carburant c''est ?',ARRAY['Café','Rien, juste la vibe','Thé'],ARRAY['food','lifestyle'],11),
  ('fr','Le pire red flag en couple ?',ARRAY['Toujours sur son tel','Jaloux','Radin'],ARRAY['couple','debat'],12),

  ('en','Pizza or tacos?',ARRAY['Pizza','Tacos'],ARRAY['food'],1),
  ('en','Pineapple on pizza: crime or genius?',ARRAY['Crime','Genius'],ARRAY['food','debat'],2),
  ('en','Your crush likes their ex''s story. You...',ARRAY['Ignore it','Stalk hard','Confront them'],ARRAY['couple','drama'],3),
  ('en','First date: who pays?',ARRAY['Whoever asked','Split it','Flip a coin'],ARRAY['couple','money'],4),
  ('en','Lose your phone for a week or friends ghost you for a week?',ARRAY['The phone','The friends'],ARRAY['tech','ado'],5),
  ('en','Perfect Friday night?',ARRAY['Out clubbing','Movie on the couch','Dinner with friends'],ARRAY['lifestyle'],6),
  ('en','Snap streak just broke. How bad is it?',ARRAY['Devastating','Who cares'],ARRAY['tech','ado'],7),
  ('en','Best season, no debate?',ARRAY['Summer','Winter','Fall'],ARRAY['debat','lifestyle'],8),
  ('en','You get $1000 right now. You...',ARRAY['Spend it all','Save it','Half and half'],ARRAY['money'],9),
  ('en','Left on read for 3 hours. Your reaction?',ARRAY['Totally chill','Mildly hurt','End of the world'],ARRAY['couple','drama'],10),
  ('en','Your morning fuel?',ARRAY['Coffee','Nothing, just vibes','Tea'],ARRAY['food','lifestyle'],11),
  ('en','Worst relationship red flag?',ARRAY['Always on their phone','Jealous','Cheap'],ARRAY['couple','debat'],12),

  ('es','¿Pizza o tacos?',ARRAY['Pizza','Tacos'],ARRAY['food'],1),
  ('es','¿Piña en la pizza: crimen o genialidad?',ARRAY['Crimen','Genialidad'],ARRAY['food','debat'],2),
  ('es','Tu crush le da like a la historia de su ex. ¿Tú...?',ARRAY['Lo ignoro','Stalkeo fuerte','Le encaro'],ARRAY['couple','drama'],3),
  ('es','Primera cita: ¿quién paga?',ARRAY['Quien invitó','A medias','Cara o cruz'],ARRAY['couple','money'],4),
  ('es','¿Perder el móvil una semana o que tus amigos te ignoren una semana?',ARRAY['El móvil','Los amigos'],ARRAY['tech','ado'],5),
  ('es','¿El viernes perfecto?',ARRAY['Salir de fiesta','Peli en el sofá','Cena con amigos'],ARRAY['lifestyle'],6),
  ('es','Se rompió la racha de Snap. ¿Qué tan grave es?',ARRAY['Devastador','Me da igual'],ARRAY['tech','ado'],7),
  ('es','¿La mejor estación, sin debate?',ARRAY['Verano','Invierno','Otoño'],ARRAY['debat','lifestyle'],8),
  ('es','Te dan 1000 euros ahora mismo. ¿Tú...?',ARRAY['Lo gasto todo','Lo ahorro','Mitad y mitad'],ARRAY['money'],9),
  ('es','Te dejan en visto 3 horas. ¿Tu reacción?',ARRAY['Tranqui total','Algo dolido','Fin del mundo'],ARRAY['couple','drama'],10),
  ('es','Por la mañana, tu combustible es...',ARRAY['Café','Nada, solo vibes','Té'],ARRAY['food','lifestyle'],11),
  ('es','¿El peor red flag en una relación?',ARRAY['Siempre con el móvil','Celoso','Tacaño'],ARRAY['couple','debat'],12),

  ('it','Pizza o tacos?',ARRAY['Pizza','Tacos'],ARRAY['food'],1),
  ('it','Ananas sulla pizza: crimine o genio?',ARRAY['Crimine','Genio'],ARRAY['food','debat'],2),
  ('it','La tua crush mette like alla storia dell''ex. Tu...',ARRAY['Lascio stare','Stalkero forte','Lo affronto'],ARRAY['couple','drama'],3),
  ('it','Primo appuntamento: chi paga?',ARRAY['Chi ha invitato','Si divide','Testa o croce'],ARRAY['couple','money'],4),
  ('it','Perdere il telefono per una settimana o gli amici ti ghostano per una settimana?',ARRAY['Il telefono','Gli amici'],ARRAY['tech','ado'],5),
  ('it','Il venerdì sera perfetto?',ARRAY['Serata in discoteca','Film sul divano','Cena con gli amici'],ARRAY['lifestyle'],6),
  ('it','Snap streak interrotta. Quanto è grave?',ARRAY['Devastante','Chi se ne frega'],ARRAY['tech','ado'],7),
  ('it','La stagione migliore, senza discussioni?',ARRAY['Estate','Inverno','Autunno'],ARRAY['debat','lifestyle'],8),
  ('it','Ti danno 1000 euro adesso. Tu...',ARRAY['Spendo tutto','Risparmio','Metà e metà'],ARRAY['money'],9),
  ('it','Messaggio visualizzato e ignorato per 3 ore. La tua reazione?',ARRAY['Tutto tranquillo','Un po'' ferito','Fine del mondo'],ARRAY['couple','drama'],10),
  ('it','La mattina, il tuo carburante è...',ARRAY['Caffè','Niente, solo vibes','Tè'],ARRAY['food','lifestyle'],11),
  ('it','Il peggior red flag in una relazione?',ARRAY['Sempre al telefono','Geloso','Tirchio'],ARRAY['couple','debat'],12),

  ('pt','Pizza ou tacos?',ARRAY['Pizza','Tacos'],ARRAY['food'],1),
  ('pt','Ananás na pizza: crime ou genialidade?',ARRAY['Crime','Genialidade'],ARRAY['food','debat'],2),
  ('pt','O teu crush curte a story do ex. Tu...',ARRAY['Ignoro','Stalkeio tudo','Confronto'],ARRAY['couple','drama'],3),
  ('pt','Primeiro encontro: quem paga?',ARRAY['Quem convidou','Dividir','Cara ou coroa'],ARRAY['couple','money'],4),
  ('pt','Perder o telemóvel uma semana ou os amigos ignorarem-te uma semana?',ARRAY['O telemóvel','Os amigos'],ARRAY['tech','ado'],5),
  ('pt','A sexta-feira perfeita?',ARRAY['Sair à noite','Filme no sofá','Jantar com amigos'],ARRAY['lifestyle'],6),
  ('pt','Snap streak quebrou. Quão grave é?',ARRAY['Devastador','Quem se importa'],ARRAY['tech','ado'],7),
  ('pt','A melhor estação, sem debate?',ARRAY['Verão','Inverno','Outono'],ARRAY['debat','lifestyle'],8),
  ('pt','Ganhas 1000 euros agora. Tu...',ARRAY['Gasto tudo','Poupo','Metade e metade'],ARRAY['money'],9),
  ('pt','Deixado em visto por 3 horas. A tua reação?',ARRAY['Super tranquilo','Um pouco magoado','Fim do mundo'],ARRAY['couple','drama'],10),
  ('pt','De manhã, o teu combustível é...',ARRAY['Café','Nada, só vibes','Chá'],ARRAY['food','lifestyle'],11),
  ('pt','O pior red flag numa relação?',ARRAY['Sempre no telemóvel','Ciumento','Forreta'],ARRAY['couple','debat'],12),

  ('de','Pizza oder Tacos?',ARRAY['Pizza','Tacos'],ARRAY['food'],1),
  ('de','Ananas auf Pizza: Verbrechen oder Genie?',ARRAY['Verbrechen','Genie'],ARRAY['food','debat'],2),
  ('de','Dein Crush liked die Story vom Ex. Du...',ARRAY['Ignorieren','Hart stalken','Ansprechen'],ARRAY['couple','drama'],3),
  ('de','Erstes Date: wer zahlt?',ARRAY['Wer eingeladen hat','Aufteilen','Münzwurf'],ARRAY['couple','money'],4),
  ('de','Handy eine Woche verlieren oder Freunde ghosten dich eine Woche?',ARRAY['Das Handy','Die Freunde'],ARRAY['tech','ado'],5),
  ('de','Der perfekte Freitagabend?',ARRAY['Feiern gehen','Film auf der Couch','Essen mit Freunden'],ARRAY['lifestyle'],6),
  ('de','Snap-Streak gerissen. Wie schlimm ist es?',ARRAY['Verheerend','Egal'],ARRAY['tech','ado'],7),
  ('de','Die beste Jahreszeit, keine Diskussion?',ARRAY['Sommer','Winter','Herbst'],ARRAY['debat','lifestyle'],8),
  ('de','Du bekommst jetzt 1000 Euro. Du...',ARRAY['Alles ausgeben','Sparen','Halbe-halbe'],ARRAY['money'],9),
  ('de','3 Stunden auf gelesen gesetzt. Deine Reaktion?',ARRAY['Total entspannt','Etwas verletzt','Weltuntergang'],ARRAY['couple','drama'],10),
  ('de','Dein Treibstoff am Morgen?',ARRAY['Kaffee','Nichts, nur Vibes','Tee'],ARRAY['food','lifestyle'],11),
  ('de','Die schlimmste Red Flag in einer Beziehung?',ARRAY['Immer am Handy','Eifersüchtig','Geizig'],ARRAY['couple','debat'],12),

  ('ja','ピザ or タコス？',ARRAY['ピザ','タコス'],ARRAY['food'],1),
  ('ja','ピザにパイナップル、アリ？ナシ？',ARRAY['アリ','ナシ'],ARRAY['food','debat'],2),
  ('ja','好きな人が元カレ元カノのストーリーにいいね。どうする？',ARRAY['スルー','がっつり見る','問い詰める'],ARRAY['couple','drama'],3),
  ('ja','初デート、誰が払う？',ARRAY['誘った方','割り勘','じゃんけん'],ARRAY['couple','money'],4),
  ('ja','スマホ1週間なし or 友達に1週間既読スルー、どっち？',ARRAY['スマホなし','友達スルー'],ARRAY['tech','ado'],5),
  ('ja','最高の金曜の夜は？',ARRAY['クラブで遊ぶ','家で映画','友達とご飯'],ARRAY['lifestyle'],6),
  ('ja','スナストが途切れた。ダメージは？',ARRAY['立ち直れない','別に'],ARRAY['tech','ado'],7),
  ('ja','一番好きな季節、議論なしで？',ARRAY['夏','冬','秋'],ARRAY['debat','lifestyle'],8),
  ('ja','今1万円もらったら？',ARRAY['全部使う','貯金','半分ずつ'],ARRAY['money'],9),
  ('ja','3時間既読スルーされた。あなたの反応は？',ARRAY['全然平気','ちょっと傷つく','この世の終わり'],ARRAY['couple','drama'],10),
  ('ja','朝のエネルギー源は？',ARRAY['コーヒー','何もなし、気合い','お茶'],ARRAY['food','lifestyle'],11),
  ('ja','恋愛で一番の地雷は？',ARRAY['ずっとスマホ','嫉妬深い','ケチ'],ARRAY['couple','debat'],12),

  ('zh','披萨还是塔可？',ARRAY['披萨','塔可'],ARRAY['food'],1),
  ('zh','披萨放菠萝：犯罪还是天才？',ARRAY['犯罪','天才'],ARRAY['food','debat'],2),
  ('zh','你的暗恋对象给前任的动态点了赞。你会...',ARRAY['直接无视','疯狂偷看','当面问清楚'],ARRAY['couple','drama'],3),
  ('zh','第一次约会谁买单？',ARRAY['谁约谁付','AA制','石头剪刀布'],ARRAY['couple','money'],4),
  ('zh','一周没手机 还是 朋友已读不回你一周？',ARRAY['没手机','朋友不回'],ARRAY['tech','ado'],5),
  ('zh','完美的周五晚上？',ARRAY['出去蹦迪','在家看电影','和朋友吃饭'],ARRAY['lifestyle'],6),
  ('zh','连续互动断了。有多严重？',ARRAY['崩溃','无所谓'],ARRAY['tech','ado'],7),
  ('zh','最好的季节，没得商量？',ARRAY['夏天','冬天','秋天'],ARRAY['debat','lifestyle'],8),
  ('zh','现在给你1000块，你会...',ARRAY['全花掉','存起来','一半一半'],ARRAY['money'],9),
  ('zh','消息已读不回3小时。你的反应？',ARRAY['完全淡定','有点受伤','世界末日'],ARRAY['couple','drama'],10),
  ('zh','早上的能量来源是？',ARRAY['咖啡','啥也不喝纯靠气势','茶'],ARRAY['food','lifestyle'],11),
  ('zh','恋爱中最大的雷区？',ARRAY['一直玩手机','爱吃醋','小气'],ARRAY['couple','debat'],12)
) as v(lang, question, options, topics, sort)
where not exists (select 1 from public.editorial_queue);
