import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasEs2: SeoPage[] = [
  {
    slug: `family-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `👨‍👩‍👧`,
    title: `Encuestas familiares — 30 ideas para decidir sin dramas`,
    h1: `Encuestas familiares: decidir en familia sin montar un drama`,
    description: `30 encuestas familiares para las vacaciones, las comidas, la deco y las series. Más el método para que los suegros y los adolescentes voten sin tensión.`,
    intro: `Las decisiones familiares son las más difíciles. Todos tienen opiniones fuertes, nadie quiere ceder y los debates se ponen feos rapidísimo. moomz lo neutraliza: cada quien vota, gana la mayoría, fin de la discusión. De bonus: les enseña a los peques que democracia ≠ berrinche.`,
    sections: [
      {
        h: `Por qué las encuestas le ganan a la conversación`,
        body: `Lo clásico: 4 destinos, cada quien vota, se sigue a la mayoría. La encuesta evita el típico "siempre eliges tú". Si mamá vota A, papá B y dos adolescentes votan C y D, todos tuvieron voz y gana la mayoría.`,
      },
      {
        h: `La comida del domingo`,
        body: `¿Quién quiere qué para comer? En vez del clásico "¿qué quieres tú?" de media hora, lanza una encuesta de 4 opciones a las 11. Para el mediodía ya tienes la respuesta.`,
      },
      {
        h: `Deco / reformas`,
        body: `¿Repintar? ¿Sofá nuevo? Lanza una encuesta con opciones. Gana la mayoría. Si la suegra no está de acuerdo, así funciona el sistema: es la casa de los hijos, no la suya.`,
      },
      {
        h: `Noche de peli familiar`,
        body: `La batalla del domingo por la noche. 4 opciones: acción, comedia, drama, documental. Todos votan, se ve y ya. Se acabó el "esa ya la vi".`,
      },
    ],
    polls: [
      { q: `¿Vacaciones de verano?`, options: [`Playa en España`, `Montaña en los Pirineos`, `Ciudad en Italia`, `Camping en Francia`] },
      { q: `¿Comida del domingo?`, options: [`Restaurante`, `A domicilio`, `Cocinar`, `Cada quien lo suyo`] },
      { q: `¿Peli esta noche?`, options: [`Comedia`, `Acción`, `Animación`, `Drama`] },
      { q: `¿Color del salón?`, options: [`Blanco roto`, `Beige`, `Verde azulado`, `Verde salvia`] },
      { q: `¿Invitamos a la abuela el domingo?`, options: [`Sí`, `No, qué pereza`, `Vale, un ratito`] },
      { q: `¿Mascota para la familia?`, options: [`Perro`, `Gato`, `Conejo`, `Ninguna`] },
      { q: `¿Deporte en familia?`, options: [`Bici`, `Senderismo`, `Fútbol`, `Piscina`] },
      { q: `¿Cena de cumple de papá?`, options: [`Cervecería`, `Italiano`, `Japonés`, `En casa`] },
      { q: `¿Consola para los peques?`, options: [`Switch`, `PS5`, `Xbox`, `Ninguna`] },
      { q: `¿Plan de finde?`, options: [`Parque`, `Cine`, `Bolera`, `En casa`] },
    ],
    faq: [
      { q: `¿Cómo evito el veto de la suegra?`, a: `Vota como todos los demás. Si la dejan en minoría siempre, sus opciones no encajan con el grupo. Ese es justo el punto de la encuesta: neutralizar las voces dominantes.` },
      { q: `¿Y si los peques son muy pequeños para leer?`, a: `Léeles las opciones. Votan en tu móvil. Hasta es educativo.` },
      { q: `¿Y si hay empate?`, a: `Lanza una segunda ronda entre las 2 más votadas. O añade a una tercera persona para desempatar.` },
      { q: `¿Y si alguien se niega a votar?`, a: `Mala suerte. El resultado se decide sin esa persona. Esa es la regla.` },
    ],
    related: [`birthday-en-es`, `high-school-en-es`, `would-you-rather-en-es`, `this-or-that-es`],
    updatedAt: today,
  },
  {
    slug: `teens-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🤳`,
    title: `Encuestas para adolescentes — 30 ideas para el insti`,
    h1: `Encuestas para adolescentes: preguntas que de verdad arman debate`,
    description: `30 encuestas pensadas para adolescentes: drama, insti, ligue, retos. Lánzalas en historias de Snap o en servidores de Discord.`,
    intro: `Los adolescentes ven encuestas a diario: historias de Snap, Instagram, grupos de chat. La mayoría son básicas ("¿te gusto?"). Aquí van 30 ideas más afiladas que de verdad arman debate sin caer en el cotilleo barato.`,
    sections: [
      {
        h: `Drama sin crueldad`,
        body: `El drama funciona, pero la encuesta debe apuntar a comportamientos, no a personas. "¿Debería contarle a su amiga que su novio le pone los cuernos?" le gana a "Lea es tonta por creerle". Construye argumento y evita el acoso directo.`,
      },
      {
        h: `Encuestas del insti (con respeto)`,
        body: `"Mejor profe del año" con nombres está bien. "Peor profe" roza el acoso. Quédate en lo positivo: mejor clase, profe más divertido, asignatura más útil. Funciona también para la revista del insti.`,
      },
      {
        h: `Encuestas de ligue`,
        body: `Basadas en comportamientos: ¿le dio like a su historia, contestó rápido, qué les dijo a sus amigos? Compártelas en historia de Snap para tener la opinión de todo el insti. Mantén los casos concretos en el anonimato para que no escale.`,
      },
      {
        h: `Encuestas de retos`,
        body: `Retos de TikTok o de la vida real: "¿te apuntas a teatro?", "¿le entras a la estética Y2K?", "¿etiquetas a Camille para que lo vea?". Las encuestas se vuelven el detonante de retos en grupo.`,
      },
    ],
    polls: [
      { q: `¿Le contamos a Lea la verdad sobre su novio?`, options: [`Sí, directo`, `No es asunto nuestro`, `Guardarse el pantallazo`] },
      { q: `¿Mejor profe de este año?`, options: [`Sr. Smith`, `Sra. Martínez`, `Sr. Lee`, `Sra. Patel`] },
      { q: `¿Peor rincón del insti?`, options: [`El recreo en el gimnasio`, `La cafetería`, `Los pasillos por la mañana`, `Los baños`] },
      { q: `¿Cuánto tardas en contestar?`, options: [`Al instante`, `1h`, `Al día siguiente`, `Nunca`] },
      { q: `¿De verdad le gusta?`, options: [`Sí`, `Solo por las views`, `No, es un cualquiera`, `Mañana se ve`] },
      { q: `¿Viaje del insti?`, options: [`España`, `Italia`, `Londres`, `Mejor me quedo`] },
      { q: `¿Optativa del próximo año?`, options: [`Teatro`, `Deporte`, `Latín`, `Ninguna`] },
      { q: `¿Tendencias 2026?`, options: [`Y2K`, `Coquette`, `Streetwear`, `Vintage 90s`] },
      { q: `¿Adónde después de clase?`, options: [`McDonald's`, `El bareto`, `A mi casa`, `Al parque`] },
      { q: `¿Te saltas el próximo recreo?`, options: [`Sí`, `Depende del tiempo`, `No, es mi recreo`] },
    ],
    faq: [
      { q: `¿Es seguro para adolescentes?`, a: `Sí. Sin registro, sin datos personales. El voto es anónimo. Para las encuestas de drama, que vayan sobre comportamientos, no sobre personas.` },
      { q: `¿Se puede compartir en historia de Snap?`, a: `Sí, el sticker de enlace de Snap acepta enlaces de moomz. Tus amigos tocan y votan.` },
      { q: `¿Y el acoso?`, a: `La moderación de moomz elimina cualquier encuesta que nombre a una persona con un insulto. La mejor protección es la cultura: haz preguntas constructivas, no humillantes.` },
      { q: `¿Lo verán mis padres?`, a: `No. La encuesta es anónima y no se les avisa. Aun así, es buena idea hablarlo con ellos si tienes menos de 15.` },
    ],
    related: [`high-school-en-es`, `snapchat-poll-es`, `drama-polls-es`, `instagram-story-poll-es`],
    updatedAt: today,
  },
  {
    slug: `high-school-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🎒`,
    title: `Encuestas para el insti — 30 ideas para clase y delegados`,
    h1: `Encuestas para el instituto: para clase, Snap y delegados`,
    description: `30 encuestas para el insti: elegir excursión, tema del baile, drama de clase, delegados. Más el modo anónimo para temas delicados.`,
    intro: `El insti = más de 30 alumnos por clase, varios grupos de Snap, unos delegados que deciden cosas y drama constante. moomz se vuelve la herramienta democrática para las decisiones de clase Y el detonante de los debates de pasillo.`,
    sections: [
      {
        h: `Encuestas de clase: decidir a lo grande`,
        body: `Excursión, peli de fin de curso, tema del viaje, camiseta de clase. En vez de pasar un papel en la cafetería, lanza una encuesta de moomz y compártela en el Snap de clase. 24 h después tienes respuesta, y hasta los profes la validan leyendo los porcentajes.`,
      },
      {
        h: `Encuestas de delegados`,
        body: `Los delegados organizan eventos. Cada uno: tema del baile, sitio de la fiesta de bienvenida, candidatos a las elecciones. Lanza una encuesta para todo el insti. Democracia de verdad, mucho mejor que las rayitas en la pizarra.`,
      },
      {
        h: `Encuestas de drama de pasillo`,
        body: `Encuestas que circulan por los pasillos: pareja más mona de la clase, quien va a triunfar, quién ligará con quién en el baile. Úsalas con cabeza: que sea divertido, no humillante.`,
      },
      {
        h: `Encuestas para grupos de estudio`,
        body: `Cuando se acercan los exámenes, moomz coordina: qué tema repasamos juntos, quién hace el resumen de qué asignatura. Organización colectiva sin tener que cuadrar 30 mensajes sueltos.`,
      },
    ],
    polls: [
      { q: `¿Excursión en abril?`, options: [`Museo`, `Sitio histórico`, `La torre`, `Cine`] },
      { q: `¿Tema del baile?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Sin tema`] },
      { q: `¿Peli de fin de curso?`, options: [`Origen`, `Forrest Gump`, `Whiplash`, `La elige el profe`] },
      { q: `¿Camiseta de clase?`, options: [`Negra con lema`, `Blanca minimalista`, `De color`, `Sin camiseta`] },
      { q: `¿Pareja más mona?`, options: [`Lea y Lucas`, `Sarah y Theo`, `Cam e Inés`, `Ninguna`] },
      { q: `¿Peor hueco del horario?`, options: [`Lunes a las 8`, `Miércoles a las 17`, `Viernes a las 17`, `Martes de 16 a 18`] },
      { q: `¿Fiesta de bienvenida?`, options: [`En el insti`, `En casa de alguien`, `Bar +18`, `Sin fiesta`] },
      { q: `¿Modalidad en bachillerato?`, options: [`Matemáticas`, `Física`, `Economía`, `Historia`] },
      { q: `¿Peor asignatura?`, options: [`Matemáticas`, `Historia`, `Filosofía`, `Ninguna, todas bien`] },
      { q: `¿En qué se centra el grupo de estudio?`, options: [`Matemáticas`, `Inglés`, `Historia`, `Estudiar cada uno`] },
    ],
    faq: [
      { q: `¿Sirve para los delegados?`, a: `Sí, es la herramienta perfecta para que vote toda la clase. Suelta el enlace de moomz en el chat del insti.` },
      { q: `¿Encuestas de drama anónimas?`, a: `Sí, los votos son anónimos. Pero evita las encuestas que apuntan a una sola persona para humillarla. Moderación de moomz + sentido común.` },
      { q: `¿Los profes pueden validar el resultado?`, a: `Sí, enséñales la pantalla con los porcentajes. Es más creíble que una votación en papel.` },
      { q: `¿Encuestas entre varios institutos?`, a: `Sí, comparte el enlace en grupos de Snap de varios institutos. La encuesta funciona mientras la gente tenga el enlace.` },
    ],
    related: [`teens-en-es`, `college-en-es`, `drama-polls-es`, `discord-poll-es`],
    updatedAt: today,
  },
  {
    slug: `college-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🎓`,
    title: `Encuestas para la uni — 30 ideas para promo, novatadas y pisos`,
    h1: `Encuestas para la universidad: para clase, vida estudiantil y dramas de piso`,
    description: `30 encuestas para la uni: temas de fiesta, viaje de bienvenida, grupos de estudio, decisiones de piso. Pensadas para promos de 200 a 1000 estudiantes.`,
    intro: `La uni = más de 200 estudiantes por promo y ninguna forma nativa de votar en grupo. moomz se vuelve la herramienta democrática de la promo. Eventos de las asociaciones, viaje de bienvenida, opiniones políticas, grupos de estudio: todo pasa por un enlace compartido.`,
    sections: [
      {
        h: `Encuestas de asociaciones y junta de promo`,
        body: `Antes de cualquier evento, lanza una encuesta: tema, sitio, precio de entrada, lema de la camiseta. La asociación junta de 200 a 500 votos en 48 h y la decisión es democrática. Lo mismo para elegir delegados de clase.`,
      },
      {
        h: `Encuestas del viaje de bienvenida`,
        body: `El evento más grande del año. moomz lo gestiona desde el principio: destino (4 opciones), tema, rango de presupuesto, actividades. Hasta el "quién comparte habitación", muy útil para la logística.`,
      },
      {
        h: `Encuestas políticas (en anónimo)`,
        body: `Durante las huelgas o asambleas, las encuestas anónimas revelan la opinión real. Los grupos más ruidosos no se imponen. La junta puede enseñar el resultado para estructurar el debate.`,
      },
      {
        h: `Coordinar grupos de estudio`,
        body: `Antes de los exámenes, lanza una encuesta: quién hace el resumen de qué asignatura, dónde quedamos a estudiar. Repartir tareas por democracia le gana a 50 mensajes sueltos en Discord.`,
      },
    ],
    polls: [
      { q: `¿Destino del viaje de bienvenida?`, options: [`España`, `Italia`, `Alemania`, `Pueblos de Francia`] },
      { q: `¿Tema de la fiesta?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Sin tema`] },
      { q: `¿Precio del evento de la asociación?`, options: [`5 €`, `10 €`, `15 €`, `Gratis`] },
      { q: `¿Hacemos huelga mañana?`, options: [`Sí, totalmente`, `No, perdemos clases`, `Que se vote en la asamblea`] },
      { q: `¿Delegado de clase?`, options: [`Lea`, `Lucas`, `Theo`, `Camille`] },
      { q: `¿Fiesta el jueves o el viernes?`, options: [`Jueves`, `Viernes`, `Los dos`, `Ninguno`] },
      { q: `¿Destino Erasmus el próximo año?`, options: [`España`, `Alemania`, `Reino Unido`, `Países Bajos`] },
      { q: `¿Peor asignatura del semestre?`, options: [`Estadística`, `Economía`, `Marketing`, `Historia`] },
      { q: `¿Quedada para estudiar en grupo?`, options: [`Sí`, `No, mejor solo`, `Solo las prácticas`] },
      { q: `¿Cómo está hoy la cafetería?`, options: [`Comestible`, `Regulera`, `Mejor paso`, `Ya he pasado`] },
    ],
    faq: [
      { q: `¿Cuántos estudiantes como máximo?`, a: `Sin límite. 200, 500, 1000: todos votan a la vez.` },
      { q: `¿Cómo lo comparto en una promo grande?`, a: `Grupo de Discord, Telegram o Facebook. El enlace corto (5 caracteres) es fácil de compartir incluso de viva voz.` },
      { q: `¿Encuestas políticas anónimas?`, a: `El anonimato protege a quien vota. El resultado revela la opinión real sin exponer quién dijo qué.` },
      { q: `¿Cuenta como voto en la asamblea?`, a: `Legalmente no. Pero es un buen indicador antes del debate.` },
    ],
    related: [`high-school-en-es`, `discord-poll-es`, `teens-en-es`, `friends-en-es`],
    updatedAt: today,
  },
  {
    slug: `classroom-teacher-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🏫`,
    title: `Encuestas de clase para profes — 25 ideas`,
    h1: `Encuestas de clase para profes: votar en clase sin papel`,
    description: `25 encuestas de clase para profes: nombre de la mascota, excursión, festival de fin de curso. Herramienta democrática para primaria y secundaria.`,
    intro: `Los profes de primaria y secundaria suelen tirar de papel o de levantar la mano. Con moomz puedes hacer una encuesta a tu clase en 30 segundos: muestra el código QR en la pizarra digital y los alumnos votan en las tablets. De bonus pedagógico: aprenden lo que es una votación de verdad.`,
    sections: [
      {
        h: `Por qué hacer encuestas en clase`,
        body: `Con 7-12 años, los peques entienden lo que es votar pero casi nunca lo practican. Una encuesta semanal se vuelve un mini ritual: nombre de la mascota de clase, elegir la excursión, tema del festival de fin de curso. Resultado público, debatible y revotable.`,
      },
      {
        h: `Cómo montarlo`,
        body: `Crea la encuesta de moomz en tu móvil o PC. Muestra la pantalla en la pizarra digital. Escribe la URL de 5 caracteres en la pizarra. Los alumnos la escriben en las tablets. Votan y el resultado se ve en directo y a lo grande.`,
      },
      {
        h: `Más allá de las decisiones colectivas`,
        body: `Usa las encuestas para evaluación formativa: "¿qué frase es correcta?" con 3 opciones. Los votos anónimos revelan la comprensión real mejor que un examen en papel.`,
      },
      {
        h: `Límites y precauciones`,
        body: `No se recogen datos personales, así que es compatible con el RGPD para este uso. Comprueba la política de tu centro, pero el diseño anónimo de moomz suele encajar con las normativas educativas.`,
      },
    ],
    polls: [
      { q: `¿Nombre de la mascota de clase?`, options: [`Choco`, `Pixel`, `Tornado`, `Galleta`] },
      { q: `¿Excursión en mayo?`, options: [`Zoo`, `Museo`, `Parque natural`, `Cine`] },
      { q: `¿Libro del mes?`, options: [`La telaraña de Carlota`, `El diario de Greg`, `La casa del árbol`, `Otro`] },
      { q: `¿Tema del festival de fin de curso?`, options: [`Circo`, `Espacio`, `Jungla`, `Historia`] },
      { q: `¿Actividad del viernes por la tarde?`, options: [`Dibujar`, `Juego en grupo`, `Lectura`, `Deporte`] },
      { q: `¿Animal favorito?`, options: [`Perro`, `Gato`, `Caballo`, `León`] },
      { q: `¿Nombre del futuro pez de clase?`, options: [`Burbujas`, `Nemo`, `Doradito`, `Patata`] },
      { q: `¿Color de la camiseta de clase?`, options: [`Rojo`, `Azul`, `Verde`, `Amarillo`] },
      { q: `¿Deporte de equipo favorito?`, options: [`Fútbol`, `Baloncesto`, `Balonmano`, `Atletismo`] },
      { q: `¿Postre favorito del comedor?`, options: [`Yogur`, `Compota de manzana`, `Fruta`, `Bizcocho`] },
    ],
    faq: [
      { q: `¿Es gratis para los profes?`, a: `Sí, totalmente gratis. No hace falta versión premium para usarlo en clase.` },
      { q: `¿Los alumnos necesitan cuenta?`, a: `No. Sin registro, sin correo. Abren el enlace, votan y ya.` },
      { q: `¿Los votos son anónimos?`, a: `Sí. Incluso tú como profe solo ves porcentajes, no quién votó qué. Tranquiliza a los alumnos más tímidos.` },
      { q: `¿Se integra con la pizarra digital?`, a: `Muestra la página de la encuesta de moomz a pantalla completa. Verás cómo se actualizan los resultados en tiempo real mientras votan.` },
    ],
    related: [`teens-en-es`, `family-en-es`, `high-school-en-es`, `college-en-es`],
    updatedAt: today,
  },
  {
    slug: `coworkers-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `💼`,
    title: `Encuestas para compañeros de curro — 30 ideas para oficina y remoto`,
    h1: `Encuestas para compañeros de trabajo: para Slack, Teams y remoto`,
    description: `30 encuestas para compañeros de curro: dónde comer, sitio del offsite, café o té. Más el método para votar por Slack o Teams.`,
    intro: `Las decisiones de oficina con 8 compañeros y 8 opiniones tardan una hora y terminan en "ya lo vemos mañana". moomz en tu canal de Slack: 10 minutos después tienes respuesta. De bonus: rompe el hielo, sobre todo en remoto, donde las pausas de café no existen.`,
    sections: [
      {
        h: `Encuestas de decisión`,
        body: `Comida del viernes, offsite anual, deco de la oficina, cafetera: moomz, 4 opciones, 24 h máximo. Se acabó el "yo propongo…" perdido en el ruido de Slack.`,
      },
      {
        h: `Encuestas de cultura`,
        body: `Conoceros sin meteros en lo personal: mejor peli del año, pódcast favorito, equipo del que eres, ciudad soñada. El mejor rompehielos para equipos en remoto.`,
      },
      {
        h: `Encuestas de feedback anónimo`,
        body: `El modo anónimo de moomz es oro para la cultura de equipo: "¿las reuniones son demasiado largas?", "¿funciona lo de 3 días de teletrabajo?", "¿el café de la oficina es decente?". Recibes la verdad en vez del feedback educado cara a cara.`,
      },
      {
        h: `Encuestas de team building`,
        body: `Antes de cualquier team building: actividad (escape, deporte, gastro, creativo), duración, presupuesto. Todos participan en la decisión, no solo RR. HH. El engagement sube antes incluso de que empiece el evento.`,
      },
    ],
    polls: [
      { q: `¿Comida del viernes?`, options: [`Italiano`, `Japonés`, `Cervecería`, `Hamburguesa`] },
      { q: `¿Dónde el offsite anual?`, options: [`Montaña`, `Costa`, `En el extranjero`, `Aquí cerca`] },
      { q: `¿Funciona lo de 3 días de teletrabajo?`, options: [`Sí, perfecto`, `Más días`, `Menos días`, `100% oficina`] },
      { q: `¿Las reuniones son demasiado largas?`, options: [`Sí, clarísimo`, `Regular`, `No, están bien`] },
      { q: `¿Cambiamos el café de la oficina?`, options: [`Sí, a cambiarlo`, `No, está bien`, `Poner una máquina decente`] },
      { q: `¿Actividad de team building?`, options: [`Escape room`, `Clase de cocina`, `Deporte`, `Coctelería`] },
      { q: `¿Café virtual cada semana?`, options: [`Sí`, `No, ya hay demasiada pantalla`, `Solo los viernes`] },
      { q: `¿Hora de la reunión semanal?`, options: [`9:00`, `10:00`, `11:00`, `Por la tarde`] },
      { q: `¿Herramienta de proyectos?`, options: [`Notion`, `Asana`, `Linear`, `Seguir con Excel`] },
      { q: `¿Dónde la fiesta de despedida?`, options: [`En la oficina`, `Bar de al lado`, `Restaurante`, `Sin fiesta`] },
    ],
    faq: [
      { q: `¿Se puede compartir en Slack?`, a: `Pega el enlace de moomz. Slack muestra una vista previa rica. Tus compañeros hacen clic y votan.` },
      { q: `¿Y en Microsoft Teams?`, a: `Igual: pega el enlace en un chat o canal. Se muestra la vista previa y se vota con un clic.` },
      { q: `¿RR. HH. puede ver quién votó?`, a: `No. 100% anónimo, incluso para quien crea la encuesta. Eso es lo que la convierte en una herramienta de feedback de verdad.` },
      { q: `¿Qué encuestas evitar en el trabajo?`, a: `Política (a quién votas) y religión. Mantente neutral o positivo para que haya seguridad psicológica.` },
    ],
    related: [`team-building-en-es`, `discord-poll-es`, `family-en-es`, `birthday-en-es`],
    updatedAt: today,
  },
  {
    slug: `team-building-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Encuestas de team building — 25 ideas para antes y durante`,
    h1: `Encuestas de team building: engancha al equipo antes y durante`,
    description: `25 encuestas de team building: preparación previa, rompehielos, toma de decisiones, feedback posterior. Para equipos de 5 a 200 personas.`,
    intro: `Un team building que funciona es uno en el que la gente se sintió incluida. moomz es la herramienta perfecta: antes, sondeas las preferencias (actividad, fechas, sitio). Durante, lanzas encuestas para animar (rompehielos, retos, elecciones). Después, recoges el feedback. Sin app dedicada, solo un enlace.`,
    sections: [
      {
        h: `Fase 1: preparar el team building`,
        body: `4 encuestas seguidas (una por semana): (1) tipo de actividad, (2) fecha, (3) sitio, (4) presupuesto. Cierra con la mayoría cada vez. El equipo se siente partícipe y el engagement sube antes del evento.`,
      },
      {
        h: `Fase 2: rompehielos al arrancar el evento`,
        body: `Al empezar, lanza 3 encuestas tipo quiz divertido: "¿quién habla más en las reuniones?", "¿quién llega siempre temprano?", "¿quién trae la mejor comida?". Anónimas, divertidas, encienden la dinámica. Las opciones = los nombres del equipo (8-15 personas).`,
      },
      {
        h: `Fase 3: encuestas que sacan decisiones a la luz`,
        body: `Durante el taller, encuesta anónima "¿qué valor representa a nuestro equipo?" con 4 opciones (colaboración, innovación, rigor, cercanía). El resultado se vuelve el punto de partida de la siguiente charla.`,
      },
      {
        h: `Fase 4: feedback después del evento`,
        body: `Al final: encuesta "¿mejor actividad?" y "¿cuándo lo repetimos?". 24 h después: "puntúa el team building del 1 al 5", anónima y sincera. Mejora continua de verdad, no un Google Form que nadie abre.`,
      },
    ],
    polls: [
      { q: `¿Actividad de team building?`, options: [`Escape room`, `Clase de cocina`, `Deporte`, `Coctelería`, `Taller creativo`] },
      { q: `¿Fecha?`, options: [`Viernes 5`, `Viernes 12`, `Sábado 13`, `Más adelante`] },
      { q: `¿Sitio?`, options: [`Centro de la ciudad`, `Afueras`, `Finde fuera de la ciudad`, `Sin viajar`] },
      { q: `¿Quién habla más en las reuniones?`, options: [`Lea`, `Lucas`, `Theo`, `Anónimo`] },
      { q: `¿Mejor valor del equipo?`, options: [`Colaboración`, `Innovación`, `Rigor`, `Cercanía`] },
      { q: `¿Qué nota le pones al team building?`, options: [`5/5`, `4/5`, `3/5`, `Menos`] },
      { q: `¿Cuándo el próximo?`, options: [`En 3 meses`, `En 6 meses`, `Cada año`, `Nunca más`] },
      { q: `¿Mejor momento del año?`, options: [`El offsite`, `La fiesta de Navidad`, `La fiesta de verano`, `Ninguno`] },
      { q: `¿Cómo está el ambiente del equipo?`, options: [`Genial`, `Bien`, `Normalito`, `Hay que currárselo`] },
      { q: `Prefieres:`, options: [`Actividad física`, `Taller creativo`, `Comida en grupo`, `Fiesta`] },
    ],
    faq: [
      { q: `¿Cuántas personas como máximo?`, a: `Sin límite. 5 o 200, todo bien.` },
      { q: `¿El feedback es de verdad anónimo?`, a: `Sí. Sin correo, sin cuenta. Los votos se guardan sin identificar a quien vota. Incluso quien lo organiza solo ve porcentajes.` },
      { q: `¿Y si los juniors no votan en contra del jefe?`, a: `El anonimato es tu protección. Recálcalo: "esta encuesta es 100% anónima, vota con sinceridad". Y no preguntes en plenario: deja que voten durante la pausa.` },
      { q: `¿Y un equipo distribuido?`, a: `Perfecto: comparte el enlace de moomz en Slack o Teams. Funciona entre zonas horarias, asíncrono si hace falta.` },
    ],
    related: [`coworkers-en-es`, `discord-poll-es`, `party-en-es`, `wedding-en-es`],
    updatedAt: today,
  },
  {
    slug: `this-or-that-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `↔️`,
    title: `Preguntas esto o aquello — 100 ideas para historias y citas`,
    h1: `Esto o aquello: 100 preguntas para Insta, Snap y primeras citas`,
    description: `100 preguntas de esto o aquello. El formato de encuesta Gen Z: dos opciones, decisión al instante. Úsalo para historias, citas o test de compatibilidad.`,
    intro: `Esto o aquello: dos opciones, un toque y listo. Es el formato de encuesta con más tasa de respuesta en historias de Insta (60-80%). Perfecto para romper el hielo, para test de compatibilidad y para cadenas de historias virales.`,
    sections: [
      {
        h: `Por qué gana el esto o aquello`,
        body: `Elección binaria = cero fatiga de decisión. El cerebro decide en 0,3 segundos y pasa a la siguiente. En historias de Insta, el formato con más tasa de respuesta. Y en las primeras citas de 2026, el rompehielos por excelencia.`,
      },
      {
        h: `Cómo usarlo en moomz`,
        body: `Crea una encuesta de moomz con exactamente 2 opciones. Eso es el modo esto o aquello. Para un test completo, crea de 5 a 10 encuestas separadas y comparte cada enlace en una cadena de historias.`,
      },
      {
        h: `El método de la cadena de historias`,
        body: `Suelta 5 encuestas de esto o aquello en historias seguidas. Tus seguidores van pasando, votan cada una y te mandan sus resultados por DM. Récord de engagement. Usa el sticker nativo de Insta para 2 opciones, o moomz cuando quieras 3 o más opciones más adelante en la cadena.`,
      },
      {
        h: `Esto o aquello para una primera cita`,
        body: `10 preguntas = rompehielos perfecto. Por turnos, sin presión, te revela los gustos. Truco: empieza suave (café/té), sube a lo concreto (perro/gato, playa/montaña) y evita los temas delicados en la primera cita.`,
      },
    ],
    polls: [
      { q: `¿Café o té?`, options: [`Café`, `Té`] },
      { q: `¿Perro o gato?`, options: [`Perro`, `Gato`] },
      { q: `¿Playa o montaña?`, options: [`Playa`, `Montaña`] },
      { q: `¿Día o noche?`, options: [`Día`, `Noche`] },
      { q: `¿Pizza o hamburguesa?`, options: [`Pizza`, `Hamburguesa`] },
      { q: `¿Dulce o salado?`, options: [`Dulce`, `Salado`] },
      { q: `¿Acción o comedia?`, options: [`Acción`, `Comedia`] },
      { q: `¿iPhone o Android?`, options: [`iPhone`, `Android`] },
      { q: `¿Tranqui o discoteca?`, options: [`Tranqui`, `Discoteca`] },
      { q: `¿Verano o invierno?`, options: [`Verano`, `Invierno`] },
    ],
    faq: [
      { q: `¿Cuántas preguntas en un test?`, a: `10-20 máximo. Más allá de eso, la gente se va.` },
      { q: `¿Puedo añadir una tercera opción?`, a: `Entonces ya no es esto o aquello. Quédate estricto en 2. Para 3 o más, usa una encuesta normal de moomz.` },
      { q: `¿Es más rápido que el nativo de Insta?`, a: `El esto o aquello nativo de Insta no muestra porcentajes. moomz muestra el % en directo. Elige según lo que necesites.` },
      { q: `¿Ideas para parejas?`, a: `Todas las preguntas de perfil: café/té, serie/peli, tranqui/salir. Mira nuestra página de encuestas para parejas, tiene 50 ideas.` },
    ],
    related: [`would-you-rather-en-es`, `couple-questions-es`, `first-date-en-es`, `instagram-story-poll-es`],
    updatedAt: today,
  },
  {
    slug: `would-you-rather-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🤔`,
    title: `Preguntas qué prefieres — 100 ideas para fiestas y parejas`,
    h1: `Qué prefieres: 100 preguntas para fiestas, citas y parejas`,
    description: `100 preguntas de qué prefieres: divertidas, filosóficas, dilemas, hipotéticas. Para juegos de fiesta, primeras citas y parejas.`,
    intro: `Qué prefieres: cada opción es una mini pesadilla o un mini sueño. Tú eliges. Es el formato que genera los debates más largos de todos los juegos de fiesta. 100 preguntas, ordenadas por intensidad. Más el método para usarlas sin silencios incómodos.`,
    sections: [
      {
        h: `El formato`,
        body: `Plantea: "¿qué prefieres, X o Y?". Cuanto más radicales las opciones, más duro el debate. El punto justo: las dos opciones igual de malas (o igual de geniales). Revela las preferencias de verdad.`,
      },
      {
        h: `Nivel 1: qué prefieres divertido`,
        body: `Apto para jugar en grupo: "¿volar o ser invisible?", "¿saber el futuro o cambiar el pasado?". 10 minutos de debate, rompehielos perfecto para arrancar la noche o una reunión.`,
      },
      {
        h: `Nivel 2: qué prefieres con dilema`,
        body: `Dilemas de verdad: "¿perder el móvil 1 año o a tu perro 1 mes?", "¿cambiarte el nombre o los apellidos?", "¿50 años rico y luego pobre, o rico/pobre alternando?". Toca los valores. Mejor para grupos de amigos muy cercanos.`,
      },
      {
        h: `Nivel 3: qué prefieres en pareja`,
        body: `Con tu pareja, en plan íntimo: "¿saberlo todo de mi pasado o nada?", "¿vivir en París sin dinero o en Nueva York con mucho?". Conversación profunda sin hacer la pregunta directamente.`,
      },
    ],
    polls: [
      { q: `¿Volar o ser invisible?`, options: [`Volar`, `Invisible`] },
      { q: `¿Saber el futuro o cambiar el pasado?`, options: [`El futuro`, `El pasado`] },
      { q: `¿Perder el móvil 1 año o al perro 1 mes?`, options: [`El móvil`, `El perro`] },
      { q: `¿Cambiarte el nombre o los apellidos?`, options: [`El nombre`, `Los apellidos`] },
      { q: `¿París sin un duro o Detroit forrado?`, options: [`París sin un duro`, `Detroit forrado`] },
      { q: `¿50 años rico y luego pobre, o alternando?`, options: [`50 años rico primero`, `Alternando`] },
      { q: `¿Saberlo todo de tu ex o nada?`, options: [`Saberlo todo`, `No saber nada`] },
      { q: `¿Leer la mente o teletransportarte?`, options: [`Leer la mente`, `Teletransporte`] },
      { q: `¿Pizza todos los días o nunca más?`, options: [`Todos los días`, `Nunca más`] },
      { q: `¿Sin internet 1 mes o sin luz 1 semana?`, options: [`Sin internet`, `Sin luz`] },
    ],
    faq: [
      { q: `¿Cuántos qué prefieres en una fiesta?`, a: `5-10. Más se hace repetitivo. Intercálalos entre otros tipos de encuesta.` },
      { q: `¿Y si las opciones no están equilibradas?`, a: `Si una opción es claramente mejor, el 95% la elige y no hay debate. Un buen qué prefieres tiene dos opciones igual de atractivas o igual de poco atractivas.` },
      { q: `¿Versión apta para la familia?`, a: `Quédate en superpoderes y elecciones triviales. Salta los dilemas éticos: pueden chocar con los suegros.` },
      { q: `¿Cuántas opciones?`, a: `Estrictamente 2. Ese es el formato. Para 3 o más, usa una encuesta normal.` },
    ],
    related: [`this-or-that-es`, `couple-questions-es`, `party-en-es`, `friends-en-es`],
    updatedAt: today,
  },
  {
    slug: `drama-polls-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🍿`,
    title: `Encuestas de drama — 30 ideas para debatir en TikTok e Insta`,
    h1: `Encuestas de drama: 30 ideas como motor de debate en TikTok`,
    description: `30 encuestas de drama: situaciones de pareja, de amistad, de familia. El formato que más engagement genera en TikTok e Insta.`,
    intro: `El drama es el formato con más engagement de TikTok e Instagram. Planteas una situación moralmente ambigua, das 3 opciones de veredicto y dejas que la gente decida. El equivalente moderno de ser jurado de un juicio. Aquí van 30 ideas.`,
    sections: [
      {
        h: `El formato drama`,
        body: `Estructura: (1) la situación en 2-3 frases, (2) la pregunta moral ("¿quién se ha equivocado?"), (3) 3 opciones de veredicto. Cuanto más ambigua, más largo el debate. Salta el blanco o negro claro: la incertidumbre es lo que mueve los votos.`,
      },
      {
        h: `Drama de pareja`,
        body: `El territorio con más engagement: ghosting, el ex que vuelve, sospechas de cuernos, la pareja que sale sin avisar. Aviso: que sea genérico, no un calco de alguien cercano (riesgo de filtración).`,
      },
      {
        h: `Drama de amistad`,
        body: `"Tu amiga sale con tu ex, ¿es una traición?", "¿tiene que contarle a su amiga que su novio le pone los cuernos?". Tan adictivo como el drama de pareja, pero con menos juicio personal. Genial para grupos mixtos.`,
      },
      {
        h: `Drama de adolescentes / insti`,
        body: `Para la Gen Z: drama de clase, profe que se pasa, chivatos. Quédate en las acciones, no en los nombres. moomz puede enseñar a ver los matices morales.`,
      },
    ],
    polls: [
      { q: `Te hizo ghosting 2 meses y ahora quiere volver. ¿Contestas?`, options: [`Sí`, `Bloquear`, `Hazlo esperar`] },
      { q: `Tu amiga sale con tu ex. ¿Traición?`, options: [`Totalmente`, `Es su vida`, `Depende de cuánto tiempo estuvisteis`] },
      { q: `Vio al novio de su amiga en Tinder. ¿Se lo cuenta?`, options: [`Sí, directo`, `No es asunto suyo`, `Guardar el pantallazo y esperar`] },
      { q: `¿Invitar a tu ex a una fiesta sin avisar?`, options: [`Imperdonable`, `Da igual`, `Si al ex le parece bien`] },
      { q: `Tras una ruptura, se niega a ver a los amigos en común. ¿Vale?`, options: [`Es legítimo`, `Es un drama`, `Cada uno con lo suyo`] },
      { q: `Un profe se pasa con un castigo. ¿Qué hacéis?`, options: [`Quejarse`, `Está en su derecho`, `Depende`] },
      { q: `Un amigo sale sin invitar al grupo. ¿Qué tal?`, options: [`Traición`, `Está en su derecho`, `Depende con quién`] },
      { q: `Quitarle el novio a tu mejor amiga, ¿se puede?`, options: [`Nunca`, `Si ya rompieron`, `Si es amor de verdad`] },
      { q: `Una amiga habla mal de ti a tus espaldas. ¿La encaras?`, options: [`Directo`, `Hacer como si nada`, `Cortar el rollo`] },
      { q: `Ir a una boda sin acompañante. ¿Qué tal?`, options: [`Genial`, `Estresante`, `Si conozco a 5 o más personas`] },
    ],
    faq: [
      { q: `¿El drama es sano?`, a: `Una encuesta de drama anónima = construir argumentos morales, eso es sano. El drama con nombres e insultos = acoso, y la moderación de moomz lo elimina.` },
      { q: `¿La gente va a votar?`, a: `Sí, el formato drama alcanza 3 veces más engagement que las encuestas normales. En TikTok e Insta, lo más top.` },
      { q: `¿Es legal?`, a: `Mientras no haya nombres reales ni difamación, sí. Quédate en lo hipotético.` },
      { q: `¿Cómo saco el máximo debate?`, a: `3 opciones con una intermedia ("depende"). El sí o no da menos juego que el sí/no/depende.` },
    ],
    related: [`tiktok-poll-es`, `couple-questions-es`, `friends-en-es`, `would-you-rather-en-es`],
    updatedAt: today,
  },
  {
    slug: `icebreaker-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🧊`,
    title: `Encuestas rompehielos — 40 ideas para cualquier grupo`,
    h1: `Encuestas rompehielos: 40 preguntas para arrancar cualquier conversación`,
    description: `40 encuestas rompehielos para reuniones, primeras citas, grupos nuevos y clases. El formato que rompe el silencio incómodo en 30 segundos.`,
    intro: `Silencio incómodo en una reunión, una cita o un grupo nuevo: suelta una encuesta rompehielos. 4 opciones divertidas, 30 segundos y todos han "hablado" con su voto. La conversación arranca de nuevo con el resultado. Aquí van 40 ideas.`,
    sections: [
      {
        h: `Cuándo las encuestas rompehielos le ganan a las preguntas rompehielos`,
        body: `Una pregunta exige hablar. Una encuesta exige un toque. En un grupo de 8 donde 3 son tímidos, el rompehielos hablado significa que 5 hablan y 3 no. La encuesta significa que las 8 personas "hablan". Inclusión del 100%.`,
      },
      {
        h: `Encuestas de arranque: al empezar la reunión o el evento`,
        body: `Los mejores rompehielos: "¿cómo estás del 1 al 5?", "energía mañanera: ¿cafeína o tranqui?", "¿el mood de la semana: 🔥 o 😴?". Rápidas, divertidas, marcan el tono.`,
      },
      {
        h: `Encuestas para conoceros`,
        body: `"¿Mejor peli del año?", "¿ciudad soñada para vivir?", "¿tu comida reconfortante de siempre?". Revela los gustos sin meterse en lo personal. Perfecto para equipos nuevos o primeras citas.`,
      },
      {
        h: `Encuestas rompehielos divertidas`,
        body: `"Si fueras un snack, ¿serías…?", "superpoder: ¿volar o ser invisible?", "¿sobrevivirías 24 h sin wifi?". Las preguntas absurdas rompen la tensión más rápido que las serias.`,
      },
    ],
    polls: [
      { q: `¿Cómo estás hoy?`, options: [`🔥 genial`, `😊 bien`, `😐 normal`, `😴 cansado`] },
      { q: `¿Energía mañanera?`, options: [`Cafeína`, `Entrenar`, `Tranqui`, `Ninguna`] },
      { q: `¿Mejor peli del año?`, options: [`Dune 3`, `Avatar 4`, `Otra`, `No la he visto`] },
      { q: `¿Ciudad soñada?`, options: [`Tokio`, `Nueva York`, `París`, `Bali`] },
      { q: `¿Comida reconfortante?`, options: [`Pizza`, `Hamburguesa`, `Pasta`, `Sushi`] },
      { q: `¿Superpoder?`, options: [`Volar`, `Invisible`, `Teletransporte`, `Leer la mente`] },
      { q: `24 h sin wifi, ¿sobrevives?`, options: [`Fácil`, `Difícil`, `Lloro`, `Ya lo hago`] },
      { q: `Si fueras un snack, ¿serías?`, options: [`Patatas fritas`, `Chocolate`, `Fruta`, `Queso`] },
      { q: `¿Café o té?`, options: [`Café`, `Té`, `Matcha`, `Ninguno`] },
      { q: `¿Energía de finde?`, options: [`Aventura`, `Tranqui`, `Social`, `Solo`] },
    ],
    faq: [
      { q: `¿Sirve para equipos nuevos?`, a: `Sí: lanza 3 rompehielos en la primera reunión general. El modo anónimo deja que los tímidos "hablen".` },
      { q: `¿Y para primeras citas?`, a: `Mezcla 3-5 rompehielos entre tramos de conversación. Pero que no se convierta en un test.` },
      { q: `¿Y en clase?`, a: `Sí: al principio de curso, lanza "snack favorito", "superpoder", "destino soñado". Crea vínculo de grupo en 5 minutos.` },
      { q: `¿Y en reuniones online?`, a: `Suelta el enlace en el chat. La gente vota durante la intro aburrida. La energía se dispara cuando aparecen los resultados.` },
    ],
    related: [`this-or-that-es`, `coworkers-en-es`, `first-date-en-es`, `team-building-en-es`],
    updatedAt: today,
  },
  {
    slug: `valentines-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `💝`,
    title: `Encuestas de San Valentín — 25 ideas para parejas o crushes`,
    h1: `Encuestas de San Valentín: para parejas, crushes y solteros`,
    description: `25 encuestas de San Valentín: restaurante, regalo, confesión anónima, anti-San Valentín para solteros. Para parejas, crushes y grupos de amigos.`,
    intro: `San Valentín = 200 mensajes de WhatsApp del tipo "¿qué hacemos?". Para parejas: elegir restaurante, regalo, plan de la noche. Para solteros: encuestas anti-San Valentín con los amigos. Para crushes: confesión anónima por encuesta. Aquí van 25 ideas.`,
    sections: [
      {
        h: `Encuestas de pareja: organizar San Valentín`,
        body: `Hazle una encuesta a tu pareja: restaurante, noche en casa, escapada de finde, Netflix. Decisión democrática, sin la presión de tener que proponer. De bonus: incluye un "yo me encargo, confía en mí" para enmarcar la sorpresa dentro de las opciones.`,
      },
      {
        h: `Encuestas para solteros: anti-San Valentín`,
        body: `Solteros en grupo: "¿qué hacemos el 14 de febrero?" con opciones: noche de pelis entre 4, cena sin tíos, sesión de copas, cada uno por su lado. moomz lo zanja, sin debate de quién propone.`,
      },
      {
        h: `Encuesta anónima para tu crush`,
        body: `El movimiento clásico: mándale a tu crush una encuesta "¿qué piensas de mí?" con 4 opciones divertidas. Quien la crea queda anónimo en el enlace compartido. El juego perfecto antes de declararte.`,
      },
      {
        h: `Encuesta de regalo`,
        body: `¿Atascada entre 3 regalos? Pregúntale a sus amigos con una encuesta anónima. Respuesta en 1 h, cero estrés de "¿le gustará?".`,
      },
    ],
    polls: [
      { q: `¿Plan de San Valentín?`, options: [`Restaurante con encanto`, `Noche en casa`, `Escapada de finde`, `Netflix`] },
      { q: `¿Anti-San Valentín con los amigos?`, options: [`Noche de pelis entre 4`, `Cena`, `Sesión de copas`, `Cada uno por su lado`] },
      { q: `¿Regalo para él?`, options: [`Perfume`, `Ropa`, `Una experiencia`, `Comida casera`] },
      { q: `¿Regalo para ella?`, options: [`Joyas`, `Flores`, `Una experiencia`, `Carta + algo hecho a mano`] },
      { q: `¿Restaurante para San Valentín?`, options: [`Italiano íntimo`, `Cervecería`, `Sushi`, `Coctelería`] },
      { q: `¿Te atreves a declararte?`, options: [`Sí`, `No`, `Con una encuesta divertida`] },
      { q: `¿San Valentín a los 2 meses de relación?`, options: [`Sí`, `Demasiado pronto`, `Un detallito`] },
      { q: `¿San Valentín a los 10 años?`, options: [`Lo celebramos`, `Como siempre`, `Un regalito`] },
      { q: `¿Rosas u otras flores?`, options: [`Rosas rojas`, `Peonías`, `Tulipanes`, `Sin flores`] },
      { q: `¿Una noche sorpresa?`, options: [`Me encanta`, `Me estresa`, `Depende`] },
    ],
    faq: [
      { q: `¿Una encuesta anónima para mi crush?`, a: `Sí: moomz no identifica a quien la crea en el enlace compartido. Puedes presentarla como un juego.` },
      { q: `¿Mis amigos pueden votar sin que me identifiquen?`, a: `Sí: compártela en el grupo de chat, todo anónimo. Nada de "quién votó qué".` },
      { q: `¿Una encuesta para sentirme querido?`, a: `Lanza "descríbeme en 1 palabra" con tus amigos. 4 opciones positivas. Mira lo que sale y disfrútalo.` },
      { q: `¿Cómo organizo el anti-San Valentín?`, a: `Hazles una encuesta a tus amigos solteros. 4 opciones de plan de noche. Gana la mayoría. Menos "es que yo no quiero proponer".` },
    ],
    related: [`couple-questions-es`, `first-date-en-es`, `friends-en-es`, `party-en-es`],
    updatedAt: today,
  },
];
