import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasEs1: SeoPage[] = [
  {
    slug: `instagram-story-poll-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `📸`,
    title: `Ideas de encuestas para historias de Instagram — 50 preguntas que sí votan`,
    h1: `Ideas de encuestas para historias de Instagram: 50 preguntas que la gente sí vota`,
    description: `50 ideas de encuestas para historias de Instagram que disparan las interacciones. Olvídate del aburrido esto-o-aquello: estas preguntas sí generan conversación.`,
    intro: `El sticker de encuesta nativo de Instagram solo te deja dos opciones y se quema rapidísimo. Las cuentas que arrasan con la interacción en 2026 lanzan encuestas con varias opciones vía sticker de link: pones un enlace de moomz, tus seguidores votan con un toque, tú filtras el resultado y lo repostas. Aquí van 50 ideas que de verdad mueven la aguja.`,
    sections: [
      {
        h: `Por qué las encuestas funcionan mejor que los stickers de preguntas`,
        body: `Una encuesta exige un toque. Una pregunta exige escribir. La diferencia de fricción es 10x. Las encuestas alcanzan un 60-80% de respuesta en cuentas de lifestyle; los stickers de preguntas se quedan en un 5-15%. Usa encuestas para interacción y preguntas para recolectar contenido (convierte las respuestas en un post de seguimiento).`,
      },
      {
        h: `Cuando el sticker nativo se queda corto`,
        body: `Las encuestas nativas de Instagram te dan dos opciones. Para tres, cuatro o seis necesitas un link a una encuesta externa. moomz crea una encuesta en 10 segundos, te da una URL de 5 caracteres y tus seguidores votan sin salir del navegador de IG. Los resultados son en vivo y animados: perfectos para reposterear en la historia.`,
      },
      {
        h: `Los 5 ángulos que generan respuestas`,
        body: `1) Esto-o-aquello visual (dos fotos). 2) Predicción del día ("quién gana esta noche"). 3) Opinión polémica ("¿piña en la pizza?"). 4) Modo drama ("¿hizo bien en dejarlo en visto?"). 5) ¿Lo vale? ("¿pagarías 200 € por esto?"). Evita: cualquier cosa que suene a encuesta de marketing. La gente lo huele al instante.`,
      },
      {
        h: `Cómo convertir las encuestas en hábito`,
        body: `Guarda moomz.com en tu pantalla de inicio (instala la PWA). Una encuesta por hueco de historia. Mete siempre un CTA en el caption: "vota en la próxima historia". Verás tu tasa de respuesta subir semana tras semana.`,
      },
    ],
    polls: [
      { q: `¿Piña en la pizza?`, options: [`Sí`, `Jamás`, `Bah`] },
      { q: `¿Café de mañana o matcha?`, options: [`Café`, `Matcha`, `Ninguno`] },
      { q: `Planes de verano: ¿playa o montaña?`, options: [`Playa`, `Montaña`, `Ciudad`, `Quedarme en casa`] },
      { q: `¿Historia a diario o nunca?`, options: [`A diario`, `A veces`, `Nunca`] },
      { q: `Jeans anchos, ¿siguen molando?`, options: [`Aprobado`, `Ni de broma`, `Depende`] },
      { q: `¿Brunch o cena fuera?`, options: [`Brunch`, `Cena`, `Las dos`] },
      { q: `¿iPhone o Android en 2026?`, options: [`iPhone`, `Android`, `Me da igual`] },
      { q: `¿Responder DMs de desconocidos?`, options: [`Siempre`, `Si está bueno`, `Nunca`] },
      { q: `¿Brunch o dormir hasta tarde?`, options: [`Brunch`, `Dormir`, `Las dos`] },
      { q: `¿Vuelves al gym?`, options: [`Esta semana`, `El mes que viene`, `Nunca`] },
    ],
    faq: [
      { q: `¿Cuántas opciones puede tener una encuesta en historias?`, a: `Nativa: 2. Con un sticker de link de moomz: de 2 a 6 opciones. Se abre el link, el seguidor vota y vuelve a tu historia.` },
      { q: `¿Los votos en las encuestas de Instagram son anónimos?`, a: `No: Instagram te muestra quién votó qué. moomz es totalmente anónimo: solo porcentajes, sin identidad del votante.` },
      { q: `¿Cuánto dura una encuesta en historias?`, a: `24 h en Instagram. El link de moomz mantiene la encuesta activa de forma indefinida: vuelve a ponerlo en la historia de mañana si quieres más votos.` },
      { q: `¿Puedo ver los resultados en vivo?`, a: `Sí: moomz anima los resultados en tiempo real. Entra a tu propia encuesta y mira cómo se mueven las barras según van llegando los votos.` },
    ],
    related: [`tiktok-poll-es`, `snapchat-poll-es`, `this-or-that-es`, `would-you-rather-en-es`],
    updatedAt: today,
  },
  {
    slug: `tiktok-poll-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🎵`,
    title: `Ideas de encuestas para TikTok — 40 preguntas para el link de la bio y tus vídeos`,
    h1: `Encuestas en TikTok: 40 ideas para enganchar en tus vídeos y en el link de la bio`,
    description: `TikTok no tiene encuestas nativas. Aquí te contamos cómo los creadores consiguen votos vía el link de la bio + 40 preguntas que disparan la interacción en 2026.`,
    intro: `TikTok no incluye un sticker de encuesta nativo. Eso es un hueco, y los creadores que lo llenan con una encuesta vía link de la bio se llevan un 30-50% extra de interacción. Plantea la pregunta en el vídeo, di "vota en la bio" y usa un link de moomz. Aquí tienes la jugada.`,
    sections: [
      {
        h: `Por qué te conviene que no haya encuesta nativa`,
        body: `El diseño de TikTok prioriza el scroll. Las encuestas nativas frenarían el feed. Eso significa que los creadores que quieren feedback estructurado tienen que montárselo vía link de la bio. moomz es la versión más simple: un link de 5 caracteres, cabe en el límite de la bio, se abre al instante en el navegador.`,
      },
      {
        h: `El bucle vídeo-y-luego-encuesta`,
        body: `El vídeo parte 1 plantea la pregunta ("¿hizo bien en dejarlo en visto?") y termina con "vota en la bio". El vídeo parte 2 muestra el resultado y reacciona. Cada parte funciona como un vídeo independiente, duplicando el alcance del mismo contenido. Las cuentas top hacen este bucle cada semana.`,
      },
      {
        h: `Preguntas de drama que generan votos`,
        body: `Lo bastante vagas para debatir, lo bastante concretas para tomar partido. "¿Hizo bien en dejarlo en visto?" supera a "¿está mal dejar en visto?" por 3x en tasa de votos. El detalle narrativo es lo que engancha la pregunta.`,
      },
      {
        h: `Evita las encuestas promocionales`,
        body: `Si estás encuestando para una marca patrocinadora, dilo. Los usuarios de TikTok huelen las encuestas promo al instante y o pasan de largo o te lo cantan en comentarios. moomz sirve tanto para contenido orgánico como patrocinado, pero declararlo no es negociable.`,
      },
    ],
    polls: [
      { q: `¿Hizo bien en dejarlo en visto?`, options: [`Sí, justificado`, `No, eso es de barata`, `Depende del contexto`] },
      { q: `¿Le dices la verdad a tu amiga?`, options: [`Sí, directo`, `No es asunto mío`, `Espera a que pregunte`] },
      { q: `Quinta cita y aún sin beso, ¿raro?`, options: [`Normal`, `Raro`, `Sospechoso`] },
      { q: `¿Cuánto tardas en responder?`, options: [`Al instante`, `1-3 h`, `Al día siguiente`, `Nunca`] },
      { q: `¿Está bien stalkear a un ex?`, options: [`Obvio`, `Un poquito`, `No, tóxico`] },
      { q: `Primera cita: ¿quién paga?`, options: [`Él/ella`, `A medias`, `El chico siempre`] },
      { q: `¿Perdonar una infidelidad una vez?`, options: [`Sí`, `Jamás`, `Depende`] },
      { q: `Tinder en 2026, ¿sigue valiendo la pena?`, options: [`Sí`, `Está muerto`, `Por divertirme`] },
      { q: `¿Pasar tu Insta en la primera cita?`, options: [`Al instante`, `En la segunda cita`, `Nunca`] },
      { q: `¿Salir con alguien más joven?`, options: [`1-2 años vale`, `Hasta 5 años`, `Ni de broma`, `Sin límite`] },
    ],
    faq: [
      { q: `¿TikTok tiene encuestas nativas?`, a: `No. Puedes hacer preguntas en el vídeo o en comentarios, pero no hay ningún widget que cuente votos. Usa moomz y pon el link en la bio.` },
      { q: `¿El link de moomz funciona en la bio?`, a: `Sí: se trata como cualquier link externo. Cabe en el límite de caracteres de la bio. Los captions solo permiten links clicables para cuentas de empresa.` },
      { q: `¿Puedo usar la misma encuesta en varios vídeos?`, a: `Sí. El mismo link de moomz se puede usar en varios TikToks. O cambia de link por vídeo para tener señal fresca.` },
      { q: `¿Los votos son anónimos?`, a: `Sí. moomz nunca asocia un voto a un perfil. Tu audiencia puede responder con sinceridad sin presión social.` },
    ],
    related: [`instagram-story-poll-es`, `snapchat-poll-es`, `drama-polls-es`, `first-date-en-es`],
    updatedAt: today,
  },
  {
    slug: `snapchat-poll-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `👻`,
    title: `Ideas de encuestas para Snapchat — 30 preguntas para historias y grupos`,
    h1: `Encuestas en Snapchat: 30 ideas para historias y chats de grupo`,
    description: `Snapchat no tiene encuestas nativas. Aquí te contamos cómo añadir una a tu historia o grupo + 30 preguntas que funcionan.`,
    intro: `Snapchat no incluye encuestas. La mayoría de la gente o le manda mensajes a sus amigos pidiendo opinión o cuenta reacciones de emoji: las dos cosas son lentas. Pon un link de moomz en tu historia (con la herramienta de link) o en el grupo, llegan los votos y los resultados siguen accesibles después de que la historia caduque.`,
    sections: [
      {
        h: `Añadir un link a la historia de Snap`,
        body: `Al crear una historia, toca la herramienta del clip en el lado derecho. Pega tu URL de moomz. Tus amigos verán un botón de "Ver más". Tocan, votan en el navegador y vuelven a la historia. Cero fricción.`,
      },
      {
        h: `Encuestas en el chat de grupo`,
        body: `Pon el link en cualquier grupo. Todos ven una vista previa y pueden tocar para votar sin salir del chat. Mejor que la guerra de mensajes donde la mitad del grupo se pierde la pregunta porque estaban AFK.`,
      },
      {
        h: `Encuestas que funcionan con adolescentes`,
        body: `Top 3: "quién del grupo es…" (el más ruidoso, el más dulce, el más pesado), encuestas de decisión ("¿a dónde vamos esta noche?"), encuestas de drama ("¿se pasó él?"). Evita demasiadas opciones: los usuarios de Snapchat scrollean rapidísimo, máximo 4.`,
      },
      {
        h: `Mantenerlo en privado`,
        body: `Los links de moomz no se indexan por defecto. Solo quien tenga el link puede encontrar la encuesta. Compártelo en un grupo concreto para votos privados. No lo publiques en la página pública de historias si lo quieres bien cerrado.`,
      },
    ],
    polls: [
      { q: `¿El más ruidoso del grupo?`, options: [`Lucas`, `Sara`, `Teo`, `Lea`] },
      { q: `¿A dónde vamos esta noche?`, options: [`Bar`, `Mi casa`, `Parque`, `Quedarnos`] },
      { q: `¿Quién es el más gracioso?`, options: [`Yo, obvio`, `Tú`, `Él/ella`, `Nadie`] },
      { q: `¿Cine o bolos?`, options: [`Cine`, `Bolos`, `Ninguno`] },
      { q: `¿Quién trae las botanas?`, options: [`Yo`, `Tú`, `Pedimos`, `Las robamos`] },
      { q: `¿Le respondo a él/ella?`, options: [`Ahora`, `Mañana`, `Nunca`, `Filtra tú por mí`] },
      { q: `¿Mejor peli de 2026?`, options: [`Dune 3`, `Avatar 4`, `Otra`, `No vi ninguna`] },
      { q: `¿Quién dejó en visto primero?`, options: [`Él`, `Ella`, `Los dos a la vez`] },
      { q: `¿Equipo rojo o azul?`, options: [`Rojo`, `Azul`, `Sin equipo`] },
      { q: `¿Le decimos la verdad a Lea?`, options: [`Sí`, `No`, `Tú decides`] },
    ],
    faq: [
      { q: `¿Snapchat tiene un sticker de encuesta?`, a: `No. Usa un link de moomz en tu historia (con la herramienta del clip) o en un grupo.` },
      { q: `¿Cómo añado un link a una historia de Snap?`, a: `Mientras la creas, toca el clip en las herramientas del lado derecho. Pega la URL de moomz. Listo.` },
      { q: `¿Mis amigos necesitan una cuenta?`, a: `No. moomz funciona sin registrarse. Se abre el link, votan y se van.` },
      { q: `¿La encuesta desaparece con la historia?`, a: `No. La historia dura 24 h; la encuesta sigue activa. Vuelve a compartir el link mañana para que sigan llegando votos.` },
    ],
    related: [`instagram-story-poll-es`, `tiktok-poll-es`, `teens-en-es`, `friends-en-es`],
    updatedAt: today,
  },
  {
    slug: `discord-poll-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🎮`,
    title: `Ideas de encuestas para Discord — 30 preguntas para servidores y comunidades`,
    h1: `Encuestas en Discord: 30 ideas para activar tu servidor`,
    description: `Olvídate de configurar bots. Pon un link de moomz en cualquier canal de Discord y tu comunidad vota de forma anónima. 30 preguntas dentro.`,
    intro: `El comando de encuesta nativo de Discord está bien para votos rápidos, pero se limita a 10 opciones y a un solo servidor. Las soluciones con bot (MEE6, Simple Poll) necesitan instalación + permisos. moomz: solo pegas el link, cualquiera vota y los resultados se mantienen en vivo. Aquí te contamos cómo sacarle partido.`,
    sections: [
      {
        h: `Nativo vs bot vs link de moomz`,
        body: `/poll nativo: gratis, 10 opciones, limitado al servidor. Bots: más funciones pero instalación + permisos. moomz: instantáneo, anónimo, sin permisos, compartible más allá de Discord. Elige según tu necesidad.`,
      },
      {
        h: `Encuestas de comunidad que funcionan`,
        body: `Los mejores servidores lanzan una encuesta semanal en #votaciones: mejor build del mes (gaming), veredicto del parche, ranking de skins. Para servidores de debate: opiniones polémicas, dilemas morales, opiniones controvertidas.`,
      },
      {
        h: `Fijar la encuesta`,
        body: `Crea la encuesta, fija el mensaje en tu canal principal. Los votos siguen entrando durante días. Ciérrala con una captura del resultado y publícala en #anuncios.`,
      },
      {
        h: `Organización de eventos`,
        body: `Usa moomz para horarios de raid, noches de juego, canales nuevos. Los mods ven los resultados en vivo sin tener que escanear reacciones de emoji.`,
      },
    ],
    polls: [
      { q: `¿Juego para la próxima noche de voz?`, options: [`LoL`, `Valorant`, `Fortnite`, `Among Us`, `Minecraft`] },
      { q: `¿Mejor parche del año?`, options: [`T1`, `T2`, `T3`, `Todos malísimos`] },
      { q: `¿Qué canal nuevo añadimos?`, options: [`#memes`, `#trading`, `#arte`, `#offtopic`] },
      { q: `¿El nuevo personaje está roto?`, options: [`Sí, nerfeo`, `Equilibrado`, `Buff`, `No lo he jugado`] },
      { q: `¿Estilo de rol preferido?`, options: [`Mucho lore`, `Casual`, `Foco PvP`, `Sin rol`] },
      { q: `¿Foto del año (post de memes)?`, options: [`El doge`, `El gato`, `La rana`, `Ninguna`] },
      { q: `¿Mantenemos el sistema de niveles?`, options: [`Sí, mola`, `No, cringe`, `Reset cada mes`] },
      { q: `¿Qué bot añadimos?`, options: [`MEE6`, `Carl-bot`, `Ninguno`] },
      { q: `¿Skin favorita?`, options: [`Skin A`, `Skin B`, `Skin C`, `Default`] },
      { q: `¿Hora del raid el sábado?`, options: [`18 h`, `20 h`, `21 h`, `22 h`] },
    ],
    faq: [
      { q: `¿Necesito un bot?`, a: `No. Pega el link de moomz en cualquier canal, Discord muestra una vista previa enriquecida y los miembros tocan para votar.` },
      { q: `¿Es anónimo?`, a: `Sí. Ningún nombre de Discord va asociado a los votos. Los miembros votan sin presión social.` },
      { q: `¿Cuántas opciones?`, a: `De 2 a 6 en moomz. Más allá de eso, la tasa de votos completados cae. Para 8-12 opciones, usa el /poll nativo.` },
      { q: `¿La encuesta caduca?`, a: `No, salvo que esté inactiva durante semanas (anti-spam). Mantenla viva volviéndola a compartir.` },
    ],
    related: [`tiktok-poll-es`, `team-building-en-es`, `high-school-en-es`, `college-en-es`],
    updatedAt: today,
  },
  {
    slug: `couple-questions-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `💖`,
    title: `Preguntas de encuesta para parejas — 50 ideas para medir la compatibilidad`,
    h1: `Encuestas para parejas: 50 preguntas para hacerle a tu pareja`,
    description: `50 preguntas anónimas para parejas, desde preferencias sin riesgo hasta conversaciones serias. Mide la compatibilidad en 30 segundos.`,
    intro: `Una encuesta esquiva el filtro social. Tu pareja elige una opción en vez de adornar una respuesta. Por eso los terapeutas de pareja empezaron a recomendarlas en 2025. Aquí van 50 preguntas, ordenadas por nivel de riesgo.`,
    sections: [
      {
        h: `Por qué las encuestas ganan a la conversación`,
        body: `Dos sesgos arruinan las preguntas directas: (1) las ganas de complacer, (2) el tiempo para pensar. Las encuestas neutralizan ambos: elección binaria, clic instintivo. Sacas datos más limpios que en una conversación real.`,
      },
      {
        h: `Nivel 1: preferencias seguras`,
        body: `Empieza suave: piso en la playa o en la montaña, café o té por la mañana, salir o quedarse en casa. Crea el hábito primero. Una vez que las encuestas se sienten normales, puedes ir más a fondo.`,
      },
      {
        h: `Nivel 2: decisiones del día a día`,
        body: `¿Nos quedamos o salimos esta noche? ¿Comida china o italiana a domicilio? ¿Vemos a los suegros este finde? Las encuestas convierten debates de 30 minutos en decisiones de 30 segundos.`,
      },
      {
        h: `Nivel 3: preguntas de verdad`,
        body: `¿Boda en 5 años? ¿Hijos sí o no? ¿Mudarse al extranjero si llega la oferta? Úsalas en modo anónimo, nunca después de una pelea. La encuesta abre la conversación, no la sustituye.`,
      },
    ],
    polls: [
      { q: `¿Café en la cama o en la cocina?`, options: [`En la cama siempre`, `Cocina`, `Sin café`] },
      { q: `Vacaciones: ¿playa o montaña?`, options: [`Playa`, `Montaña`, `Las dos`, `Quedarnos`] },
      { q: `Prefieres:`, options: [`Noche tranqui en casa`, `Cena con poca gente`, `Fiestón`, `Sin preferencia`] },
      { q: `¿Boda en 5 años?`, options: [`Sí`, `Más adelante`, `No es lo mío`, `Quizás`] },
      { q: `¿Hijos?`, options: [`Sí, 1`, `Sí, 2 o más`, `Jamás`, `Sin decidir`] },
      { q: `¿Mudarte al extranjero si te lo ofrecen?`, options: [`Sí, sin dudar`, `Depende`, `No, quiero quedarme`] },
      { q: `¿Cumple sorpresa?`, options: [`Me encanta`, `Me estresa`, `Depende de quién`] },
      { q: `¿Postura para dormir?`, options: [`Abrazados`, `Lado a lado`, `Cada uno a su lado`] },
      { q: `¿Sueldo transparente en la pareja?`, options: [`Total transparencia`, `Cifras por encima`, `Privado`] },
      { q: `¿El ex en Instagram?`, options: [`Me da igual`, `Me molesta`, `Dejar de seguir juntos`] },
    ],
    faq: [
      { q: `¿Mi pareja verá que yo creé la encuesta?`, a: `No. El link compartido no muestra quién la creó. También puedes crearla de incógnito para negarlo todo.` },
      { q: `¿Podemos ver quién votó qué?`, a: `No. moomz es totalmente anónimo. Solo ves porcentajes.` },
      { q: `Solo dos votantes, ¿sigue siendo anónimo?`, a: `Técnicamente sí, pero está claro que puedes deducirlo. Suma a 2-3 amigos para un anonimato real, o úsala para respuestas reveladas.` },
      { q: `¿Cómo mantener el hábito?`, a: `Una encuesta cada noche durante una semana. 5 minutos para votar, 10 para comentar el resultado. Engancha más que el "¿qué tal tu día?".` },
    ],
    related: [`first-date-en-es`, `this-or-that-es`, `would-you-rather-en-es`, `valentines-en-es`],
    updatedAt: today,
  },
  {
    slug: `first-date-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🌹`,
    title: `Encuestas rompehielos para la primera cita — 30 preguntas para salvar el rollo`,
    h1: `Encuestas para la primera cita: 30 preguntas rompehielos que sí funcionan`,
    description: `30 encuestas rompehielos para la primera cita. Saca el móvil, lanza una votación rápida y salva la conversación del silencio incómodo.`,
    intro: `¿La primera cita se atasca a los 30 minutos? Saca el móvil, di "tengo una app tontísima, ¿la probamos?" y lanza una encuesta rápida. Los dos votan, los dos ven el resultado y se desbloquean 10 minutos de conversación nueva.`,
    sections: [
      {
        h: `Cuándo usarla (y cuándo no)`,
        body: `Buen momento: a los 30 minutos, cuando la charla trivial ya se secó. Mal momento: pidiendo las bebidas. Mala forma de presentarla: "vine con un guion". Buena forma: "acabo de descubrir esta tontería".`,
      },
      {
        h: `Encuestas de citas que funcionan`,
        body: `Evita la intimidad al principio (política, religión, exes, sexualidad). Quédate en preferencias: viajes, comida, estilo de fiesta, animales, hobbies. Guarda lo pesado para la cita 2 o 3.`,
      },
      {
        h: `El truco del voto con los ojos cerrados`,
        body: `Haz la pregunta. Los dos cierran los ojos 5 segundos. Votan por separado. Lo revelan a la vez. Elimina el efecto "votar lo que el otro quiere oír". La verdad sale más rápido.`,
      },
      {
        h: `Encuestas que evitar en la cita 1`,
        body: `Cualquier cosa que te ponga en modo juez ("¿crees que soy demasiado X?"). Encuestas trampa ("¿acabamos juntos esta noche?"). Política, religión, exes. Que sea ligero: la encuesta es un juego, no un interrogatorio.`,
      },
    ],
    polls: [
      { q: `¿Perro o gato?`, options: [`Perro`, `Gato`, `Los dos`, `Ninguno`] },
      { q: `¿Playa o montaña?`, options: [`Playa`, `Montaña`, `Ciudad`, `Aventura`] },
      { q: `Desayuno: ¿dulce o salado?`, options: [`Salado`, `Dulce`, `Los dos`, `Me lo salto`] },
      { q: `Esta noche: ¿plan ideal?`, options: [`Restaurante`, `Cine`, `Bar`, `Quedarse en casa`] },
      { q: `Karaoke, ¿te atreves o paso?`, options: [`Me encanta`, `Si bebo`, `Nunca`, `Solo a mirar`] },
      { q: `¿Cocinas?`, options: [`A menudo`, `A veces`, `Nunca`, `Lo estoy intentando`] },
      { q: `¿Qué deporte ves?`, options: [`Fútbol`, `Tenis`, `F1`, `Ninguno`] },
      { q: `Fiestas, ¿qué rollo?`, options: [`Tranqui para dos`, `Grupo pequeño`, `Fiestón`, `Solo`] },
      { q: `¿Género de peli?`, options: [`Acción`, `Comedia`, `Drama`, `Terror`] },
      { q: `¿A qué hora te levantas?`, options: [`Antes de las 7`, `7-9 h`, `9-11 h`, `Después de mediodía`] },
    ],
    faq: [
      { q: `¿No es cringe sacar una encuesta?`, a: `Solo si la presentas mal. "Tengo una tontería" funciona. Y si no cuela, ya has aprendido algo sobre la compatibilidad.` },
      { q: `¿Cuántas encuestas por cita?`, a: `3-5 máximo. Más que eso ya es un test, no una cita.` },
      { q: `Coincidimos en todo, ¿buena señal?`, a: `O genial, o los dos estáis mintiendo. Sube el nivel de riesgo en las siguientes preguntas.` },
      { q: `No coincidimos en nada, ¿es para descartar?`, a: `Casi nunca. Acabas de desbloquear 10 temas de conversación.` },
    ],
    related: [`couple-questions-es`, `valentines-en-es`, `would-you-rather-en-es`, `this-or-that-es`],
    updatedAt: today,
  },
  {
    slug: `friends-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Ideas de encuestas para el grupo de amigos — 50 preguntas para chats e IRL`,
    h1: `Encuestas para el grupo de amigos: 50 ideas para decidir y debatir`,
    description: `50 encuestas para tu grupo de amigos: decisiones, rankings, debates. Úsalas en WhatsApp, Discord o en fiestas IRL.`,
    intro: `Tu grupo tiene dos modos: decisión (¿dónde comemos?) y debate (¿quién es el más ruidoso?). Las encuestas arreglan los dos. Pones un link de moomz, marcas un límite de 1 hora, capturas el resultado. Se acabó el peaje del scroll en WhatsApp.`,
    sections: [
      {
        h: `Encuestas de decisión: mata el ruido del chat`,
        body: `¿Dónde comemos? ¿Qué peli? ¿Qué viaje? Sin encuesta: 30 mensajes, la mitad ignorados. Con encuesta: 5 minutos y listo. Truco: anuncia un límite ("la votación cierra a las 19 h").`,
      },
      {
        h: `Encuestas de ranking: oro puro de comedia`,
        body: `Rankings del grupo: el más ruidoso, el más dulce, el más probable de dejar en visto. Votos anónimos, honestidad brutal. Guárdalo para grupos de amigos que aguanten la quemada.`,
      },
      {
        h: `Encuestas de debate: opiniones polémicas`,
        body: `"¿El cilantro es del demonio?", "¿piña en la pizza?", "¿el grupo está demasiado activo?". No va de resolver nada, va de descubrir cómo se divide tu grupo.`,
      },
      {
        h: `Encuestas para cumpleaños sorpresa`,
        body: `¿Planeas un cumple sorpresa? Crea un subgrupo sin la persona del cumple y lanza ahí todas las encuestas. moomz no avisa a nadie: cero filtraciones.`,
      },
    ],
    polls: [
      { q: `¿Quién es el más ruidoso esta noche?`, options: [`Lucas`, `Sara`, `Teo`, `Lea`] },
      { q: `¿Dónde el viernes?`, options: [`El bar de siempre`, `Sitio nuevo`, `Mi casa`, `Restaurante`] },
      { q: `¿Regalo de cumple para Lea?`, options: [`Flores`, `Cena`, `Tarjeta de Amazon`, `Bote común`] },
      { q: `¿Quién nunca trae nada?`, options: [`Teo`, `Camila`, `Yo (lo asumo)`, `Todos pagan`] },
      { q: `¿Piña en la pizza?`, options: [`Sí`, `Jamás`, `Bah`] },
      { q: `¿Escapada de finde?`, options: [`Costa`, `Montaña`, `Ciudad`, `Quedarnos`] },
      { q: `¿Temática de la fiesta del viernes?`, options: [`Y2K`, `Pijama`, `Disco`, `Sin temática`] },
      { q: `¿Invitamos a Marc?`, options: [`Sí`, `No, bah`, `Si Lea está OK`] },
      { q: `¿Las copas a qué hora?`, options: [`18 h`, `19 h`, `20 h`, `Tarde`] },
      { q: `¿Quién paga el Uber?`, options: [`Bote`, `El primero en entrar`, `Cada uno el suyo`] },
    ],
    faq: [
      { q: `¿Los amigos verán quién creó la encuesta?`, a: `No. Tanto quien la crea como quien vota son anónimos en el link compartido.` },
      { q: `¿Cuántos amigos pueden votar?`, a: `Sin límite. 4 o 400, funciona.` },
      { q: `¿Cómo cierro la votación?`, a: `No hay cierre manual. Anuncia un límite, captura el resultado al llegar la hora y dala por cerrada.` },
      { q: `¿Y si alguien vota dos veces?`, a: `No puede. moomz bloquea los votos duplicados vía cookie. Una persona = un voto.` },
    ],
    related: [`bff-en-es`, `party-en-es`, `drama-polls-es`, `would-you-rather-en-es`],
    updatedAt: today,
  },
  {
    slug: `bff-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `👯`,
    title: `Preguntas de encuesta para tu BFF — 30 ideas para poner a prueba a tu mejor amiga`,
    h1: `Encuestas para BFF: 30 preguntas para poner a prueba el vínculo con tu mejor amiga`,
    description: `30 encuestas anónimas para comprobar cuánto conoces a tu BFF, y cuánto te conoce ella a ti. Sinceras, divertidas y a veces brutales.`,
    intro: `Crees que os conocéis de pe a pa. ¿En serio? 30 encuestas para poner a prueba el vínculo: divertidas, íntimas y a veces brutales. El modo anónimo significa respuestas sinceras, sin retoques diplomáticos.`,
    sections: [
      {
        h: `Formato quiz de BFF`,
        body: `Crea 10 encuestas y comparte los links con tu BFF. Las dos votáis por separado y comparáis al día siguiente. Le gana al típico quiz de BFF de Insta porque las respuestas son anónimas: sin presión de dar la respuesta "correcta".`,
      },
      {
        h: `Preguntas que de verdad revelan algo`,
        body: `Olvídate de lo obvio (color favorito). Sube al nivel 2: quién es más pesada, quién paga más, quién juzga mejor a los exes. Aprieta más: quién es más celosa, quién sobreviviría si la otra la dejara en visto.`,
      },
      {
        h: `Cumpleaños sorpresa vía encuesta`,
        body: `Para su cumple, lanza una encuesta "¿qué describe mejor a Lea?" con el grupo. Opciones: "siempre llega tarde", "la más graciosa", "siempre paga". Captura el resultado y mándaselo como una tarjeta. Pega más fuerte que un "feliz cumple".`,
      },
      {
        h: `Compatibilidad BFF`,
        body: `5 encuestas sobre dilemas: "perder el viaje o perder al chico", "decirle que su novio le pone los cuernos o callarse", "prestar 500 € que no volverás a ver o decir que no". Mides cuánto creéis estar alineadas.`,
      },
    ],
    polls: [
      { q: `¿Quién paga más a menudo?`, options: [`Yo`, `Tú`, `Al 50%`] },
      { q: `¿Quién llega tarde más a menudo?`, options: [`Yo`, `Tú`, `Igual`] },
      { q: `¿Quién es más graciosa?`, options: [`Yo, obvio`, `Tú`, `Empate`] },
      { q: `¿Le cuentas lo de su novio?`, options: [`Sí, directo`, `No es asunto nuestro`, `Depende`] },
      { q: `Si te dejara en visto, ¿qué harías?`, options: [`Llorar una semana`, `Pasar página en 2 meses`, `Ir a buscarte`] },
      { q: `¿Quién es más celosa?`, options: [`Yo`, `Tú`, `Ninguna`] },
      { q: `¿Quién es más leal?`, options: [`Yo`, `Tú`, `Al 50%`] },
      { q: `¿Restaurante por el que pelearíamos?`, options: [`Sushi`, `Italiano`, `Hamburguesas`, `Vegano`] },
      { q: `Viaje juntas: ¿el principal choque?`, options: [`Horarios`, `Dinero`, `Música`, `Somos perfectas`] },
      { q: `Si pudieras cambiarme una cosa, ¿cuál?`, options: [`Mi vagancia`, `Mis celos`, `Mis monólogos`, `Nada`] },
    ],
    faq: [
      { q: `¿Mi BFF sabrá que la creé yo?`, a: `Sí, si se la mandas directamente. Para probarla a través del grupo, el anonimato se mantiene.` },
      { q: `¿Idea para regalo de cumple?`, a: `Lanza 5 encuestas "¿quién describe mejor a Lea?" al grupo. La captura final es un regalo majo.` },
      { q: `¿Quiz conjunto?`, a: `Sí: cada una crea 5 encuestas, intercambiáis links, las dos respondéis 10 y comparáis.` },
      { q: `¿Y si la respuesta duele?`, a: `Es el riesgo del juego. Si quieres saberlo, vota. Si no, no crees la encuesta.` },
    ],
    related: [`friends-en-es`, `party-en-es`, `would-you-rather-en-es`, `drama-polls-es`],
    updatedAt: today,
  },
  {
    slug: `party-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🎉`,
    title: `Ideas de encuestas para fiestas — 40 preguntas para animar cualquier noche`,
    h1: `Encuestas para fiestas: 40 ideas para fiestas en casa y afters`,
    description: `40 encuestas de fiesta para soltar en el grupo: rompehielos, rankings, debates. Desde el principio de la noche hasta la decisión de las 3 de la mañana.`,
    intro: `Las fiestas que funcionan tienen algo en común: un tema sobre el que discutir. Las encuestas son un detonante de debate al instante. Suelta la pregunta, todos votan y dos minutos después estáis discutiendo cómo es posible que alguien elija eso.`,
    sections: [
      {
        h: `Principio de la noche: encuestas rompehielos`,
        body: `Cuando la gente todavía está en grupitos sueltos, suelta una encuesta en el grupo. "¿Quién llega tarde esta noche?", "¿qué picamos?". Engancha a todo el grupo en una sola conversación.`,
      },
      {
        h: `A media noche: encuestas de ranking`,
        body: `Hacia las 22 h, suelta el ranking del grupo de amigos. "¿Quién es el más pesado?", "¿quién nunca trae nada?". El debate dura 30 minutos. Aviso: honestidad brutal, solo para grupos que lo aguanten.`,
      },
      {
        h: `De madrugada: encuestas de debate`,
        body: `La 1 de la mañana, la mitad del grupo se fue. Los supervivientes quieren conversación de la buena. Suelta opiniones filosóficas polémicas: "¿la relación abierta es válida?", "¿hay que volver a hablar con un ex alguna vez?". Se mantiene tranquilo y reactiva la energía.`,
      },
      {
        h: `Las 3 de la mañana: encuestas de decisión`,
        body: `¿Dónde nos quedamos a dormir? ¿Pedimos pizza? ¿Lo dejamos? Lanza una encuesta de 30 segundos y haz caso al resultado. El único momento de la noche en que todos respetan el veredicto porque nadie tiene energía para volver a debatir.`,
      },
    ],
    polls: [
      { q: `¿Qué pedimos?`, options: [`Pizza`, `Sushi`, `Tacos`, `Nada más`] },
      { q: `¿El más ruidoso esta noche?`, options: [`Lucas`, `Teo`, `Sara`, `Yo`] },
      { q: `¿A dónde después?`, options: [`Mi casa`, `La tuya`, `Disco`, `A dormir`] },
      { q: `¿Chill o a bailar?`, options: [`Chill`, `A bailar`, `Karaoke`, `Silencio`] },
      { q: `¿El peor ex de la sala?`, options: [`El mío`, `El tuyo`, `El suyo`, `Mejor no lo digo`] },
      { q: `Relación abierta, ¿válida?`, options: [`Sí`, `No`, `Para algunos`, `Depende`] },
      { q: `¿Casarse a los 30?`, options: [`Romántico`, `Presión`, `Anticuado`, `Genial si lo eliges`] },
      { q: `¿Jugamos a algo?`, options: [`Verdad o reto`, `Mafia`, `Karaoke`, `Solo charlar`] },
      { q: `¿Peor deporte olímpico?`, options: [`Doma`, `Tiro con arco`, `Marcha atlética`, `Curling`] },
      { q: `¿Quién se queda a dormir aquí?`, options: [`Yo`, `Tú`, `Nadie`, `Todos`] },
    ],
    faq: [
      { q: `¿Cuánta gente puede votar?`, a: `Sin límite. 8, 30, funciona.` },
      { q: `¿Hace falta wifi?`, a: `Sí para cargar. Una vez cargada, los votos funcionan en modo avión.` },
      { q: `¿Los amigos necesitan una app?`, a: `No. Se abre en cualquier navegador. Sin registro.` },
      { q: `¿La forma más rápida de compartir en la fiesta?`, a: `Tres opciones: (1) hacer AirDrop del link a todos, (2) soltarlo en el grupo de WhatsApp, (3) enseñar la pantalla y dejar que tecleen la URL de 5 caracteres.` },
    ],
    related: [`friends-en-es`, `birthday-en-es`, `would-you-rather-en-es`, `drama-polls-es`],
    updatedAt: today,
  },
  {
    slug: `birthday-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🎂`,
    title: `Ideas de encuestas para cumpleaños — 30 preguntas para quien organiza`,
    h1: `Encuestas de cumpleaños: 30 ideas para organizar y montar la fiesta`,
    description: `30 encuestas de cumpleaños para quien organiza: regalo, fecha, sorpresa, temática. Además de encuestas para usar durante la fiesta como entretenimiento.`,
    intro: `Organizar un cumpleaños de 15 personas son 200 mensajes de WhatsApp sobre fecha, sitio y regalo. moomz lo resuelve en 30 minutos. El día de la fiesta, las encuestas se vuelven entretenimiento: rankings, "qué describe a la persona del cumple", juegos de memoria.`,
    sections: [
      {
        h: `Antes de la fiesta: las 4 encuestas esenciales`,
        body: `1) Fecha (3-4 opciones de finde). 2) Sitio (casa de alguien, restaurante, bar). 3) Regalo (4-5 opciones, incluye "regalo en efectivo del grupo"). 4) Sorpresa sí/no. Espácialas 24 h, no satures el grupo.`,
      },
      {
        h: `Durante: encuestas de entretenimiento`,
        body: `Lanza "¿qué describe mejor a [la persona del cumple]?" con opciones que propuso el grupo. Muestra el resultado en la tele o léelo durante la tarta. Momento de memoria colectiva.`,
      },
      {
        h: `Encuesta del regalo en grupo`,
        body: `En vez de 3 horas de debate, lanza 4 opciones de regalo con presupuesto fijado. Gana la mayoría, se abre el bote por Bizum/Verse. Se acabó el "yo quería otra cosa".`,
      },
      {
        h: `Encuesta del mejor del año`,
        body: `Para un cumple de fin de año, lanza una encuesta de "lo mejor del año": mejor momento con [la persona], mejor fiesta, mejor cagada. 6 opciones de las fotos del grupo. El resultado se vuelve un regalo emotivo.`,
      },
    ],
    polls: [
      { q: `¿Fecha del cumple de Lea?`, options: [`Vie 12`, `Sáb 13`, `Sáb 20`, `El mes que viene`] },
      { q: `¿Dónde?`, options: [`Casa de Lea`, `Mi casa`, `Restaurante`, `Bar`] },
      { q: `¿Sorpresa?`, options: [`Sí`, `No, odia las sorpresas`, `Reveal pequeño`] },
      { q: `¿Regalo de grupo?`, options: [`100 € en Amazon`, `Cena para 6`, `Finde de spa`, `Bote en efectivo`] },
      { q: `¿Temática?`, options: [`Disco`, `Pastel`, `Y2K`, `Sin temática`] },
      { q: `Tarta: ¿quién la trae?`, options: [`Yo`, `Tú`, `La pedimos`, `Casera`] },
      { q: `Fotos: ¿pro o móvil?`, options: [`Fotógrafo`, `Polaroid`, `Con el móvil vale`, `Sin fotos`] },
      { q: `¿Qué describe mejor a la persona del cumple?`, options: [`La más graciosa`, `La más generosa`, `Siempre llega tarde`, `La más atrevida`] },
      { q: `¿Karaoke como entretenimiento?`, options: [`Sí`, `No, cringe`, `Si está bien preparado`] },
      { q: `¿Hora de la tarta?`, options: [`21 h`, `22 h`, `Medianoche`, `Cuando haya hambre`] },
    ],
    faq: [
      { q: `¿Cómo evito el debate infinito del regalo?`, a: `4 opciones en una encuesta, cierra en 24 h. Gana la mayoría. Quien no quede contento añade presupuesto personal.` },
      { q: `¿Cómo mantengo la sorpresa en WhatsApp?`, a: `Subgrupo sin la persona del cumple, lanza ahí las encuestas. moomz no filtra nada.` },
      { q: `¿Idea original de cumpleaños?`, a: `Antes de la fiesta, lanza "describe a [nombre] en una palabra" con 6 opciones. Muéstralo durante el brindis. Momento emotivo fuerte.` },
      { q: `¿Cumpleaños de niños?`, a: `Adapta las opciones a su mundo: superhéroe favorito, postre, juego. Les encanta votar.` },
    ],
    related: [`party-en-es`, `family-en-es`, `bachelorette-en-es`, `bachelor-en-es`],
    updatedAt: today,
  },
  {
    slug: `wedding-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `💍`,
    title: `Ideas de encuestas para bodas — 40 preguntas para los novios y los invitados`,
    h1: `Encuestas de boda: 40 ideas para organizar y montar la celebración`,
    description: `40 encuestas para parejas que preparan una boda: lugar, catering, vestido, además de encuestas para invitados sobre alergias, alojamiento y entretenimiento.`,
    intro: `Organizar una boda = 50 decisiones, cada una con opiniones fuertes. moomz se encarga de dos niveles: decisiones de los novios (lugar, catering, fotógrafo) y aportaciones de los invitados (restricciones alimentarias, compartir habitación, niños invitados). Además de encuestas de entretenimiento el día de la boda.`,
    sections: [
      {
        h: `Encuestas de preparación: decisiones de los novios`,
        body: `Cada domingo, lanza una decisión importante vía encuesta. Los dos votáis por separado, comparáis y solo debatís en los desacuerdos. Recorta el tiempo de decisión en un 80%.`,
      },
      {
        h: `Encuestas para invitados: antes de la boda`,
        body: `Crea encuestas para los detalles del RSVP: dieta (omnívoro / vegetariano / vegano / sin gluten), niños sí/no, alojamiento sí/no, transporte compartido. Recoge todo en 2 días en vez de 200 mensajes individuales.`,
      },
      {
        h: `El día de la boda: encuestas de entretenimiento`,
        body: `Durante el aperitivo, lanza "¿cómo se conoció la pareja?" con 4 opciones, una verdadera. Los invitados votan, la novia revela. Rompehielos perfecto. O: "¿quién es más probable que acabe borracho a medianoche?" — arriesgada pero hilarante.`,
      },
      {
        h: `Después de la boda: lo mejor`,
        body: `Días después, lanza "¿el mejor momento de la boda?" con los invitados. Opciones de las fotos: ceremonia, primer beso, primer baile, tarta, brindis. Consigue un mejor-de democrático para un mini álbum de fotos.`,
      },
    ],
    polls: [
      { q: `Vestido: ¿sirena, princesa o boho?`, options: [`Sirena`, `Princesa`, `Boho`, `Ninguno de los tres`] },
      { q: `Lugar: ¿castillo, viñedo o playa?`, options: [`Castillo`, `Viñedo`, `Playa`, `Salón clásico`] },
      { q: `Catering:`, options: [`Cóctel cena`, `Menú de 3 platos`, `Food trucks`, `Bufé`] },
      { q: `¿DJ o banda en vivo?`, options: [`DJ`, `Banda`, `Las dos`, `Solo playlist`] },
      { q: `¿Barra libre o de pago?`, options: [`Barra libre`, `Libre con límites`, `Barra de pago`, `Solo vino de la casa`] },
      { q: `¿Niños invitados?`, options: [`Todos`, `Solo sobrinos`, `Ninguno`] },
      { q: `¿Primer baile?`, options: [`Lento clásico`, `Coreografiado`, `Sorpresa`, `Sin primer baile`] },
      { q: `¿Dieta del invitado?`, options: [`Omnívoro`, `Vegetariano`, `Vegano`, `Sin gluten`] },
      { q: `¿Alojamiento compartido?`, options: [`Sí`, `Cada uno el suyo`, `Solo familia`] },
      { q: `¿El mejor momento de la boda?`, options: [`Ceremonia`, `Primer beso`, `Primer baile`, `El brindis del padrino`] },
    ],
    faq: [
      { q: `¿Cuántos invitados pueden votar?`, a: `Sin límite. 50, 200, funciona de maravilla.` },
      { q: `¿Cómo mantengo la encuesta privada solo para invitados?`, a: `Los links de moomz no se indexan. Compártelo solo en el WhatsApp de invitados. Quien no tenga el link no lo encuentra.` },
      { q: `¿Encuesta anónima para elegir al padrino?`, a: `Sí: lanza "¿quién debería dar el brindis principal?" con opciones. Los votos son anónimos, el resultado se comparte.` },
      { q: `¿Cómo recuerdo a quienes no han votado?`, a: `moomz no rastrea identidades. Vuelve a compartir el link en el grupo con "faltan 5 votos".` },
    ],
    related: [`bachelorette-en-es`, `bachelor-en-es`, `family-en-es`, `birthday-en-es`],
    updatedAt: today,
  },
  {
    slug: `bachelorette-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `💃`,
    title: `Ideas de encuestas para la despedida de soltera — 30 preguntas para organizarla`,
    h1: `Encuestas para despedida de soltera: organiza y monta la despedida perfecta`,
    description: `30 encuestas para organizar una despedida de soltera: destino, temática, actividades. Además de encuestas tipo quiz para la propia noche.`,
    intro: `Organizar una despedida de soltera son 4-8 amigas con 4-8 opiniones. moomz recorta el debate a 5 minutos. El día de la despedida, las encuestas se vuelven juegos de fiesta: "quién conoce mejor a la novia", "lo primero que le dijo a su prometido".`,
    sections: [
      {
        h: `Antes de la despedida: 4 decisiones rápidas`,
        body: `Lanza 4 encuestas con 24 h de diferencia: (1) ciudad, (2) temática (chic, deportiva, fiestera, spa), (3) presupuesto por cabeza, (4) duración. Proyecto enmarcado en 96 h, quedan detalles manejables.`,
      },
      {
        h: `La noche de la despedida: encuestas de trivia sobre la novia`,
        body: `Durante la cena, lanza "¿quién conoce mejor a Lea?" con 5 preguntas de trivia (primer beso, ciudad soñada, animal favorito). Cada una vota a ciegas, comparáis al final. La perdedora paga los chupitos.`,
      },
      {
        h: `Encuesta de recuerdos`,
        body: `Antes del evento, recoge recuerdos de las amigas. Lanza una encuesta "el mejor recuerdo con Lea" con 6 opciones. Muestra el resultado durante la noche. Momento de regalo emotivo.`,
      },
      {
        h: `Encuesta del juego de la verdad`,
        body: `Después de unas copas, lanza una anónima de "el peor recuerdo con Lea". Anonimato = honestidad. Lee los resultados en voz alta, filtra lo subido de tono y guarda las joyas para un brindis estilo roast.`,
      },
    ],
    polls: [
      { q: `¿Ciudad para la despedida?`, options: [`París`, `Lisboa`, `Barcelona`, `Marrakech`, `Berlín`] },
      { q: `¿Temática?`, options: [`Cena chic`, `Aventura deportiva`, `Fiesta y discoteca`, `Spa para relajarse`] },
      { q: `¿Presupuesto por cabeza?`, options: [`150-200 €`, `200-350 €`, `350-500 €`, `500 € o más`] },
      { q: `¿Duración?`, options: [`1 día`, `Finde`, `3 días`, `4-5 días`] },
      { q: `¿Actividad?`, options: [`Clase de baile`, `Taller de cócteles`, `Spa`, `Escape room`] },
      { q: `¿Disfraz temático?`, options: [`Gracioso`, `Chic`, `Ninguno`, `Blanco minimalista`] },
      { q: `¿Sorpresa para la novia?`, options: [`Vídeo de su prometido`, `Discursos de las amigas`, `Regalo especial`, `Ya está planeado`] },
      { q: `¿El primer beso de Lea?`, options: [`A los 14`, `A los 15`, `A los 16`, `Más tarde`] },
      { q: `¿La ciudad soñada de Lea?`, options: [`París`, `Tokio`, `Nueva York`, `Bali`] },
      { q: `¿Quién llora más en la ceremonia?`, options: [`La novia`, `La madre`, `El novio`, `La dama de honor`] },
    ],
    faq: [
      { q: `¿Cómo mantengo la despedida en secreto?`, a: `Subgrupo sin la novia. moomz no avisa a nadie: cero filtraciones.` },
      { q: `¿Máximo de amigas?`, a: `Sin límite. 4, 20, todas votan en paralelo.` },
      { q: `¿Y si no hay cobertura el día de la despedida?`, a: `Una vez que la página está cargada, los votos funcionan en modo avión. Cárgala al llegar.` },
      { q: `¿Idea de regalo original?`, a: `Semanas antes, lanza 5 encuestas anónimas ("el mejor recuerdo de Lea", "una palabra para describir a Lea"). Imprime los resultados en un pequeño librito de regalo para el día.` },
    ],
    related: [`wedding-en-es`, `bachelor-en-es`, `birthday-en-es`, `friends-en-es`],
    updatedAt: today,
  },
  {
    slug: `bachelor-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `🍻`,
    title: `Ideas de encuestas para la despedida de soltero — 30 preguntas para organizarla y jugar`,
    h1: `Encuestas para despedida de soltero: organiza una despedida memorable`,
    description: `30 encuestas para la despedida de soltero: destino, actividad, retos. Desde la organización hasta los juegos de la noche.`,
    intro: `Organizar una despedida de soltero = 6-12 chicos, un padrino, 6 opiniones distintas. moomz lo recorta a una sola tarde. La noche de la despedida, las encuestas = detonantes de debate y generadores de retos. Aquí tienes la jugada sin caer en los clichés de las despedidas.`,
    sections: [
      {
        h: `Antes de la despedida: encuestas decisivas`,
        body: `4 encuestas: ciudad, tipo de actividad (deporte extremo, gastro, fiesta, casino), presupuesto por cabeza, duración. Si la mayoría quiere karting, es karting. Sin debates de 2 horas.`,
      },
      {
        h: `Encuestas de actividad`,
        body: `Karting vs paintball, bolos vs escape room, póker vs bar de mala muerte, barco vs spa. Lanza las opciones de dos en dos. Para la noche: discoteca techno o coctelería, karaoke sí/no, after en casa o fuera.`,
      },
      {
        h: `Trivia sobre el novio`,
        body: `Durante la cena, lanza 5 encuestas de trivia sobre el novio: primer beso, primera resaca, ciudad favorita, mayor cagada. Los chicos votan, el novio revela. Salen historias ocultas para la próxima década de bromas recurrentes.`,
      },
      {
        h: `Encuesta de reto`,
        body: `Lanza una encuesta de reto con 4 opciones. La ganadora por mayoría = su desafío de la noche. Que sea gracioso pero no humillante. El límite: que lo recuerde bien y se ría al día siguiente.`,
      },
    ],
    polls: [
      { q: `¿Ciudad para la despedida?`, options: [`Ámsterdam`, `Berlín`, `Lisboa`, `Aquí mismo`, `Las Vegas`] },
      { q: `¿Tipo de despedida?`, options: [`Deporte extremo`, `Gastro`, `Fiesta`, `Casino`] },
      { q: `¿Presupuesto por cabeza?`, options: [`150-250 €`, `250-400 €`, `400-600 €`, `600 € o más`] },
      { q: `¿Duración?`, options: [`1 noche`, `Finde`, `3 días`] },
      { q: `¿Actividad?`, options: [`Karting`, `Paintball`, `Escape room`, `Barco`] },
      { q: `¿La noche?`, options: [`Discoteca techno`, `Coctelería`, `Karaoke`, `Casino`] },
      { q: `¿El reto del novio?`, options: [`Striptease cutre`, `Karaoke en calzoncillos`, `Tatuaje temporal`, `Juego de beber`] },
      { q: `¿El primer beso del novio?`, options: [`A los 14`, `A los 16`, `A los 18`, `Más tarde`] },
      { q: `¿La mayor cagada del novio?`, options: [`El Erasmus`, `Una fiesta de la uni`, `Unas vacaciones`, `Indecible`] },
      { q: `¿Quién acaba KO esta noche?`, options: [`El novio`, `El padrino`, `Teo`, `Todos`] },
    ],
    faq: [
      { q: `¿Mantener la despedida en secreto?`, a: `Subgrupo sin el novio. moomz no avisa. Cero filtraciones.` },
      { q: `¿Máximo de chicos?`, a: `Sin límite. 6 o 20, todo bien.` },
      { q: `¿Puede votar el novio en el día de trivia?`, a: `Sí: puede ser quien revele la respuesta correcta al final de cada encuesta.` },
      { q: `¿Idea de regalo en grupo?`, a: `Encuesta anónima "una palabra para describir a [el novio]" a todos los amigos. Imprime los resultados en un regalo enmarcado. Recuerdo emotivo.` },
    ],
    related: [`bachelorette-en-es`, `wedding-en-es`, `friends-en-es`, `party-en-es`],
    updatedAt: today,
  },
  {
    slug: `baby-shower-en-es`,
    locale: `es`,
    category: `ideas`,
    emoji: `👶`,
    title: `Ideas de encuestas para baby shower — 30 preguntas para anfitriones e invitados`,
    h1: `Encuestas para baby shower: adivina y anima la fiesta`,
    description: `30 encuestas para baby shower: nombre, sexo, fecha de nacimiento, primera palabra. Además de encuestas para el regalo en grupo.`,
    intro: `Los baby showers = 15 invitados que quieren participar pero no saben cómo. moomz se vuelve el juego de la tarde: adivinar la fecha de nacimiento, el peso, la primera palabra, el sexo (si no se ha revelado). Los futuros papás se quedan las capturas como recuerdo.`,
    sections: [
      {
        h: `Encuestas para adivinar cosas del bebé`,
        body: `Clásicas: fecha de nacimiento (4 opciones alrededor de la fecha prevista), peso, altura, color de pelo. Cada uno vota; 6 meses después, los papás revelan quién acertó. Para ir más lejos: "la futura profesión del bebé". Una tontería pero divertida.`,
      },
      {
        h: `Encuesta del regalo en grupo`,
        body: `¿Los papás tienen lista de nacimiento? Lanza "¿qué regalo de grupo?" con 4 opciones de la lista + presupuesto indicado. Sin duplicados, sin debate. Todos se suman al mismo bote.`,
      },
      {
        h: `Encuesta del nombre (si no está elegido)`,
        body: `¿Los papás aún no se han decidido (o quieren opiniones)? Lanza una encuesta de 4-5 nombres. Ojo: los papás no están obligados a hacer caso. Aun así es un juego genial para los invitados.`,
      },
      {
        h: `Encuestas meta sobre el grupo`,
        body: `Entre juego y juego, lanza "¿quién será la próxima embarazada del grupo?", "¿quién hará más fotos del bebé?", "¿quién será la madrina?". Divertidas, generan debate y no humillan a nadie.`,
      },
    ],
    polls: [
      { q: `¿Fecha de nacimiento?`, options: [`Antes de lo previsto`, `El día previsto`, `1-3 días después`, `Más de una semana después`] },
      { q: `¿Sexo del bebé?`, options: [`Niña`, `Niño`, `Sorpresa`, `Gemelos`] },
      { q: `¿Peso al nacer?`, options: [`Menos de 2,7 kg`, `2,7-3,2 kg`, `3,2-3,6 kg`, `Más de 3,6 kg`] },
      { q: `¿Color de pelo?`, options: [`Rubio`, `Castaño`, `Moreno`, `Pelirrojo`] },
      { q: `¿Nombre favorito?`, options: [`Leo`, `Adam`, `Camila`, `Sasha`, `Mila`] },
      { q: `¿La futura profesión del bebé?`, options: [`Artista`, `Deportista`, `Científico`, `Influencer`] },
      { q: `¿Primera palabra?`, options: [`Mamá`, `Papá`, `No`, `Más`] },
      { q: `¿Regalo de grupo?`, options: [`Carrito`, `Silla de coche`, `Lamparita`, `Bote en efectivo`] },
      { q: `¿La próxima embarazada del grupo?`, options: [`Lea`, `Sara`, `Camila`, `Yo`] },
      { q: `¿Color dominante del cuarto del bebé?`, options: [`Rosa pastel`, `Azul pastel`, `Beige`, `Verde salvia`] },
    ],
    faq: [
      { q: `¿Guardar los resultados como recuerdo?`, a: `Haz una captura al final del baby shower. La encuesta sigue accesible vía el link de moomz, pero una pantalla con fecha es mejor recuerdo.` },
      { q: `¿Pueden votar también los papás?`, a: `Sí, sobre todo en las encuestas de nombre o regalo. En las de adivinar la fecha de nacimiento, mejor que se abstengan.` },
      { q: `¿Amigos a distancia?`, a: `Manda el link de moomz por WhatsApp. Votan desde casa, el mismo recuento. Perfecto para amigos en el extranjero.` },
      { q: `¿Cuántas encuestas en un baby shower?`, a: `Espácialas: 1 cada 15-20 minutos. Total: 5-7 encuestas a lo largo de una tarde. Más y se convierte en una reunión.` },
    ],
    related: [`birthday-en-es`, `family-en-es`, `bachelorette-en-es`, `this-or-that-es`],
    updatedAt: today,
  },
];
