import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasIt1: SeoPage[] = [
  {
    slug: `instagram-story-poll-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `📸`,
    title: `Idee Sondaggi per le Storie Instagram — 50 Domande che Fanno Votare`,
    h1: `Idee Sondaggi per le Storie Instagram: 50 Domande che Fanno Davvero Votare`,
    description: `50 idee di sondaggi per le Storie Instagram che spingono le interazioni. Lascia perdere il classico questo-o-quello noioso — questi spunti fanno davvero partire le conversazioni.`,
    intro: `Lo sticker sondaggio nativo di Instagram ti blocca a due opzioni e si esaurisce in fretta. Gli account che spaccano con l'engagement nel 2026 usano sondaggi multi-opzione tramite link sticker — metti un link moomz, i tuoi follower votano con un tap, tu controlli il risultato e lo ricondividi. Ecco 50 idee che fanno davvero la differenza.`,
    sections: [
      {
        h: `Perché i sondaggi battono lo sticker domande`,
        body: `Un sondaggio chiede un tap. Una domanda chiede di scrivere. La differenza di sforzo è 10x. I sondaggi raggiungono il 60-80% di risposte sugli account lifestyle; gli sticker domande si fermano al 5-15%. Usa i sondaggi per l'engagement, le domande per raccogliere contenuti (trasforma le risposte in un post di follow-up).`,
      },
      {
        h: `Quando lo sticker nativo non basta`,
        body: `I sondaggi nativi di Instagram ti danno due opzioni. Per tre, quattro o sei opzioni ti serve un link a un sondaggio esterno. moomz crea un sondaggio in 10 secondi, ti dà un URL di 5 caratteri e i tuoi follower votano senza uscire dal browser di IG. I risultati sono live e animati — perfetti per le re-stories.`,
      },
      {
        h: `I 5 angoli che fanno arrivare le risposte`,
        body: `1) Questo-o-quello visivo (due foto). 2) Pronostico del giorno ("chi vince stasera"). 3) Opinione forte ("ananas sulla pizza?"). 4) Drama check ("ha fatto bene a sparire?"). 5) Ne vale la pena ("spenderesti 200€ per questo?"). Da evitare: tutto ciò che sembra un sondaggio di marketing. La gente lo fiuta all'istante.`,
      },
      {
        h: `Come trasformare i sondaggi in abitudine`,
        body: `Aggiungi moomz.com alla schermata home (installazione PWA). Un sondaggio per slot di storia. Metti sempre una call to action nella caption: "vota nella prossima storia". Guarda il tasso di risposta salire settimana dopo settimana.`,
      },
    ],
    polls: [
      { q: `Ananas sulla pizza?`, options: [`Sì`, `Mai`, `Boh`] },
      { q: `Caffè o matcha al mattino?`, options: [`Caffè`, `Matcha`, `Nessuno dei due`] },
      { q: `Piani per l'estate: mare o montagna?`, options: [`Mare`, `Montagna`, `Città`, `Resto a casa`] },
      { q: `Storia ogni giorno o mai?`, options: [`Ogni giorno`, `Ogni tanto`, `Mai`] },
      { q: `Jeans larghi, vanno ancora?`, options: [`Approvati`, `No grazie`, `Dipende`] },
      { q: `Brunch o cena fuori?`, options: [`Brunch`, `Cena`, `Entrambi`] },
      { q: `iPhone o Android nel 2026?`, options: [`iPhone`, `Android`, `Non mi interessa`] },
      { q: `Rispondi ai DM degli sconosciuti?`, options: [`Sempre`, `Se è figo/a`, `Mai`] },
      { q: `Brunch o dormire fino a tardi?`, options: [`Brunch`, `Dormo`, `Entrambi`] },
      { q: `Si torna in palestra?`, options: [`Questa settimana`, `Il mese prossimo`, `Mai`] },
    ],
    faq: [
      { q: `Quante opzioni può avere un sondaggio nelle Storie?`, a: `Nativo: 2. Con un link sticker moomz: 2-6 opzioni. Il link si apre, il follower vota e torna nella tua storia.` },
      { q: `I voti dei sondaggi Instagram sono anonimi?`, a: `No — Instagram ti mostra chi ha votato cosa. moomz è completamente anonimo: solo percentuali, nessuna identità dei votanti.` },
      { q: `Quanto dura un sondaggio nelle Storie?`, a: `24h su Instagram. Il link moomz tiene il sondaggio attivo all'infinito — rimettilo nella storia di domani se vuoi più voti.` },
      { q: `Posso vedere i risultati in diretta?`, a: `Sì — moomz anima i risultati in tempo reale. Entra nel tuo sondaggio e guarda le barre muoversi mentre arrivano i voti.` },
    ],
    related: [`tiktok-poll-it`, `snapchat-poll-it`, `this-or-that-it`, `would-you-rather-en-it`],
    updatedAt: today,
  },
  {
    slug: `tiktok-poll-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🎵`,
    title: `Idee Sondaggi TikTok — 40 Spunti per Link in Bio e Video`,
    h1: `Sondaggi TikTok: 40 Idee per Hook nei Video e Link in Bio`,
    description: `TikTok non ha un sondaggio nativo. Ecco come i creator stanno raccogliendo voti tramite il link in bio + 40 spunti che spingono l'engagement nel 2026.`,
    intro: `TikTok non offre uno sticker sondaggio nativo. È una mancanza — e i creator che la colmano con un sondaggio nel link in bio guadagnano un 30-50% extra di loop di engagement. Poni la domanda nel video, scrivi "vota in bio" e usa un link moomz. Ecco il manuale.`,
    sections: [
      {
        h: `Perché l'assenza del sondaggio nativo conta per te`,
        body: `Il design di TikTok dà priorità allo scroll. I sondaggi nativi rallenterebbero il feed. Questo significa che i creator che vogliono feedback strutturati devono crearli tramite il link in bio. moomz è la versione più semplice: un link di 5 caratteri, sta nel limite di caratteri della bio, si apre subito nel browser.`,
      },
      {
        h: `Il loop video-poi-sondaggio`,
        body: `Il video Parte 1 pone la domanda ("ha fatto bene a sparire?"), chiudendo con "vota in bio". Il video Parte 2 mostra il risultato e reagisce. Ogni parte fa il suo come video separato, raddoppiando la reach sullo stesso contenuto. I top account fanno questo loop ogni settimana.`,
      },
      {
        h: `Domande drama che fanno votare`,
        body: `Abbastanza vaghe da generare dibattito, abbastanza specifiche da far schierare. "Ha fatto bene a sparire?" batte "ghostare è sbagliato?" di 3x nel tasso di voto. Il dettaglio narrativo fa restare in testa la domanda.`,
      },
      {
        h: `Evita i sondaggi promozionali`,
        body: `Se stai facendo un sondaggio per uno sponsor, dichiaralo. Gli utenti TikTok fiutano i sondaggi promo all'istante e o passano oltre o commentano per smascherarti. moomz funziona sia per l'organico che per lo sponsorizzato, ma la trasparenza non è negoziabile.`,
      },
    ],
    polls: [
      { q: `Ha fatto bene a ghostarlo?`, options: [`Sì, giustificata`, `No, è una mossa da poco`, `Dipende dal contesto`] },
      { q: `Dici la verità alla tua amica?`, options: [`Sì, diretta`, `Non sta a me`, `Aspetto che lo chieda`] },
      { q: `Quinto appuntamento, ancora nessun bacio — strano?`, options: [`Normale`, `Strano`, `Sospetto`] },
      { q: `Quanto aspetti prima di rispondere?`, options: [`Subito`, `1-3h`, `Il giorno dopo`, `Mai`] },
      { q: `È ok stalkerare un ex?`, options: [`Ovvio`, `Un pochino`, `No, tossico`] },
      { q: `Primo appuntamento: chi paga?`, options: [`Lui/lei`, `Alla romana`, `Sempre il ragazzo`] },
      { q: `Perdoneresti un tradimento una volta?`, options: [`Sì`, `Mai`, `Dipende`] },
      { q: `Tinder nel 2026, ne vale ancora la pena?`, options: [`Sì`, `Morto`, `Per divertimento`] },
      { q: `Dare l'Insta al primo appuntamento?`, options: [`Subito`, `Al secondo appuntamento`, `Mai`] },
      { q: `Uscire con qualcuno più giovane?`, options: [`1-2 anni ok`, `Fino a 5 anni`, `Assolutamente no`, `Nessun limite`] },
    ],
    faq: [
      { q: `TikTok ha un sondaggio nativo?`, a: `No. Puoi fare domande nel video o nei commenti, ma non c'è un widget che conta i voti. Usa moomz e metti il link in bio.` },
      { q: `Il link moomz funziona in bio?`, a: `Sì — viene trattato come qualsiasi link esterno. Sta nel limite di caratteri della bio. Le caption supportano link cliccabili solo per gli account business.` },
      { q: `Posso usare lo stesso sondaggio per più video?`, a: `Sì. Lo stesso link moomz può essere usato su più TikTok. Oppure ruotalo per ogni video per avere un segnale fresco.` },
      { q: `I voti sono anonimi?`, a: `Sì. moomz non associa mai un voto a un profilo. I tuoi spettatori possono rispondere onestamente senza pressione sociale.` },
    ],
    related: [`instagram-story-poll-it`, `snapchat-poll-it`, `drama-polls-it`, `first-date-en-it`],
    updatedAt: today,
  },
  {
    slug: `snapchat-poll-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `👻`,
    title: `Idee Sondaggi Snapchat — 30 Domande per Storie e Chat di Gruppo`,
    h1: `Sondaggi Snapchat: 30 Idee per Storie e Chat di Gruppo`,
    description: `Snapchat non ha un sondaggio nativo. Ecco come aggiungerne uno alla tua storia o chat di gruppo + 30 spunti che funzionano.`,
    intro: `Snapchat non offre sondaggi. La maggior parte degli utenti o scrive in DM agli amici per un'opinione o conta le reazioni emoji — entrambi lenti. Metti un link moomz nella tua Storia (strumento link) o in una chat di gruppo, i voti arrivano e i risultati restano accessibili dopo che la storia scade.`,
    sections: [
      {
        h: `Aggiungere un link a una Snap Story`,
        body: `Quando crei una storia, tocca lo strumento graffetta sulla destra. Incolla l'URL moomz. I tuoi amici vedono un pulsante "Mostra altro". Toccano, votano nel browser, tornano alla storia. Zero attrito.`,
      },
      {
        h: `Sondaggi nelle chat di gruppo`,
        body: `Metti il link in qualsiasi chat di gruppo. Tutti vedono un'anteprima e possono toccare per votare senza uscire dalla chat. Meglio della guerra di messaggi in cui metà del gruppo si perde la domanda perché era AFK.`,
      },
      {
        h: `Sondaggi che funzionano per i teenager`,
        body: `Top 3: "chi del nostro gruppo è…" (il più rumoroso, il più dolce, il più rompiscatole), sondaggi decisionali ("dove andiamo stasera?"), sondaggi drama ("aveva torto lui?"). Evita troppe opzioni — gli utenti Snapchat scrollano veloce, max 4.`,
      },
      {
        h: `Tenerlo privato`,
        body: `I link moomz non sono indicizzati di default. Solo chi ha il link può trovare il sondaggio. Condividilo in una chat di gruppo specifica per voti privati. Non postarlo pubblicamente nella pagina Storie se lo vuoi riservato.`,
      },
    ],
    polls: [
      { q: `Il più rumoroso del nostro gruppo?`, options: [`Luca`, `Sara`, `Teo`, `Lea`] },
      { q: `Dove andiamo stasera?`, options: [`Bar`, `Da me`, `Parco`, `Restiamo dentro`] },
      { q: `Chi è il più divertente?`, options: [`Io ovviamente`, `Tu`, `Lui/lei`, `Nessuno`] },
      { q: `Film o bowling?`, options: [`Film`, `Bowling`, `Né l'uno né l'altro`] },
      { q: `Chi porta gli snack?`, options: [`Io`, `Tu`, `Ordiniamo`, `Li rubiamo`] },
      { q: `Rispondere a lui/lei?`, options: [`Adesso`, `Domani`, `Mai`, `Controlla tu per me`] },
      { q: `Miglior film del 2026?`, options: [`Dune 3`, `Avatar 4`, `Altro`, `Non ne ho visto nessuno`] },
      { q: `Chi ha ghostato per primo?`, options: [`Lui`, `Lei`, `Tutti e due insieme`] },
      { q: `Squadra rossa o blu?`, options: [`Rossa`, `Blu`, `Nessuna squadra`] },
      { q: `Diciamo la verità a Lea?`, options: [`Sì`, `No`, `Decidi tu`] },
    ],
    faq: [
      { q: `Snapchat ha uno sticker sondaggio?`, a: `No. Usa un link moomz nella tua Storia (strumento graffetta) o in una chat di gruppo.` },
      { q: `Come aggiungo un link a una Snap Story?`, a: `Mentre la crei, tocca la graffetta tra gli strumenti sulla destra. Incolla l'URL moomz. Fatto.` },
      { q: `I miei amici hanno bisogno di un account?`, a: `No. moomz funziona senza registrazione. Il link si apre, votano, escono.` },
      { q: `Il sondaggio sparisce con la Storia?`, a: `No. La Storia dura 24h; il sondaggio resta attivo. Ricondividi il link domani per continuare a far arrivare voti.` },
    ],
    related: [`instagram-story-poll-it`, `tiktok-poll-it`, `teens-en-it`, `friends-en-it`],
    updatedAt: today,
  },
  {
    slug: `discord-poll-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🎮`,
    title: `Idee Sondaggi Discord — 30 Spunti per Server e Community`,
    h1: `Sondaggi Discord: 30 Idee per Coinvolgere il Tuo Server`,
    description: `Lascia perdere la configurazione dei bot. Metti un link moomz in qualsiasi canale Discord e la tua community vota in modo anonimo. 30 spunti dentro.`,
    intro: `Il comando sondaggio nativo di Discord va bene per voti veloci, ma è limitato a 10 opzioni e un solo server. Le soluzioni con bot (MEE6, Simple Poll) richiedono installazione + permessi. moomz: incolli e basta il link, chiunque vota, i risultati restano live. Ecco come usarlo bene.`,
    sections: [
      {
        h: `Nativo vs bot vs link moomz`,
        body: `/poll nativo: gratis, 10 opzioni, limitato al server. Bot: più funzioni ma installazione + permessi. moomz: istantaneo, anonimo, nessun permesso necessario, condivisibile anche fuori da Discord. Scegli in base alle tue esigenze.`,
      },
      {
        h: `Sondaggi per la community che funzionano`,
        body: `I top server fanno un sondaggio settimanale in #vote: miglior build del mese (gaming), giudizio sulla patch, classifica skin. Per i server di dibattito: opinioni forti, dilemmi morali, opinioni controverse.`,
      },
      {
        h: `Fissare il sondaggio`,
        body: `Crea il sondaggio, fissa il messaggio nel tuo canale principale. I voti continuano ad arrivare per giorni. Chiudi facendo uno screen del risultato e postandolo in #announcements.`,
      },
      {
        h: `Organizzazione degli eventi`,
        body: `Usa moomz per gli orari dei raid, le serate di gioco, i nuovi canali. I mod vedono i risultati in diretta senza scansionare le reazioni emoji.`,
      },
    ],
    polls: [
      { q: `Gioco per la prossima serata in vocale?`, options: [`LoL`, `Valorant`, `Fortnite`, `Among Us`, `Minecraft`] },
      { q: `Miglior patch di quest'anno?`, options: [`S1`, `S2`, `S3`, `Tutte pessime`] },
      { q: `Nuovo canale da aggiungere?`, options: [`#meme`, `#trading`, `#art`, `#offtopic`] },
      { q: `Il nuovo personaggio è OP?`, options: [`Sì, va nerfato`, `Bilanciato`, `Va buffato`, `Non ci ho giocato`] },
      { q: `Stile di RP preferito?`, options: [`Lore-pesante`, `Casual`, `Focus PVP`, `Niente RP`] },
      { q: `Foto dell'anno (post meme)?`, options: [`Il doge`, `Il gatto`, `La rana`, `Nessuna`] },
      { q: `Teniamo il sistema dei livelli?`, options: [`Sì, è divertente`, `No, è cringe`, `Reset ogni mese`] },
      { q: `Bot da aggiungere?`, options: [`MEE6`, `Carl-bot`, `Nessuno`] },
      { q: `Skin preferita?`, options: [`Skin A`, `Skin B`, `Skin C`, `Default`] },
      { q: `Orario raid sabato?`, options: [`18:00`, `20:00`, `21:00`, `22:00`] },
    ],
    faq: [
      { q: `Mi serve un bot?`, a: `No. Incolla il link moomz in qualsiasi canale, Discord mostra un'anteprima ricca, i membri toccano per votare.` },
      { q: `È anonimo?`, a: `Sì. Nessun nome Discord collegato ai voti. I membri votano senza pressione sociale.` },
      { q: `Quante opzioni?`, a: `2-6 su moomz. Oltre, il completamento dei voti cala. Per 8-12 opzioni, usa il /poll nativo.` },
      { q: `Il sondaggio scade?`, a: `No, a meno che resti inattivo per settimane (anti-spam). Tienilo vivo ricondividendolo.` },
    ],
    related: [`tiktok-poll-it`, `team-building-en-it`, `high-school-en-it`, `college-en-it`],
    updatedAt: today,
  },
  {
    slug: `couple-questions-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `💖`,
    title: `Domande Sondaggio per Coppie — 50 Spunti per Testare la Compatibilità`,
    h1: `Sondaggi per Coppie: 50 Domande da Fare al Partner`,
    description: `50 domande di sondaggio anonime per coppie — dalle preferenze leggere ai discorsi seri. Testa la compatibilità in 30 secondi.`,
    intro: `Un sondaggio bypassa il filtro sociale. Il tuo partner sceglie un'opzione invece di abbellire una risposta. Per questo i terapisti di coppia hanno iniziato a consigliarlo nel 2025. Ecco 50 domande, ordinate per livello di rischio.`,
    sections: [
      {
        h: `Perché i sondaggi battono la conversazione`,
        body: `Due bias rovinano le domande dirette: (1) la voglia di compiacere, (2) il tempo di riflettere. I sondaggi neutralizzano entrambi — scelta binaria, click istintivo. Ottieni dati più puliti di una vera conversazione.`,
      },
      {
        h: `Livello 1: preferenze sicure`,
        body: `Inizia soft: appartamento al mare o in montagna, caffè o tè al mattino, uscire o restare a casa. Crea prima l'abitudine. Una volta che i sondaggi sembrano normali, puoi andare più a fondo.`,
      },
      {
        h: `Livello 2: decisioni quotidiane`,
        body: `Restiamo a casa o usciamo stasera? Cinese o italiano a domicilio? Vediamo i suoceri questo weekend? I sondaggi trasformano dibattiti di 30 minuti in decisioni di 30 secondi.`,
      },
      {
        h: `Livello 3: domande vere`,
        body: `Matrimonio tra 5 anni? Figli sì o no? Trasloco all'estero se arriva l'offerta? Usalo in modo anonimo, mai dopo un litigio. Il sondaggio apre la conversazione — non la sostituisce.`,
      },
    ],
    polls: [
      { q: `Caffè a letto o in cucina?`, options: [`Sempre a letto`, `In cucina`, `Niente caffè`] },
      { q: `Vacanza: mare o montagna?`, options: [`Mare`, `Montagna`, `Entrambi`, `Resto a casa`] },
      { q: `Preferisci:`, options: [`Serata tranquilla a casa`, `Cenetta tra pochi`, `Festone`, `Nessuna preferenza`] },
      { q: `Matrimonio tra 5 anni?`, options: [`Sì`, `Più avanti`, `Non fa per me`, `Forse`] },
      { q: `Figli?`, options: [`Sì 1`, `Sì 2+`, `Mai`, `Indeciso/a`] },
      { q: `Ti trasferiresti all'estero se ti offrissero un lavoro?`, options: [`Sì senza dubbi`, `Dipende`, `No, voglio restare`] },
      { q: `Compleanno a sorpresa?`, options: [`Lo adoro`, `Mi stressa`, `Dipende da chi`] },
      { q: `Posizione per dormire?`, options: [`Abbracciati`, `Fianco a fianco`, `Lontani`] },
      { q: `Stipendio trasparente in coppia?`, options: [`Trasparenza totale`, `Cifre approssimative`, `Privato`] },
      { q: `L'ex su Instagram?`, options: [`Non mi importa`, `Mi dà fastidio`, `Smettiamo di seguirlo insieme`] },
    ],
    faq: [
      { q: `Il mio partner vedrà che ho creato io il sondaggio?`, a: `No. Il link condiviso non mostra il creatore. Puoi anche crearlo in incognito per negare tutto.` },
      { q: `Possiamo vedere chi ha votato cosa?`, a: `No. moomz è completamente anonimo. Vedi solo le percentuali.` },
      { q: `Solo due votanti — è comunque anonimo?`, a: `Tecnicamente sì, ma ovviamente puoi dedurlo. Aggiungi 2-3 amici per un vero anonimato, oppure usalo per risposte da rivelare.` },
      { q: `Come mantengo l'abitudine?`, a: `Un sondaggio a sera per una settimana. 5 minuti per votare, 10 per discutere il risultato. Più coinvolgente di "com'è andata la giornata".` },
    ],
    related: [`first-date-en-it`, `this-or-that-it`, `would-you-rather-en-it`, `valentines-en-it`],
    updatedAt: today,
  },
  {
    slug: `first-date-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🌹`,
    title: `Sondaggi Rompighiaccio per il Primo Appuntamento — 30 Domande Salva-Atmosfera`,
    h1: `Sondaggi per il Primo Appuntamento: 30 Domande Rompighiaccio che Funzionano Davvero`,
    description: `30 sondaggi rompighiaccio per il primo appuntamento. Tira fuori il telefono, fai un voto veloce, salva la conversazione dal silenzio imbarazzante.`,
    intro: `Primo appuntamento che si blocca dopo 30 minuti? Tira fuori il telefono, di' "ho questa app un po' scema — la proviamo?", fai un sondaggio veloce. Votate entrambi, vedete il risultato, e sblocchi 10 minuti di nuova conversazione.`,
    sections: [
      {
        h: `Quando usarlo (e quando no)`,
        body: `Tempismo giusto: dopo 30 minuti, quando i convenevoli si sono esauriti. Tempismo sbagliato: mentre ordinate da bere. Approccio sbagliato: "sono arrivato con un copione". Approccio giusto: "ho appena scoperto questa cosa scema".`,
      },
      {
        h: `Sondaggi sugli appuntamenti che funzionano`,
        body: `Evita l'intimità all'inizio (politica, religione, ex, sessualità). Resta sulle preferenze: viaggi, cibo, stile di feste, animali, hobby. Lascia i temi pesanti per il secondo o terzo appuntamento.`,
      },
      {
        h: `Il trucco del voto a occhi chiusi`,
        body: `Fai la domanda. Chiudete entrambi gli occhi per 5 secondi. Votate separatamente. Rivelate insieme. Elimina l'effetto "voto quello che vuole sentire". La verità esce più in fretta.`,
      },
      {
        h: `Sondaggi da evitare al primo appuntamento`,
        body: `Tutto ciò che ti mette in modalità giudice ("pensi che io sia troppo X?"). Sondaggi trappola ("dormiamo insieme stasera?"). Politica, religione, ex. Tienilo leggero, il sondaggio è un gioco, non un interrogatorio.`,
      },
    ],
    polls: [
      { q: `Cane o gatto?`, options: [`Cane`, `Gatto`, `Entrambi`, `Nessuno dei due`] },
      { q: `Mare o montagna?`, options: [`Mare`, `Montagna`, `Città`, `Avventura`] },
      { q: `Colazione: dolce o salata?`, options: [`Salata`, `Dolce`, `Entrambe`, `La salto`] },
      { q: `Stasera: serata ideale?`, options: [`Ristorante`, `Film`, `Bar`, `Resto a casa`] },
      { q: `Karaoke, ci stai o passi?`, options: [`Lo adoro`, `Solo se brillo`, `Mai`, `Solo per guardare`] },
      { q: `Cucini?`, options: [`Spesso`, `Ogni tanto`, `Mai`, `Ci sto provando`] },
      { q: `Sport da guardare?`, options: [`Calcio`, `Tennis`, `F1`, `Nessuno`] },
      { q: `Feste — che vibe?`, options: [`Tranquille in due`, `Piccolo gruppo`, `Festone`, `Da solo/a`] },
      { q: `Genere di film?`, options: [`Azione`, `Commedia`, `Drammatico`, `Horror`] },
      { q: `A che ora ti svegli?`, options: [`Prima delle 7`, `7-9`, `9-11`, `Dopo mezzogiorno`] },
    ],
    faq: [
      { q: `Tirare fuori un sondaggio non è cringe?`, a: `Solo se lo presenti male. "Ho questa cosa scema" funziona. Se non attacca, hai imparato qualcosa sulla compatibilità.` },
      { q: `Quanti sondaggi in un appuntamento?`, a: `Massimo 3-5. Più di così diventa un quiz, non un appuntamento.` },
      { q: `Eravamo d'accordo su tutto — buon segno?`, a: `O fantastico, o state mentendo entrambi. Alza il livello di rischio nelle domande successive.` },
      { q: `Eravamo in disaccordo su tutto — è una rottura?`, a: `Raramente. Hai appena sbloccato 10 argomenti di conversazione.` },
    ],
    related: [`couple-questions-it`, `valentines-en-it`, `would-you-rather-en-it`, `this-or-that-it`],
    updatedAt: today,
  },
  {
    slug: `friends-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Idee Sondaggi per il Gruppo di Amici — 50 Spunti per Chat e IRL`,
    h1: `Sondaggi per il Gruppo di Amici: 50 Idee per Decidere e Discutere`,
    description: `50 sondaggi per il tuo gruppo di amici: decisioni, tier list, dibattiti. Usali in WhatsApp, Discord o alle feste IRL.`,
    intro: `Il tuo gruppo ha due modalità: decisione (dove mangiamo?) e dibattito (chi è il più rumoroso?). I sondaggi risolvono entrambe. Metti un link moomz, dai una scadenza di 1 ora, fai uno screen del risultato. Niente più tassa-scroll su WhatsApp.`,
    sections: [
      {
        h: `Sondaggi decisionali: zittisci il rumore della chat`,
        body: `Dove mangiamo? Che film? Quale viaggio? Senza un sondaggio: 30 messaggi, metà ignorati. Con un sondaggio: 5 minuti, fatto. Trucco: annuncia una scadenza ("il voto chiude alle 19").`,
      },
      {
        h: `Sondaggi tier list: la miniera d'oro delle risate`,
        body: `Classifiche di gruppo: il più rumoroso, il più dolce, il più probabile a ghostare. Voti anonimi, onestà brutale. Tieni per i gruppi di amici che reggono la frecciatina.`,
      },
      {
        h: `Sondaggi dibattito: opinioni forti`,
        body: `"Il coriandolo è il male?", "ananas sulla pizza?", "la chat di gruppo è troppo attiva?". Non si tratta di risolvere — si tratta di scoprire la spaccatura nel tuo gruppo.`,
      },
      {
        h: `Sondaggi a sorpresa per i compleanni`,
        body: `Organizzi un compleanno a sorpresa? Crea una sotto-chat senza il festeggiato, fai lì tutti i sondaggi. moomz non avvisa nessuno — nessuna fuga di notizie.`,
      },
    ],
    polls: [
      { q: `Chi è il più rumoroso stasera?`, options: [`Luca`, `Sara`, `Teo`, `Lea`] },
      { q: `Dove venerdì?`, options: [`Solito bar`, `Posto nuovo`, `Da me`, `Ristorante`] },
      { q: `Regalo di compleanno per Lea?`, options: [`Fiori`, `Cena`, `Gift card Amazon`, `Colletta`] },
      { q: `Chi non porta mai niente?`, options: [`Teo`, `Camilla`, `Io (lo ammetto)`, `Pagano tutti`] },
      { q: `Ananas sulla pizza?`, options: [`Sì`, `Mai`, `Boh`] },
      { q: `Gita del weekend?`, options: [`Costa`, `Montagna`, `Città`, `Resto a casa`] },
      { q: `Tema della festa di venerdì?`, options: [`Y2K`, `Pigiama`, `Disco`, `Senza tema`] },
      { q: `Invitiamo Marco?`, options: [`Sì`, `No, mah`, `Se a Lea va bene`] },
      { q: `Aperitivo a che ora?`, options: [`18:00`, `19:00`, `20:00`, `Tardi`] },
      { q: `Chi paga l'Uber?`, options: [`Colletta`, `Il primo che entra`, `Ognuno il suo`] },
    ],
    faq: [
      { q: `Gli amici vedranno chi ha creato il sondaggio?`, a: `No. Sia il creatore che i votanti sono anonimi nel link condiviso.` },
      { q: `Quanti amici possono votare?`, a: `Illimitati. 4 o 400, funziona.` },
      { q: `Come chiudo le votazioni?`, a: `Nessuna chiusura manuale. Annuncia una scadenza, fai uno screen del risultato alla scadenza, dichiaralo chiuso.` },
      { q: `E se qualcuno vota due volte?`, a: `Non può. moomz blocca i voti doppi tramite cookie. Una persona = un voto.` },
    ],
    related: [`bff-en-it`, `party-en-it`, `drama-polls-it`, `would-you-rather-en-it`],
    updatedAt: today,
  },
  {
    slug: `bff-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `👯`,
    title: `Domande Sondaggio per Migliori Amiche — 30 Spunti per Testare la Tua BFF`,
    h1: `Sondaggi BFF: 30 Domande per Testare il Legame con la Tua Migliore Amica`,
    description: `30 sondaggi anonimi per testare quanto conosci la tua BFF — e quanto lei conosce te. Onesti, divertenti, a volte brutali.`,
    intro: `Pensate di conoscervi a memoria. Davvero? 30 sondaggi per testare il legame — divertenti, intimi, a volte brutali. La modalità anonima significa risposte oneste, niente ritocchi diplomatici.`,
    sections: [
      {
        h: `Formato quiz per BFF`,
        body: `Crea 10 sondaggi, condividi i link con la tua BFF. Votate entrambe separatamente, confrontate il giorno dopo. Batte il classico quiz BFF di Insta perché le risposte sono anonime — nessuna pressione a dare la risposta "giusta".`,
      },
      {
        h: `Domande che rivelano davvero`,
        body: `Lascia perdere le ovvietà (colore preferito). Vai al livello 2: chi è la più rompiscatole, chi paga di più, chi è la migliore a giudicare gli ex. Spingi oltre: chi è più gelosa, chi sopravvivrebbe se l'altra sparisse.`,
      },
      {
        h: `Sorpresa di compleanno tramite sondaggio`,
        body: `Per il suo compleanno, fai un sondaggio "cosa descrive meglio Lea?" con il gruppo. Opzioni: "sempre in ritardo", "la più divertente", "paga sempre lei". Fai uno screen del risultato, mandalo come gift card. Colpisce più di "auguri".`,
      },
      {
        h: `Compatibilità BFF`,
        body: `5 sondaggi su dilemmi: "perdi il viaggio o perdi il ragazzo", "dici al fidanzato di lei che la tradisce o resti in silenzio", "presti 500€ che non rivedrai mai o dici di no". Misurate quanto pensate allineate.`,
      },
    ],
    polls: [
      { q: `Chi paga più spesso?`, options: [`Io`, `Tu`, `50-50`] },
      { q: `Chi è più spesso in ritardo?`, options: [`Io`, `Tu`, `Uguale`] },
      { q: `Chi è più divertente?`, options: [`Io ovvio`, `Tu`, `Pari`] },
      { q: `Le diciamo del suo fidanzato?`, options: [`Sì, dirette`, `Non sta a noi`, `Dipende`] },
      { q: `Se io sparissi, cosa faresti?`, options: [`Piangerei per una settimana`, `Andrei avanti in 2 mesi`, `Verresti a cercarmi`] },
      { q: `Chi è più gelosa?`, options: [`Io`, `Tu`, `Nessuna delle due`] },
      { q: `Chi è più leale?`, options: [`Io`, `Tu`, `50-50`] },
      { q: `Ristorante su cui litigheremmo?`, options: [`Sushi`, `Italiano`, `Burger`, `Vegano`] },
      { q: `Viaggio insieme — scontro principale?`, options: [`Orari`, `Soldi`, `Musica`, `Siamo perfette`] },
      { q: `Se potessi cambiare una cosa di me?`, options: [`La mia pigrizia`, `La mia gelosia`, `Le mie lamentele`, `Niente`] },
    ],
    faq: [
      { q: `La mia BFF saprà che l'ho creato io?`, a: `Sì, se lo mandi direttamente. Per testarlo tramite il gruppo, l'anonimato regge.` },
      { q: `Idea regalo di compleanno?`, a: `Fai 5 sondaggi "chi descrive meglio Lea?" al gruppo. Lo screen finale fa un bel regalo.` },
      { q: `Quiz in due?`, a: `Sì — ognuna crea 5 sondaggi, vi scambiate i link, rispondete entrambe a 10, confrontate.` },
      { q: `E se la risposta fa male?`, a: `Rischio del gioco. Se vuoi sapere, vota. Se no, non creare il sondaggio.` },
    ],
    related: [`friends-en-it`, `party-en-it`, `would-you-rather-en-it`, `drama-polls-it`],
    updatedAt: today,
  },
  {
    slug: `party-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🎉`,
    title: `Idee Sondaggi per le Feste — 40 Spunti per Ravvivare Qualsiasi Serata`,
    h1: `Sondaggi per le Feste: 40 Idee per Feste in Casa e Afterparty`,
    description: `40 sondaggi per le feste da lanciare nella chat di gruppo — rompighiaccio, tier list, dibattiti. Dalla serata presto fino alla decisione delle 3 di notte.`,
    intro: `Le feste che funzionano hanno una cosa in comune: un argomento su cui litigare. I sondaggi sono inneschi di dibattito istantanei. Lancia la domanda, tutti votano, due minuti dopo state discutendo su come si possa scegliere quella roba.`,
    sections: [
      {
        h: `Inizio serata: sondaggi rompighiaccio`,
        body: `Quando la gente è ancora in piccoli capannelli, lancia un sondaggio nella chat di gruppo. "Chi è in ritardo stasera?", "cosa sgranocchiamo?". Tira tutto il gruppo in un'unica conversazione.`,
      },
      {
        h: `Sera inoltrata: sondaggi tier list`,
        body: `Verso le 22, lancia la tier list del gruppo di amici. "Chi è il più rompiscatole?", "chi non porta mai niente?". Il dibattito dura 30 minuti. Attenzione: onestà brutale, solo per gruppi che la reggono.`,
      },
      {
        h: `Notte fonda: sondaggi dibattito`,
        body: `Una di notte, metà del gruppo è andata via. I sopravvissuti vogliono discorsi veri. Lancia opinioni forti filosofiche: "la relazione aperta è valida?", "si dovrebbe mai riparlare con un ex?". Resta civile, riaccende l'energia.`,
      },
      {
        h: `Le 3 di notte: sondaggi decisionali`,
        body: `Dove crolliamo? Ordiniamo pizza? Si chiude? Fai un sondaggio di 30 secondi, segui il risultato. È l'unico momento della serata in cui tutti rispettano il verdetto, perché nessuno ha l'energia per ri-discutere.`,
      },
    ],
    polls: [
      { q: `Cosa ordiniamo?`, options: [`Pizza`, `Sushi`, `Tacos`, `Niente più`] },
      { q: `Il più rumoroso stasera?`, options: [`Luca`, `Teo`, `Sara`, `Io`] },
      { q: `Dove dopo?`, options: [`Da me`, `Da te`, `Discoteca`, `A casa`] },
      { q: `Chill o si balla?`, options: [`Chill`, `Si balla`, `Karaoke`, `Silenzio`] },
      { q: `Peggior ex nella stanza?`, options: [`Il mio`, `Il tuo`, `Il suo`, `Non lo dico`] },
      { q: `Relazione aperta — valida?`, options: [`Sì`, `No`, `Per alcuni`, `Dipende`] },
      { q: `Matrimonio a 30 anni?`, options: [`Romantico`, `Pressione`, `Sorpassato`, `Figo se scelto`] },
      { q: `Facciamo un gioco?`, options: [`Obbligo o verità`, `Lupus`, `Karaoke`, `Solo chiacchiere`] },
      { q: `Sport olimpico peggiore?`, options: [`Dressage`, `Tiro con l'arco`, `Marcia`, `Curling`] },
      { q: `Chi crolla qui stanotte?`, options: [`Io`, `Tu`, `Nessuno`, `Tutti`] },
    ],
    faq: [
      { q: `Quante persone possono votare?`, a: `Nessun limite. 8, 30, funziona.` },
      { q: `Serve il Wi-Fi?`, a: `Sì per caricare. Una volta caricato, i voti funzionano anche in modalità aereo.` },
      { q: `Gli amici hanno bisogno di un'app?`, a: `No. Si apre in qualsiasi browser. Niente registrazione.` },
      { q: `Modo più veloce per condividere alla festa?`, a: `Tre opzioni: (1) AirDrop del link a tutti, (2) lancialo nel gruppo WhatsApp, (3) mostra lo schermo e fai digitare l'URL di 5 caratteri.` },
    ],
    related: [`friends-en-it`, `birthday-en-it`, `would-you-rather-en-it`, `drama-polls-it`],
    updatedAt: today,
  },
  {
    slug: `birthday-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🎂`,
    title: `Idee Sondaggi per Feste di Compleanno — 30 Spunti per Organizzatori`,
    h1: `Sondaggi di Compleanno: 30 Idee per Organizzare e Ospitare`,
    description: `30 sondaggi di compleanno per organizzatori: regalo, data, sorpresa, tema. Più sondaggi da usare durante la festa come intrattenimento.`,
    intro: `Organizzare un compleanno da 15 persone significa 200 messaggi WhatsApp su data, location, regalo. moomz lo gestisce in 30 minuti. Il giorno stesso, i sondaggi diventano intrattenimento: tier list, "cosa descrive il festeggiato", giochi a quiz sui ricordi.`,
    sections: [
      {
        h: `Pre-festa: i 4 sondaggi essenziali`,
        body: `1) Data (3-4 opzioni di weekend). 2) Location (casa di qualcuno, ristorante, bar). 3) Regalo (4-5 opzioni, includi "colletta"). 4) Sorpresa sì/no. Distanziali di 24h, non sovraccaricare il gruppo.`,
      },
      {
        h: `Durante: sondaggi di intrattenimento`,
        body: `Fai "cosa descrive meglio [il festeggiato]?" con opzioni proposte dal gruppo. Mostra il risultato in TV o leggilo durante la torta. Momento di memoria collettiva.`,
      },
      {
        h: `Sondaggio per il regalo di gruppo`,
        body: `Invece di 3 ore di dibattito, fai 4 opzioni di regalo con budget fissato. Vince la maggioranza, parte la colletta su Satispay/PayPal. Niente più "io volevo qualcos'altro".`,
      },
      {
        h: `Sondaggio best-of dell'anno`,
        body: `Per un compleanno di fine anno, fai un sondaggio best-of: miglior momento con [il festeggiato], festa migliore, fail migliore. 6 opzioni dalle foto del gruppo. Il risultato diventa un regalo emozionante.`,
      },
    ],
    polls: [
      { q: `Data del compleanno di Lea?`, options: [`Ven 12`, `Sab 13`, `Sab 20`, `Il mese prossimo`] },
      { q: `Dove?`, options: [`Da Lea`, `Da me`, `Ristorante`, `Bar`] },
      { q: `Sorpresa?`, options: [`Sì`, `No, odia le sorprese`, `Piccola sorpresa`] },
      { q: `Regalo di gruppo?`, options: [`100€ Amazon`, `Cena per 6`, `Weekend spa`, `Colletta`] },
      { q: `Tema?`, options: [`Disco`, `Pastello`, `Y2K`, `Senza tema`] },
      { q: `Torta — chi la porta?`, options: [`Io`, `Tu`, `La ordiniamo`, `Fatta in casa`] },
      { q: `Foto: professionista o telefono?`, options: [`Fotografo`, `Polaroid`, `Telefono va bene`, `Niente foto`] },
      { q: `Cosa descrive meglio il festeggiato?`, options: [`Il più divertente`, `Il più generoso`, `Sempre in ritardo`, `Il più coraggioso`] },
      { q: `Karaoke come intrattenimento?`, options: [`Sì`, `No, cringe`, `Se ben preparato`] },
      { q: `Ora della torta?`, options: [`21:00`, `22:00`, `Mezzanotte`, `Quando abbiamo fame`] },
    ],
    faq: [
      { q: `Come evitare l'interminabile dibattito sul regalo?`, a: `4 opzioni in un sondaggio, chiudi in 24h. Vince la maggioranza. Chi non è contento aggiunge budget personale.` },
      { q: `Come mantenere la sorpresa su WhatsApp?`, a: `Sotto-chat senza il festeggiato, fai lì i sondaggi. Nessuna fuga da moomz.` },
      { q: `Idea originale per il compleanno?`, a: `Prima della festa, fai "descrivi [nome] in una parola" con 6 opzioni. Mostralo durante il brindisi. Momento emotivo forte.` },
      { q: `Compleanno di bambini?`, a: `Adatta le opzioni al loro mondo: supereroe preferito, dolce, gioco. Adorano votare.` },
    ],
    related: [`party-en-it`, `family-en-it`, `bachelorette-en-it`, `bachelor-en-it`],
    updatedAt: today,
  },
  {
    slug: `wedding-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `💍`,
    title: `Idee Sondaggi per Matrimoni — 40 Spunti per Sposi e Invitati`,
    h1: `Sondaggi per Matrimoni: 40 Idee per Organizzare e Ospitare`,
    description: `40 sondaggi per coppie che preparano un matrimonio: location, catering, abito, più sondaggi per gli invitati su allergie, alloggi e intrattenimento.`,
    intro: `Organizzare un matrimonio = 50 decisioni, ognuna con opinioni forti. moomz gestisce due livelli: decisioni di coppia (location, catering, fotografo) e input degli invitati (intolleranze alimentari, condivisione alloggi, bambini invitati). Più sondaggi di intrattenimento il giorno stesso.`,
    sections: [
      {
        h: `Sondaggi di preparazione: decisioni di coppia`,
        body: `Ogni domenica, fai una decisione importante tramite sondaggio. Votate entrambi separatamente, confrontate, discutete solo sui disaccordi. Taglia i tempi decisionali dell'80%.`,
      },
      {
        h: `Sondaggi per gli invitati: pre-matrimonio`,
        body: `Crea sondaggi per i dettagli della conferma: dieta (onnivoro / veg / vegano / senza glutine), bambini sì/no, alloggio sì/no, trasporto condiviso. Raccogli tutto in 2 giorni invece di 200 messaggi individuali.`,
      },
      {
        h: `Il giorno stesso: sondaggi di intrattenimento`,
        body: `Durante l'aperitivo, fai "come si sono conosciuti gli sposi?" con 4 opzioni di cui una vera. Gli invitati votano, la sposa rivela. Rompighiaccio perfetto. Oppure: "chi è il più probabile a essere ubriaco entro mezzanotte?" — rischioso ma esilarante.`,
      },
      {
        h: `Post-matrimonio: best-of`,
        body: `Qualche giorno dopo, fai "miglior momento del matrimonio?" con gli invitati. Opzioni dalle foto: cerimonia, primo bacio, primo ballo, torta, brindisi. Ottieni un best-of democratico per un mini album fotografico.`,
      },
    ],
    polls: [
      { q: `Abito: a sirena, da principessa o boho?`, options: [`Sirena`, `Principessa`, `Boho`, `Nessuno dei tre`] },
      { q: `Location: castello, vigneto o mare?`, options: [`Castello`, `Vigneto`, `Mare`, `Sala classica`] },
      { q: `Catering: ?`, options: [`Cena con cocktail`, `Servito al piatto, 3 portate`, `Food truck`, `Buffet`] },
      { q: `DJ o band dal vivo?`, options: [`DJ`, `Band`, `Entrambi`, `Solo playlist`] },
      { q: `Open bar o a pagamento?`, options: [`Open bar`, `Open bar con limiti`, `Bar a pagamento`, `Solo vino della casa`] },
      { q: `Bambini invitati?`, options: [`Tutti`, `Solo nipoti`, `Nessuno`] },
      { q: `Primo ballo?`, options: [`Lento classico`, `Coreografato`, `A sorpresa`, `Niente primo ballo`] },
      { q: `Dieta degli invitati?`, options: [`Onnivoro`, `Veg`, `Vegano`, `Senza glutine`] },
      { q: `Alloggio condiviso?`, options: [`Sì`, `Ognuno pensa al suo`, `Solo famiglia`] },
      { q: `Miglior momento del matrimonio?`, options: [`Cerimonia`, `Primo bacio`, `Primo ballo`, `Discorso del testimone`] },
    ],
    faq: [
      { q: `Quanti invitati possono votare?`, a: `Nessun limite. 50, 200, funziona benissimo.` },
      { q: `Come tenere il sondaggio privato agli invitati?`, a: `I link moomz non sono indicizzati. Condividilo solo nel WhatsApp degli invitati. Chi non ha il link non lo troverà.` },
      { q: `Sondaggio anonimo per scegliere il testimone?`, a: `Sì — fai "chi dovrebbe fare il discorso principale?" con le opzioni. I voti sono anonimi, il risultato è condiviso.` },
      { q: `Come sollecitare chi non vota?`, a: `moomz non traccia l'identità. Ricondividi il link nel gruppo con "mancano 5 voti".` },
    ],
    related: [`bachelorette-en-it`, `bachelor-en-it`, `family-en-it`, `birthday-en-it`],
    updatedAt: today,
  },
  {
    slug: `bachelorette-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `💃`,
    title: `Idee Sondaggi per Addio al Nubilato — 30 Spunti per Organizzare`,
    h1: `Sondaggi per l'Addio al Nubilato: Organizza e Ospita il Saluto Perfetto`,
    description: `30 sondaggi per organizzare l'addio al nubilato: destinazione, tema, attività. Più sondaggi a quiz per la serata stessa.`,
    intro: `Organizzare un addio al nubilato significa 4-8 amiche con 4-8 opinioni. moomz riduce il dibattito a 5 minuti. Il giorno stesso, i sondaggi diventano giochi di festa: "chi conosce meglio la sposa", "la prima cosa che ha detto al suo fidanzato".`,
    sections: [
      {
        h: `Pre-festa: 4 decisioni veloci`,
        body: `Fai 4 sondaggi a 24h di distanza: (1) città, (2) tema (chic, sportivo, festa, spa), (3) budget a testa, (4) durata. Progetto incorniciato in 96h, restano dettagli gestibili.`,
      },
      {
        h: `La sera stessa: sondaggi trivia sulla sposa`,
        body: `Durante la cena, fai "chi conosce meglio Lea?" con 5 domande trivia (primo bacio, città dei sogni, animale preferito). Ognuna vota alla cieca, confrontate alla fine. Chi perde paga gli shottini.`,
      },
      {
        h: `Sondaggio dei ricordi`,
        body: `Prima dell'evento, raccogli i ricordi dalle amiche. Fai un sondaggio "miglior ricordo con Lea" con 6 opzioni. Mostra il risultato durante la serata. Momento regalo emozionante.`,
      },
      {
        h: `Sondaggio gioco della verità`,
        body: `Dopo qualche drink, fai un sondaggio anonimo "peggior ricordo con Lea". Anonimato = onestà. Leggi i risultati ad alta voce, filtra quelli pesanti, tieni le perle per un brindisi stile roast.`,
      },
    ],
    polls: [
      { q: `Città dell'addio al nubilato?`, options: [`Parigi`, `Lisbona`, `Barcellona`, `Marrakech`, `Berlino`] },
      { q: `Tema?`, options: [`Cena chic`, `Avventura sportiva`, `Serata in discoteca`, `Relax spa`] },
      { q: `Budget a testa?`, options: [`150-200€`, `200-350€`, `350-500€`, `500€+`] },
      { q: `Durata?`, options: [`1 giorno`, `Weekend`, `3 giorni`, `4-5 giorni`] },
      { q: `Attività?`, options: [`Lezione di ballo`, `Workshop di cocktail`, `Spa`, `Escape room`] },
      { q: `Costume a tema?`, options: [`Divertente`, `Chic`, `Nessuno`, `Bianco minimal`] },
      { q: `Sorpresa per la sposa?`, options: [`Video del suo fidanzato`, `Discorsi delle amiche`, `Regalo speciale`, `Già organizzata`] },
      { q: `Il primo bacio di Lea?`, options: [`A 14 anni`, `A 15 anni`, `A 16 anni`, `Più tardi`] },
      { q: `La città dei sogni di Lea?`, options: [`Parigi`, `Tokyo`, `New York`, `Bali`] },
      { q: `Chi piange di più alla cerimonia?`, options: [`La sposa`, `La mamma`, `Lo sposo`, `La testimone`] },
    ],
    faq: [
      { q: `Come tenere segreto l'addio al nubilato?`, a: `Sotto-chat senza la sposa. moomz non avvisa nessuno — nessuna fuga.` },
      { q: `Numero massimo di amiche?`, a: `Illimitato. 4, 20, votano tutte in parallelo.` },
      { q: `E se non c'è segnale il giorno stesso?`, a: `Una volta caricata la pagina, i voti funzionano in modalità aereo. Caricala all'arrivo.` },
      { q: `Idea regalo originale?`, a: `Settimane prima, fai 5 sondaggi anonimi ("miglior ricordo di Lea", "una parola per descrivere Lea"). Stampa i risultati in un piccolo libretto regalo per il giorno.` },
    ],
    related: [`wedding-en-it`, `bachelor-en-it`, `birthday-en-it`, `friends-en-it`],
    updatedAt: today,
  },
  {
    slug: `bachelor-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🍻`,
    title: `Idee Sondaggi per Addio al Celibato — 30 Spunti per Organizzare e Giocare`,
    h1: `Sondaggi per l'Addio al Celibato: Organizza un Saluto Memorabile`,
    description: `30 sondaggi per l'addio al celibato: destinazione, attività, penitenze. Dall'organizzazione ai giochi della serata.`,
    intro: `Organizzare un addio al celibato = 6-12 ragazzi, un testimone, 6 opinioni diverse. moomz lo riduce a un solo pomeriggio. La sera stessa, i sondaggi = inneschi di dibattito e generatori di penitenze. Ecco il manuale senza cadere nei cliché da addio al celibato.`,
    sections: [
      {
        h: `Pre-festa: sondaggi decisivi`,
        body: `4 sondaggi: città, tipo di attività (sport estremo, gastronomia, festa, casinò), budget a testa, durata. Se la maggioranza vuole il karting, è karting. Niente dibattiti da 2 ore.`,
      },
      {
        h: `Sondaggi sulle attività`,
        body: `Karting vs paintball, bowling vs escape room, poker vs dive bar, barca vs spa. Fai le opzioni 2 a 2. Per la sera: discoteca techno o cocktail bar, karaoke sì/no, afterparty a casa o fuori.`,
      },
      {
        h: `Trivia sullo sposo`,
        body: `Durante la cena, fai 5 sondaggi trivia sullo sposo: primo bacio, prima sbronza, città preferita, cazzata più grossa. I ragazzi votano, lo sposo rivela. Vengono fuori storie nascoste per il prossimo decennio di battute ricorrenti.`,
      },
      {
        h: `Sondaggio delle penitenze`,
        body: `Fai un sondaggio penitenza a 4 opzioni. Vince la maggioranza = la sua sfida per la serata. Tienilo divertente ma non umiliante. Il limite: deve ricordarselo bene e riderci sopra il giorno dopo.`,
      },
    ],
    polls: [
      { q: `Città dell'addio al celibato?`, options: [`Amsterdam`, `Berlino`, `Lisbona`, `In zona`, `Las Vegas`] },
      { q: `Tipo di addio al celibato?`, options: [`Sport estremo`, `Gastronomia`, `Festa`, `Casinò`] },
      { q: `Budget a testa?`, options: [`150-250€`, `250-400€`, `400-600€`, `600€+`] },
      { q: `Durata?`, options: [`1 notte`, `Weekend`, `3 giorni`] },
      { q: `Attività?`, options: [`Karting`, `Paintball`, `Escape room`, `Barca`] },
      { q: `Serata?`, options: [`Discoteca techno`, `Cocktail bar`, `Karaoke`, `Casinò`] },
      { q: `Penitenza per lo sposo?`, options: [`Spogliarello imbarazzante`, `Karaoke in boxer`, `Tatuaggio temporaneo`, `Gioco alcolico`] },
      { q: `Il primo bacio dello sposo?`, options: [`A 14 anni`, `A 16 anni`, `A 18 anni`, `Più tardi`] },
      { q: `La cazzata più grossa dello sposo?`, options: [`Erasmus`, `Festa universitaria`, `In vacanza`, `Indicibile`] },
      { q: `Chi va in blackout stanotte?`, options: [`Lo sposo`, `Il testimone`, `Teo`, `Tutti`] },
    ],
    faq: [
      { q: `Tenere segreto l'addio al celibato?`, a: `Sotto-chat senza lo sposo. moomz non avvisa. Nessuna fuga.` },
      { q: `Numero massimo di ragazzi?`, a: `Illimitato. 6 o 20, va tutto bene.` },
      { q: `Lo sposo può votare al trivia il giorno stesso?`, a: `Sì — può fare lui il rivelatore della risposta giusta alla fine di ogni sondaggio.` },
      { q: `Idea regalo di gruppo?`, a: `Sondaggio anonimo "una parola per descrivere [lo sposo]" a tutti gli amici. Stampa i risultati in un quadretto regalo. Ricordo che commuove.` },
    ],
    related: [`bachelorette-en-it`, `wedding-en-it`, `friends-en-it`, `party-en-it`],
    updatedAt: today,
  },
  {
    slug: `baby-shower-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `👶`,
    title: `Idee Sondaggi per Baby Shower — 30 Spunti per Organizzatori e Invitati`,
    h1: `Sondaggi per Baby Shower: Indovina e Anima la Festa`,
    description: `30 sondaggi per baby shower: nome, sesso, data di nascita, prima parola. Più sondaggi per il regalo di gruppo.`,
    intro: `I baby shower = 15 invitati che vogliono partecipare ma non sanno come. moomz diventa il gioco del pomeriggio: indovina la data di nascita, il peso, la prima parola, il sesso (se non rivelato). I futuri genitori conservano gli screenshot come ricordo.`,
    sections: [
      {
        h: `Sondaggi indovina-il-bebè`,
        body: `Classici: data di nascita (4 opzioni attorno alla data presunta), peso, lunghezza, colore dei capelli. Ognuno vota; 6 mesi dopo, i genitori rivelano il vincitore. Per spingere oltre: "futura carriera del bebè". Una cavolata ma divertente.`,
      },
      {
        h: `Sondaggio per il regalo di gruppo`,
        body: `I genitori hanno una lista nascita? Fai "quale regalo di gruppo?" con 4 opzioni della lista + budget specificato. Niente doppioni, niente dibattiti. Tutti partecipano all'unica colletta.`,
      },
      {
        h: `Sondaggio sul nome (se non scelto)`,
        body: `I genitori non hanno ancora deciso (o vogliono pareri)? Fai un sondaggio con 4-5 nomi. Nota: i genitori non sono obbligati a seguirlo. Resta comunque un bel gioco per gli invitati.`,
      },
      {
        h: `Meta-sondaggi sul gruppo`,
        body: `Tra un gioco e l'altro, fai "chi sarà la prossima incinta del gruppo?", "chi farà più foto al bebè?", "chi sarà la madrina?". Divertenti, generano dibattito, non umiliano.`,
      },
    ],
    polls: [
      { q: `Data di nascita?`, options: [`Prima della data presunta`, `Proprio il giorno`, `1-3 giorni dopo`, `Oltre una settimana dopo`] },
      { q: `Sesso del bebè?`, options: [`Femmina`, `Maschio`, `Sorpresa`, `Gemelli`] },
      { q: `Peso alla nascita?`, options: [`Meno di 2,7 kg`, `2,7-3,2 kg`, `3,2-3,6 kg`, `Oltre 3,6 kg`] },
      { q: `Colore dei capelli?`, options: [`Biondo`, `Castano`, `Scuro`, `Rosso`] },
      { q: `Nome preferito?`, options: [`Leo`, `Adam`, `Camille`, `Sasha`, `Mila`] },
      { q: `Futura carriera del bebè?`, options: [`Artista`, `Atleta`, `Scienziato`, `Influencer`] },
      { q: `Prima parola?`, options: [`Mamma`, `Papà`, `No`, `Ancora`] },
      { q: `Regalo di gruppo?`, options: [`Passeggino`, `Seggiolino auto`, `Lucina notturna`, `Colletta`] },
      { q: `Prossima del gruppo a restare incinta?`, options: [`Lea`, `Sara`, `Camilla`, `Io`] },
      { q: `Colore dominante della cameretta?`, options: [`Rosa pastello`, `Azzurro pastello`, `Beige`, `Verde salvia`] },
    ],
    faq: [
      { q: `Conservare i risultati come ricordo?`, a: `Fai uno screen alla fine del baby shower. Il sondaggio resta accessibile tramite il link moomz, ma uno screen datato è un ricordo migliore.` },
      { q: `Possono votare anche i genitori?`, a: `Sì — soprattutto sui sondaggi del nome o del regalo. Sulle previsioni della data di nascita, meglio che si astengano.` },
      { q: `Amici lontani?`, a: `Manda il link moomz via WhatsApp. Votano da casa, stesso conteggio. Perfetto per gli amici all'estero.` },
      { q: `Quanti sondaggi in un baby shower?`, a: `Distanziali: 1 ogni 15-20 minuti. Totale: 5-7 sondaggi in un pomeriggio. Di più lo trasforma in una riunione.` },
    ],
    related: [`birthday-en-it`, `family-en-it`, `bachelorette-en-it`, `this-or-that-it`],
    updatedAt: today,
  },
];
