import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasPt1: SeoPage[] = [
  {
    slug: "instagram-story-poll-pt",
    locale: "pt",
    category: "ideas",
    emoji: "📸",
    title: `Enquetes pro Story do Instagram — 50 perguntas que bombam`,
    h1: `Ideias de enquete pro Story do Insta: 50 perguntas que o povo realmente vota`,
    description: `50 ideias de enquete pro Story do Instagram que geram interação de verdade. Esquece o "isso ou aquilo" sem graça — essas perguntas puxam conversa mesmo.`,
    intro: `A figurinha de enquete do Insta te limita a duas opções e cansa rapidinho. Os perfis que estão arrasando no engajamento em 2026 rodam enquetes com várias opções via figurinha de link — cola um link do moomz, teus seguidores votam num toque, você dá uma filtrada no resultado e reposta. Aqui vão 50 ideias que fazem diferença de verdade.`,
    sections: [
      {
        h: `Por que enquete bate caixinha de pergunta`,
        body: `Enquete pede um toque. Caixinha de pergunta pede digitar. A diferença de preguiça é absurda. Enquete chega a 60-80% de resposta em perfis de lifestyle; caixinha fica em 5-15%. Usa enquete pra engajamento e caixinha pra coletar conteúdo (transforma as respostas num post de continuação).`,
      },
      {
        h: `Quando a figurinha nativa não dá conta`,
        body: `A enquete nativa do Instagram te dá duas opções. Pra três, quatro ou seis, você precisa de um link pra uma enquete externa. O moomz cria uma enquete em 10 segundos, te dá uma URL de 5 caracteres, e teus seguidores votam sem sair do navegador do IG. Os resultados são ao vivo e animados — perfeitos pra repostar no Story.`,
      },
      {
        h: `Os 5 ângulos que puxam resposta`,
        body: `1) "Isso ou aquilo" visual (duas fotos). 2) Palpite do dia ("quem ganha hoje à noite"). 3) Opinião polêmica ("abacaxi na pizza?"). 4) Treta pra julgar ("ela tava certa em dar o gelo?"). 5) Vale-a-pena ("você pagaria R$1000 nisso?"). Foge de: qualquer coisa com cara de pesquisa de marketing. O povo sente isso na hora.`,
      },
      {
        h: `Como transformar enquete em hábito`,
        body: `Salva o moomz.com na tela inicial do celular (instala como app). Uma enquete por Story. Sempre coloca um chamado na legenda: "vota no próximo Story". Assiste tua taxa de resposta subir semana a semana.`,
      },
    ],
    polls: [
      { q: `Abacaxi na pizza?`, options: [`Sim`, `Jamais`, `Sei lá`] },
      { q: `Café ou matcha de manhã?`, options: [`Café`, `Matcha`, `Nenhum`] },
      { q: `Plano de verão: praia ou montanha?`, options: [`Praia`, `Montanha`, `Cidade`, `Ficar em casa`] },
      { q: `Story todo dia ou nunca?`, options: [`Todo dia`, `Às vezes`, `Nunca`] },
      { q: `Calça larga, ainda tá valendo?`, options: [`Aprovada`, `De jeito nenhum`, `Depende`] },
      { q: `Brunch ou jantar fora?`, options: [`Brunch`, `Jantar`, `Os dois`] },
      { q: `iPhone ou Android em 2026?`, options: [`iPhone`, `Android`, `Tanto faz`] },
      { q: `Responde DM de desconhecido?`, options: [`Sempre`, `Se for gato`, `Nunca`] },
      { q: `Brunch ou dormir até tarde?`, options: [`Brunch`, `Dormir`, `Os dois`] },
      { q: `Voltar pra academia?`, options: [`Essa semana`, `Mês que vem`, `Nunca`] },
    ],
    faq: [
      { q: `Quantas opções uma enquete de Story pode ter?`, a: `Nativa: 2. Com a figurinha de link do moomz: 2 a 6 opções. O link abre, o seguidor vota e volta pro teu Story.` },
      { q: `Os votos da enquete do Instagram são anônimos?`, a: `Não — o Instagram te mostra quem votou em quê. O moomz é totalmente anônimo: só porcentagem, sem identidade de quem votou.` },
      { q: `Quanto tempo dura uma enquete de Story?`, a: `24h no Instagram. O link do moomz mantém a enquete ativa pra sempre — cola de novo no Story de amanhã se quiser mais votos.` },
      { q: `Dá pra ver os resultados ao vivo?`, a: `Sim — o moomz anima os resultados em tempo real. Entra na tua própria enquete e vê as barras se mexerem conforme os votos chegam.` },
    ],
    related: ["tiktok-poll-pt", "snapchat-poll-pt", "this-or-that-pt", "would-you-rather-en-pt"],
    updatedAt: today,
  },
  {
    slug: "tiktok-poll-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🎵",
    title: `Enquetes pro TikTok — 40 ideias pro link da bio e vídeos`,
    h1: `Enquetes no TikTok: 40 ideias pra ganchos de vídeo e link da bio`,
    description: `O TikTok não tem enquete nativa. Aqui está como os criadores conseguem votos pelo link da bio + 40 ideias que geram engajamento em 2026.`,
    intro: `O TikTok não tem figurinha de enquete nativa. Isso é uma brecha — e os criadores que preenchem com uma enquete no link da bio ganham um loop extra de 30-50% de engajamento. Faz a pergunta no vídeo, escreve "vota na bio" e usa um link do moomz. Aqui está o passo a passo.`,
    sections: [
      {
        h: `Por que não ter enquete nativa importa pra você`,
        body: `O design do TikTok prioriza a rolagem. Enquete nativa atrapalharia o feed. Ou seja, criador que quer feedback estruturado tem que dar um jeito pelo link da bio. O moomz é a versão mais simples: um link de 5 caracteres, cabe no limite de caracteres da bio, abre na hora no navegador.`,
      },
      {
        h: `O loop vídeo-depois-enquete`,
        body: `Vídeo parte 1 faz a pergunta ("ela tava certa em dar o gelo?"), terminando com "vota na bio". Vídeo parte 2 mostra o resultado e reage. Cada parte funciona como um vídeo separado, dobrando o alcance do mesmo conteúdo. Os perfis grandes rodam esse loop toda semana.`,
      },
      {
        h: `Perguntas de treta que puxam voto`,
        body: `Vaga o suficiente pra render debate, específica o suficiente pra ter que escolher um lado. "Ela tava certa em dar o gelo?" rende 3x mais voto que "dar o gelo é errado?". O detalhe da história faz a pergunta grudar.`,
      },
      {
        h: `Foge de enquete de publi`,
        body: `Se você tá enquetando pra uma marca patrocinada, avisa. O povo do TikTok sente publi de longe e ou pula ou comenta pra te expor. O moomz funciona tanto pro orgânico quanto pro pago, mas o aviso não é negociável.`,
      },
    ],
    polls: [
      { q: `Ela tava certa em dar o gelo nele?`, options: [`Sim, justíssimo`, `Não, isso é mancada`, `Depende do contexto`] },
      { q: `Conta a verdade pra tua amiga?`, options: [`Sim, na lata`, `Não é da minha conta`, `Espero ela perguntar`] },
      { q: `Quinto encontro e nenhum beijo — esquisito?`, options: [`Normal`, `Esquisito`, `Suspeito`] },
      { q: `Quanto tempo até você responder?`, options: [`Na hora`, `1-3h`, `No dia seguinte`, `Nunca`] },
      { q: `Pode stalkear ex?`, options: [`Claro`, `Um pouquinho`, `Não, tóxico`] },
      { q: `Primeiro encontro: quem paga?`, options: [`Ele/ela`, `Rachar`, `O cara sempre`] },
      { q: `Perdoa uma traição?`, options: [`Sim`, `Jamais`, `Depende`] },
      { q: `Tinder em 2026, ainda vale?`, options: [`Vale`, `Morreu`, `Só por diversão`] },
      { q: `Passa o Insta no primeiro encontro?`, options: [`Na hora`, `Segundo encontro`, `Nunca`] },
      { q: `Sair com alguém mais novo?`, options: [`1-2 anos ok`, `Até 5 anos`, `Nem pensar`, `Sem limite`] },
    ],
    faq: [
      { q: `O TikTok tem enquete nativa?`, a: `Não. Dá pra fazer perguntas no vídeo ou nos comentários, mas não tem um contador de votos. Usa o moomz e linka na bio.` },
      { q: `O link do moomz funciona na bio?`, a: `Sim — é tratado como qualquer link externo. Cabe no limite de caracteres da bio. As legendas só aceitam link clicável pra contas business.` },
      { q: `Posso usar a mesma enquete em vários vídeos?`, a: `Sim. O mesmo link do moomz pode ser usado em vários TikToks. Ou troca por vídeo pra ter um sinal mais fresco.` },
      { q: `Os votos são anônimos?`, a: `Sim. O moomz nunca liga um voto a um perfil. Quem te assiste pode responder com sinceridade, sem pressão social.` },
    ],
    related: ["instagram-story-poll-pt", "snapchat-poll-pt", "drama-polls-pt", "first-date-en-pt"],
    updatedAt: today,
  },
  {
    slug: "snapchat-poll-pt",
    locale: "pt",
    category: "ideas",
    emoji: "👻",
    title: `Enquetes pro Snapchat — 30 perguntas pra Stories e grupos`,
    h1: `Enquetes no Snapchat: 30 ideias pra Stories e grupos`,
    description: `O Snapchat não tem enquete nativa. Aqui está como adicionar uma no teu Story ou grupo + 30 ideias que funcionam.`,
    intro: `O Snapchat não tem enquete. A maioria do povo ou manda DM pros amigos pra pedir opinião ou conta reação de emoji — os dois são lentos. Cola um link do moomz no teu Story (ferramenta de link) ou no grupo, os votos chegam, e os resultados continuam acessíveis depois que o Story sumir.`,
    sections: [
      {
        h: `Adicionar um link no Story do Snap`,
        body: `Na hora de criar o Story, toca na ferramenta de clipe de papel na direita. Cola a URL do moomz. Teus amigos veem um botão "Ver mais". Tocam, votam no navegador e voltam pro Story. Zero atrito.`,
      },
      {
        h: `Enquetes no grupo`,
        body: `Cola o link em qualquer grupo. Todo mundo vê uma prévia e pode tocar pra votar sem sair da conversa. Bem melhor que a guerra de mensagens onde metade do grupo perde a pergunta porque estava ausente.`,
      },
      {
        h: `Enquetes que funcionam pros adolescentes`,
        body: `Top 3: "quem do nosso grupo é…" (o mais barulhento, o mais fofo, o mais chato), enquete de decisão ("pra onde a gente vai hoje?"), enquete de treta ("ele tava errado?"). Foge de muitas opções — quem usa o Snap rola rápido, máximo 4.`,
      },
      {
        h: `Mantendo privado`,
        body: `Os links do moomz não aparecem em buscador por padrão. Só quem tem o link acha a enquete. Compartilha num grupo específico pra votos privados. Não posta na página pública de Stories se quiser manter discreto.`,
      },
    ],
    polls: [
      { q: `Quem é o mais barulhento do grupo?`, options: [`Lucas`, `Sarah`, `Théo`, `Léa`] },
      { q: `Pra onde a gente vai hoje?`, options: [`Bar`, `Minha casa`, `Parque`, `Ficar em casa`] },
      { q: `Quem é o mais engraçado?`, options: [`Eu, óbvio`, `Você`, `Ele/ela`, `Ninguém`] },
      { q: `Cinema ou boliche?`, options: [`Cinema`, `Boliche`, `Nenhum`] },
      { q: `Quem leva os petiscos?`, options: [`Eu`, `Você`, `Pedir`, `Surrupiar`] },
      { q: `Responder ele/ela?`, options: [`Agora`, `Amanhã`, `Nunca`, `Filtra pra mim`] },
      { q: `Melhor filme de 2026?`, options: [`Duna 3`, `Avatar 4`, `Outro`, `Não vi nenhum`] },
      { q: `Quem deu o gelo primeiro?`, options: [`Ele`, `Ela`, `Os dois ao mesmo tempo`] },
      { q: `Time vermelho ou azul?`, options: [`Vermelho`, `Azul`, `Sem time`] },
      { q: `Conta a verdade pra Léa?`, options: [`Sim`, `Não`, `Você que sabe`] },
    ],
    faq: [
      { q: `O Snapchat tem figurinha de enquete?`, a: `Não. Usa um link do moomz no teu Story (ferramenta de clipe de papel) ou num grupo.` },
      { q: `Como adiciono um link no Story do Snap?`, a: `Enquanto cria, toca no clipe de papel nas ferramentas do lado direito. Cola a URL do moomz. Pronto.` },
      { q: `Meus amigos precisam de conta?`, a: `Não. O moomz funciona sem cadastro. O link abre, eles votam, vão embora.` },
      { q: `A enquete some junto com o Story?`, a: `Não. O Story dura 24h; a enquete continua ativa. Compartilha o link de novo amanhã pra manter os votos rolando.` },
    ],
    related: ["instagram-story-poll-pt", "tiktok-poll-pt", "teens-en-pt", "friends-en-pt"],
    updatedAt: today,
  },
  {
    slug: "discord-poll-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🎮",
    title: `Enquetes pro Discord — 30 ideias pra servidores e comunidades`,
    h1: `Enquetes no Discord: 30 ideias pra engajar teu servidor`,
    description: `Esquece a configuração de bot. Cola um link do moomz em qualquer canal do Discord e tua comunidade vota anônima. 30 ideias aqui dentro.`,
    intro: `O comando de enquete nativo do Discord é ok pra votação rápida, mas limita a 10 opções e um servidor só. As soluções de bot (MEE6, Simple Poll) precisam de instalação + permissões. moomz: só cola o link, qualquer um vota, os resultados ficam ao vivo. Aqui está como usar direito.`,
    sections: [
      {
        h: `Nativo vs bot vs link do moomz`,
        body: `Comando /poll nativo: grátis, 10 opções, preso ao servidor. Bots: mais recursos, mas instalação + permissões. moomz: instantâneo, anônimo, sem precisar de permissão, compartilhável fora do Discord. Escolhe conforme a tua necessidade.`,
      },
      {
        h: `Enquetes de comunidade que funcionam`,
        body: `Os servidores top rodam uma enquete semanal no #votação: melhor build do mês (gaming), veredito do patch, ranking de skin. Pra servidores de debate: opiniões polêmicas, dilemas morais, opiniões controversas.`,
      },
      {
        h: `Fixando a enquete`,
        body: `Cria a enquete, fixa a mensagem no teu canal principal. Os votos continuam chegando por dias. Encerra dando print no resultado e postando no #anúncios.`,
      },
      {
        h: `Organização de eventos`,
        body: `Usa o moomz pra horário de raid, noite de jogo, novos canais. Os mods veem o resultado ao vivo sem ter que contar reação de emoji.`,
      },
    ],
    polls: [
      { q: `Jogo pra próxima noite de call?`, options: [`LoL`, `Valorant`, `Fortnite`, `Among Us`, `Minecraft`] },
      { q: `Melhor patch do ano?`, options: [`S1`, `S2`, `S3`, `Todos péssimos`] },
      { q: `Novo canal pra adicionar?`, options: [`#memes`, `#trade`, `#arte`, `#offtopic`] },
      { q: `O novo personagem tá OP?`, options: [`Sim, nerfa`, `Equilibrado`, `Buffa`, `Não joguei`] },
      { q: `Estilo de RP preferido?`, options: [`Cheio de lore`, `Casual`, `Foco em PVP`, `Sem RP`] },
      { q: `Foto do ano (post de meme)?`, options: [`O doge`, `O gato`, `O sapo`, `Nenhuma`] },
      { q: `Mantém o sistema de níveis?`, options: [`Sim, é divertido`, `Não, é cringe`, `Zera todo mês`] },
      { q: `Bot pra adicionar?`, options: [`MEE6`, `Carl-bot`, `Nenhum`] },
      { q: `Skin favorita?`, options: [`Skin A`, `Skin B`, `Skin C`, `Padrão`] },
      { q: `Horário da raid de sábado?`, options: [`18h`, `20h`, `21h`, `22h`] },
    ],
    faq: [
      { q: `Preciso de um bot?`, a: `Não. Cola o link do moomz em qualquer canal, o Discord mostra uma prévia bonita, e a galera toca pra votar.` },
      { q: `É anônimo?`, a: `Sim. Nenhum nome do Discord ligado aos votos. A galera vota sem pressão social.` },
      { q: `Quantas opções?`, a: `2 a 6 no moomz. Acima disso, a taxa de conclusão cai. Pra 8-12 opções, usa o /poll nativo.` },
      { q: `A enquete expira?`, a: `Não, a menos que fique parada por semanas (anti-spam). Mantém viva compartilhando de novo.` },
    ],
    related: ["tiktok-poll-pt", "team-building-en-pt", "high-school-en-pt", "college-en-pt"],
    updatedAt: today,
  },
  {
    slug: "couple-questions-pt",
    locale: "pt",
    category: "ideas",
    emoji: "💖",
    title: `Perguntas de enquete pra casal — 50 ideias pra testar a sintonia`,
    h1: `Enquetes de casal: 50 perguntas pra fazer pro seu par`,
    description: `50 perguntas de enquete anônima pra casais — de preferências leves até papo sério. Testa a sintonia em 30 segundos.`,
    intro: `Uma enquete dribla o filtro social. Teu par escolhe uma opção em vez de enfeitar uma resposta. É por isso que terapeutas de casal começaram a recomendar isso em 2025. Aqui vão 50 perguntas, organizadas por nível de risco.`,
    sections: [
      {
        h: `Por que enquete bate conversa`,
        body: `Dois vícios atrapalham as perguntas diretas: (1) querer agradar, (2) tempo pra pensar. A enquete neutraliza os dois — escolha binária, clique no instinto. Você consegue um dado mais limpo que numa conversa de verdade.`,
      },
      {
        h: `Nível 1: preferências tranquilas`,
        body: `Começa leve: apartamento na praia ou na montanha, café ou chá de manhã, sair ou ficar em casa. Cria o hábito primeiro. Quando enquete virar algo normal, dá pra ir mais fundo.`,
      },
      {
        h: `Nível 2: decisões do dia a dia`,
        body: `Fica em casa ou sai hoje? Comida japonesa ou italiana por delivery? Visitar a sogra esse fim de semana? A enquete transforma debate de 30 minutos em decisão de 30 segundos.`,
      },
      {
        h: `Nível 3: as perguntas de verdade`,
        body: `Casamento daqui a 5 anos? Filhos sim ou não? Morar fora se a proposta vier? Usa anônimo, nunca depois de uma briga. A enquete abre a conversa — não substitui ela.`,
      },
    ],
    polls: [
      { q: `Café na cama ou na cozinha?`, options: [`Sempre na cama`, `Cozinha`, `Sem café`] },
      { q: `Férias: praia ou montanha?`, options: [`Praia`, `Montanha`, `Os dois`, `Ficar em casa`] },
      { q: `Você prefere:`, options: [`Noite tranquila em casa`, `Jantarzinho com poucos`, `Festão`, `Sem preferência`] },
      { q: `Casamento daqui a 5 anos?`, options: [`Sim`, `Mais pra frente`, `Não é pra mim`, `Talvez`] },
      { q: `Filhos?`, options: [`Sim, 1`, `Sim, 2+`, `Nunca`, `Não decidi`] },
      { q: `Morar fora se rolar uma proposta?`, options: [`Sim, sem pensar`, `Depende`, `Não, quero ficar`] },
      { q: `Festa surpresa de aniversário?`, options: [`Amo`, `Me estressa`, `Depende de quem`] },
      { q: `Posição pra dormir?`, options: [`Grudados`, `Lado a lado`, `Cada um pro seu canto`] },
      { q: `Salário transparente no casal?`, options: [`Transparência total`, `Valores por cima`, `Cada um na sua`] },
      { q: `Ex no Instagram?`, options: [`Tanto faz`, `Me incomoda`, `Deixar de seguir juntos`] },
    ],
    faq: [
      { q: `Meu par vai ver que eu criei a enquete?`, a: `Não. O link compartilhado não mostra quem criou. Dá pra criar no modo anônimo do navegador pra negar tudo com segurança.` },
      { q: `Dá pra ver quem votou em quê?`, a: `Não. O moomz é totalmente anônimo. Você só vê porcentagem.` },
      { q: `Só dois votando — ainda é anônimo?`, a: `Tecnicamente sim, mas óbvio que dá pra deduzir. Adiciona 2-3 amigos pra anonimato de verdade, ou usa pra respostas reveladas.` },
      { q: `Como manter o hábito?`, a: `Uma enquete por noite durante uma semana. 5 minutos pra votar, 10 pra discutir o resultado. Bem mais envolvente que "como foi seu dia".` },
    ],
    related: ["first-date-en-pt", "this-or-that-pt", "would-you-rather-en-pt", "valentines-en-pt"],
    updatedAt: today,
  },
  {
    slug: "first-date-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🌹",
    title: `Enquetes quebra-gelo pra primeiro encontro — 30 perguntas pra salvar o clima`,
    h1: `Enquetes pra primeiro encontro: 30 perguntas quebra-gelo que funcionam de verdade`,
    description: `30 enquetes quebra-gelo pra primeiro encontro. Saca o celular, roda uma votação rápida e salva a conversa do silêncio constrangedor.`,
    intro: `Primeiro encontro travando lá pelos 30 minutos? Saca o celular, fala "tenho esse app meio bobo — quer testar?", roda uma enquete rapidinha. Os dois votam, os dois veem o resultado, e pronto: 10 minutos de conversa nova destravados.`,
    sections: [
      {
        h: `Quando usar (e quando não)`,
        body: `Hora boa: 30 minutos de papo, depois que o assunto secou. Hora ruim: na hora de pedir a bebida. Jeito ruim de apresentar: "vim com um roteiro". Jeito bom: "descobri esse negócio bobo agora".`,
      },
      {
        h: `Enquetes de paquera que funcionam`,
        body: `Foge de intimidade no começo (política, religião, ex, sexualidade). Fica nas preferências: viagem, comida, estilo de festa, animais, hobbies. Guarda os assuntos pesados pro segundo ou terceiro encontro.`,
      },
      {
        h: `Truque do voto de olho fechado`,
        body: `Faz a pergunta. Os dois fecham os olhos por 5 segundos. Votam separados. Revelam juntos. Tira o efeito "vota o que o outro quer ouvir". A verdade aparece mais rápido.`,
      },
      {
        h: `Enquetes pra evitar no primeiro encontro`,
        body: `Qualquer coisa que te coloque no modo juiz ("você acha que eu sou X demais?"). Enquetes-armadilha ("dormir juntos hoje?"). Política, religião, ex. Mantém leve, a enquete é um joguinho, não uma entrevista.`,
      },
    ],
    polls: [
      { q: `Cachorro ou gato?`, options: [`Cachorro`, `Gato`, `Os dois`, `Nenhum`] },
      { q: `Praia ou montanha?`, options: [`Praia`, `Montanha`, `Cidade`, `Aventura`] },
      { q: `Café da manhã: doce ou salgado?`, options: [`Salgado`, `Doce`, `Os dois`, `Pulo`] },
      { q: `Hoje à noite: rolê ideal?`, options: [`Restaurante`, `Cinema`, `Bar`, `Ficar em casa`] },
      { q: `Karaokê, encara ou passa?`, options: [`Amo`, `Se tiver bebido`, `Nunca`, `Só pra assistir`] },
      { q: `Você cozinha?`, options: [`Sempre`, `Às vezes`, `Nunca`, `Tô tentando`] },
      { q: `Esporte pra assistir?`, options: [`Futebol`, `Tênis`, `F1`, `Nenhum`] },
      { q: `Festas — qual é o teu clima?`, options: [`Tranquilo a dois`, `Grupinho pequeno`, `Festão`, `Sozinho`] },
      { q: `Gênero de filme?`, options: [`Ação`, `Comédia`, `Drama`, `Terror`] },
      { q: `Hora de acordar?`, options: [`Antes das 7h`, `7-9h`, `9-11h`, `Depois do meio-dia`] },
    ],
    faq: [
      { q: `Sacar uma enquete não é cringe?`, a: `Só se você apresentar errado. "Tenho esse negócio bobo" funciona. Se não colar, você já aprendeu algo sobre a sintonia de vocês.` },
      { q: `Quantas enquetes num encontro?`, a: `Máximo 3 a 5. Mais que isso vira um quiz, não um encontro.` },
      { q: `A gente concordou em tudo — bom sinal?`, a: `Ou é ótimo, ou os dois estão mentindo. Aumenta o nível de risco nas próximas perguntas.` },
      { q: `A gente discordou em tudo — fim de papo?`, a: `Raramente. Vocês só destravaram 10 assuntos de conversa.` },
    ],
    related: ["couple-questions-pt", "valentines-en-pt", "would-you-rather-en-pt", "this-or-that-pt"],
    updatedAt: today,
  },
  {
    slug: "friends-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🤝",
    title: `Enquetes pro grupo de amigos — 50 ideias pra grupo e na vida real`,
    h1: `Enquetes pro grupo de amigos: 50 ideias pra decidir e debater`,
    description: `50 enquetes pro teu grupo de amigos: decisões, tier lists, debates. Usa no WhatsApp, no Discord ou em festas presenciais.`,
    intro: `Teu grupo tem dois modos: decisão (onde a gente come?) e debate (quem é o mais barulhento?). Enquete resolve os dois. Cola um link do moomz, marca um prazo de 1 hora, dá print no resultado. Adeus, rolagem infinita no WhatsApp.`,
    sections: [
      {
        h: `Enquete de decisão: mata o ruído do grupo`,
        body: `Onde a gente come? Qual filme? Qual viagem? Sem enquete: 30 mensagens, metade ignorada. Com enquete: 5 minutos, resolvido. Truque: anuncia um prazo ("votação fecha às 19h").`,
      },
      {
        h: `Enquete de tier list: a comédia garantida`,
        body: `Ranking do grupo: o mais barulhento, o mais fofo, o mais provável de dar gelo. Voto anônimo, sinceridade brutal. Guarda pra grupos que aguentam o tranco.`,
      },
      {
        h: `Enquete de debate: opiniões polêmicas`,
        body: `"Coentro é o capeta?", "abacaxi na pizza?", "o grupo é ativo demais?". Não é sobre resolver — é sobre descobrir como teu grupo se divide.`,
      },
      {
        h: `Enquetes de surpresa de aniversário`,
        body: `Planejando uma festa surpresa? Cria um subgrupo sem o aniversariante, roda todas as enquetes lá. O moomz não notifica ninguém — sem vazamento.`,
      },
    ],
    polls: [
      { q: `Quem é o mais barulhento hoje?`, options: [`Lucas`, `Sarah`, `Théo`, `Léa`] },
      { q: `Onde a gente vai sexta?`, options: [`Bar de sempre`, `Lugar novo`, `Minha casa`, `Restaurante`] },
      { q: `Presente de aniversário pra Léa?`, options: [`Flores`, `Jantar`, `Vale-presente`, `Vaquinha`] },
      { q: `Quem nunca leva nada?`, options: [`Théo`, `Camille`, `Eu (assumo)`, `Todo mundo paga`] },
      { q: `Abacaxi na pizza?`, options: [`Sim`, `Jamais`, `Sei lá`] },
      { q: `Viagem de fim de semana?`, options: [`Litoral`, `Montanha`, `Cidade`, `Ficar em casa`] },
      { q: `Tema da festa de sexta?`, options: [`Anos 2000`, `Pijama`, `Disco`, `Sem tema`] },
      { q: `Chama o Marc?`, options: [`Sim`, `Não, sei lá`, `Se a Léa topar`] },
      { q: `Bebida que horas?`, options: [`18h`, `19h`, `20h`, `Mais tarde`] },
      { q: `Quem paga o Uber?`, options: [`Vaquinha`, `Quem chegar primeiro`, `Cada um o seu`] },
    ],
    faq: [
      { q: `Os amigos vão ver quem criou a enquete?`, a: `Não. Tanto quem cria quanto quem vota são anônimos no link compartilhado.` },
      { q: `Quantos amigos podem votar?`, a: `Ilimitado. 4 ou 400, funciona.` },
      { q: `Como encerro a votação?`, a: `Não tem encerramento manual. Anuncia um prazo, dá print no resultado na hora do prazo e declara encerrado.` },
      { q: `E se alguém votar duas vezes?`, a: `Não consegue. O moomz bloqueia voto duplicado via cookie. Uma pessoa = um voto.` },
    ],
    related: ["bff-en-pt", "party-en-pt", "drama-polls-pt", "would-you-rather-en-pt"],
    updatedAt: today,
  },
  {
    slug: "bff-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "👯",
    title: `Perguntas de enquete pra BFF — 30 ideias pra testar a melhor amiga`,
    h1: `Enquetes pra BFF: 30 perguntas pra testar a amizade com a melhor amiga`,
    description: `30 enquetes anônimas pra testar o quanto você conhece a tua BFF — e o quanto ela te conhece. Sinceras, engraçadas, às vezes brutais.`,
    intro: `Vocês acham que se conhecem de cor. Sério? 30 enquetes pra testar a amizade — engraçadas, íntimas, às vezes brutais. O modo anônimo garante respostas sinceras, sem aquele ajuste diplomático.`,
    sections: [
      {
        h: `Formato quiz de BFF`,
        body: `Cria 10 enquetes, manda os links pra tua BFF. As duas votam separadas, comparam no dia seguinte. Bate o quiz padrão de BFF do Insta porque as respostas são anônimas — sem pressão pra dar a resposta "certa".`,
      },
      {
        h: `Perguntas que revelam de verdade`,
        body: `Pula o óbvio (cor favorita). Vai pro nível 2: quem é mais chata, quem paga mais, quem julga melhor os ex. Empurra mais: quem é mais ciumenta, quem sobreviveria se a outra desse o gelo.`,
      },
      {
        h: `Surpresa de aniversário por enquete`,
        body: `No aniversário dela, roda uma enquete "o que mais define a Léa?" com o grupo. Opções: "sempre atrasada", "a mais engraçada", "paga sempre". Dá print no resultado e manda como presente. Pega mais que um "feliz aniversário".`,
      },
      {
        h: `Sintonia de BFF`,
        body: `5 enquetes sobre dilemas: "perde a viagem ou perde o cara", "conta que o namorado dela traiu ou fica calada", "empresta R$2 mil que nunca mais vê ou diz não". Você mede o quanto vocês pensam parecido.`,
      },
    ],
    polls: [
      { q: `Quem paga com mais frequência?`, options: [`Eu`, `Você`, `Meio a meio`] },
      { q: `Quem se atrasa mais?`, options: [`Eu`, `Você`, `Igual`] },
      { q: `Quem é mais engraçada?`, options: [`Eu, óbvio`, `Você`, `Empate`] },
      { q: `Conta pra ela sobre o namorado?`, options: [`Sim, na lata`, `Não é da nossa conta`, `Depende`] },
      { q: `Se eu desse o gelo, o que você faria?`, options: [`Chorava uma semana`, `Superava em 2 meses`, `Vinha me buscar`] },
      { q: `Quem é mais ciumenta?`, options: [`Eu`, `Você`, `Nenhuma`] },
      { q: `Quem é mais leal?`, options: [`Eu`, `Você`, `Meio a meio`] },
      { q: `Restaurante que a gente brigaria pra escolher?`, options: [`Sushi`, `Italiano`, `Hambúrguer`, `Vegano`] },
      { q: `Viagem juntas — qual seria o atrito?`, options: [`Horários`, `Dinheiro`, `Música`, `A gente é perfeita`] },
      { q: `Se pudesse mudar uma coisa em mim?`, options: [`Minha preguiça`, `Meu ciúme`, `Meus desabafos`, `Nada`] },
    ],
    faq: [
      { q: `Minha BFF vai saber que eu criei?`, a: `Vai, se você mandar direto. Pra testar pelo grupo, o anonimato se mantém.` },
      { q: `Ideia de presente de aniversário?`, a: `Roda 5 enquetes "quem mais descreve a Léa?" pro grupo. O print final vira um presente fofo.` },
      { q: `Quiz conjunto?`, a: `Sim — cada uma cria 5 enquetes, trocam os links, as duas respondem 10 e comparam.` },
      { q: `E se a resposta machucar?`, a: `Risco do jogo. Se você quer saber, vota. Se não, não cria a enquete.` },
    ],
    related: ["friends-en-pt", "party-en-pt", "would-you-rather-en-pt", "drama-polls-pt"],
    updatedAt: today,
  },
  {
    slug: "party-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🎉",
    title: `Enquetes pra festa — 40 ideias pra animar qualquer noite`,
    h1: `Enquetes pra festa: 40 ideias pra festa em casa e afters`,
    description: `40 enquetes pra festa pra jogar no teu grupo — quebra-gelos, tier lists, debates. Do começo da noite até a decisão das 3 da manhã.`,
    intro: `As festas que dão certo têm uma coisa em comum: um assunto pra discutir. Enquete é gatilho de debate na hora. Cola a pergunta, todo mundo vota, e dois minutos depois vocês estão discutindo como alguém pode ter escolhido aquilo.`,
    sections: [
      {
        h: `Começo da noite: enquetes quebra-gelo`,
        body: `Quando o povo ainda tá em rodinhas separadas, cola uma enquete no grupo. "Quem tá atrasado hoje?", "o que a gente pede pra petiscar?". Puxa o grupo todo pra uma conversa só.`,
      },
      {
        h: `Fim da noite: enquetes de tier list`,
        body: `Lá pelas 22h, cola a tier list do grupo de amigos. "Quem é o mais chato?", "quem nunca leva nada?". O debate dura 30 min. Aviso: sinceridade brutal, só pra grupos que aguentam.`,
      },
      {
        h: `Madrugada: enquetes de debate`,
        body: `1h da manhã, metade do grupo já foi. Os sobreviventes querem papo de verdade. Cola polêmicas filosóficas: "relacionamento aberto é válido?", "pode voltar a falar com um ex?". Mantém o clima civil, recarrega a energia.`,
      },
      {
        h: `3h da manhã: enquetes de decisão`,
        body: `Onde a gente dorme? Pede pizza? Para? Roda uma enquete de 30 segundos, segue o resultado. Único momento da noite em que todo mundo respeita o veredito porque ninguém tem energia pra debater de novo.`,
      },
    ],
    polls: [
      { q: `Pedir o quê?`, options: [`Pizza`, `Sushi`, `Tacos`, `Nada mais`] },
      { q: `Quem é o mais barulhento hoje?`, options: [`Lucas`, `Théo`, `Sarah`, `Eu`] },
      { q: `Pra onde depois?`, options: [`Minha casa`, `A tua`, `Balada`, `Casa`] },
      { q: `Chill ou dançar?`, options: [`Chill`, `Dançar`, `Karaokê`, `Silêncio`] },
      { q: `Pior ex da sala?`, options: [`O meu`, `O teu`, `O dele/dela`, `Não fala`] },
      { q: `Relacionamento aberto — válido?`, options: [`Sim`, `Não`, `Pra alguns`, `Depende`] },
      { q: `Casar aos 30?`, options: [`Romântico`, `Pressão`, `Ultrapassado`, `Legal se for escolha`] },
      { q: `Jogar alguma coisa?`, options: [`Verdade ou desafio`, `Máfia`, `Karaokê`, `Só conversar`] },
      { q: `Pior esporte olímpico?`, options: [`Adestramento`, `Tiro com arco`, `Marcha atlética`, `Curling`] },
      { q: `Quem dorme aqui hoje?`, options: [`Eu`, `Você`, `Ninguém`, `Todo mundo`] },
    ],
    faq: [
      { q: `Quantas pessoas podem votar?`, a: `Sem limite. 8, 30, funciona.` },
      { q: `Precisa de Wi-Fi?`, a: `Sim pra carregar. Depois de carregado, os votos funcionam até no modo avião.` },
      { q: `Os amigos precisam de app?`, a: `Não. Abre em qualquer navegador. Sem cadastro.` },
      { q: `Jeito mais rápido de compartilhar na festa?`, a: `Três opções: (1) manda o link por AirDrop pra todo mundo, (2) cola no grupo do WhatsApp, (3) mostra a tela e deixa o povo digitar a URL de 5 caracteres.` },
    ],
    related: ["friends-en-pt", "birthday-en-pt", "would-you-rather-en-pt", "drama-polls-pt"],
    updatedAt: today,
  },
  {
    slug: "birthday-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🎂",
    title: `Enquetes pra festa de aniversário — 30 ideias pra quem organiza`,
    h1: `Enquetes de aniversário: 30 ideias pra planejar e receber`,
    description: `30 enquetes de aniversário pra quem organiza: presente, data, surpresa, tema. Mais enquetes pra usar como entretenimento durante a festa.`,
    intro: `Organizar um aniversário de 15 pessoas significa 200 mensagens no WhatsApp sobre data, lugar, presente. O moomz resolve isso em 30 minutos. No dia, as enquetes viram entretenimento: tier lists, "o que descreve o aniversariante", jogos de memória.`,
    sections: [
      {
        h: `Antes da festa: as 4 enquetes essenciais`,
        body: `1) Data (3-4 opções de fim de semana). 2) Lugar (casa de alguém, restaurante, bar). 3) Presente (4-5 opções, inclui "vaquinha coletiva"). 4) Surpresa sim/não. Espaça elas de 24h em 24h, não enche o grupo.`,
      },
      {
        h: `Durante: enquetes de entretenimento`,
        body: `Roda "o que descreve melhor o(a) [aniversariante]?" com opções que o grupo enviou. Mostra o resultado na TV ou lê na hora do bolo. Momento de memória coletiva.`,
      },
      {
        h: `Enquete de presente coletivo`,
        body: `Em vez de 3 horas de debate, roda 4 opções de presente com orçamento definido. A maioria ganha, vaquinha lançada via Pix. Adeus "eu queria outra coisa".`,
      },
      {
        h: `Enquete de retrospectiva do ano`,
        body: `Pra um aniversário de fim de ano, roda uma enquete de retrospectiva: melhor momento com o(a) [aniversariante], melhor festa, melhor mancada. 6 opções tiradas das fotos do grupo. O resultado vira um presente emocionante.`,
      },
    ],
    polls: [
      { q: `Data do aniversário da Léa?`, options: [`Sex 12`, `Sáb 13`, `Sáb 20`, `Mês que vem`] },
      { q: `Onde?`, options: [`Casa da Léa`, `Minha casa`, `Restaurante`, `Bar`] },
      { q: `Surpresa?`, options: [`Sim`, `Não, ela odeia surpresa`, `Revelação pequena`] },
      { q: `Presente coletivo?`, options: [`Vale-presente de R$200`, `Jantar pra 6`, `Fim de semana de spa`, `Vaquinha em dinheiro`] },
      { q: `Tema?`, options: [`Disco`, `Pastel`, `Anos 2000`, `Sem tema`] },
      { q: `Bolo — quem traz?`, options: [`Eu`, `Você`, `Encomendar`, `Fazer em casa`] },
      { q: `Fotos: profissional ou celular?`, options: [`Fotógrafo`, `Polaroid`, `Celular tá bom`, `Sem fotos`] },
      { q: `O que melhor descreve o aniversariante?`, options: [`O mais engraçado`, `O mais generoso`, `Sempre atrasado`, `O mais corajoso`] },
      { q: `Karaokê de entretenimento?`, options: [`Sim`, `Não, é cringe`, `Se for bem ensaiado`] },
      { q: `Hora do bolo?`, options: [`21h`, `22h`, `Meia-noite`, `Quando der fome`] },
    ],
    faq: [
      { q: `Como evitar o debate infinito sobre o presente?`, a: `4 opções numa enquete, fecha em 24h. A maioria ganha. Quem não gostar coloca uma graninha pessoal.` },
      { q: `Como manter a surpresa no WhatsApp?`, a: `Subgrupo sem o aniversariante, roda as enquetes lá. O moomz não vaza nada.` },
      { q: `Ideia original de aniversário?`, a: `Antes da festa, roda "descreva o(a) [nome] em uma palavra" com 6 opções. Mostra na hora do brinde. Momento emocionante.` },
      { q: `Aniversário infantil?`, a: `Adapta as opções pro mundo deles: super-herói favorito, sobremesa, jogo. As crianças amam votar.` },
    ],
    related: ["party-en-pt", "family-en-pt", "bachelorette-en-pt", "bachelor-en-pt"],
    updatedAt: today,
  },
  {
    slug: "wedding-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "💍",
    title: `Enquetes pra casamento — 40 ideias pra noivos e convidados`,
    h1: `Enquetes de casamento: 40 ideias pra planejar e receber`,
    description: `40 enquetes pra casais organizando um casamento: local, buffet, vestido, mais enquetes pra convidados sobre alergias, hospedagem e entretenimento.`,
    intro: `Organizar casamento = 50 decisões, cada uma com opiniões fortes. O moomz cuida de dois níveis: decisões dos noivos (local, buffet, fotógrafo) e opinião dos convidados (restrições alimentares, dividir quarto, criança convidada). Mais enquetes de entretenimento no grande dia.`,
    sections: [
      {
        h: `Enquetes de preparação: decisões dos noivos`,
        body: `Todo domingo, roda uma grande decisão por enquete. Os dois votam separados, comparam e só discutem nas discordâncias. Corta o tempo de decisão em 80%.`,
      },
      {
        h: `Enquetes pros convidados: antes do casamento`,
        body: `Cria enquetes pros detalhes da confirmação: dieta (onívoro / vegetariano / vegano / sem glúten), criança sim/não, hospedagem sim/não, transporte compartilhado. Coleta tudo em 2 dias em vez de 200 mensagens individuais.`,
      },
      {
        h: `No dia: enquetes de entretenimento`,
        body: `Durante o coquetel, roda "como o casal se conheceu?" com 4 opções, uma delas a verdadeira. Os convidados votam, a noiva revela. Quebra-gelo perfeito. Ou: "quem tem mais chance de estar bêbado até a meia-noite?" — arriscado, mas hilário.`,
      },
      {
        h: `Depois do casamento: retrospectiva`,
        body: `Dias depois, roda "melhor momento do casamento?" com os convidados. Opções tiradas das fotos: cerimônia, primeiro beijo, primeira dança, bolo, brinde. Monta uma retrospectiva democrática pra um mini álbum de fotos.`,
      },
    ],
    polls: [
      { q: `Vestido: sereia, princesa ou boho?`, options: [`Sereia`, `Princesa`, `Boho`, `Nenhum dos três`] },
      { q: `Local: castelo, vinícola ou praia?`, options: [`Castelo`, `Vinícola`, `Praia`, `Salão clássico`] },
      { q: `Buffet:`, options: [`Jantar de coquetel`, `Prato servido em 3 etapas`, `Food trucks`, `Bufê`] },
      { q: `DJ ou banda ao vivo?`, options: [`DJ`, `Banda`, `Os dois`, `Só playlist`] },
      { q: `Open bar ou bar pago?`, options: [`Open bar`, `Open bar com limites`, `Bar pago`, `Só vinho da casa`] },
      { q: `Crianças convidadas?`, options: [`Todas`, `Só sobrinhos`, `Nenhuma`] },
      { q: `Primeira dança?`, options: [`Lenta clássica`, `Coreografada`, `Surpresa`, `Sem primeira dança`] },
      { q: `Dieta dos convidados?`, options: [`Onívoro`, `Vegetariano`, `Vegano`, `Sem glúten`] },
      { q: `Quarto compartilhado?`, options: [`Sim`, `Cada um se vira`, `Só família`] },
      { q: `Melhor momento do casamento?`, options: [`Cerimônia`, `Primeiro beijo`, `Primeira dança`, `Discurso do padrinho`] },
    ],
    faq: [
      { q: `Quantos convidados podem votar?`, a: `Sem limite. 50, 200, funciona numa boa.` },
      { q: `Como manter a enquete privada pros convidados?`, a: `Os links do moomz não aparecem em buscador. Compartilha só no grupo do WhatsApp dos convidados. Quem não tem o link não acha.` },
      { q: `Enquete anônima pra escolher o padrinho?`, a: `Sim — roda "quem deveria fazer o discurso principal?" com opções. Os votos são anônimos, o resultado é compartilhado.` },
      { q: `Como cobrar quem não votou?`, a: `O moomz não rastreia identidade. Compartilha o link de novo no grupo com "faltam 5 votos".` },
    ],
    related: ["bachelorette-en-pt", "bachelor-en-pt", "family-en-pt", "birthday-en-pt"],
    updatedAt: today,
  },
  {
    slug: "bachelorette-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "💃",
    title: `Enquetes pra despedida de solteira — 30 ideias pra planejar`,
    h1: `Enquetes pra despedida de solteira: planeje e comande a despedida perfeita`,
    description: `30 enquetes pra planejar despedida de solteira: destino, tema, atividades. Mais enquetes de quiz pra noite em si.`,
    intro: `Planejar despedida de solteira significa 4-8 amigas com 4-8 opiniões. O moomz corta o debate pra 5 minutos. No dia, as enquetes viram jogo de festa: "quem conhece melhor a noiva", "primeira coisa que ela disse pro noivo".`,
    sections: [
      {
        h: `Antes da festa: 4 decisões rápidas`,
        body: `Roda 4 enquetes de 24h em 24h: (1) cidade, (2) tema (chique, esportivo, balada, spa), (3) orçamento por cabeça, (4) duração. Projeto fechado em 96h, com só os detalhes pequenos faltando.`,
      },
      {
        h: `Na noite: enquetes de quiz sobre a noiva`,
        body: `Durante o jantar, roda "quem conhece melhor a Léa?" com 5 perguntas de quiz (primeiro beijo, cidade dos sonhos, animal favorito). Cada uma vota às cegas, comparem no final. Quem perder paga as doses.`,
      },
      {
        h: `Enquete de memória`,
        body: `Antes do evento, coleta memórias das amigas. Roda uma enquete "melhor memória com a Léa" com 6 opções. Mostra o resultado durante a noite. Momento de presente emocionante.`,
      },
      {
        h: `Enquete de jogo da verdade`,
        body: `Depois de algumas bebidas, roda uma enquete anônima "pior memória com a Léa". Anonimato = sinceridade. Lê os resultados em voz alta, filtra os pesados, guarda as pérolas pra um brinde estilo zoeira.`,
      },
    ],
    polls: [
      { q: `Cidade da despedida de solteira?`, options: [`Paris`, `Lisboa`, `Barcelona`, `Marrakech`, `Berlim`] },
      { q: `Tema?`, options: [`Jantar chique`, `Aventura esportiva`, `Balada`, `Spa relax`] },
      { q: `Orçamento por cabeça?`, options: [`R$300-400`, `R$400-700`, `R$700-1000`, `R$1000+`] },
      { q: `Duração?`, options: [`1 dia`, `Fim de semana`, `3 dias`, `4-5 dias`] },
      { q: `Atividade?`, options: [`Aula de dança`, `Workshop de coquetéis`, `Spa`, `Escape room`] },
      { q: `Fantasia temática?`, options: [`Engraçada`, `Chique`, `Nenhuma`, `Branco minimalista`] },
      { q: `Surpresa pra noiva?`, options: [`Vídeo do noivo`, `Discurso das amigas`, `Presente especial`, `Já tá planejado`] },
      { q: `Primeiro beijo da Léa?`, options: [`Aos 14`, `Aos 15`, `Aos 16`, `Mais tarde`] },
      { q: `Cidade dos sonhos da Léa?`, options: [`Paris`, `Tóquio`, `Nova York`, `Bali`] },
      { q: `Quem chora mais na cerimônia?`, options: [`Noiva`, `Mãe`, `Noivo`, `Madrinha`] },
    ],
    faq: [
      { q: `Como manter a despedida de solteira em segredo?`, a: `Subgrupo sem a noiva. O moomz não notifica ninguém — sem vazamento.` },
      { q: `Máximo de amigas?`, a: `Ilimitado. 4, 20, todas votam em paralelo.` },
      { q: `E se não tiver sinal no dia?`, a: `Depois que a página carrega, os votos funcionam no modo avião. Carrega tudo na chegada.` },
      { q: `Ideia original de presente?`, a: `Semanas antes, roda 5 enquetes anônimas ("melhor memória da Léa", "uma palavra pra descrever a Léa"). Imprime os resultados num livrinho de presente pro dia.` },
    ],
    related: ["wedding-en-pt", "bachelor-en-pt", "birthday-en-pt", "friends-en-pt"],
    updatedAt: today,
  },
  {
    slug: "bachelor-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "🍻",
    title: `Enquetes pra despedida de solteiro — 30 ideias pra planejar e brincar`,
    h1: `Enquetes pra despedida de solteiro: planeje uma despedida memorável`,
    description: `30 enquetes pra despedida de solteiro: destino, atividade, desafios. Do planejamento até os jogos da noite.`,
    intro: `Planejar despedida de solteiro = 6-12 caras, um padrinho, 6 opiniões diferentes. O moomz corta isso pra uma tarde só. Na noite, enquete = gatilho de debate e gerador de desafios. Aqui está o passo a passo sem cair nos clichês de despedida de solteiro.`,
    sections: [
      {
        h: `Antes da festa: enquetes decisivas`,
        body: `4 enquetes: cidade, tipo de atividade (esporte radical, gastronomia, balada, cassino), orçamento por cabeça, duração. Se a maioria quer kart, é kart. Sem debate de 2 horas.`,
      },
      {
        h: `Enquetes de atividade`,
        body: `Kart vs paintball, boliche vs escape room, pôquer vs barzinho. Roda as opções de duas em duas. Pra noite: balada de techno ou bar de coquetel, karaokê sim/não, after na casa de alguém ou na rua.`,
      },
      {
        h: `Quiz sobre o noivo`,
        body: `Durante o jantar, roda 5 enquetes de quiz sobre o noivo: primeiro beijo, primeira ressaca, cidade favorita, maior mancada. Os caras votam, o noivo revela. Histórias escondidas vêm à tona pra render piada interna pela próxima década.`,
      },
      {
        h: `Enquete de desafio`,
        body: `Roda uma enquete de desafio com 4 opções. A maioria vencedora = o desafio dele pra noite. Mantém engraçado, mas sem humilhar. Limite: ele se lembra bem e ri no dia seguinte.`,
      },
    ],
    polls: [
      { q: `Cidade da despedida de solteiro?`, options: [`Amsterdã`, `Berlim`, `Lisboa`, `Aqui mesmo`, `Las Vegas`] },
      { q: `Tipo de despedida de solteiro?`, options: [`Esporte radical`, `Gastronomia`, `Balada`, `Cassino`] },
      { q: `Orçamento por cabeça?`, options: [`R$300-500`, `R$500-800`, `R$800-1200`, `R$1200+`] },
      { q: `Duração?`, options: [`1 noite`, `Fim de semana`, `3 dias`] },
      { q: `Atividade?`, options: [`Kart`, `Paintball`, `Escape room`, `Barco`] },
      { q: `À noite?`, options: [`Balada de techno`, `Bar de coquetel`, `Karaokê`, `Cassino`] },
      { q: `Desafio do noivo?`, options: [`Strip ruim`, `Karaokê de cueca`, `Tatuagem temporária`, `Jogo de bebida`] },
      { q: `Primeiro beijo do noivo?`, options: [`Aos 14`, `Aos 16`, `Aos 18`, `Mais tarde`] },
      { q: `Maior mancada do noivo?`, options: [`Intercâmbio`, `Festa de faculdade`, `Férias`, `Indizível`] },
      { q: `Quem apaga primeiro hoje?`, options: [`Noivo`, `Padrinho`, `Théo`, `Todo mundo`] },
    ],
    faq: [
      { q: `Manter a despedida de solteiro em segredo?`, a: `Subgrupo sem o noivo. O moomz não notifica. Sem vazamento.` },
      { q: `Máximo de caras?`, a: `Ilimitado. 6 ou 20, tudo certo.` },
      { q: `O noivo pode votar no quiz no dia?`, a: `Sim — ele pode ser quem revela a resposta certa no final de cada enquete.` },
      { q: `Ideia de presente coletivo?`, a: `Enquete anônima "uma palavra pra descrever o [noivo]" pra todos os amigos. Imprime os resultados num quadro de presente. Lembrança emocionante.` },
    ],
    related: ["bachelorette-en-pt", "wedding-en-pt", "friends-en-pt", "party-en-pt"],
    updatedAt: today,
  },
  {
    slug: "baby-shower-en-pt",
    locale: "pt",
    category: "ideas",
    emoji: "👶",
    title: `Enquetes pra chá de bebê — 30 ideias pra anfitriões e convidados`,
    h1: `Enquetes pra chá de bebê: adivinhe e anime a festa`,
    description: `30 enquetes pra chá de bebê: nome, sexo, data de nascimento, primeira palavra. Mais enquetes de presente coletivo.`,
    intro: `Chá de bebê = 15 convidados que querem participar mas não sabem como. O moomz vira o jogo da tarde: adivinhar a data de nascimento, o peso, a primeira palavra, o sexo (se não foi revelado). Os futuros pais guardam os prints de lembrança.`,
    sections: [
      {
        h: `Enquetes pra adivinhar o bebê`,
        body: `Clássicas: data de nascimento (4 opções perto da data prevista), peso, altura, cor do cabelo. Cada um vota; 6 meses depois, os pais revelam quem acertou. Pra ir além: "futura profissão do bebê". Bobagem, mas divertido.`,
      },
      {
        h: `Enquete de presente coletivo`,
        body: `Os pais têm lista de presentes? Roda "qual presente coletivo?" com 4 opções da lista + orçamento definido. Sem presente repetido, sem debate. Todo mundo entra na mesma vaquinha.`,
      },
      {
        h: `Enquete de nome (se ainda não escolheram)`,
        body: `Os pais ainda não decidiram (ou querem opinião)? Roda uma enquete com 4-5 nomes. Atenção: os pais não são obrigados a seguir. Ainda assim, um ótimo jogo pros convidados.`,
      },
      {
        h: `Enquetes meta sobre o grupo`,
        body: `Entre os jogos, roda "quem é a próxima a engravidar no grupo?", "quem vai tirar mais foto do bebê?", "quem vai ser a madrinha?". Engraçado, gera debate, não humilha ninguém.`,
      },
    ],
    polls: [
      { q: `Data de nascimento?`, options: [`Antes da data prevista`, `No dia`, `1-3 dias depois`, `Mais de uma semana depois`] },
      { q: `Sexo do bebê?`, options: [`Menina`, `Menino`, `Surpresa`, `Gêmeos`] },
      { q: `Peso ao nascer?`, options: [`Menos de 2,7 kg`, `2,7-3,2 kg`, `3,2-3,6 kg`, `Mais de 3,6 kg`] },
      { q: `Cor do cabelo?`, options: [`Loiro`, `Castanho`, `Preto`, `Ruivo`] },
      { q: `Nome favorito?`, options: [`Léo`, `Adam`, `Camille`, `Sasha`, `Mila`] },
      { q: `Futura profissão do bebê?`, options: [`Artista`, `Atleta`, `Cientista`, `Influencer`] },
      { q: `Primeira palavra?`, options: [`Mamãe`, `Papai`, `Não`, `Mais`] },
      { q: `Presente coletivo?`, options: [`Carrinho`, `Bebê conforto`, `Abajur`, `Vaquinha em dinheiro`] },
      { q: `Próxima do grupo a engravidar?`, options: [`Léa`, `Sarah`, `Camille`, `Eu`] },
      { q: `Cor predominante do quartinho?`, options: [`Rosa pastel`, `Azul pastel`, `Bege`, `Verde sálvia`] },
    ],
    faq: [
      { q: `Guardar os resultados de lembrança?`, a: `Dá print no fim do chá de bebê. A enquete continua acessível pelo link do moomz, mas um print com data é uma lembrança melhor.` },
      { q: `Os pais também podem votar?`, a: `Sim — principalmente nas enquetes de nome ou presente. Nas de adivinhar a data de nascimento, é melhor que eles se abstenham.` },
      { q: `Amigos que moram longe?`, a: `Manda o link do moomz pelo WhatsApp. Eles votam de casa, conta igual. Perfeito pra amigos no exterior.` },
      { q: `Quantas enquetes num chá de bebê?`, a: `Espaça elas: 1 a cada 15-20 min. Total: 5-7 enquetes numa tarde. Mais que isso vira reunião.` },
    ],
    related: ["birthday-en-pt", "family-en-pt", "bachelorette-en-pt", "this-or-that-pt"],
    updatedAt: today,
  },
];
