import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasIt2: SeoPage[] = [
  {
    slug: `family-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `👨‍👩‍👧`,
    title: `Sondaggi per la Famiglia — 30 Idee per Decidere Senza Drammi`,
    h1: `Sondaggi di Famiglia: Decidere Insieme Senza Litigare`,
    description: `30 sondaggi di famiglia per vacanze, pranzi, arredamento, serie TV. E il metodo per far votare suoceri e adolescenti senza tensioni.`,
    intro: `Le decisioni di famiglia sono le più difficili. Tutti hanno opinioni forti, nessuno vuole cedere e le discussioni degenerano in fretta. moomz neutralizza tutto: ognuno vota, vince la maggioranza, fine del discorso. Bonus: insegna ai più piccoli che democrazia ≠ capriccio.`,
    sections: [
      {
        h: `Vacanze: stop al dibattito che dura 3 mesi`,
        body: `Il classico: 4 destinazioni, ognuno vota, si segue la maggioranza. Il sondaggio elimina il "scegli sempre tu". Se mamma vota A, papà B e due ragazzi C e D, tutti hanno avuto voce in capitolo e vince la maggioranza.`,
      },
      {
        h: `Il pranzo della domenica`,
        body: `Chi vuole cosa per pranzo? Invece del classico "cosa vuoi?" che dura mezz'ora, lancia un sondaggio con 4 opzioni alle 11. Per mezzogiorno la risposta c'è già.`,
      },
      {
        h: `Arredamento / ristrutturazione`,
        body: `Ridipingere? Divano nuovo? Lancia un sondaggio con le opzioni. Vince la maggioranza. Se la suocera non è d'accordo, è il gioco: è casa dei figli, non sua.`,
      },
      {
        h: `Serata film in famiglia`,
        body: `La battaglia della domenica sera. 4 opzioni: azione, commedia, drama, documentario. Tutti votano, si guarda. Basta con "questo l'ho già visto".`,
      },
    ],
    polls: [
      { q: `Vacanze estive?`, options: [`Mare in Spagna`, `Montagna sulle Alpi`, `Città in Italia`, `Camping in Francia`] },
      { q: `Pranzo della domenica?`, options: [`Ristorante`, `Delivery`, `Cuciniamo`, `Ognuno per sé`] },
      { q: `Film stasera?`, options: [`Commedia`, `Azione`, `Animazione`, `Drama`] },
      { q: `Colore del salotto?`, options: [`Bianco panna`, `Beige`, `Petrolio`, `Salvia`] },
      { q: `Invitiamo la nonna domenica?`, options: [`Sì`, `No, troppa fatica`, `Ok ma breve`] },
      { q: `Animale in famiglia?`, options: [`Cane`, `Gatto`, `Coniglio`, `Nessuno`] },
      { q: `Sport in famiglia?`, options: [`Bici`, `Trekking`, `Calcio`, `Piscina`] },
      { q: `Cena di compleanno di papà?`, options: [`Trattoria`, `Italiano`, `Giapponese`, `A casa`] },
      { q: `Console per i ragazzi?`, options: [`Switch`, `PS5`, `Xbox`, `Nessuna`] },
      { q: `Gita del weekend?`, options: [`Parco`, `Cinema`, `Bowling`, `A casa`] },
    ],
    faq: [
      { q: `Come evitare i veti della suocera?`, a: `Vota come tutti gli altri. Se finisce sempre in minoranza, le sue scelte non sono in linea col gruppo. È esattamente il senso del sondaggio: neutralizzare le voci dominanti.` },
      { q: `Bambini troppo piccoli per leggere?`, a: `Leggi tu le opzioni ad alta voce. Votano sul tuo telefono. Educativo.` },
      { q: `E se finisce in parità?`, a: `Si fa un secondo turno tra i primi due. Oppure aggiungi una terza persona che fa da spareggio.` },
      { q: `Se qualcuno si rifiuta di votare?`, a: `Pazienza. Il risultato si decide senza di lui. È la regola.` },
    ],
    related: [`birthday-en-it`, `high-school-en-it`, `would-you-rather-en-it`, `this-or-that-it`],
    updatedAt: today,
  },
  {
    slug: `teens-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🤳`,
    title: `Sondaggi per Teenager — 30 Idee per le Medie e le Superiori`,
    h1: `Sondaggi per Teen: Domande che Fanno Davvero Discutere`,
    description: `30 sondaggi pensati per teenager: drama, scuola, amori, challenge. Da lanciare nelle storie di Snap o nei server Discord.`,
    intro: `I teenager scrollano sondaggi ogni giorno — storie di Snap, Instagram, gruppi. La maggior parte sono basici ("ti piaccio?"). Ecco 30 idee più furbe che fanno davvero discutere senza scadere nel gossip-drama puro.`,
    sections: [
      {
        h: `Drama senza cattiveria`,
        body: `Il drama funziona, ma il sondaggio deve puntare ai comportamenti, non alle persone. "Deve dire all'amica che il ragazzo la tradisce?" funziona meglio di "Lea è stupida a credergli". Crea dibattito, evita il bullismo diretto.`,
      },
      {
        h: `Sondaggi sulla scuola (con rispetto)`,
        body: `"Miglior prof dell'anno" con i nomi va bene. "Peggior prof" rischia di diventare mobbing. Resta sul positivo: classe migliore, prof più simpatico, materia più utile. Funziona anche per il giornalino scolastico.`,
      },
      {
        h: `Sondaggi sugli amori`,
        body: `Basati sui comportamenti: ha messo like alla sua storia, ha risposto in fretta, cosa ha detto agli amici. Condividi nella storia di Snap per un'opinione di tutta la scuola. Tieni i casi specifici anonimi per non far degenerare.`,
      },
      {
        h: `Sondaggi challenge`,
        body: `Challenge di TikTok / IRL: "mi iscrivo a teatro?", "lancio l'estetica Y2K?", "taggo Camille così lo vede?". I sondaggi diventano il via libera per le sfide di gruppo.`,
      },
    ],
    polls: [
      { q: `Diciamo a Lea la verità sul suo ragazzo?`, options: [`Sì, diretto`, `Non tocca a noi`, `Teniamo lo screenshot`] },
      { q: `Miglior prof di quest'anno?`, options: [`Prof. Rossi`, `Prof.ssa Bianchi`, `Prof. Conti`, `Prof.ssa Greco`] },
      { q: `Posto peggiore della scuola?`, options: [`Palestra all'intervallo`, `Mensa`, `Corridoi la mattina`, `Bagni`] },
      { q: `Quanto ci metti a rispondere?`, options: [`Subito`, `1 ora`, `Il giorno dopo`, `Mai`] },
      { q: `Le piace davvero?`, options: [`Sì`, `Solo per le visualizzazioni`, `No, è meschino`, `Lo vediamo domani`] },
      { q: `Gita scolastica?`, options: [`Spagna`, `Roma`, `Londra`, `Restiamo qui`] },
      { q: `Materia opzionale l'anno prossimo?`, options: [`Teatro`, `Sport`, `Latino`, `Niente`] },
      { q: `Trend 2026?`, options: [`Y2K`, `Coquette`, `Streetwear`, `Vintage anni 90`] },
      { q: `Dopo scuola dove?`, options: [`McDonald's`, `Bar`, `Da me`, `Al parco`] },
      { q: `Salto il prossimo intervallo?`, options: [`Sì`, `Dipende dal meteo`, `No, è il mio intervallo`] },
    ],
    faq: [
      { q: `È sicuro per i teenager?`, a: `Sì. Niente registrazione, niente dati personali. Il voto resta anonimo. Per i sondaggi drama, tienili sui comportamenti, non sulle persone.` },
      { q: `Si può condividere nella storia di Snap?`, a: `Sì — lo sticker link di Snap accetta i link moomz. Gli amici toccano e votano.` },
      { q: `E il bullismo?`, a: `La moderazione di moomz rimuove qualsiasi sondaggio che nomini una persona con un insulto. La protezione migliore è la cultura: fai domande costruttive, non umilianti.` },
      { q: `I miei genitori lo vedranno?`, a: `No. Il sondaggio è anonimo, i genitori non ricevono notifiche. Comunque, se hai meno di 15 anni, è meglio parlarne con loro.` },
    ],
    related: [`high-school-en-it`, `snapchat-poll-it`, `drama-polls-it`, `instagram-story-poll-it`],
    updatedAt: today,
  },
  {
    slug: `high-school-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🎒`,
    title: `Sondaggi per le Superiori — 30 Idee per la Classe e i Rappresentanti`,
    h1: `Sondaggi per le Superiori: Per la Classe, Snap e i Rappresentanti`,
    description: `30 sondaggi per le superiori: scelta della gita, tema del ballo, drama di classe, rappresentanti. E la modalità anonima per i temi delicati.`,
    intro: `Le superiori = 30+ studenti per classe, gruppi Snap a non finire, rappresentanti che decidono cose e drama continuo. moomz diventa lo strumento democratico per le decisioni di classe E lo spunto per i dibattiti nei corridoi.`,
    sections: [
      {
        h: `Sondaggi di classe: decidere in tanti`,
        body: `Gita, film di fine anno, tema del viaggio, maglietta di classe. Invece di passarsi il foglietto a pranzo, lancia un sondaggio moomz e condividilo nel gruppo Snap della classe. 24 ore dopo hai una risposta, e anche i prof possono validarla leggendo le percentuali.`,
      },
      {
        h: `Sondaggi per i rappresentanti`,
        body: `I rappresentanti organizzano eventi. Ogni volta: tema del ballo, location della festa di accoglienza, candidati alle elezioni. Lancia un sondaggio per tutta la scuola. Vera democrazia, molto meglio di una conta alla lavagna.`,
      },
      {
        h: `Sondaggi drama da corridoio`,
        body: `Sondaggi che girano per i corridoi: coppia più carina della classe, chi avrà più successo, chi si metterà con chi al ballo. Usali con moderazione — resta giocoso, non umiliante.`,
      },
      {
        h: `Sondaggi per i gruppi studio`,
        body: `Sotto esami, moomz coordina: quale capitolo ripassiamo insieme, chi prepara quale schema. Organizzazione collettiva senza dover mettere d'accordo 30 messaggi sparpagliati.`,
      },
    ],
    polls: [
      { q: `Gita ad aprile?`, options: [`Museo`, `Sito storico`, `Torre`, `Cinema`] },
      { q: `Tema del ballo?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Nessun tema`] },
      { q: `Film di fine anno?`, options: [`Inception`, `Forrest Gump`, `Whiplash`, `Sceglie il prof`] },
      { q: `Maglietta di classe?`, options: [`Nera con slogan`, `Bianca minimal`, `Colorata`, `Niente maglietta`] },
      { q: `Coppia più carina?`, options: [`Lea & Luca`, `Sara & Teo`, `Cam & Ines`, `Nessuna`] },
      { q: `Ora peggiore in orario?`, options: [`Lunedì alle 8`, `Mercoledì alle 17`, `Venerdì alle 17`, `Martedì 16-18`] },
      { q: `Festa di accoglienza?`, options: [`A scuola`, `A casa di qualcuno`, `In un locale 18+`, `Niente festa`] },
      { q: `Indirizzo dal terzo anno?`, options: [`Matematica`, `Fisica`, `Economia`, `Storia`] },
      { q: `Materia peggiore?`, options: [`Matematica`, `Storia`, `Filosofia`, `Nessuna, vanno bene tutte`] },
      { q: `Focus del gruppo studio?`, options: [`Matematica`, `Inglese`, `Storia`, `Studio da solo`] },
    ],
    faq: [
      { q: `Va bene per i rappresentanti?`, a: `Sì — è lo strumento giusto per far votare tutta la classe. Basta condividere il link moomz nel gruppo della scuola.` },
      { q: `Sondaggi drama anonimi?`, a: `Sì — i voti sono anonimi. Ma evita sondaggi che prendono di mira una sola persona per umiliarla. Moderazione di moomz + buon senso.` },
      { q: `I prof possono validare il risultato?`, a: `Sì — mostra loro lo schermo con le percentuali. Più credibile di una scheda di carta.` },
      { q: `Sondaggi tra scuole diverse?`, a: `Sì — condividi il link nei gruppi Snap tra scuole. Il sondaggio funziona finché la gente ha il link.` },
    ],
    related: [`teens-en-it`, `college-en-it`, `drama-polls-it`, `discord-poll-it`],
    updatedAt: today,
  },
  {
    slug: `college-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🎓`,
    title: `Sondaggi per l'Università — 30 Idee per Corso, Goliardia e Studentati`,
    h1: `Sondaggi Universitari: Per il Corso, la Goliardia e i Drama dello Studentato`,
    description: `30 sondaggi universitari: temi delle feste, weekend di matricole, gruppi studio, decisioni dello studentato. Pensati per corsi da 200-1000 studenti.`,
    intro: `L'università = 200+ studenti per corso senza alcun modo nativo di votare insieme. moomz diventa lo strumento democratico del corso. Eventi goliardici, weekend delle matricole, opinioni politiche, gruppi studio — tutto passa da un link condiviso.`,
    sections: [
      {
        h: `Sondaggi per goliardia e consiglio di corso`,
        body: `Prima di ogni evento, lancia un sondaggio: tema, location, prezzo d'ingresso, slogan della maglietta. La goliardia raccoglie 200-500 voti in 48 ore, la decisione è democratica. Lo stesso per le elezioni dei rappresentanti di corso.`,
      },
      {
        h: `Sondaggi per il weekend delle matricole`,
        body: `L'evento più grande dell'anno. moomz gestisce tutto a monte: destinazione (4 opzioni), tema, fascia di budget, attività. Anche "chi divide la stanza con chi" — utile per la logistica.`,
      },
      {
        h: `Sondaggi politici (in anonimo)`,
        body: `Durante scioperi / assemblee, i sondaggi anonimi rivelano l'opinione reale. I gruppi più rumorosi non dominano. Il consiglio può mostrare il risultato per impostare il dibattito.`,
      },
      {
        h: `Coordinamento dei gruppi studio`,
        body: `Prima degli esami, lancia un sondaggio: chi prepara quale schema, dove ci si vede per studiare. La condivisione gestita democraticamente batte 50 messaggi Discord sparpagliati.`,
      },
    ],
    polls: [
      { q: `Destinazione del weekend matricole?`, options: [`Spagna`, `Sud Italia`, `Germania`, `Campagna italiana`] },
      { q: `Tema della festa?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Nessun tema`] },
      { q: `Prezzo dell'evento goliardico?`, options: [`5 €`, `10 €`, `15 €`, `Gratis`] },
      { q: `Saltiamo lezione domani?`, options: [`Sì, decisamente`, `No, perdiamo lezioni`, `Decidiamo in assemblea`] },
      { q: `Rappresentante di corso?`, options: [`Lea`, `Luca`, `Teo`, `Camilla`] },
      { q: `Festa giovedì o venerdì?`, options: [`Giovedì`, `Venerdì`, `Entrambi`, `Nessuno dei due`] },
      { q: `Destinazione Erasmus l'anno prossimo?`, options: [`Spagna`, `Germania`, `UK`, `Paesi Bassi`] },
      { q: `Esame peggiore di questo semestre?`, options: [`Statistica`, `Economia`, `Marketing`, `Storia`] },
      { q: `Sessione di studio di gruppo?`, options: [`Sì`, `No, studio da solo`, `Solo per le esercitazioni`] },
      { q: `Mensa oggi?`, options: [`Mangiabile`, `Insomma`, `La salto`, `Già saltata`] },
    ],
    faq: [
      { q: `Quanti studenti al massimo?`, a: `Nessun limite. 200, 500, 1000 — votano tutti in parallelo.` },
      { q: `Come si condivide in un corso enorme?`, a: `Gruppo Discord / Telegram / Facebook. Il link è corto (5 caratteri) ed è facile da condividere anche a voce.` },
      { q: `Sondaggi politici anonimi?`, a: `L'anonimato protegge chi vota. Il risultato rivela l'opinione reale senza esporre chi ha detto cosa.` },
      { q: `Conta come voto in assemblea?`, a: `Legalmente no. Ma è un ottimo indicatore prima del dibattito.` },
    ],
    related: [`high-school-en-it`, `discord-poll-it`, `teens-en-it`, `friends-en-it`],
    updatedAt: today,
  },
  {
    slug: `classroom-teacher-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🏫`,
    title: `Sondaggi in Classe per Insegnanti — 25 Idee`,
    h1: `Sondaggi in Classe per Insegnanti: Votare Senza Carta`,
    description: `25 sondaggi in classe per insegnanti: nome della mascotte, gita, spettacolo di fine anno. Strumento democratico per la primaria e le medie.`,
    intro: `Gli insegnanti della primaria e delle medie usano da sempre la carta o l'alzata di mano. Con moomz fai votare la classe in 30 secondi: mostri il QR code sulla LIM, gli alunni votano dai tablet. Bonus pedagogico: imparano cos'è davvero un voto.`,
    sections: [
      {
        h: `Perché fare sondaggi in classe`,
        body: `Tra i 7 e i 12 anni i bambini capiscono il voto ma quasi non lo praticano. Un sondaggio settimanale diventa un mini-rito: nome della mascotte di classe, scelta della gita, tema dello spettacolo di fine anno. Risultato pubblico, discutibile, ri-votabile.`,
      },
      {
        h: `Come si imposta`,
        body: `Crei il sondaggio moomz dal telefono o dal PC. Mostri lo schermo sulla LIM. Scrivi alla lavagna il link da 5 caratteri. Gli alunni lo digitano sui tablet. Votano, il risultato live appare in grande.`,
      },
      {
        h: `Oltre le decisioni collettive`,
        body: `Usa i sondaggi per la valutazione formativa: "quale frase è corretta?" con 3 opzioni. I voti anonimi rivelano la reale comprensione meglio di un test su carta.`,
      },
      {
        h: `Limiti e accortezze`,
        body: `Nessun dato personale raccolto — compatibile col GDPR per questo uso. Verifica la policy della tua scuola, ma il design anonimo di moomz è in genere in linea con le indicazioni per la scuola.`,
      },
    ],
    polls: [
      { q: `Nome della mascotte di classe?`, options: [`Choco`, `Pixel`, `Tornado`, `Biscotto`] },
      { q: `Gita a maggio?`, options: [`Zoo`, `Museo`, `Parco naturale`, `Cinema`] },
      { q: `Libro del mese?`, options: [`La tela di Carlotta`, `Diario di una schiappa`, `La casa sull'albero`, `Altro`] },
      { q: `Tema dello spettacolo di fine anno?`, options: [`Circo`, `Spazio`, `Giungla`, `Storia`] },
      { q: `Attività del venerdì pomeriggio?`, options: [`Disegno`, `Gioco di gruppo`, `Lettura`, `Sport`] },
      { q: `Animale preferito?`, options: [`Cane`, `Gatto`, `Cavallo`, `Leone`] },
      { q: `Nome del futuro pesciolino?`, options: [`Bolla`, `Nemo`, `Goldie`, `Pinna`] },
      { q: `Colore della maglietta di classe?`, options: [`Rosso`, `Blu`, `Verde`, `Giallo`] },
      { q: `Sport di squadra preferito?`, options: [`Calcio`, `Basket`, `Pallamano`, `Corsa`] },
      { q: `Dolce preferito della mensa?`, options: [`Yogurt`, `Composta di mele`, `Frutta`, `Torta`] },
    ],
    faq: [
      { q: `È gratis per gli insegnanti?`, a: `Sì, totalmente gratis. Nessun premium necessario per l'uso in classe.` },
      { q: `Gli alunni devono creare un account?`, a: `No. Niente registrazione, niente email. Aprono il link, votano, fatto.` },
      { q: `I voti sono anonimi?`, a: `Sì. Anche tu come insegnante vedi solo le percentuali, non chi ha votato cosa. Rassicurante per gli alunni più timidi.` },
      { q: `Si integra con la LIM?`, a: `Mostra la pagina del sondaggio moomz a schermo intero. Guardi i risultati aggiornarsi in tempo reale man mano che gli alunni votano.` },
    ],
    related: [`teens-en-it`, `family-en-it`, `high-school-en-it`, `college-en-it`],
    updatedAt: today,
  },
  {
    slug: `coworkers-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `💼`,
    title: `Sondaggi tra Colleghi — 30 Idee per Ufficio e Smart Working`,
    h1: `Sondaggi tra Colleghi: Per Slack, Teams e il Lavoro da Remoto`,
    description: `30 sondaggi tra colleghi: ristorante per il pranzo, location dell'offsite, caffè o tè. E il metodo per votare via Slack o Teams.`,
    intro: `Le decisioni in ufficio con 8 colleghi e 8 opinioni durano un'ora e finiscono con "vediamo domani". moomz nel canale Slack: 10 minuti dopo hai una risposta. Bonus: rompe il ghiaccio, soprattutto da remoto dove le pause caffè non esistono.`,
    sections: [
      {
        h: `Sondaggi decisionali`,
        body: `Pranzo del venerdì, offsite annuale, arredamento dell'ufficio, macchina del caffè — moomz, 4 opzioni, 24 ore al massimo. Basta con i "proporrei..." persi nel rumore di Slack.`,
      },
      {
        h: `Sondaggi sulla cultura del team`,
        body: `Conoscersi senza invadenza: miglior film dell'anno, podcast preferito, squadra per cui si tifa, città dei sogni. Il miglior rompighiaccio per i team da remoto.`,
      },
      {
        h: `Sondaggi di feedback anonimo`,
        body: `La modalità anonima di moomz è oro per la cultura aziendale: "le riunioni sono troppo lunghe?", "lo smart working a 3 giorni funziona?", "il caffè dell'ufficio è abbastanza buono?". Ottieni la verità invece del feedback educato a quattr'occhi.`,
      },
      {
        h: `Sondaggi per il team building`,
        body: `Prima di ogni team building: attività (escape, sport, gastronomia, creativa), durata, budget. Tutti partecipano alla decisione, non solo le HR. L'engagement cresce ancora prima che l'evento inizi.`,
      },
    ],
    polls: [
      { q: `Pranzo del venerdì?`, options: [`Italiano`, `Giapponese`, `Trattoria`, `Burger`] },
      { q: `Location dell'offsite annuale?`, options: [`Montagna`, `Mare`, `All'estero`, `In zona`] },
      { q: `Smart working a 3 giorni funziona?`, options: [`Sì, perfetto`, `Di più`, `Di meno`, `100% in ufficio`] },
      { q: `Riunioni troppo lunghe?`, options: [`Sì, chiaramente`, `Insomma`, `No, vanno bene`] },
      { q: `Caffè dell'ufficio — cambiamo?`, options: [`Sì, cambiamo`, `No, va bene`, `Installiamo una macchina come si deve`] },
      { q: `Attività di team building?`, options: [`Escape room`, `Corso di cucina`, `Sport`, `Cocktail bar`] },
      { q: `Caffè virtuale settimanale?`, options: [`Sì`, `No, troppo schermo`, `Solo il venerdì`] },
      { q: `Orario della riunione settimanale?`, options: [`Le 9`, `Le 10`, `Le 11`, `Pomeriggio`] },
      { q: `Strumento di project management?`, options: [`Notion`, `Asana`, `Linear`, `Restiamo su Excel`] },
      { q: `Festa di addio dove?`, options: [`In ufficio`, `Al bar qui vicino`, `Al ristorante`, `Niente festa`] },
    ],
    faq: [
      { q: `Si può condividere su Slack?`, a: `Incolla il link moomz. Slack mostra un'anteprima ricca. I colleghi cliccano e votano.` },
      { q: `Microsoft Teams?`, a: `Uguale — incolla il link in chat o nel canale. Appare l'anteprima, voto con un clic.` },
      { q: `Le HR possono vedere chi ha votato?`, a: `No. 100% anonimo, anche per chi crea il sondaggio. È questo che lo rende un vero strumento di feedback.` },
      { q: `Sondaggi da evitare al lavoro?`, a: `Politica (chi vota chi) e religione. Resta neutrale o positivo per la sicurezza psicologica.` },
    ],
    related: [`team-building-en-it`, `discord-poll-it`, `family-en-it`, `birthday-en-it`],
    updatedAt: today,
  },
  {
    slug: `team-building-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Sondaggi per il Team Building — 25 Idee per Prima e Durante`,
    h1: `Sondaggi per il Team Building: Coinvolgere il Team Prima e Durante`,
    description: `25 sondaggi per il team building: preparazione, rompighiaccio, decisioni, feedback post-evento. Per team da 5 a 200 persone.`,
    intro: `Un team building che funziona è un team building in cui le persone si sono sentite incluse. moomz è lo strumento perfetto: prima sondi le preferenze (attività, date, location). Durante, lanci sondaggi di animazione (rompighiaccio, sfide, elezioni). Dopo, raccogli il feedback. Nessuna app dedicata, solo un link.`,
    sections: [
      {
        h: `Fase 1: preparare il team building`,
        body: `4 sondaggi consecutivi (uno a settimana): (1) tipo di attività, (2) data, (3) location, (4) budget. Chiudi a maggioranza ogni volta. Il team si sente decisionale, l'engagement sale ancora prima dell'evento.`,
      },
      {
        h: `Fase 2: rompighiaccio all'apertura dell'evento`,
        body: `All'apertura, lancia 3 sondaggi quiz divertenti: "chi parla di più in riunione?", "chi è sempre in anticipo?", "chi porta gli snack migliori?". Anonimi, divertenti, danno il via alla dinamica. Le opzioni = i nomi del team (8-15 persone).`,
      },
      {
        h: `Fase 3: sondaggi che fanno emergere le decisioni`,
        body: `Durante il workshop, sondaggio anonimo "quale valore rappresenta il nostro team?" con 4 opzioni (collaborazione, innovazione, rigore, gentilezza). Il risultato diventa il punto di partenza per la discussione successiva.`,
      },
      {
        h: `Fase 4: feedback post-evento`,
        body: `Alla fine: sondaggio "attività migliore?" e "quando lo rifacciamo?". 24 ore dopo: "voto al team building da 1 a 5" — anonimo, onesto. Vero miglioramento continuo, non il solito Google Form che nessuno apre.`,
      },
    ],
    polls: [
      { q: `Attività di team building?`, options: [`Escape room`, `Corso di cucina`, `Sport`, `Cocktail bar`, `Workshop creativo`] },
      { q: `Data?`, options: [`Ven 5`, `Ven 12`, `Sab 13`, `Più avanti`] },
      { q: `Location?`, options: [`Centro città`, `Periferia`, `Weekend fuori città`, `Niente spostamenti`] },
      { q: `Chi parla di più in riunione?`, options: [`Lea`, `Luca`, `Teo`, `Anonimo`] },
      { q: `Miglior valore del team?`, options: [`Collaborazione`, `Innovazione`, `Rigore`, `Gentilezza`] },
      { q: `Voto al team building?`, options: [`5/5`, `4/5`, `3/5`, `Meno`] },
      { q: `Quando il prossimo?`, options: [`Tra 3 mesi`, `Tra 6 mesi`, `Ogni anno`, `Mai`] },
      { q: `Miglior momento dell'anno?`, options: [`L'offsite`, `La festa di Natale`, `La festa d'estate`, `Nessuno`] },
      { q: `Atmosfera del team?`, options: [`Top`, `Buona`, `Nella media`, `Da migliorare`] },
      { q: `Preferisci:`, options: [`Attività fisica`, `Workshop creativo`, `Pranzo di gruppo`, `Festa`] },
    ],
    faq: [
      { q: `Quante persone al massimo?`, a: `Illimitate. 5 o 200, va bene.` },
      { q: `Il feedback è davvero anonimo?`, a: `Sì. Niente email, niente account. I voti sono salvati senza identificare chi vota. Anche chi organizza vede solo le percentuali.` },
      { q: `I junior non voteranno contro l'opinione del capo?`, a: `L'anonimato è la tua protezione. Mettilo in chiaro: "questo sondaggio è totalmente anonimo, votate con sincerità". E non chiedere in plenaria — lascia che votino durante la pausa.` },
      { q: `Team distribuito?`, a: `Perfetto — condividi il link moomz su Slack/Teams. Funziona tra fusi orari diversi, anche in modo asincrono.` },
    ],
    related: [`coworkers-en-it`, `discord-poll-it`, `party-en-it`, `wedding-en-it`],
    updatedAt: today,
  },
  {
    slug: `this-or-that-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `↔️`,
    title: `Domande Questo o Quello — 100 Idee per Storie e Primi Appuntamenti`,
    h1: `Questo o Quello: 100 Domande per Insta, Snap e Primi Appuntamenti`,
    description: `100 domande questo-o-quello. Il formato sondaggio della Gen Z — due opzioni, decisione istantanea. Per storie, appuntamenti o quiz di compatibilità.`,
    intro: `Questo o quello — due opzioni, un tap, fatto. È il formato di sondaggio con il tasso di completamento più alto su Insta Story (60-80%). Perfetto per rompere il ghiaccio, per i quiz di compatibilità e per le catene di storie virali.`,
    sections: [
      {
        h: `Perché questo-o-quello vince`,
        body: `Scelta binaria = zero stanchezza decisionale. Il cervello decide in 0,3 secondi e passa alla prossima. Su Insta Story è il formato con il tasso di risposta più alto. Ai primi appuntamenti del 2026 è il rompighiaccio per eccellenza.`,
      },
      {
        h: `Come si usa su moomz`,
        body: `Crea un sondaggio moomz con esattamente 2 opzioni. Quella è la modalità questo-o-quello. Per un quiz completo, crea 5-10 sondaggi separati e condividi ogni link in una catena di storie.`,
      },
      {
        h: `Il metodo della catena di storie`,
        body: `Lancia 5 sondaggi questo-o-quello in storie consecutive. I follower scorrono, votano ognuno e ti mandano in DM i loro risultati. Engagement da record. Usa lo sticker nativo di Insta per 2 opzioni, oppure moomz quando più avanti nella catena ti servono 3+ opzioni.`,
      },
      {
        h: `Questo-o-quello al primo appuntamento`,
        body: `10 domande = il rompighiaccio perfetto. A turno, senza pressione, rivela i gusti. Consiglio: parti soft (caffè/tè), sali di specificità (cane/gatto, mare/montagna), evita i temi delicati al primo appuntamento.`,
      },
    ],
    polls: [
      { q: `Caffè o tè?`, options: [`Caffè`, `Tè`] },
      { q: `Cane o gatto?`, options: [`Cane`, `Gatto`] },
      { q: `Mare o montagna?`, options: [`Mare`, `Montagna`] },
      { q: `Giorno o notte?`, options: [`Giorno`, `Notte`] },
      { q: `Pizza o burger?`, options: [`Pizza`, `Burger`] },
      { q: `Dolce o salato?`, options: [`Dolce`, `Salato`] },
      { q: `Azione o commedia?`, options: [`Azione`, `Commedia`] },
      { q: `iPhone o Android?`, options: [`iPhone`, `Android`] },
      { q: `Serata tranquilla o discoteca?`, options: [`Tranquilla`, `Discoteca`] },
      { q: `Estate o inverno?`, options: [`Estate`, `Inverno`] },
    ],
    faq: [
      { q: `Quante domande in un quiz?`, a: `10-20 al massimo. Oltre, il pubblico molla.` },
      { q: `Posso aggiungere una terza opzione?`, a: `Allora non è più questo-o-quello. Resta rigido sulle 2. Per 3+ usa un normale sondaggio moomz.` },
      { q: `È più veloce del nativo di Insta?`, a: `Il questo-o-quello nativo di Insta non mostra le percentuali. moomz mostra le % live. Scegli in base a cosa ti serve.` },
      { q: `Idee per le coppie?`, a: `Tutte le domande sui gusti: caffè/tè, serie/film, casa/uscita. Guarda la nostra pagina sui sondaggi di coppia per 50 idee.` },
    ],
    related: [`would-you-rather-en-it`, `couple-questions-it`, `first-date-en-it`, `instagram-story-poll-it`],
    updatedAt: today,
  },
  {
    slug: `would-you-rather-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🤔`,
    title: `Domande Preferiresti — 100 Idee per Feste e Coppie`,
    h1: `Preferiresti: 100 Domande per Feste, Appuntamenti e Coppie`,
    description: `100 domande "preferiresti": divertenti, filosofiche, dilemmi, ipotetiche. Per giochi di gruppo, primi appuntamenti e coppie.`,
    intro: `Preferiresti: ogni opzione è un mini-incubo o un mini-sogno. Scegli. È il formato che genera i dibattiti più lunghi tra tutti i giochi da festa. 100 domande, ordinate per intensità. E il metodo per usarle senza silenzi imbarazzanti.`,
    sections: [
      {
        h: `Il formato`,
        body: `Poni: "preferiresti X o Y?". Più radicali sono le opzioni, più duro è il dibattito. Il punto perfetto: due opzioni ugualmente brutte (o ugualmente belle). Rivela le preferenze vere.`,
      },
      {
        h: `Livello 1: preferiresti divertenti`,
        body: `Da giocare in gruppo in sicurezza: "volare o essere invisibile?", "conoscere il futuro o cambiare il passato?". 10 minuti di dibattito, rompighiaccio perfetto per l'inizio di una serata o di una riunione.`,
      },
      {
        h: `Livello 2: preferiresti con dilemmi`,
        body: `Veri dilemmi: "perdere il telefono per 1 anno o il cane per 1 mese?", "cambiare nome o cognome?", "50 anni ricco poi povero, o ricco/povero alternati?". Tocca i valori. Meglio coi gruppi di amici stretti.`,
      },
      {
        h: `Livello 3: preferiresti di coppia`,
        body: `Col partner, in modo intimo: "sapere tutto del mio passato o niente?", "vivere a Roma senza soldi o a New York con tanti?". Scambio profondo senza fare la domanda diretta.`,
      },
    ],
    polls: [
      { q: `Volare o essere invisibile?`, options: [`Volare`, `Invisibile`] },
      { q: `Conoscere il futuro o cambiare il passato?`, options: [`Futuro`, `Passato`] },
      { q: `Perdere il telefono per 1 anno o il cane per 1 mese?`, options: [`Telefono`, `Cane`] },
      { q: `Cambiare nome o cognome?`, options: [`Nome`, `Cognome`] },
      { q: `Roma al verde o Milano ricco?`, options: [`Roma al verde`, `Milano ricco`] },
      { q: `50 anni ricco poi povero, o alternati?`, options: [`50 anni ricco prima`, `Alternati`] },
      { q: `Sapere tutto dell'ex o niente?`, options: [`Sapere tutto`, `Non sapere niente`] },
      { q: `Leggere la mente o teletrasporto?`, options: [`Leggere la mente`, `Teletrasporto`] },
      { q: `Pizza ogni giorno o mai più?`, options: [`Ogni giorno`, `Mai più`] },
      { q: `Niente internet per 1 mese o niente luce per 1 settimana?`, options: [`Niente internet`, `Niente luce`] },
    ],
    faq: [
      { q: `Quanti "preferiresti" in una festa?`, a: `5-10. Di più diventa ripetitivo. Distanziali tra altri tipi di sondaggio.` },
      { q: `Opzioni non bilanciate — è un problema?`, a: `Se un'opzione è chiaramente migliore, il 95% la sceglie, niente dibattito. Un buon "preferiresti" ha due opzioni ugualmente attraenti o ugualmente sgradevoli.` },
      { q: `Versione soft per la famiglia?`, a: `Resta su poteri magici e scelte banali. Salta i dilemmi etici — possono scatenare scontri con i suoceri.` },
      { q: `Quante opzioni?`, a: `Rigorosamente 2. È il formato. Per 3+ usa un normale sondaggio.` },
    ],
    related: [`this-or-that-it`, `couple-questions-it`, `party-en-it`, `friends-en-it`],
    updatedAt: today,
  },
  {
    slug: `drama-polls-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🍿`,
    title: `Sondaggi Drama — 30 Idee per Far Discutere su TikTok e Insta`,
    h1: `Sondaggi Drama: 30 Idee per Scatenare il Dibattito su TikTok`,
    description: `30 sondaggi drama: situazioni di coppia, di amicizia, di famiglia. Il formato che genera più engagement su TikTok e Insta.`,
    intro: `Il drama è il formato con più engagement su TikTok e Instagram. Poni una situazione moralmente ambigua, dai 3 opzioni di verdetto, lascia decidere al pubblico. L'equivalente moderno della giuria popolare. Ecco 30 idee.`,
    sections: [
      {
        h: `Il formato drama`,
        body: `Struttura: (1) situazione in 2-3 frasi, (2) domanda morale ("chi ha torto?"), (3) 3 opzioni di verdetto. Più è ambigua, più lungo è il dibattito. Evita il bianco/nero netto — è l'incertezza che genera voti.`,
      },
      {
        h: `Drama di coppia`,
        body: `Il territorio con più engagement: ghosting, l'ex che torna, sospetto tradimento, il partner che esce senza dirlo. Avvertenza: tieni tutto generico, non rendere riconoscibile qualcuno vicino a te (rischio leak).`,
      },
      {
        h: `Drama di amicizia`,
        body: `"L'amica si mette col tuo ex — tradimento?", "deve dire all'amica che il suo ragazzo la tradisce?". Coinvolgente come il drama di coppia ma con meno giudizio personale. Ottimo per gruppi misti.`,
      },
      {
        h: `Drama da teenager / scuola`,
        body: `Per la Gen Z: drama di classe, prof che esagera, comportamento da spia. Resta sulle azioni, non sui nomi. moomz può insegnare la sfumatura morale.`,
      },
    ],
    polls: [
      { q: `Ti ha fatto ghosting per 2 mesi, ora vuole tornare. Rispondi?`, options: [`Sì`, `Bloccalo`, `Fallo aspettare`] },
      { q: `L'amica si mette col tuo ex. Tradimento?`, options: [`Assolutamente`, `È la sua vita`, `Dipende da quanto tempo`] },
      { q: `Ha visto il ragazzo dell'amica su Tinder. Glielo dice?`, options: [`Sì, diretto`, `Non tocca a lei`, `Tiene lo screenshot e aspetta`] },
      { q: `Invitare l'ex a una festa senza dirlo?`, options: [`Imperdonabile`, `Vabbè`, `Se l'ex è d'accordo`] },
      { q: `Dopo la rottura, rifiuta i contatti con gli amici in comune?`, options: [`Legittimo`, `È drama`, `Ognuno fa come crede`] },
      { q: `Prof che esagera con la punizione?`, options: [`Fai reclamo`, `È un suo diritto`, `Dipende`] },
      { q: `L'amico esce senza invitare il gruppo?`, options: [`Tradimento`, `È un suo diritto`, `Dipende da chi`] },
      { q: `Rubare il ragazzo della migliore amica, è possibile?`, options: [`Mai`, `Se si sono lasciati`, `Se è vero amore`] },
      { q: `L'amica parla male di te alle spalle. La affronti?`, options: [`Diretto`, `Fai finta di niente`, `Tagli i ponti`] },
      { q: `Andare a un matrimonio senza accompagnatore?`, options: [`Tranquillo`, `Stressante`, `Se conosco 5+ persone`] },
    ],
    faq: [
      { q: `Il drama è sano?`, a: `Un sondaggio drama anonimo = costruire argomentazioni morali, è sano. Drama con nomi + insulti = bullismo, la moderazione di moomz lo rimuove.` },
      { q: `I follower voteranno?`, a: `Sì — il formato drama tocca un engagement 3 volte superiore ai sondaggi standard. Su TikTok/Insta, fascia top.` },
      { q: `È legale?`, a: `Finché non ci sono nomi reali e nessuna diffamazione, sì. Resta sull'ipotetico.` },
      { q: `Dibattito massimo?`, a: `3 opzioni con una via di mezzo ("dipende"). Il sì/no fa discutere meno del sì/no/dipende.` },
    ],
    related: [`tiktok-poll-it`, `couple-questions-it`, `friends-en-it`, `would-you-rather-en-it`],
    updatedAt: today,
  },
  {
    slug: `icebreaker-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `🧊`,
    title: `Sondaggi Rompighiaccio — 40 Domande per Qualsiasi Gruppo`,
    h1: `Sondaggi Rompighiaccio: 40 Domande per Avviare Qualsiasi Conversazione`,
    description: `40 sondaggi rompighiaccio per riunioni, primi appuntamenti, gruppi nuovi, classi. Il formato che batte il silenzio imbarazzante in 30 secondi.`,
    intro: `Silenzio imbarazzante in una riunione, a un appuntamento, in un gruppo nuovo — lancia un sondaggio rompighiaccio. 4 opzioni divertenti, 30 secondi, tutti hanno "parlato" col voto. La conversazione riparte dal risultato. Ecco 40 idee.`,
    sections: [
      {
        h: `Quando i sondaggi rompighiaccio battono le domande rompighiaccio`,
        body: `Una domanda richiede di parlare. Un sondaggio richiede un tap. In un gruppo di 8 dove 3 sono timidi, il rompighiaccio verbale significa che parlano in 5 e in 3 restano zitti. Il sondaggio significa che "parlano" in 8. Inclusione al 100%.`,
      },
      {
        h: `Sondaggi di apertura — inizio riunione / evento`,
        body: `I migliori rompighiaccio: "come stai da 1 a 5?", "energia mattutina: caffeina o relax?", "umore della settimana: 🔥 o 😴?". Veloci, divertenti, danno il tono.`,
      },
      {
        h: `Sondaggi per conoscersi`,
        body: `"Miglior film dell'anno?", "città dei sogni in cui vivere?", "il tuo comfort food immancabile?". Rivela i gusti senza invadenza. Perfetti per team nuovi o primi appuntamenti.`,
      },
      {
        h: `Sondaggi rompighiaccio divertenti`,
        body: `"Se fossi uno snack, saresti...?", "superpotere: volare o invisibile?", "sopravvivresti a 24 ore senza WiFi?". Le domande assurde sciolgono la tensione più in fretta di quelle serie.`,
      },
    ],
    polls: [
      { q: `Come stai oggi?`, options: [`🔥 alla grande`, `😊 bene`, `😐 così così`, `😴 stanco`] },
      { q: `Energia mattutina?`, options: [`Caffeina`, `Allenamento`, `Relax`, `Niente`] },
      { q: `Miglior film dell'anno?`, options: [`Dune 3`, `Avatar 4`, `Altro`, `Non l'ho visto`] },
      { q: `Città dei sogni?`, options: [`Tokyo`, `New York`, `Parigi`, `Bali`] },
      { q: `Comfort food?`, options: [`Pizza`, `Burger`, `Pasta`, `Sushi`] },
      { q: `Superpotere?`, options: [`Volare`, `Invisibile`, `Teletrasporto`, `Leggere la mente`] },
      { q: `24 ore senza WiFi — sopravvivi?`, options: [`Facilmente`, `Dura`, `Piango`, `Lo faccio già`] },
      { q: `Se fossi uno snack?`, options: [`Patatine`, `Cioccolato`, `Frutta`, `Formaggio`] },
      { q: `Caffè o tè?`, options: [`Caffè`, `Tè`, `Matcha`, `Nessuno`] },
      { q: `Energia del weekend?`, options: [`Avventura`, `Relax`, `Vita sociale`, `Da solo`] },
    ],
    faq: [
      { q: `Per team nuovi?`, a: `Sì — lancia 3 rompighiaccio alla prima riunione plenaria. La modalità anonima fa "parlare" anche i timidi.` },
      { q: `Primi appuntamenti?`, a: `Mescola 3-5 rompighiaccio tra una parte di conversazione e l'altra. Non trasformarlo in un quiz.` },
      { q: `In classe?`, a: `Sì — a inizio anno, lancia "snack preferito", "superpotere", "destinazione dei sogni". Crea legame di gruppo in 5 minuti.` },
      { q: `Riunioni online?`, a: `Lascia il link in chat. La gente vota durante l'introduzione noiosa. L'energia schizza quando appaiono i risultati.` },
    ],
    related: [`this-or-that-it`, `coworkers-en-it`, `first-date-en-it`, `team-building-en-it`],
    updatedAt: today,
  },
  {
    slug: `valentines-en-it`,
    locale: `it`,
    category: `ideas`,
    emoji: `💝`,
    title: `Sondaggi per San Valentino — 25 Idee per Coppie o Cotte`,
    h1: `Sondaggi per San Valentino: Per Coppie, Cotte e Single`,
    description: `25 sondaggi per San Valentino: ristorante, regalo, dichiarazione anonima, anti-San Valentino per single. Per coppie, cotte e gruppi di amici.`,
    intro: `San Valentino = 200 messaggi WhatsApp "cosa facciamo?". Per le coppie: ristorante, regalo, scelta della serata. Per i single: sondaggi anti-San Valentino tra amici. Per le cotte: dichiarazione anonima via sondaggio. Ecco 25 idee.`,
    sections: [
      {
        h: `Sondaggi di coppia: organizzare San Valentino`,
        body: `Fai votare il partner: ristorante, serata a casa, weekend, Netflix. Decisione democratica, niente pressione di dover proporre. Bonus: aggiungi "ci penso io, fidati" per inquadrare la sorpresa dentro le opzioni.`,
      },
      {
        h: `Sondaggi per single: anti-San Valentino`,
        body: `Single in gruppo: "cosa facciamo il 14 febbraio?" con le opzioni — serata film in 4, cena tra ragazze, serata a bere, ognuno per sé. moomz risolve, niente dibattito su chi propone cosa.`,
      },
      {
        h: `Sondaggio anonimo per la cotta`,
        body: `La mossa classica: manda alla tua cotta un sondaggio "cosa pensi di me?" con 4 opzioni divertenti. Chi crea resta anonimo sul link condiviso. Il gioco perfetto prima della dichiarazione.`,
      },
      {
        h: `Sondaggio per il regalo`,
        body: `Indeciso tra 3 regali? Chiedi ai suoi amici con un sondaggio anonimo. Risposta in 1 ora, zero stress da "gli piacerà?".`,
      },
    ],
    polls: [
      { q: `Programma per San Valentino?`, options: [`Ristorante chic`, `Serata a casa`, `Weekend fuori`, `Netflix`] },
      { q: `Anti-San Valentino tra amici?`, options: [`Serata film in 4`, `Cena`, `Si beve`, `Ognuno per sé`] },
      { q: `Regalo per lui?`, options: [`Profumo`, `Vestiti`, `Un'esperienza`, `Cena fatta in casa`] },
      { q: `Regalo per lei?`, options: [`Gioielli`, `Fiori`, `Un'esperienza`, `Lettera + fai da te`] },
      { q: `Ristorante per San Valentino?`, options: [`Italiano intimo`, `Trattoria`, `Sushi`, `Cocktail bar`] },
      { q: `Dichiarazione — ci provo?`, options: [`Sì`, `No`, `Con un sondaggio divertente`] },
      { q: `San Valentino dopo 2 mesi insieme?`, options: [`Sì`, `Troppo presto`, `Un piccolo gesto`] },
      { q: `San Valentino dopo 10 anni insieme?`, options: [`Festeggiamo`, `Come al solito`, `Un regalino`] },
      { q: `Rose o altri fiori?`, options: [`Rose rosse`, `Peonie`, `Tulipani`, `Niente fiori`] },
      { q: `Serata a sorpresa?`, options: [`La adoro`, `Mi stressa`, `Dipende`] },
    ],
    faq: [
      { q: `Sondaggio anonimo per una cotta?`, a: `Sì — moomz non identifica chi crea sul link condiviso. Puoi presentarlo come un gioco.` },
      { q: `Gli amici possono votare senza identificarmi?`, a: `Sì — condividi nel gruppo, tutti anonimi. Nessun "chi ha votato cosa".` },
      { q: `Sondaggio per sentirsi amati?`, a: `Lancia "descrivimi in 1 parola" con gli amici. 4 opzioni positive. Guarda cosa emerge, e sentilo.` },
      { q: `Organizzare l'anti-San Valentino?`, a: `Fai votare gli amici single. 4 opzioni di serata. Vince la maggioranza. Meno "non voglio proporre io".` },
    ],
    related: [`couple-questions-it`, `first-date-en-it`, `friends-en-it`, `party-en-it`],
    updatedAt: today,
  },
];
