import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasDe1: SeoPage[] = [
  {
    slug: `instagram-story-poll-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `📸`,
    title: `Instagram-Story-Umfrage Ideen — 50 Fragen, die wirklich abgehen`,
    h1: `Instagram-Story-Umfragen: 50 Fragen, bei denen echt abgestimmt wird`,
    description: `50 Ideen für Instagram-Story-Umfragen, die für mega Interaktion sorgen. Schluss mit langweiligem Dies-oder-das — diese Fragen starten echte Gespräche.`,
    intro: `Der native Umfrage-Sticker von Instagram lässt dich bei zwei Optionen hängen und ist schnell ausgelutscht. Die Accounts, die 2026 bei Engagement abräumen, fahren Multi-Options-Umfragen per Link-Sticker — du droppst einen moomz-Link, deine Follower voten mit einem Tap, du checkst das Ergebnis und repostest es. Hier sind 50 Ideen, die wirklich was bewegen.`,
    sections: [
      {
        h: `Warum Umfragen besser performen als Fragen-Sticker`,
        body: `Eine Umfrage will einen Tap. Ein Fragen-Sticker will Tippen. Der Unterschied bei der Hürde ist krass — 10-mal größer. Umfragen kommen bei Lifestyle-Accounts auf 60-80 % Antwortquote, Fragen-Sticker auf 5-15 %. Nimm Umfragen für Engagement, Fragen fürs Content-Sammeln (mach aus den Antworten einen Follow-up-Post).`,
      },
      {
        h: `Wenn der native Sticker einfach nicht reicht`,
        body: `Native Instagram-Umfragen geben dir zwei Optionen. Für drei, vier oder sechs brauchst du einen Link zu einer externen Umfrage. moomz erstellt eine Umfrage in 10 Sekunden, gibt dir eine 5-Zeichen-URL, und deine Follower voten, ohne den IG-Browser zu verlassen. Die Ergebnisse sind live und animiert — perfekt zum Reposten in die Story.`,
      },
      {
        h: `Die 5 Blickwinkel, die Antworten bringen`,
        body: `1) Visuelles Dies-oder-das (zwei Fotos). 2) Tages-Prognose („wer gewinnt heute Abend"). 3) Hot Take („Ananas auf Pizza?"). 4) Drama-Check („war es okay von ihr zu ghosten?"). 5) Lohnt-sich-das („würdest du 200 € dafür hinlegen?"). Finger weg von allem, was nach Marktforschungs-Umfrage klingt. Das riechen die Leute sofort.`,
      },
      {
        h: `Wie Umfragen zur Gewohnheit werden`,
        body: `Speicher moomz.com auf deinem Homescreen (PWA installieren). Eine Umfrage pro Story-Slot. Pack immer einen CTA in die Caption: „voten in der nächsten Story." Schau zu, wie deine Antwortquote Woche für Woche steigt.`,
      },
    ],
    polls: [
      { q: `Ananas auf Pizza?`, options: [`Ja`, `Niemals`, `Joa`] },
      { q: `Morgens Kaffee oder Matcha?`, options: [`Kaffee`, `Matcha`, `Weder noch`] },
      { q: `Sommerpläne: Strand oder Berge?`, options: [`Strand`, `Berge`, `Stadt`, `Daheim bleiben`] },
      { q: `Jeden Tag eine Story oder nie?`, options: [`Jeden Tag`, `Manchmal`, `Nie`] },
      { q: `Baggy Jeans, immer noch ein Vibe?`, options: [`Voll im Trend`, `Auf keinen Fall`, `Kommt drauf an`] },
      { q: `Brunch oder Dinner draußen?`, options: [`Brunch`, `Dinner`, `Beides`] },
      { q: `iPhone oder Android 2026?`, options: [`iPhone`, `Android`, `Egal`] },
      { q: `DMs von Fremden beantworten?`, options: [`Immer`, `Nur wenn hot`, `Nie`] },
      { q: `Brunch oder ausschlafen?`, options: [`Brunch`, `Schlafen`, `Beides`] },
      { q: `Zurück ins Gym?`, options: [`Diese Woche`, `Nächsten Monat`, `Nie`] },
    ],
    faq: [
      { q: `Wie viele Optionen kann eine Story-Umfrage haben?`, a: `Nativ: 2. Mit einem moomz-Link-Sticker: 2-6 Optionen. Der Link öffnet sich, der Follower votet und ist wieder in deiner Story.` },
      { q: `Sind Instagram-Umfrage-Stimmen anonym?`, a: `Nein — Instagram zeigt dir, wer was gewählt hat. moomz ist komplett anonym: nur Prozente, keine Identität der Voter.` },
      { q: `Wie lange läuft eine Story-Umfrage?`, a: `24 h auf Instagram. Der moomz-Link hält die Umfrage unbegrenzt aktiv — pack ihn morgen einfach wieder in die Story, wenn du mehr Stimmen willst.` },
      { q: `Kann ich Live-Ergebnisse sehen?`, a: `Ja — moomz animiert die Ergebnisse in Echtzeit. Tipp auf deine eigene Umfrage und schau zu, wie die Balken wandern, während die Stimmen reinkommen.` },
    ],
    related: [`tiktok-poll-de`, `snapchat-poll-de`, `this-or-that-de`, `would-you-rather-en-de`],
    updatedAt: today,
  },
  {
    slug: `tiktok-poll-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🎵`,
    title: `TikTok-Umfrage Ideen — 40 Fragen für Bio-Link & Videos`,
    h1: `TikTok-Umfragen: 40 Ideen für Video-Hooks & Bio-Link`,
    description: `TikTok hat keine native Umfrage. So holen sich Creator Stimmen per Bio-Link — plus 40 Fragen, die 2026 für Engagement sorgen.`,
    intro: `TikTok liefert keinen nativen Umfrage-Sticker. Das ist eine Lücke — und Creator, die sie mit einer Bio-Link-Umfrage füllen, holen sich einen extra Engagement-Loop von 30-50 %. Stell die Frage im Video, droppe „voten in der Bio" und nutze einen moomz-Link. Hier ist der Spielplan.`,
    sections: [
      {
        h: `Warum die fehlende native Umfrage für dich wichtig ist`,
        body: `TikToks Design priorisiert Scrollen. Native Umfragen würden den Feed bremsen. Heißt: Creator, die strukturiertes Feedback wollen, müssen es selbst per Bio-Link bauen. moomz ist die einfachste Variante: ein 5-Zeichen-Link, passt ins Bio-Zeichenlimit, öffnet sofort im Browser.`,
      },
      {
        h: `Der Video-dann-Umfrage-Loop`,
        body: `Teil 1 stellt die Frage („war es okay von ihr zu ghosten?") und endet mit „voten in der Bio". Teil 2 zeigt das Ergebnis und reagiert. Jeder Teil ist ein eigenes Video — doppelte Reichweite mit demselben Content. Top-Accounts fahren diesen Loop jede Woche.`,
      },
      {
        h: `Drama-Fragen, die Stimmen bringen`,
        body: `Vage genug zum Diskutieren, konkret genug, um Position zu beziehen. „War es okay von ihr zu ghosten?" schlägt „ist Ghosting schlecht?" um das 3-Fache bei der Vote-Rate. Das Detail in der Story macht die Frage griffig.`,
      },
      {
        h: `Finger weg von Promo-Umfragen`,
        body: `Wenn du für einen Marken-Sponsor abstimmen lässt, kennzeichne es. TikTok-User riechen Promo-Umfragen sofort und scrollen weiter oder callen dich in den Kommentaren aus. moomz funktioniert für organisch und gesponsert — aber die Kennzeichnung ist Pflicht, kein Vorschlag.`,
      },
    ],
    polls: [
      { q: `War es okay, dass sie ihn geghostet hat?`, options: [`Ja, gerechtfertigt`, `Nein, das ist billig`, `Kommt auf den Kontext an`] },
      { q: `Deiner Freundin die Wahrheit sagen?`, options: [`Ja, direkt`, `Nicht meine Sache`, `Warten, bis sie fragt`] },
      { q: `Fünftes Date, noch kein Kuss — komisch?`, options: [`Normal`, `Komisch`, `Sus`] },
      { q: `Wie lange, bis du antwortest?`, options: [`Sofort`, `1-3 h`, `Am nächsten Tag`, `Nie`] },
      { q: `Ist es okay, einen Ex zu stalken?`, options: [`Na klar`, `Ein bisschen`, `Nein, toxisch`] },
      { q: `Erstes Date: wer zahlt?`, options: [`Er/sie`, `Geteilt`, `Immer der Typ`] },
      { q: `Fremdgehen einmal verzeihen?`, options: [`Ja`, `Niemals`, `Kommt drauf an`] },
      { q: `Tinder 2026, noch der Mühe wert?`, options: [`Ja`, `Tot`, `Zum Spaß`] },
      { q: `Insta beim ersten Date teilen?`, options: [`Sofort`, `Zweites Date`, `Nie`] },
      { q: `Mit jemand Jüngerem daten?`, options: [`1-2 J. okay`, `Bis 5 J.`, `Auf keinen Fall`, `Kein Limit`] },
    ],
    faq: [
      { q: `Hat TikTok eine native Umfrage?`, a: `Nein. Du kannst im Video oder in den Kommentaren Fragen stellen, aber es gibt kein Widget, das Stimmen zählt. Nutz moomz und verlink es in der Bio.` },
      { q: `Funktioniert der moomz-Link in der Bio?`, a: `Ja — er wird wie jeder externe Link behandelt. Passt ins Bio-Zeichenlimit. Klickbare Links in Captions gibt's nur bei Business-Accounts.` },
      { q: `Kann ich dieselbe Umfrage für mehrere Videos nutzen?`, a: `Ja. Derselbe moomz-Link funktioniert über mehrere TikToks hinweg. Oder du wechselst pro Video für frische Signale.` },
      { q: `Sind die Stimmen anonym?`, a: `Ja. moomz verknüpft eine Stimme nie mit einem Profil. Deine Zuschauer können ehrlich antworten, ohne sozialen Druck.` },
    ],
    related: [`instagram-story-poll-de`, `snapchat-poll-de`, `drama-polls-de`, `first-date-en-de`],
    updatedAt: today,
  },
  {
    slug: `snapchat-poll-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `👻`,
    title: `Snapchat-Umfrage Ideen — 30 Fragen für Storys & Gruppenchats`,
    h1: `Snapchat-Umfragen: 30 Ideen für Storys und Gruppenchats`,
    description: `Snapchat hat keine native Umfrage. So baust du eine in deine Story oder deinen Gruppenchat ein — plus 30 Fragen, die funktionieren.`,
    intro: `Snapchat liefert keine Umfragen. Die meisten User DM-en ihre Freunde für Meinungen oder zählen Emoji-Reaktionen — beides langsam. Droppe einen moomz-Link in deine Story (Link-Tool) oder deinen Gruppenchat, die Stimmen kommen rein, und die Ergebnisse bleiben erreichbar, auch wenn die Story weg ist.`,
    sections: [
      {
        h: `Einen Link zur Snap-Story hinzufügen`,
        body: `Wenn du eine Story erstellst, tippe rechts auf das Büroklammer-Tool. Füg deine moomz-URL ein. Deine Freunde sehen einen „Mehr ansehen"-Button. Tippen, im Browser voten, zurück zur Story. Null Reibung.`,
      },
      {
        h: `Umfragen im Gruppenchat`,
        body: `Droppe den Link in einen beliebigen Gruppenchat. Alle sehen eine Vorschau und können tippen, um abzustimmen, ohne den Chat zu verlassen. Besser als der Nachrichten-Krieg, bei dem die halbe Gruppe die Frage verpasst, weil sie gerade AFK war.`,
      },
      {
        h: `Umfragen, die bei Teens ziehen`,
        body: `Top 3: „wer in unserer Gruppe ist…" (am lautesten, am süßesten, am nervigsten), Entscheidungs-Umfragen („wo gehen wir heute Abend hin?"), Drama-Umfragen („war er im Unrecht?"). Nicht zu viele Optionen — Snapchat-User scrollen schnell, maximal 4.`,
      },
      {
        h: `So bleibt's privat`,
        body: `moomz-Links werden standardmäßig nicht indexiert. Nur Leute mit dem Link finden die Umfrage. Teile sie in einen bestimmten Gruppenchat für private Stimmen. Poste sie nicht öffentlich auf die Stories-Seite, wenn du es eng halten willst.`,
      },
    ],
    polls: [
      { q: `Wer ist am lautesten in unserer Gruppe?`, options: [`Lukas`, `Sarah`, `Theo`, `Lea`] },
      { q: `Wo gehen wir heute Abend hin?`, options: [`Bar`, `Bei mir`, `Park`, `Daheim bleiben`] },
      { q: `Wer ist am lustigsten?`, options: [`Ich, na logo`, `Du`, `Er/sie`, `Niemand`] },
      { q: `Kino oder Bowling?`, options: [`Kino`, `Bowling`, `Weder noch`] },
      { q: `Wer bringt Snacks mit?`, options: [`Ich`, `Du`, `Bestellen`, `Klauen`] },
      { q: `Ihm/ihr antworten?`, options: [`Jetzt`, `Morgen`, `Nie`, `Screen mir das mal`] },
      { q: `Bester Film 2026?`, options: [`Dune 3`, `Avatar 4`, `Anderer`, `Keinen gesehen`] },
      { q: `Wer hat zuerst geghostet?`, options: [`Er`, `Sie`, `Beide gleichzeitig`] },
      { q: `Team Rot oder Blau?`, options: [`Rot`, `Blau`, `Kein Team`] },
      { q: `Lea die Wahrheit sagen?`, options: [`Ja`, `Nein`, `Deine Entscheidung`] },
    ],
    faq: [
      { q: `Hat Snapchat einen Umfrage-Sticker?`, a: `Nein. Nutz einen moomz-Link in deiner Story (Büroklammer-Tool) oder in einem Gruppenchat.` },
      { q: `Wie füge ich einer Snap-Story einen Link hinzu?`, a: `Während du sie erstellst, tippe auf die Büroklammer in den Tools rechts. Füg die moomz-URL ein. Fertig.` },
      { q: `Brauchen meine Freunde einen Account?`, a: `Nein. moomz funktioniert ohne Anmeldung. Der Link öffnet sich, sie voten, sie gehen wieder.` },
      { q: `Verschwindet die Umfrage mit der Story?`, a: `Nein. Die Story ist 24 h da, die Umfrage bleibt aktiv. Teile den Link morgen erneut, damit die Stimmen weiterfließen.` },
    ],
    related: [`instagram-story-poll-de`, `tiktok-poll-de`, `teens-en-de`, `friends-en-de`],
    updatedAt: today,
  },
  {
    slug: `discord-poll-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🎮`,
    title: `Discord-Umfrage Ideen — 30 Fragen für Server & Communitys`,
    h1: `Discord-Umfragen: 30 Ideen, um deinen Server zu aktivieren`,
    description: `Spar dir das Bot-Setup. Droppe einen moomz-Link in einen beliebigen Discord-Channel und deine Community votet anonym. 30 Fragen drin.`,
    intro: `Discords nativer Umfrage-Befehl ist okay für schnelle Votes, aber auf 10 Optionen und einen Server begrenzt. Bot-Lösungen (MEE6, Simple Poll) brauchen Installation plus Rechte. moomz: einfach den Link einfügen, alle voten, die Ergebnisse bleiben live. So nutzt du es richtig.`,
    sections: [
      {
        h: `Nativ vs. Bot vs. moomz-Link`,
        body: `Natives /poll: kostenlos, 10 Optionen, nur auf dem Server. Bots: mehr Features, aber Installation plus Rechte. moomz: sofort, anonym, keine Rechte nötig, teilbar auch außerhalb von Discord. Wähl nach deinem Bedarf.`,
      },
      {
        h: `Community-Umfragen, die funktionieren`,
        body: `Top-Server fahren wöchentlich eine Umfrage in #vote: bester Build des Monats (Gaming), Patch-Urteil, Skin-Ranking. Für Debatten-Server: Hot Takes, moralische Dilemmata, kontroverse Meinungen.`,
      },
      {
        h: `Die Umfrage anpinnen`,
        body: `Erstell die Umfrage, pinne die Nachricht in deinem Haupt-Channel. Die Stimmen laufen tagelang weiter. Schließe ab, indem du das Ergebnis screenshotest und in #announcements postest.`,
      },
      {
        h: `Event-Organisation`,
        body: `Nutz moomz für Raid-Zeiten, Game Nights, neue Channels. Mods sehen die Live-Ergebnisse, ohne Emoji-Reaktionen abzuscannen.`,
      },
    ],
    polls: [
      { q: `Spiel für den nächsten Voice-Abend?`, options: [`LoL`, `Valorant`, `Fortnite`, `Among Us`, `Minecraft`] },
      { q: `Bester Patch dieses Jahr?`, options: [`S1`, `S2`, `S3`, `Alle grottig`] },
      { q: `Neuer Channel?`, options: [`#memes`, `#trading`, `#art`, `#offtopic`] },
      { q: `Ist der neue Charakter OP?`, options: [`Ja, nerfen`, `Ausgewogen`, `Buffen`, `Noch nicht gespielt`] },
      { q: `Welcher RP-Stil?`, options: [`Lore-lastig`, `Casual`, `PvP-Fokus`, `Kein RP`] },
      { q: `Bild des Jahres (Meme-Post)?`, options: [`Der Doge`, `Die Katze`, `Der Frosch`, `Keins`] },
      { q: `Level-System behalten?`, options: [`Ja, macht Spaß`, `Nein, cringe`, `Monatlich resetten`] },
      { q: `Welchen Bot hinzufügen?`, options: [`MEE6`, `Carl-bot`, `Keinen`] },
      { q: `Lieblings-Skin?`, options: [`Skin A`, `Skin B`, `Skin C`, `Standard`] },
      { q: `Raid-Zeit am Samstag?`, options: [`18 Uhr`, `20 Uhr`, `21 Uhr`, `22 Uhr`] },
    ],
    faq: [
      { q: `Brauche ich einen Bot?`, a: `Nein. Füg den moomz-Link in einen beliebigen Channel ein, Discord zeigt eine schicke Vorschau, die Mitglieder tippen zum Abstimmen.` },
      { q: `Ist es anonym?`, a: `Ja. Keine Discord-Namen an den Stimmen. Die Mitglieder voten ohne sozialen Druck.` },
      { q: `Wie viele Optionen?`, a: `2-6 bei moomz. Darüber sinkt die Abschlussquote. Für 8-12 Optionen nimm das native /poll.` },
      { q: `Läuft die Umfrage ab?`, a: `Nein, außer sie liegt wochenlang brach (Anti-Spam). Halte sie am Leben, indem du sie erneut teilst.` },
    ],
    related: [`tiktok-poll-de`, `team-building-en-de`, `high-school-en-de`, `college-en-de`],
    updatedAt: today,
  },
  {
    slug: `couple-questions-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `💖`,
    title: `Pärchen-Umfrage Fragen — 50 Ideen, um die Kompatibilität zu testen`,
    h1: `Pärchen-Umfragen: 50 Fragen, die du deinem Partner stellen kannst`,
    description: `50 anonyme Umfrage-Fragen für Paare — von harmlosen Vorlieben bis zum echten Klartext. Teste die Kompatibilität in 30 Sekunden.`,
    intro: `Eine Umfrage umgeht den sozialen Filter. Dein Partner pickt eine Option, statt eine Antwort schön zu verpacken. Genau deshalb haben Paartherapeuten 2025 angefangen, sie zu empfehlen. Hier sind 50 Fragen, sortiert nach Risikolevel.`,
    sections: [
      {
        h: `Warum Umfragen das Gespräch schlagen`,
        body: `Zwei Verzerrungen versauen direkte Fragen: (1) der Wunsch zu gefallen, (2) die Bedenkzeit. Umfragen schalten beides aus — binäre Wahl, Bauchgefühl-Klick. Du bekommst sauberere Daten als in einem echten Gespräch.`,
      },
      {
        h: `Level 1: harmlose Vorlieben`,
        body: `Fang sanft an: Strandwohnung in der Stadt oder Berghütte, morgens Kaffee oder Tee, ausgehen oder daheim bleiben. Bau erst die Gewohnheit auf. Sobald Umfragen normal sind, könnt ihr tiefer gehen.`,
      },
      {
        h: `Level 2: tägliche Entscheidungen`,
        body: `Heute Abend daheim oder raus? Chinesisch oder Italienisch bestellen? Dieses Wochenende die Schwiegereltern sehen? Umfragen machen aus 30-Minuten-Debatten 30-Sekunden-Entscheidungen.`,
      },
      {
        h: `Level 3: die echten Fragen`,
        body: `Heiraten in 5 Jahren? Kinder ja oder nein? Ins Ausland ziehen, wenn das Angebot kommt? Nutz es anonym, niemals nach einem Streit. Die Umfrage öffnet das Gespräch — sie ersetzt es nicht.`,
      },
    ],
    polls: [
      { q: `Kaffee im Bett oder in der Küche?`, options: [`Immer im Bett`, `Küche`, `Kein Kaffee`] },
      { q: `Urlaub: Strand oder Berge?`, options: [`Strand`, `Berge`, `Beides`, `Daheim bleiben`] },
      { q: `Du bevorzugst:`, options: [`Ruhiger Abend daheim`, `Kleine Dinnerparty`, `Große Party`, `Keine Präferenz`] },
      { q: `Heiraten in 5 Jahren?`, options: [`Ja`, `Später`, `Nichts für mich`, `Vielleicht`] },
      { q: `Kinder?`, options: [`Ja, 1`, `Ja, 2+`, `Niemals`, `Unentschieden`] },
      { q: `Ins Ausland ziehen, wenn angeboten?`, options: [`Ja, ohne Frage`, `Kommt drauf an`, `Nein, ich will bleiben`] },
      { q: `Überraschungs-Geburtstag?`, options: [`Liebe ich`, `Stresst mich`, `Kommt drauf an, wer`] },
      { q: `Schlafposition?`, options: [`Gekuschelt`, `Nebeneinander`, `Weit auseinander`] },
      { q: `Gehalt offen in der Beziehung?`, options: [`Volle Transparenz`, `Grobe Zahlen`, `Privat`] },
      { q: `Ex auf Instagram?`, options: [`Egal`, `Stört mich`, `Zusammen entfolgen`] },
    ],
    faq: [
      { q: `Sieht mein Partner, dass ich die Umfrage erstellt habe?`, a: `Nein. Der geteilte Link zeigt den Ersteller nicht. Du kannst auch im Inkognito-Modus erstellen, für volle Abstreitbarkeit.` },
      { q: `Können wir sehen, wer was gewählt hat?`, a: `Nein. moomz ist komplett anonym. Du siehst nur Prozente.` },
      { q: `Nur zwei Voter — trotzdem anonym?`, a: `Technisch ja, aber natürlich kannst du es ableiten. Hol 2-3 Freunde dazu für echte Anonymität, oder nutz es für Antworten, die ihr eh aufdecken wollt.` },
      { q: `Wie hält man die Gewohnheit?`, a: `Eine Umfrage pro Abend, eine Woche lang. 5 Minuten zum Abstimmen, 10 zum Besprechen des Ergebnisses. Spannender als „wie war dein Tag".` },
    ],
    related: [`first-date-en-de`, `this-or-that-de`, `would-you-rather-en-de`, `valentines-en-de`],
    updatedAt: today,
  },
  {
    slug: `first-date-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🌹`,
    title: `Erstes-Date Eisbrecher-Umfragen — 30 Fragen, die den Vibe retten`,
    h1: `Erstes-Date-Umfragen: 30 Eisbrecher-Fragen, die wirklich ziehen`,
    description: `30 Eisbrecher-Umfragen fürs erste Date. Hol dein Handy raus, mach ein schnelles Voting und rette das Gespräch vor peinlicher Stille.`,
    intro: `Erstes Date hängt bei der 30-Minuten-Marke fest? Hol dein Handy raus, sag „ich hab da diese alberne App — wollen wir die mal testen?", mach eine schnelle Umfrage. Beide voten, beide sehen das Ergebnis, 10 Minuten neues Gespräch freigeschaltet.`,
    sections: [
      {
        h: `Wann du es nutzt (und wann nicht)`,
        body: `Gutes Timing: nach 30 Minuten, wenn der Smalltalk versiegt ist. Schlechtes Timing: beim Getränke-Bestellen. Schlechte Ansage: „ich bin mit einem Skript gekommen." Gute Ansage: „ich hab gerade dieses alberne Ding entdeckt."`,
      },
      {
        h: `Dating-Umfragen, die funktionieren`,
        body: `Am Anfang keine Intimität (Politik, Religion, Exes, Sexualität). Bleib bei Vorlieben: Reisen, Essen, Party-Stil, Tiere, Hobbys. Heb die schweren Themen für Date 2 oder 3 auf.`,
      },
      {
        h: `Der Augen-zu-Voting-Trick`,
        body: `Stell die Frage. Beide schließen 5 Sekunden die Augen. Getrennt voten. Zusammen aufdecken. Killt den „ich vote, was er hören will"-Effekt. Die Wahrheit kommt schneller raus.`,
      },
      {
        h: `Umfragen, die du an Date 1 weglässt`,
        body: `Alles, was dich in den Richter-Modus versetzt („findest du, ich bin zu X?"). Fallen-Umfragen („schlafen wir heute zusammen?"). Politik, Religion, Exes. Halt es leicht — die Umfrage ist ein Spiel, kein Vorstellungsgespräch.`,
      },
    ],
    polls: [
      { q: `Hund oder Katze?`, options: [`Hund`, `Katze`, `Beides`, `Weder noch`] },
      { q: `Strand oder Berge?`, options: [`Strand`, `Berge`, `Stadt`, `Abenteuer`] },
      { q: `Frühstück: süß oder herzhaft?`, options: [`Herzhaft`, `Süß`, `Beides`, `Lass ich aus`] },
      { q: `Heute Abend: idealer Ausgeh-Abend?`, options: [`Restaurant`, `Kino`, `Bar`, `Daheim bleiben`] },
      { q: `Karaoke: Mut oder Pass?`, options: [`Liebe ich`, `Nur betrunken`, `Niemals`, `Nur zum Zuschauen`] },
      { q: `Kochst du?`, options: [`Oft`, `Manchmal`, `Nie`, `Ich übe`] },
      { q: `Welchen Sport schaust du?`, options: [`Fußball`, `Tennis`, `F1`, `Keinen`] },
      { q: `Partys — dein Vibe?`, options: [`Ruhig zu zweit`, `Kleine Gruppe`, `Große Party`, `Solo`] },
      { q: `Film-Genre?`, options: [`Action`, `Komödie`, `Drama`, `Horror`] },
      { q: `Wann stehst du auf?`, options: [`Vor 7 Uhr`, `7-9 Uhr`, `9-11 Uhr`, `Nach Mittag`] },
    ],
    faq: [
      { q: `Ist es nicht cringe, eine Umfrage rauszuholen?`, a: `Nur, wenn du es falsch framst. „Ich hab da dieses alberne Ding" funktioniert. Wenn es nicht ankommt, hast du was über die Kompatibilität gelernt.` },
      { q: `Wie viele Umfragen pro Date?`, a: `Maximal 3-5. Mehr macht daraus ein Quiz statt ein Date.` },
      { q: `Wir waren bei allem einer Meinung — gutes Zeichen?`, a: `Entweder super, oder ihr lügt beide. Dreh bei den nächsten Fragen das Risikolevel hoch.` },
      { q: `Wir waren bei allem uneinig — Dealbreaker?`, a: `Selten. Ihr habt gerade 10 Gesprächsthemen freigeschaltet.` },
    ],
    related: [`couple-questions-de`, `valentines-en-de`, `would-you-rather-en-de`, `this-or-that-de`],
    updatedAt: today,
  },
  {
    slug: `friends-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Freundesgruppe-Umfrage Ideen — 50 Fragen für Chats & IRL`,
    h1: `Freundesgruppe-Umfragen: 50 Ideen zum Entscheiden & Diskutieren`,
    description: `50 Umfragen für deine Clique: Entscheidungen, Tier-Lists, Debatten. Nutzbar in WhatsApp, Discord oder bei IRL-Partys.`,
    intro: `Deine Gruppe hat zwei Modi: Entscheidung (wo essen wir?) und Debatte (wer ist am lautesten?). Umfragen lösen beides. Droppe einen moomz-Link, setz eine 1-Stunden-Deadline, screenshote das Ergebnis. Schluss mit der WhatsApp-Scroll-Steuer.`,
    sections: [
      {
        h: `Entscheidungs-Umfragen: kill den Chat-Lärm`,
        body: `Wo essen wir? Welcher Film? Welcher Trip? Ohne Umfrage: 30 Nachrichten, die Hälfte ignoriert. Mit Umfrage: 5 Minuten, erledigt. Trick: kündige eine Deadline an („Voting endet 19 Uhr").`,
      },
      {
        h: `Tier-List-Umfragen: das Comedy-Gold`,
        body: `Gruppen-Rankings: am lautesten, am süßesten, am ehesten ein Ghoster. Anonyme Stimmen, brutale Ehrlichkeit. Spar dir das für Cliquen, die den Burn vertragen.`,
      },
      {
        h: `Debatten-Umfragen: Hot Takes`,
        body: `„Ist Koriander böse?", „Ananas auf Pizza?", „ist der Gruppenchat zu aktiv?". Es geht nicht um die Lösung — es geht darum, den Riss in deiner Gruppe aufzudecken.`,
      },
      {
        h: `Überraschungs-Geburtstag-Umfragen`,
        body: `Du planst einen Überraschungs-Geburtstag? Erstell einen Sub-Chat ohne das Geburtstagskind, fahr dort alle Umfragen. moomz benachrichtigt niemanden — kein Leak.`,
      },
    ],
    polls: [
      { q: `Wer ist heute Abend am lautesten?`, options: [`Lukas`, `Sarah`, `Theo`, `Lea`] },
      { q: `Wohin am Freitag?`, options: [`Stamm-Bar`, `Neuer Laden`, `Bei mir`, `Restaurant`] },
      { q: `Geburtstagsgeschenk für Lea?`, options: [`Blumen`, `Dinner`, `Amazon-Gutschein`, `Geld zusammenlegen`] },
      { q: `Wer bringt nie was mit?`, options: [`Theo`, `Camille`, `Ich (cope)`, `Alle zahlen`] },
      { q: `Ananas auf Pizza?`, options: [`Ja`, `Niemals`, `Joa`] },
      { q: `Wochenend-Trip?`, options: [`Küste`, `Berge`, `Stadt`, `Daheim bleiben`] },
      { q: `Party-Motto am Freitag?`, options: [`Y2K`, `Schlafanzug`, `Disco`, `Kein Motto`] },
      { q: `Marc einladen?`, options: [`Ja`, `Nö, joa`, `Wenn Lea okay ist`] },
      { q: `Drinks um wie viel Uhr?`, options: [`18 Uhr`, `19 Uhr`, `20 Uhr`, `Spät`] },
      { q: `Wer zahlt das Uber?`, options: [`Aus der Kasse`, `Wer zuerst da war`, `Jeder seins`] },
    ],
    faq: [
      { q: `Sehen die Freunde, wer die Umfrage erstellt hat?`, a: `Nein. Sowohl der Ersteller als auch die Voter sind im geteilten Link anonym.` },
      { q: `Wie viele Freunde können abstimmen?`, a: `Unbegrenzt. 4 oder 400, läuft.` },
      { q: `Wie schließe ich das Voting?`, a: `Kein manuelles Schließen. Kündige eine Deadline an, screenshote das Ergebnis zur Deadline, erklär es für geschlossen.` },
      { q: `Was, wenn jemand doppelt votet?`, a: `Geht nicht. moomz blockiert Doppel-Stimmen per Cookie. Eine Person = eine Stimme.` },
    ],
    related: [`bff-en-de`, `party-en-de`, `drama-polls-de`, `would-you-rather-en-de`],
    updatedAt: today,
  },
  {
    slug: `bff-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `👯`,
    title: `BFF-Umfrage Fragen — 30 Tests für deine beste Freundin`,
    h1: `BFF-Umfragen: 30 Fragen, die eure Freundschaft auf die Probe stellen`,
    description: `30 anonyme Umfragen, die testen, wie gut du deine BFF kennst — und wie gut sie dich. Ehrlich, lustig, manchmal brutal.`,
    intro: `Ihr glaubt, ihr kennt euch in- und auswendig. Wirklich? 30 Umfragen, die die Freundschaft testen — lustig, intim, manchmal brutal. Anonym-Modus heißt ehrliche Antworten, keine diplomatischen Korrekturen.`,
    sections: [
      {
        h: `Das BFF-Quiz-Format`,
        body: `Erstell 10 Umfragen, teil die Links mit deiner BFF. Beide voten getrennt, vergleicht am nächsten Tag. Schlägt das Standard-Insta-BFF-Quiz, weil die Antworten anonym sind — kein Druck, die „richtige" Antwort zu geben.`,
      },
      {
        h: `Fragen, die wirklich was verraten`,
        body: `Lass das Offensichtliche weg (Lieblingsfarbe). Geh auf Level 2: wer ist nerviger, wer zahlt mehr, wer ist der bessere Ex-Richter. Schieb weiter: wer ist eifersüchtiger, wer würde es überleben, wenn die andere ghostet.`,
      },
      {
        h: `Überraschungs-Geburtstag per Umfrage`,
        body: `Zu ihrem Geburtstag fahr mit der Gruppe eine Umfrage „was beschreibt Lea am besten?". Optionen: „immer zu spät", „die Lustigste", „zahlt jedes Mal". Screenshote das Ergebnis, schick es als Geschenk-Karte. Trifft härter als ein „happy birthday".`,
      },
      {
        h: `BFF-Kompatibilität`,
        body: `5 Umfragen zu Dilemmata: „den Trip verlieren oder den Typen verlieren", „ihrem Freund sagen, dass er fremdgeht, oder schweigen", „500 € verleihen, die du nie wiedersiehst, oder Nein sagen". Du misst, wie aligned ihr denkt.`,
      },
    ],
    polls: [
      { q: `Wer zahlt öfter?`, options: [`Ich`, `Du`, `50-50`] },
      { q: `Wer kommt öfter zu spät?`, options: [`Ich`, `Du`, `Gleich`] },
      { q: `Wer ist lustiger?`, options: [`Ich, na logo`, `Du`, `Unentschieden`] },
      { q: `Ihr von ihrem Freund erzählen?`, options: [`Ja, direkt`, `Nicht unsere Sache`, `Kommt drauf an`] },
      { q: `Wenn ich ghosten würde, was würdest du tun?`, options: [`Eine Woche heulen`, `In 2 Monaten drüber sein`, `Mich aufspüren`] },
      { q: `Wer ist eifersüchtiger?`, options: [`Ich`, `Du`, `Keine`] },
      { q: `Wer ist loyaler?`, options: [`Ich`, `Du`, `50-50`] },
      { q: `Restaurant, um das wir streiten würden?`, options: [`Sushi`, `Italienisch`, `Burger`, `Vegan`] },
      { q: `Trip zu zweit — größter Zoff?`, options: [`Timing`, `Geld`, `Musik`, `Wir sind perfekt`] },
      { q: `Wenn du eine Sache an mir ändern könntest?`, options: [`Meine Faulheit`, `Meine Eifersucht`, `Mein Rumgeheule`, `Nichts`] },
    ],
    faq: [
      { q: `Weiß meine BFF, dass ich es erstellt habe?`, a: `Ja, wenn du es direkt schickst. Wenn du über die Gruppe testest, bleibt die Anonymität.` },
      { q: `Geschenk-Idee zum Geburtstag?`, a: `Fahr in der Gruppe 5 Umfragen „wer beschreibt Lea am besten?". Der finale Screenshot wird ein schönes Geschenk.` },
      { q: `Gemeinsames Quiz?`, a: `Ja — jede erstellt 5 Umfragen, tauscht die Links, beide beantworten 10, vergleicht.` },
      { q: `Was, wenn die Antwort wehtut?`, a: `Risiko des Spiels. Wenn du es wissen willst, vote. Wenn nicht, erstell die Umfrage nicht.` },
    ],
    related: [`friends-en-de`, `party-en-de`, `would-you-rather-en-de`, `drama-polls-de`],
    updatedAt: today,
  },
  {
    slug: `party-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🎉`,
    title: `Party-Umfrage Ideen — 40 Fragen, die jeden Abend aufmischen`,
    h1: `Party-Umfragen: 40 Ideen für Hauspartys und Afters`,
    description: `40 Party-Umfragen für deinen Gruppenchat — Eisbrecher, Tier-Lists, Debatten. Vom frühen Abend bis zur 3-Uhr-Entscheidung.`,
    intro: `Partys, die abgehen, haben eines gemeinsam: ein Thema zum Streiten. Umfragen sind sofortige Debatten-Auslöser. Droppe die Frage, alle voten, zwei Minuten später diskutiert ihr, wie irgendjemand das wählen konnte.`,
    sections: [
      {
        h: `Früher Abend: Eisbrecher-Umfragen`,
        body: `Wenn die Leute noch in kleinen Grüppchen stehen, droppe eine Umfrage in den Gruppenchat. „Wer kommt heute Abend zu spät?", „was knabbern wir?". Zieht die ganze Gruppe in ein Gespräch.`,
      },
      {
        h: `Später Abend: Tier-List-Umfragen`,
        body: `Ab 22 Uhr droppe die Freundesgruppe-Tier-List. „Wer ist am nervigsten?", „wer bringt nie was mit?". Die Debatte dauert 30 Min. Warnung: brutale Ehrlichkeit, nur für Gruppen, die das abkönnen.`,
      },
      {
        h: `Tief in der Nacht: Debatten-Umfragen`,
        body: `1 Uhr, die halbe Gruppe ist weg. Die Übriggebliebenen wollen Klartext. Droppe philosophische Hot Takes: „ist eine offene Beziehung legit?", „sollte man je wieder mit einem Ex reden?". Bleibt zivilisiert, bringt die Energie zurück.`,
      },
      {
        h: `3 Uhr: Entscheidungs-Umfragen`,
        body: `Wo pennen wir? Pizza bestellen? Schluss machen? Fahr eine 30-Sekunden-Umfrage, folg dem Ergebnis. Der einzige Moment des Abends, in dem alle das Urteil respektieren, weil keiner mehr die Energie hat, neu zu debattieren.`,
      },
    ],
    polls: [
      { q: `Was bestellen?`, options: [`Pizza`, `Sushi`, `Tacos`, `Nichts mehr`] },
      { q: `Wer ist heute Abend am lautesten?`, options: [`Lukas`, `Theo`, `Sarah`, `Ich`] },
      { q: `Wohin danach?`, options: [`Zu mir`, `Zu dir`, `Club`, `Heim`] },
      { q: `Chillen oder tanzen?`, options: [`Chillen`, `Tanzen`, `Karaoke`, `Stille`] },
      { q: `Schlimmster Ex im Raum?`, options: [`Meiner`, `Deiner`, `Seiner/ihrer`, `Lieber nicht sagen`] },
      { q: `Offene Beziehung — legit?`, options: [`Ja`, `Nein`, `Für manche`, `Kommt drauf an`] },
      { q: `Heiraten mit 30?`, options: [`Romantisch`, `Druck`, `Veraltet`, `Cool, wenn gewollt`] },
      { q: `Ein Spiel spielen?`, options: [`Wahrheit oder Pflicht`, `Werwolf`, `Karaoke`, `Einfach reden`] },
      { q: `Schlimmste olympische Sportart?`, options: [`Dressur`, `Bogenschießen`, `Gehen`, `Curling`] },
      { q: `Wer pennt heute hier?`, options: [`Ich`, `Du`, `Niemand`, `Alle`] },
    ],
    faq: [
      { q: `Wie viele Leute können abstimmen?`, a: `Kein Limit. 8, 30, läuft.` },
      { q: `Braucht man WLAN?`, a: `Ja zum Laden. Einmal geladen, funktionieren die Stimmen auch im Flugmodus.` },
      { q: `Brauchen die Freunde eine App?`, a: `Nein. Öffnet sich in jedem Browser. Keine Anmeldung.` },
      { q: `Schnellster Weg zum Teilen auf der Party?`, a: `Drei Optionen: (1) den Link per AirDrop an alle, (2) in den WhatsApp-Gruppenchat droppen, (3) den Bildschirm zeigen und alle die 5-Zeichen-URL tippen lassen.` },
    ],
    related: [`friends-en-de`, `birthday-en-de`, `would-you-rather-en-de`, `drama-polls-de`],
    updatedAt: today,
  },
  {
    slug: `birthday-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🎂`,
    title: `Geburtstagsparty-Umfrage Ideen — 30 Fragen für Organisatoren`,
    h1: `Geburtstags-Umfragen: 30 Ideen fürs Planen und Hosten`,
    description: `30 Geburtstags-Umfragen für Organisatoren: Geschenk, Datum, Überraschung, Motto. Plus Umfragen als Unterhaltung während der Party.`,
    intro: `Einen Geburtstag für 15 Leute zu organisieren heißt 200 WhatsApp-Nachrichten zu Datum, Location, Geschenk. moomz erledigt das in 30 Minuten. Am Tag selbst werden Umfragen zur Unterhaltung: Tier-Lists, „was beschreibt das Geburtstagskind", Erinnerungs-Ratespiele.`,
    sections: [
      {
        h: `Vor der Party: die 4 wichtigsten Umfragen`,
        body: `1) Datum (3-4 Wochenend-Optionen). 2) Location (bei jemandem, Restaurant, Bar). 3) Geschenk (4-5 Optionen, inkl. „Geld zusammenlegen"). 4) Überraschung ja/nein. Verteil sie 24 h auseinander, überlade die Gruppe nicht.`,
      },
      {
        h: `Während: Unterhaltungs-Umfragen`,
        body: `Fahr „was beschreibt [Geburtstagskind] am besten?" mit Optionen, die die Gruppe eingereicht hat. Zeig das Ergebnis auf dem Fernseher oder lies es beim Kuchen vor. Ein Moment kollektiver Erinnerung.`,
      },
      {
        h: `Gruppen-Geschenk-Umfrage`,
        body: `Statt 3 Stunden Debatte fahr 4 Geschenk-Optionen mit festem Budget. Mehrheit gewinnt, PayPal-Pool gestartet. Schluss mit „ich wollte was anderes".`,
      },
      {
        h: `Jahresrückblick-Umfrage`,
        body: `Für einen Geburtstag am Jahresende fahr eine Best-of-Umfrage: bester Moment mit [Geburtstagskind], beste Party, bester Fail. 6 Optionen aus den Fotos der Gruppe. Das Ergebnis wird ein emotionales Geschenk.`,
      },
    ],
    polls: [
      { q: `Datum für Leas Geburtstag?`, options: [`Fr 12.`, `Sa 13.`, `Sa 20.`, `Nächsten Monat`] },
      { q: `Wo?`, options: [`Bei Lea`, `Bei mir`, `Restaurant`, `Bar`] },
      { q: `Überraschung?`, options: [`Ja`, `Nein, sie hasst Überraschungen`, `Kleine Enthüllung`] },
      { q: `Gruppen-Geschenk?`, options: [`100 € Amazon`, `Dinner für 6`, `Spa-Wochenende`, `Geld zusammenlegen`] },
      { q: `Motto?`, options: [`Disco`, `Pastell`, `Y2K`, `Kein Motto`] },
      { q: `Kuchen — wer bringt ihn?`, options: [`Ich`, `Du`, `Bestellen`, `Selber backen`] },
      { q: `Fotos: Profi oder Handy?`, options: [`Fotograf`, `Polaroid`, `Handy reicht`, `Keine Fotos`] },
      { q: `Was beschreibt das Geburtstagskind am besten?`, options: [`Am lustigsten`, `Am großzügigsten`, `Immer zu spät`, `Am furchtlosesten`] },
      { q: `Karaoke als Unterhaltung?`, options: [`Ja`, `Nein, cringe`, `Nur wenn gut vorbereitet`] },
      { q: `Wann gibt's Kuchen?`, options: [`21 Uhr`, `22 Uhr`, `Mitternacht`, `Wenn alle Hunger haben`] },
    ],
    faq: [
      { q: `Wie vermeidet man die endlose Geschenk-Debatte?`, a: `4 Optionen in einer Umfrage, in 24 h schließen. Mehrheit gewinnt. Wer unzufrieden ist, legt persönliches Budget drauf.` },
      { q: `Wie hält man die Überraschung auf WhatsApp geheim?`, a: `Sub-Chat ohne das Geburtstagskind, fahr die Umfragen dort. Kein Leak von moomz.` },
      { q: `Originelle Geburtstags-Idee?`, a: `Vor der Party fahr „beschreibe [Name] in einem Wort" mit 6 Optionen. Zeig es während des Toasts. Starker emotionaler Moment.` },
      { q: `Kindergeburtstag?`, a: `Pass die Optionen an ihre Welt an: Lieblings-Superheld, Dessert, Spiel. Kinder lieben es abzustimmen.` },
    ],
    related: [`party-en-de`, `family-en-de`, `bachelorette-en-de`, `bachelor-en-de`],
    updatedAt: today,
  },
  {
    slug: `wedding-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `💍`,
    title: `Hochzeits-Umfrage Ideen — 40 Fragen für Brautpaare & Gäste`,
    h1: `Hochzeits-Umfragen: 40 Ideen fürs Planen und Feiern`,
    description: `40 Umfragen für Brautpaare in der Hochzeitsplanung: Location, Catering, Kleid — plus Gäste-Umfragen zu Allergien, Zimmern und Unterhaltung.`,
    intro: `Hochzeitsplanung = 50 Entscheidungen, jede mit starken Meinungen. moomz packt zwei Ebenen: Brautpaar-Entscheidungen (Location, Catering, Fotograf) und Gäste-Input (Ernährungswünsche, geteilte Zimmer, Kinder eingeladen). Plus Unterhaltungs-Umfragen am großen Tag.`,
    sections: [
      {
        h: `Planungs-Umfragen: Brautpaar-Entscheidungen`,
        body: `Jeden Sonntag fahrt ihr eine große Entscheidung per Umfrage. Beide voten getrennt, vergleicht, diskutiert nur bei Uneinigkeiten. Kürzt die Entscheidungszeit um 80 %.`,
      },
      {
        h: `Gäste-Umfragen: vor der Hochzeit`,
        body: `Erstell Umfragen für die RSVP-Details: Ernährung (Allesesser / vegetarisch / vegan / glutenfrei), Kinder ja/nein, Übernachtung ja/nein, Mitfahrgelegenheit. Sammelt es in 2 Tagen statt mit 200 Einzelnachrichten.`,
      },
      {
        h: `Am Tag: Unterhaltungs-Umfragen`,
        body: `Beim Sektempfang fahr „wie hat sich das Paar kennengelernt?" mit 4 Optionen, eine davon echt. Die Gäste voten, die Braut deckt auf. Perfekter Eisbrecher. Oder: „wer ist am ehesten um Mitternacht betrunken?" — riskant, aber lustig.`,
      },
      {
        h: `Nach der Hochzeit: Best-of`,
        body: `Tage danach fahr „bester Moment der Hochzeit?" mit den Gästen. Optionen aus den Fotos: Zeremonie, erster Kuss, erster Tanz, Kuchen, Rede. Du bekommst ein demokratisches Best-of für ein Mini-Fotoalbum.`,
      },
    ],
    polls: [
      { q: `Kleid: Meerjungfrau, Prinzessin oder Boho?`, options: [`Meerjungfrau`, `Prinzessin`, `Boho`, `Keins von dreien`] },
      { q: `Location: Schloss, Weingut oder Strand?`, options: [`Schloss`, `Weingut`, `Strand`, `Klassischer Saal`] },
      { q: `Catering: ?`, options: [`Flying Buffet`, `3-Gänge-Menü`, `Foodtrucks`, `Buffet`] },
      { q: `DJ oder Live-Band?`, options: [`DJ`, `Band`, `Beides`, `Nur Playlist`] },
      { q: `Open Bar oder Selbstzahler?`, options: [`Open Bar`, `Open Bar mit Limit`, `Selbstzahler-Bar`, `Nur Hauswein`] },
      { q: `Kinder eingeladen?`, options: [`Alle`, `Nur Nichten/Neffen`, `Keine`] },
      { q: `Erster Tanz?`, options: [`Klassischer Walzer`, `Choreografiert`, `Überraschung`, `Kein erster Tanz`] },
      { q: `Ernährung der Gäste?`, options: [`Allesesser`, `Vegetarisch`, `Vegan`, `Glutenfrei`] },
      { q: `Zimmer teilen?`, options: [`Ja`, `Jeder regelt selbst`, `Nur Familie`] },
      { q: `Bester Moment der Hochzeit?`, options: [`Zeremonie`, `Erster Kuss`, `Erster Tanz`, `Rede des Trauzeugen`] },
    ],
    faq: [
      { q: `Wie viele Gäste können abstimmen?`, a: `Kein Limit. 50, 200, läuft problemlos.` },
      { q: `Wie hält man die Umfrage privat für die Gäste?`, a: `moomz-Links werden nicht indexiert. Teil sie nur im Gäste-WhatsApp. Wer den Link nicht hat, findet sie nicht.` },
      { q: `Anonyme Umfrage für die Wahl des Trauzeugen?`, a: `Ja — fahr „wer sollte die Hauptrede halten?" mit Optionen. Die Stimmen sind anonym, das Ergebnis wird geteilt.` },
      { q: `Wie erinnert man Nicht-Voter?`, a: `moomz trackt keine Identität. Teil den Link in der Gruppe erneut mit „es fehlen noch 5 Stimmen".` },
    ],
    related: [`bachelorette-en-de`, `bachelor-en-de`, `family-en-de`, `birthday-en-de`],
    updatedAt: today,
  },
  {
    slug: `bachelorette-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `💃`,
    title: `JGA-Umfrage Ideen — 30 Fragen zum Planen des Junggesellinnenabschieds`,
    h1: `JGA-Umfragen: Plant und feiert den perfekten Junggesellinnenabschied`,
    description: `30 Umfragen für die JGA-Planung: Reiseziel, Motto, Aktivitäten. Plus Quiz-Umfragen für den Abend selbst.`,
    intro: `Einen JGA zu planen heißt 4-8 Freundinnen mit 4-8 Meinungen. moomz kürzt die Debatte auf 5 Minuten. Am Tag selbst werden Umfragen zu Partyspielen: „wer kennt die Braut am besten", „was sie als Erstes zu ihrem Verlobten gesagt hat".`,
    sections: [
      {
        h: `Vor der Party: 4 schnelle Entscheidungen`,
        body: `Fahr 4 Umfragen, je 24 h auseinander: (1) Stadt, (2) Motto (schick, sportlich, Party, Spa), (3) Budget pro Kopf, (4) Dauer. Projekt in 96 h gerahmt, nur die Details bleiben.`,
      },
      {
        h: `Am Abend: Quiz-Umfragen über die Braut`,
        body: `Beim Dinner fahr „wer kennt Lea am besten?" mit 5 Quizfragen (erster Kuss, Traumstadt, Lieblingstier). Jede votet blind, vergleicht am Ende. Die Gewinnerin zahlt die Shots.`,
      },
      {
        h: `Erinnerungs-Umfrage`,
        body: `Vor dem Event sammelst du Erinnerungen von den Freundinnen. Fahr „schönste Erinnerung mit Lea" mit 6 Optionen. Zeig das Ergebnis während des Abends. Emotionaler Geschenk-Moment.`,
      },
      {
        h: `Wahrheits-Spiel-Umfrage`,
        body: `Nach ein paar Drinks fahr anonym „peinlichste Erinnerung mit Lea". Anonymität = Ehrlichkeit. Lies die Ergebnisse vor, sortier das Heftige raus, behalt die Perlen für eine Roast-Rede.`,
      },
    ],
    polls: [
      { q: `JGA-Stadt?`, options: [`Paris`, `Lissabon`, `Barcelona`, `Marrakesch`, `Berlin`] },
      { q: `Motto?`, options: [`Schickes Dinner`, `Sportliches Abenteuer`, `Party-Clubbing`, `Relax-Spa`] },
      { q: `Budget pro Kopf?`, options: [`150-200 €`, `200-350 €`, `350-500 €`, `500 €+`] },
      { q: `Dauer?`, options: [`1 Tag`, `Wochenende`, `3 Tage`, `4-5 Tage`] },
      { q: `Aktivität?`, options: [`Tanzkurs`, `Cocktail-Workshop`, `Spa`, `Escape Room`] },
      { q: `Verkleidung mit Motto?`, options: [`Lustig`, `Schick`, `Keine`, `Schlicht in Weiß`] },
      { q: `Überraschung für die Braut?`, options: [`Video vom Verlobten`, `Reden der Freundinnen`, `Besonderes Geschenk`, `Schon geplant`] },
      { q: `Leas erster Kuss?`, options: [`Mit 14`, `Mit 15`, `Mit 16`, `Später`] },
      { q: `Leas Traumstadt?`, options: [`Paris`, `Tokio`, `New York`, `Bali`] },
      { q: `Wer heult bei der Zeremonie am meisten?`, options: [`Braut`, `Mutter`, `Bräutigam`, `Trauzeugin`] },
    ],
    faq: [
      { q: `Wie hält man den JGA geheim?`, a: `Sub-Chat ohne die Braut. moomz benachrichtigt niemanden — kein Leak.` },
      { q: `Maximale Zahl an Freundinnen?`, a: `Unbegrenzt. 4, 20, alle voten parallel.` },
      { q: `Was, wenn am Tag kein Empfang ist?`, a: `Sobald die Seite geladen ist, funktionieren die Stimmen im Flugmodus. Lad sie bei der Ankunft vor.` },
      { q: `Originelle Geschenk-Idee?`, a: `Wochen vorher fahr 5 anonyme Umfragen („schönste Erinnerung an Lea", „ein Wort für Lea"). Druck die Ergebnisse in ein kleines Geschenk-Heftchen für den Tag.` },
    ],
    related: [`wedding-en-de`, `bachelor-en-de`, `birthday-en-de`, `friends-en-de`],
    updatedAt: today,
  },
  {
    slug: `bachelor-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🍻`,
    title: `JGA-Umfrage Ideen für Männer — 30 Fragen zum Planen & für Spiele`,
    h1: `Männer-JGA-Umfragen: Plant einen unvergesslichen Abschied`,
    description: `30 Umfragen für den Junggesellenabschied: Reiseziel, Aktivität, Mutproben. Vom Planen bis zu den Spielen am Abend.`,
    intro: `JGA-Planung für Männer = 6-12 Typen, ein Trauzeuge, 6 verschiedene Meinungen. moomz kürzt das auf einen einzigen Nachmittag. Am Abend sind Umfragen Debatten-Auslöser und Mutproben-Generatoren. Hier ist der Spielplan, ohne in JGA-Klischees abzurutschen.`,
    sections: [
      {
        h: `Vor der Party: entscheidende Umfragen`,
        body: `4 Umfragen: Stadt, Art der Aktivität (Extremsport, Gourmet, Party, Casino), Budget pro Kopf, Dauer. Wenn die Mehrheit Kart fahren will, dann wird Kart gefahren. Keine 2-Stunden-Debatten.`,
      },
      {
        h: `Aktivitäts-Umfragen`,
        body: `Kart fahren vs. Paintball, Bowling vs. Escape Room, Poker vs. Eckkneipe, Boot vs. Spa. Fahr die Optionen paarweise. Für den Abend: Techno-Club oder Cocktailbar, Karaoke ja/nein, After-Party daheim oder draußen.`,
      },
      {
        h: `Quiz über den Bräutigam`,
        body: `Beim Dinner fahr 5 Quiz-Umfragen über den Bräutigam: erster Kuss, erster Kater, Lieblingsstadt, größter Fail. Die Jungs voten, der Bräutigam deckt auf. Versteckte Storys kommen ans Licht — Material für die nächsten zehn Jahre Insider-Witze.`,
      },
      {
        h: `Mutproben-Umfrage`,
        body: `Fahr eine Mutproben-Umfrage mit 4 Optionen. Der Mehrheits-Sieger = seine Challenge für den Abend. Halt es lustig, aber nicht erniedrigend. Limit: Er erinnert sich gut daran und lacht am nächsten Tag.`,
      },
    ],
    polls: [
      { q: `JGA-Stadt?`, options: [`Amsterdam`, `Berlin`, `Lissabon`, `Vor Ort`, `Vegas`] },
      { q: `Art des JGA?`, options: [`Extremsport`, `Gourmet`, `Party`, `Casino`] },
      { q: `Budget pro Kopf?`, options: [`150-250 €`, `250-400 €`, `400-600 €`, `600 €+`] },
      { q: `Dauer?`, options: [`1 Nacht`, `Wochenende`, `3 Tage`] },
      { q: `Aktivität?`, options: [`Kart fahren`, `Paintball`, `Escape Room`, `Boot`] },
      { q: `Abend?`, options: [`Techno-Club`, `Cocktailbar`, `Karaoke`, `Casino`] },
      { q: `Mutprobe für den Bräutigam?`, options: [`Schlechter Striptease`, `Karaoke in Boxershorts`, `Klebe-Tattoo`, `Trinkspiel`] },
      { q: `Erster Kuss des Bräutigams?`, options: [`Mit 14`, `Mit 16`, `Mit 18`, `Später`] },
      { q: `Größter Fail des Bräutigams?`, options: [`Erasmus`, `Studentenparty`, `Urlaub`, `Unaussprechlich`] },
      { q: `Wer ist heute Abend als Erstes hinüber?`, options: [`Bräutigam`, `Trauzeuge`, `Theo`, `Alle`] },
    ],
    faq: [
      { q: `Den JGA geheim halten?`, a: `Sub-Chat ohne den Bräutigam. moomz benachrichtigt nicht. Kein Leak.` },
      { q: `Maximale Zahl an Jungs?`, a: `Unbegrenzt. 6 oder 20, alles gut.` },
      { q: `Kann der Bräutigam beim Quiz am Tag mit abstimmen?`, a: `Ja — er kann am Ende jeder Umfrage die richtige Antwort aufdecken.` },
      { q: `Idee für ein Gruppengeschenk?`, a: `Anonyme Umfrage „ein Wort für [Bräutigam]" an alle Freunde. Druck die Ergebnisse gerahmt als Geschenk. Ein rührendes Andenken.` },
    ],
    related: [`bachelorette-en-de`, `wedding-en-de`, `friends-en-de`, `party-en-de`],
    updatedAt: today,
  },
  {
    slug: `baby-shower-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `👶`,
    title: `Babyparty-Umfrage Ideen — 30 Fragen für Gastgeber & Gäste`,
    h1: `Babyparty-Umfragen: Rate mit und bring die Party in Schwung`,
    description: `30 Babyparty-Umfragen: Name, Geschlecht, Geburtsdatum, erstes Wort. Plus Umfragen fürs Gruppengeschenk.`,
    intro: `Babypartys = 15 Gäste, die mitmachen wollen, aber nicht wissen wie. moomz wird zum Nachmittags-Spiel: rate das Geburtsdatum, das Gewicht, das erste Wort, das Geschlecht (falls noch nicht verraten). Die werdenden Eltern behalten die Screenshots als Andenken.`,
    sections: [
      {
        h: `Rate-das-Baby-Umfragen`,
        body: `Klassiker: Geburtsdatum (4 Optionen rund um den errechneten Termin), Gewicht, Größe, Haarfarbe. Jeder votet; 6 Monate später decken die Eltern den Gewinner auf. Noch einen draufsetzen: „der spätere Beruf des Babys". Quatsch, aber lustig.`,
      },
      {
        h: `Gruppengeschenk-Umfrage`,
        body: `Die Eltern haben eine Wunschliste? Fahr „welches Gruppengeschenk?" mit 4 Wunschlisten-Optionen plus angegebenem Budget. Keine Dopplungen, keine Debatte. Alle steigen in den einen Pool ein.`,
      },
      {
        h: `Namens-Umfrage (falls nicht gewählt)`,
        body: `Die Eltern sind noch unentschlossen (oder wollen Input)? Fahr eine Umfrage mit 4-5 Namen. Hinweis: Die Eltern müssen sich nicht daran halten. Trotzdem ein super Gäste-Spiel.`,
      },
      {
        h: `Meta-Umfragen über die Gruppe`,
        body: `Zwischen den Spielen fahr „wer in der Gruppe ist als Nächstes schwanger?", „wer macht die meisten Babyfotos?", „wer wird die Patin?". Lustig, sorgt für Debatte, erniedrigt niemanden.`,
      },
    ],
    polls: [
      { q: `Geburtsdatum?`, options: [`Vor dem Termin`, `Am Tag selbst`, `1-3 Tage danach`, `Über eine Woche danach`] },
      { q: `Geschlecht des Babys?`, options: [`Mädchen`, `Junge`, `Überraschung`, `Zwillinge`] },
      { q: `Geburtsgewicht?`, options: [`Unter 2,7 kg`, `2,7-3,2 kg`, `3,2-3,6 kg`, `Über 3,6 kg`] },
      { q: `Haarfarbe?`, options: [`Blond`, `Braun`, `Dunkel`, `Rot`] },
      { q: `Lieblingsname?`, options: [`Leo`, `Adam`, `Camille`, `Sasha`, `Mila`] },
      { q: `Der spätere Beruf des Babys?`, options: [`Künstler`, `Sportler`, `Wissenschaftler`, `Influencer`] },
      { q: `Erstes Wort?`, options: [`Mama`, `Papa`, `Nein`, `Mehr`] },
      { q: `Gruppengeschenk?`, options: [`Kinderwagen`, `Autositz`, `Nachtlicht`, `Geld zusammenlegen`] },
      { q: `Wer in der Gruppe ist als Nächstes schwanger?`, options: [`Lea`, `Sarah`, `Camille`, `Ich`] },
      { q: `Dominante Farbe im Kinderzimmer?`, options: [`Pastellrosa`, `Pastellblau`, `Beige`, `Salbeigrün`] },
    ],
    faq: [
      { q: `Die Ergebnisse als Andenken behalten?`, a: `Screenshote am Ende der Babyparty. Die Umfrage bleibt über den moomz-Link erreichbar, aber ein datierter Screen ist das bessere Andenken.` },
      { q: `Können die Eltern auch abstimmen?`, a: `Ja — besonders bei Namens- oder Geschenk-Umfragen. Beim Geburtsdatum-Raten sollten sie sich lieber enthalten.` },
      { q: `Freunde, die nicht da sein können?`, a: `Schick den moomz-Link per WhatsApp. Sie voten von zu Hause, gleiche Zählung. Perfekt für Freunde im Ausland.` },
      { q: `Wie viele Umfragen bei einer Babyparty?`, a: `Verteil sie: 1 alle 15-20 Min. Insgesamt: 5-7 Umfragen über einen Nachmittag. Mehr macht daraus ein Meeting.` },
    ],
    related: [`birthday-en-de`, `family-en-de`, `bachelorette-en-de`, `this-or-that-de`],
    updatedAt: today,
  },
];
