import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasDe2: SeoPage[] = [
  {
    slug: `family-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `👨‍👩‍👧`,
    title: `Umfrage-Ideen für die Familie — 30 Prompts für Entscheidungen ohne Drama`,
    h1: `Familien-Umfragen: als Familie entscheiden, ohne Stress`,
    description: `30 Familien-Umfragen für Urlaub, Essen, Deko, Serien. Plus die Methode, mit der sogar Schwiegereltern und Teenies mitvoten — ohne Zoff.`,
    intro: `Familienentscheidungen sind die härtesten. Jede:r hat eine knallharte Meinung, keiner will nachgeben, und Diskussionen eskalieren in Sekunden. moomz entschärft das: alle voten, Mehrheit gewinnt, Thema durch. Bonus: Die Kids lernen, dass Demokratie ≠ Trotzanfall ist.`,
    sections: [
      {
        h: `Urlaub: Schluss mit der 3-Monats-Debatte`,
        body: `Klassiker: 4 Reiseziele, alle voten, der Mehrheit folgen. Die Umfrage killt das "ihr sucht eh immer aus". Wenn Mama A wählt, Papa B, zwei Teenies C und D — hatte jede:r eine Stimme, Mehrheit gewinnt.`,
      },
      {
        h: `Sonntagsessen`,
        body: `Wer will was zum Mittag? Statt 30-Minuten-Theater à la "Was wollt ihr denn?" startest du um 11 Uhr eine Umfrage mit 4 Optionen. Bis Mittag steht die Antwort.`,
      },
      {
        h: `Deko / Renovierung`,
        body: `Neu streichen? Neues Sofa? Mach eine Umfrage mit Optionen. Mehrheit gewinnt. Wenn die Schwiegermutter dagegen ist — so läuft das System. Es ist die Wohnung der Kids, nicht ihre.`,
      },
      {
        h: `Familien-Filmabend`,
        body: `Der Sonntagabend-Kampf. 4 Optionen: Action, Comedy, Drama, Doku. Alle voten, wir schauen. Schluss mit "das hab ich schon gesehen".`,
      },
    ],
    polls: [
      { q: `Sommerurlaub?`, options: [`Strand Spanien`, `Berge Pyrenäen`, `Städtetrip Italien`, `Camping Frankreich`] },
      { q: `Sonntagsessen?`, options: [`Restaurant`, `Lieferdienst`, `Selber kochen`, `Jeder für sich`] },
      { q: `Film heute Abend?`, options: [`Comedy`, `Action`, `Animation`, `Drama`] },
      { q: `Wohnzimmer-Farbe?`, options: [`Cremeweiß`, `Beige`, `Petrol`, `Salbeigrün`] },
      { q: `Oma am Sonntag einladen?`, options: [`Ja`, `Nee, keine Lust`, `Ok, aber kurz`] },
      { q: `Haustier für die Familie?`, options: [`Hund`, `Katze`, `Kaninchen`, `Keins`] },
      { q: `Familiensport?`, options: [`Radeln`, `Wandern`, `Fußball`, `Schwimmbad`] },
      { q: `Papas Geburtstagsessen?`, options: [`Brasserie`, `Italiener`, `Japaner`, `Zuhause`] },
      { q: `Konsole für die Kids?`, options: [`Switch`, `PS5`, `Xbox`, `Keine`] },
      { q: `Wochenend-Ausflug?`, options: [`Park`, `Kino`, `Bowling`, `Zuhause`] },
    ],
    faq: [
      { q: `Wie umgehe ich das Veto der Schwiegermutter?`, a: `Sie votet wie alle anderen. Wenn sie jedes Mal überstimmt wird, passen ihre Picks einfach nicht. Genau das ist der Sinn der Umfrage: dominante Stimmen neutralisieren.` },
      { q: `Kids zu klein zum Lesen?`, a: `Lies ihnen die Optionen vor. Sie voten auf deinem Handy. Pädagogisch wertvoll.` },
      { q: `Was bei Gleichstand?`, a: `Runde 2 zwischen den Top 2. Oder eine 3. Person dazuholen, die das Patt bricht.` },
      { q: `Was, wenn jemand nicht voten will?`, a: `Pech. Das Ergebnis wird ohne sie:ihn entschieden. So lautet die Regel.` },
    ],
    related: [`birthday-en-de`, `high-school-en-de`, `would-you-rather-en-de`, `this-or-that-de`],
    updatedAt: today,
  },
  {
    slug: `teens-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🤳`,
    title: `Umfrage-Ideen für Teenies — 30 Prompts für Mittel- und Oberstufe`,
    h1: `Teenie-Umfragen: Fragen, die wirklich Debatten auslösen`,
    description: `30 Umfragen extra für Teenies: Drama, Schule, Dating, Challenges. Ab in die Snap-Story oder den Discord-Server.`,
    intro: `Teenies scrollen täglich durch Umfragen — Snap-Storys, Instagram, Gruppenchats. Die meisten sind voll basic ("magst du mich?"). Hier sind 30 smartere Prompts, die echte Debatten zünden, ohne in reines Gossip-Drama abzurutschen.`,
    sections: [
      {
        h: `Drama ohne Gemeinheit`,
        body: `Drama zieht, aber die Umfrage sollte auf Verhalten zielen, nicht auf Personen. "Soll sie ihrer Freundin sagen, dass ihr Freund fremdgeht?" schlägt "Lea ist dumm, dass sie ihm glaubt". Baut Argumente auf, vermeidet direktes Mobbing.`,
      },
      {
        h: `Schul-Umfragen (mit Respekt)`,
        body: `"Beste:r Lehrer:in des Jahres" mit Namen ist okay. "Schlechteste:r Lehrer:in" riskiert Mobbing. Bleib positiv: bester Kurs, lustigste:r Lehrer:in, nützlichstes Fach. Funktioniert auch für die Schülerzeitung.`,
      },
      {
        h: `Dating-Umfragen`,
        body: `Verhaltensbasiert: hat er ihre Story geliked, hat er schnell geantwortet, was hat er den Freunden erzählt. In der Snap-Story teilen für eine schulweite Meinung. Konkrete Fälle anonym halten, um Eskalation zu vermeiden.`,
      },
      {
        h: `Challenge-Umfragen`,
        body: `TikTok- / IRL-Challenges: "bei Theater anmelden?", "den Y2K-Look starten?", "Camille taggen, damit sie's sieht?". Umfragen werden zu Auslösern für Gruppen-Challenges.`,
      },
    ],
    polls: [
      { q: `Lea die Wahrheit über ihren Freund sagen?`, options: [`Ja, direkt`, `Nicht unser Ding`, `Screenshot aufheben`] },
      { q: `Beste:r Lehrer:in dieses Jahr?`, options: [`Herr Schmidt`, `Frau Martinez`, `Herr Lee`, `Frau Patel`] },
      { q: `Schlimmste Ecke an der Schule?`, options: [`Sportpause`, `Mensa`, `Flure am Morgen`, `Toiletten`] },
      { q: `Wie lang, bis du antwortest?`, options: [`Sofort`, `1 Std.`, `Nächster Tag`, `Nie`] },
      { q: `Steht er wirklich auf sie?`, options: [`Ja`, `Nur für die Views`, `Nee, billig`, `Sehen wir morgen`] },
      { q: `Klassenfahrt?`, options: [`Spanien`, `Italien`, `London`, `Hierbleiben`] },
      { q: `Wahlfach nächstes Jahr?`, options: [`Theater`, `Sport`, `Latein`, `Nichts`] },
      { q: `Trends 2026?`, options: [`Y2K`, `Coquette`, `Streetwear`, `90er-Vintage`] },
      { q: `Nach der Schule wohin?`, options: [`McDonald's`, `Imbiss`, `Zu mir`, `Park`] },
      { q: `Nächste Pause schwänzen?`, options: [`Ja`, `Kommt aufs Wetter an`, `Nee, ist meine Pause`] },
    ],
    faq: [
      { q: `Sicher für Teenies?`, a: `Ja. Keine Anmeldung, keine persönlichen Daten. Die Stimme bleibt anonym. Bei Drama-Umfragen: bei Verhalten bleiben, nicht bei Personen.` },
      { q: `In der Snap-Story teilen?`, a: `Ja — Snaps Link-Sticker akzeptiert moomz-Links. Freunde tippen drauf und voten.` },
      { q: `Und Mobbing?`, a: `Die moomz-Moderation entfernt jede Umfrage, die eine Person namentlich nennt + beleidigt. Der beste Schutz ist die Kultur: konstruktive Fragen stellen, keine demütigenden.` },
      { q: `Sehen das meine Eltern?`, a: `Nein. Die Umfrage ist anonym, Eltern werden nicht benachrichtigt. Unter 15 trotzdem schlau, es mit ihnen zu besprechen.` },
    ],
    related: [`high-school-en-de`, `snapchat-poll-de`, `drama-polls-de`, `instagram-story-poll-de`],
    updatedAt: today,
  },
  {
    slug: `high-school-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🎒`,
    title: `Umfrage-Ideen für die Oberstufe — 30 Prompts für Klasse & Schülervertretung`,
    h1: `Oberstufen-Umfragen: für die Klasse, Snap und die Schülervertretung`,
    description: `30 Umfragen für die Oberstufe: Wandertag-Wahl, Abi-Motto, Klassendrama, Schülervertretung. Plus Anonym-Modus für heikle Themen.`,
    intro: `Oberstufe = 30+ Schüler:innen pro Klasse, mehrere Snap-Gruppen, eine Schülervertretung, die Dinge entscheidet, und Dauer-Drama. moomz wird zum demokratischen Tool für Klassenentscheidungen UND zum Gesprächsöffner für Flur-Debatten.`,
    sections: [
      {
        h: `Klassen-Umfragen: im großen Stil entscheiden`,
        body: `Wandertag, Abschlussfilm, Reise-Motto, Klassen-Shirt. Statt Zettel rumzureichen in der Mittagspause startest du eine moomz-Umfrage und teilst sie im Klassen-Snap. 24 Std. später hast du eine Antwort, sogar Lehrkräfte können sie an den Prozentwerten ablesen.`,
      },
      {
        h: `Umfragen für die Schülervertretung`,
        body: `Die SV organisiert Events. Bei jedem: Abi-Motto, Location der Kennenlernparty, Wahlkandidat:innen. Mach eine schulweite Umfrage. Echte Demokratie statt Strichliste an der Tafel.`,
      },
      {
        h: `Flur-Drama-Umfragen`,
        body: `Umfragen, die durch die Flure kursieren: niedlichstes Pärchen der Klasse, "wird's am weitesten bringen", wer wen auf dem Abiball datet. Sparsam einsetzen — verspielt bleiben, nicht demütigend.`,
      },
      {
        h: `Lerngruppen-Umfragen`,
        body: `Kurz vor den Klausuren koordiniert moomz: welches Kapitel wir gemeinsam wiederholen, wer welche Themen-Zusammenfassung macht. Gemeinsame Orga ohne 30 wild durcheinander geschriebene Nachrichten.`,
      },
    ],
    polls: [
      { q: `Wandertag im April?`, options: [`Museum`, `Historische Stätte`, `Aussichtsturm`, `Kino`] },
      { q: `Abi-Motto?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Kein Motto`] },
      { q: `Film zum Schuljahresende?`, options: [`Inception`, `Forrest Gump`, `Whiplash`, `Lehrkraft wählt`] },
      { q: `Klassen-Shirt?`, options: [`Schwarz mit Spruch`, `Weiß minimal`, `Bunt`, `Kein Shirt`] },
      { q: `Niedlichstes Pärchen?`, options: [`Lea & Lucas`, `Sarah & Theo`, `Cam & Ines`, `Keins`] },
      { q: `Schlimmster Stundenplan-Slot?`, options: [`Montag 8 Uhr`, `Mi 17 Uhr`, `Freitag 17 Uhr`, `Dienstag 16-18 Uhr`] },
      { q: `Kennenlernparty?`, options: [`In der Schule`, `Bei jemandem`, `Bar ab 18`, `Keine Party`] },
      { q: `Leistungskurs-Fokus?`, options: [`Mathe`, `Physik`, `Wirtschaft`, `Geschichte`] },
      { q: `Schlimmstes Fach?`, options: [`Mathe`, `Geschichte`, `Philosophie`, `Keins, alles okay`] },
      { q: `Lerngruppen-Fokus?`, options: [`Mathe`, `Englisch`, `Geschichte`, `Allein lernen`] },
    ],
    faq: [
      { q: `Für die Schülervertretung nutzbar?`, a: `Ja — genau das richtige Tool, um die ganze Klasse abstimmen zu lassen. Wirf den moomz-Link in den Schul-Chat.` },
      { q: `Anonyme Drama-Umfragen?`, a: `Ja — Stimmen sind anonym. Aber vermeide Umfragen, die eine einzelne Person demütigen. moomz-Moderation + gesunder Menschenverstand.` },
      { q: `Können Lehrkräfte das Ergebnis bestätigen?`, a: `Ja — zeig ihnen den Bildschirm mit Prozentwerten. Glaubwürdiger als ein Zettel.` },
      { q: `Schulübergreifende Umfragen?`, a: `Ja — teil den Link in schulübergreifenden Snap-Gruppen. Die Umfrage läuft, solange Leute den Link haben.` },
    ],
    related: [`teens-en-de`, `college-en-de`, `drama-polls-de`, `discord-poll-de`],
    updatedAt: today,
  },
  {
    slug: `college-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🎓`,
    title: `Umfrage-Ideen fürs Studium — 30 Prompts für Jahrgang, Fachschaft & WG`,
    h1: `Uni-Umfragen: für den Kurs, die Fachschaft und WG-Drama`,
    description: `30 Uni-Umfragen: Party-Mottos, Erstiwochenende, Lerngruppen, WG-Entscheidungen. Gebaut für Jahrgänge von 200-1000 Studierenden.`,
    intro: `Uni = 200+ Studierende pro Jahrgang ohne native Möglichkeit, gemeinsam abzustimmen. moomz wird zum demokratischen Tool des Jahrgangs. Fachschafts-Events, Erstiwochenende, politische Meinungen, Lerngruppen — alles läuft über einen geteilten Link.`,
    sections: [
      {
        h: `Umfragen für Fachschaft und Jahrgangsrat`,
        body: `Vor jedem Event eine Umfrage: Motto, Location, Eintrittspreis, Shirt-Spruch. Die Fachschaft sammelt 200-500 Stimmen in 48 Std., die Entscheidung ist demokratisch. Genauso bei Wahlen der Kursvertretung.`,
      },
      {
        h: `Umfragen fürs Erstiwochenende`,
        body: `Das größte Event des Jahres. moomz klärt vorab: Reiseziel (4 Optionen), Motto, Budget-Stufe, Aktivitäten. Sogar "wer teilt sich ein Zimmer" — nützlich für die Logistik.`,
      },
      {
        h: `Politische Umfragen (anonym)`,
        body: `Bei Streiks / Vollversammlungen zeigen anonyme Umfragen die echte Meinung. Lautstarke Gruppen dominieren nicht. Die Fachschaft kann das Ergebnis zeigen, um die Debatte zu strukturieren.`,
      },
      {
        h: `Koordination von Lerngruppen`,
        body: `Vor den Klausuren eine Umfrage: wer welche Themen-Zusammenfassung macht, Orte für die Lernsessions. Aufgabenteilung per Demokratie schlägt 50 wild verstreute Discord-Nachrichten.`,
      },
    ],
    polls: [
      { q: `Reiseziel Erstiwochenende?`, options: [`Spanien`, `Italien`, `Deutschland`, `Landidylle`] },
      { q: `Party-Motto?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Kein Motto`] },
      { q: `Preis fürs Fachschafts-Event?`, options: [`5 €`, `10 €`, `15 €`, `Gratis`] },
      { q: `Morgen Vorlesungen blockieren?`, options: [`Ja, auf jeden`, `Nee, wir verlieren Stunden`, `In der VV abstimmen`] },
      { q: `Kursvertretung?`, options: [`Lea`, `Lucas`, `Theo`, `Camille`] },
      { q: `Party Donnerstag oder Freitag?`, options: [`Donnerstag`, `Freitag`, `Beides`, `Keins`] },
      { q: `Erasmus-Ziel nächstes Jahr?`, options: [`Spanien`, `Deutschland`, `UK`, `Niederlande`] },
      { q: `Schlimmster Kurs dieses Semester?`, options: [`Statistik`, `VWL`, `Marketing`, `Geschichte`] },
      { q: `Gemeinsame Lernsession?`, options: [`Ja`, `Nee, allein`, `Nur die Übungen`] },
      { q: `Mensa heute?`, options: [`Essbar`, `Naja`, `Skip`, `Schon geskippt`] },
    ],
    faq: [
      { q: `Wie viele Studierende maximal?`, a: `Kein Limit. 200, 500, 1000 — alle voten parallel.` },
      { q: `In einem großen Jahrgang teilen?`, a: `Discord- / Telegram- / Facebook-Gruppe. Der kurze Link (5 Zeichen) lässt sich sogar mündlich easy teilen.` },
      { q: `Anonyme politische Umfragen?`, a: `Anonymität schützt die Votenden. Das Ergebnis zeigt die echte Meinung, ohne jemanden bloßzustellen.` },
      { q: `Zählt das als Abstimmung in der Vollversammlung?`, a: `Rechtlich nein. Aber ein top Indikator vor der Debatte.` },
    ],
    related: [`high-school-en-de`, `discord-poll-de`, `teens-en-de`, `friends-en-de`],
    updatedAt: today,
  },
  {
    slug: `classroom-teacher-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🏫`,
    title: `Umfrage-Ideen für den Unterricht — 25 Prompts für Lehrkräfte`,
    h1: `Klassen-Umfragen für Lehrkräfte: im Unterricht abstimmen ohne Papier`,
    description: `25 Umfragen für den Unterricht: Maskottchen-Name, Wandertag, Schuljahres-Aufführung. Demokratisches Tool für Grund- und Mittelschule.`,
    intro: `Grund- und Mittelschullehrkräfte nutzen traditionell Papier oder Handzeichen. Mit moomz befragst du deine Klasse in 30 Sekunden: QR-Code aufs Smartboard, die Schüler:innen voten auf Tablets. Pädagogischer Bonus: Sie lernen, was eine echte Abstimmung ist.`,
    sections: [
      {
        h: `Warum Umfragen im Unterricht`,
        body: `Mit 7-12 Jahren verstehen Kinder das Abstimmen, üben es aber selten. Eine wöchentliche Umfrage wird zum Mini-Ritual: Name des Klassenmaskottchens, Wahl des Wandertags, Motto der Schuljahres-Aufführung. Öffentliches Ergebnis, diskutierbar, wiederholbar.`,
      },
      {
        h: `So richtest du es ein`,
        body: `Erstell die moomz-Umfrage am Handy/PC. Zeig den Bildschirm übers Smartboard. Schreib die 5-Zeichen-URL an die Tafel. Die Schüler:innen tippen sie aufs Tablet. Voten, Live-Ergebnis groß angezeigt.`,
      },
      {
        h: `Mehr als gemeinsame Entscheidungen`,
        body: `Nutz Umfragen für formative Bewertung: "Welcher Satz ist korrekt?" mit 3 Optionen. Anonyme Stimmen zeigen das echte Verständnis besser als ein Test auf Papier.`,
      },
      {
        h: `Grenzen und Vorsichtsmaßnahmen`,
        body: `Keine persönlichen Daten erhoben — für diesen Zweck DSGVO-freundlich. Prüf die Richtlinien deiner Schule, aber das anonyme Design von moomz ist mit Bildungsvorgaben in der Regel kompatibel.`,
      },
    ],
    polls: [
      { q: `Name des Klassenmaskottchens?`, options: [`Choco`, `Pixel`, `Tornado`, `Keks`] },
      { q: `Wandertag im Mai?`, options: [`Zoo`, `Museum`, `Naturpark`, `Kino`] },
      { q: `Buch des Monats?`, options: [`Charlottes Spinne`, `Gregs Tagebuch`, `Das magische Baumhaus`, `Anderes`] },
      { q: `Motto der Schuljahres-Aufführung?`, options: [`Zirkus`, `Weltraum`, `Dschungel`, `Geschichte`] },
      { q: `Freitagnachmittags-Aktivität?`, options: [`Malen`, `Gruppenspiel`, `Lesen`, `Sport`] },
      { q: `Lieblingstier?`, options: [`Hund`, `Katze`, `Pferd`, `Löwe`] },
      { q: `Name fürs künftige Goldfischlein?`, options: [`Blubber`, `Nemo`, `Goldi`, `Knolle`] },
      { q: `Farbe des Klassen-Shirts?`, options: [`Rot`, `Blau`, `Grün`, `Gelb`] },
      { q: `Lieblings-Mannschaftssport?`, options: [`Fußball`, `Basketball`, `Handball`, `Laufen`] },
      { q: `Lieblings-Nachtisch in der Mensa?`, options: [`Joghurt`, `Apfelmus`, `Obst`, `Kuchen`] },
    ],
    faq: [
      { q: `Kostenlos für Lehrkräfte?`, a: `Ja, komplett kostenlos. Kein Premium nötig für die Nutzung im Unterricht.` },
      { q: `Brauchen Schüler:innen Accounts?`, a: `Nein. Keine Anmeldung, keine E-Mail. Link öffnen, voten, fertig.` },
      { q: `Sind die Stimmen anonym?`, a: `Ja. Selbst du als Lehrkraft siehst nur Prozentwerte, nicht wer was gevotet hat. Beruhigend für schüchterne Kinder.` },
      { q: `Mit dem Smartboard verbinden?`, a: `Zeig die moomz-Umfrageseite im Vollbild. Beobachte, wie sich die Ergebnisse in Echtzeit aktualisieren, während die Kinder voten.` },
    ],
    related: [`teens-en-de`, `family-en-de`, `high-school-en-de`, `college-en-de`],
    updatedAt: today,
  },
  {
    slug: `coworkers-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `💼`,
    title: `Umfrage-Ideen für Kolleg:innen — 30 Prompts fürs Büro & Homeoffice`,
    h1: `Kolleg:innen-Umfragen: für Slack, Teams und Remote-Arbeit`,
    description: `30 Umfragen für Kolleg:innen: Mittagsrestaurant, Offsite-Location, Kaffee vs. Tee. Plus die Methode, um per Slack oder Teams abzustimmen.`,
    intro: `Büro-Entscheidungen bei 8 Kolleg:innen mit 8 Meinungen dauern eine Stunde und enden mit "klären wir morgen". moomz in deinem Slack-Channel: 10 Minuten später hast du eine Antwort. Bonus: bricht das Eis, gerade im Homeoffice, wo die Kaffeepause fehlt.`,
    sections: [
      {
        h: `Entscheidungs-Umfragen`,
        body: `Freitagsmittag, jährliches Offsite, Büro-Deko, Kaffeemaschine — moomz, 4 Optionen, max. 24 Std. Schluss mit "Ich schlage vor…", das im Slack-Lärm untergeht.`,
      },
      {
        h: `Kultur-Umfragen`,
        body: `Kennenlernen ohne Intimität: bester Film des Jahres, Lieblings-Podcast, Lieblingsverein, Traumstadt. Bester Eisbrecher für Remote-Teams.`,
      },
      {
        h: `Anonyme Feedback-Umfragen`,
        body: `Der Anonym-Modus von moomz ist Gold für die Team-Kultur: "Meetings zu lang?", "Funktioniert 3 Tage Homeoffice?", "Ist der Büro-Kaffee gut genug?". Du bekommst die Wahrheit statt höfliches Face-to-Face-Feedback.`,
      },
      {
        h: `Teambuilding-Umfragen`,
        body: `Vor jedem Teambuilding: Aktivität (Escape, Sport, Gastro, Kreatives), Dauer, Budget. Alle sind an der Entscheidung beteiligt, nicht nur HR. Engagement steigt, bevor das Event überhaupt startet.`,
      },
    ],
    polls: [
      { q: `Freitags-Mittagessen?`, options: [`Italiener`, `Japaner`, `Brasserie`, `Burger`] },
      { q: `Ort fürs jährliche Offsite?`, options: [`Berge`, `Küste`, `Ausland`, `Lokal`] },
      { q: `Funktionieren 3 Tage Homeoffice?`, options: [`Ja, perfekt`, `Mehr`, `Weniger`, `100 % Büro`] },
      { q: `Meetings zu lang?`, options: [`Ja, klar`, `Naja`, `Nee, passt`] },
      { q: `Büro-Kaffee — wechseln?`, options: [`Ja, wechseln`, `Nee, passt`, `Richtige Maschine her`] },
      { q: `Teambuilding-Aktivität?`, options: [`Escape Room`, `Kochkurs`, `Sport`, `Cocktailbar`] },
      { q: `Wöchentlicher Online-Kaffee?`, options: [`Ja`, `Nee, zu viel Screen`, `Nur freitags`] },
      { q: `Uhrzeit fürs Wochenmeeting?`, options: [`9 Uhr`, `10 Uhr`, `11 Uhr`, `Nachmittags`] },
      { q: `Projekt-Tool?`, options: [`Notion`, `Asana`, `Linear`, `Bei Excel bleiben`] },
      { q: `Abschiedsparty wo?`, options: [`Büro`, `Bar nebenan`, `Restaurant`, `Keine Party`] },
    ],
    faq: [
      { q: `In Slack teilen?`, a: `Wirf den moomz-Link rein. Slack zeigt eine Vorschau. Kolleg:innen klicken und voten.` },
      { q: `Microsoft Teams?`, a: `Genauso — Link in Chat oder Channel posten. Vorschau erscheint, Vote mit einem Klick.` },
      { q: `Kann HR sehen, wer gevotet hat?`, a: `Nein. 100 % anonym, sogar für die Person, die die Umfrage erstellt hat. Genau das macht es zum echten Feedback-Tool.` },
      { q: `Welche Umfragen meiden bei der Arbeit?`, a: `Politik (wer wen wählt) und Religion. Bleib neutral oder positiv für psychologische Sicherheit.` },
    ],
    related: [`team-building-en-de`, `discord-poll-de`, `family-en-de`, `birthday-en-de`],
    updatedAt: today,
  },
  {
    slug: `team-building-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Teambuilding-Umfrage-Ideen — 25 Prompts für davor & währenddessen`,
    h1: `Teambuilding-Umfragen: das Team davor und währenddessen einbinden`,
    description: `25 Teambuilding-Umfragen: Vorbereitung, Eisbrecher, Entscheidungen, Feedback danach. Für Teams von 5 bis 200 Personen.`,
    intro: `Teambuilding, das funktioniert, ist Teambuilding, bei dem sich Leute eingebunden fühlten. moomz ist das perfekte Tool: davor erfragst du Vorlieben (Aktivität, Termine, Location). Währenddessen startest du Animations-Umfragen (Eisbrecher, Challenges, Wahlen). Danach sammelst du Feedback. Keine eigene App, nur ein Link.`,
    sections: [
      {
        h: `Phase 1: das Teambuilding vorbereiten`,
        body: `4 aufeinanderfolgende Umfragen (eine pro Woche): (1) Art der Aktivität, (2) Termin, (3) Location, (4) Budget. Jedes Mal mit der Mehrheit abschließen. Das Team fühlt sich entscheidend, das Engagement steigt vor dem Event.`,
      },
      {
        h: `Phase 2: Eisbrecher beim Event-Start`,
        body: `Zum Auftakt 3 lustige Quiz-Umfragen: "Wer redet in Meetings am meisten?", "Wer ist immer zu früh?", "Wer bringt die besten Snacks?". Anonym, lustig, bringt Dynamik rein. Optionen = die Namen aus dem Team (8-15 Personen).`,
      },
      {
        h: `Phase 3: Team-Umfragen, die Entscheidungen sichtbar machen`,
        body: `Während des Workshops eine anonyme Umfrage: "Welcher Wert steht für unser Team?" mit 4 Optionen (Zusammenarbeit, Innovation, Sorgfalt, Freundlichkeit). Das Ergebnis wird zum Ausgangspunkt der nächsten Diskussion.`,
      },
      {
        h: `Phase 4: Feedback nach dem Event`,
        body: `Zum Schluss: Umfrage "beste Aktivität?" und "wann machen wir das wieder?". 24 Std. später: "Teambuilding-Note von 5" — anonym, ehrlich. Echte kontinuierliche Verbesserung, kein Google-Formular-Lärm, den keiner öffnet.`,
      },
    ],
    polls: [
      { q: `Teambuilding-Aktivität?`, options: [`Escape Room`, `Kochkurs`, `Sport`, `Cocktailbar`, `Kreativ-Workshop`] },
      { q: `Termin?`, options: [`Fr 5.`, `Fr 12.`, `Sa 13.`, `Später`] },
      { q: `Location?`, options: [`Stadtzentrum`, `Umland`, `Wochenende auswärts`, `Keine Anreise`] },
      { q: `Wer redet in Meetings am meisten?`, options: [`Lea`, `Lucas`, `Theo`, `Anonym`] },
      { q: `Bester Team-Wert?`, options: [`Zusammenarbeit`, `Innovation`, `Sorgfalt`, `Freundlichkeit`] },
      { q: `Teambuilding-Note?`, options: [`5/5`, `4/5`, `3/5`, `Niedriger`] },
      { q: `Wann das nächste Mal?`, options: [`In 3 Monaten`, `In 6 Monaten`, `Jährlich`, `Nie`] },
      { q: `Bester Moment des Jahres?`, options: [`Offsite`, `Weihnachtsfeier`, `Sommerfest`, `Keiner`] },
      { q: `Team-Stimmung?`, options: [`Top`, `Gut`, `Mittel`, `Da geht was`] },
      { q: `Lieber:`, options: [`Sportliche Aktivität`, `Kreativ-Workshop`, `Gemeinsames Essen`, `Party`] },
    ],
    faq: [
      { q: `Maximale Personenzahl?`, a: `Unbegrenzt. 5 oder 200, alles geht.` },
      { q: `Wirklich anonymes Feedback?`, a: `Ja. Keine E-Mail, kein Account. Stimmen werden ohne Identifizierung gespeichert. Selbst die Orga sieht nur Prozentwerte.` },
      { q: `Werden Junioren nicht gegen die Meinung des Chefs voten?`, a: `Anonymität ist dein Schutz. Betone es: "Diese Umfrage ist komplett anonym, votet ehrlich." Und frag nicht im Plenum — lass die Leute in der Pause voten.` },
      { q: `Verteiltes Team?`, a: `Perfekt — teil den moomz-Link in Slack/Teams. Funktioniert über Zeitzonen hinweg, bei Bedarf async.` },
    ],
    related: [`coworkers-en-de`, `discord-poll-de`, `party-en-de`, `wedding-en-de`],
    updatedAt: today,
  },
  {
    slug: `this-or-that-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `↔️`,
    title: `Entweder-oder-Fragen — 100 Prompts für Storys & Dates`,
    h1: `Entweder oder: 100 Fragen für Insta, Snap und erste Dates`,
    description: `100 Entweder-oder-Fragen. Das Gen-Z-Umfrageformat — zwei Optionen, sofortige Entscheidung. Für Storys, Dates oder Kompatibilitäts-Quizze.`,
    intro: `Entweder oder — zwei Optionen, ein Tipp, fertig. Es ist das Umfrageformat mit der höchsten Abschlussrate in der Insta-Story (60-80 %). Perfekt für Eisbrecher, Kompatibilitäts-Quizze und virale Story-Ketten.`,
    sections: [
      {
        h: `Warum Entweder-oder gewinnt`,
        body: `Binäre Wahl = keine Entscheidungsmüdigkeit. Das Hirn entscheidet in 0,3 Sekunden und geht zur nächsten Frage. In der Insta-Story das Format mit der höchsten Antwortrate. Bei ersten Dates 2026 der Go-to-Eisbrecher.`,
      },
      {
        h: `So nutzt du es auf moomz`,
        body: `Erstell eine moomz-Umfrage mit genau 2 Optionen. Das ist der Entweder-oder-Modus. Für ein ganzes Quiz erstellst du 5-10 separate Umfragen und teilst jeden Link in einer Story-Kette.`,
      },
      {
        h: `Die Story-Ketten-Methode`,
        body: `Wirf 5 Entweder-oder-Umfragen in aufeinanderfolgende Storys. Follower swipen durch, voten jede einzeln und schicken dir ihre Ergebnisse per DM. Engagement-Rekord. Nutz Instas nativen Sticker für 2 Optionen oder moomz, wenn du später in der Kette 3+ Optionen willst.`,
      },
      {
        h: `Entweder-oder fürs erste Date`,
        body: `10 Fragen = perfekter Eisbrecher. Abwechselnd, kein Druck, zeigt den Geschmack. Tipp: Fang sanft an (Kaffee/Tee), steigere dich Richtung Konkretem (Hund/Katze, Strand/Berge), meide heikle Themen am ersten Date.`,
      },
    ],
    polls: [
      { q: `Kaffee oder Tee?`, options: [`Kaffee`, `Tee`] },
      { q: `Hund oder Katze?`, options: [`Hund`, `Katze`] },
      { q: `Strand oder Berge?`, options: [`Strand`, `Berge`] },
      { q: `Tag oder Nacht?`, options: [`Tag`, `Nacht`] },
      { q: `Pizza oder Burger?`, options: [`Pizza`, `Burger`] },
      { q: `Süß oder salzig?`, options: [`Süß`, `Salzig`] },
      { q: `Action oder Comedy?`, options: [`Action`, `Comedy`] },
      { q: `iPhone oder Android?`, options: [`iPhone`, `Android`] },
      { q: `Chillen oder Club?`, options: [`Chillen`, `Club`] },
      { q: `Sommer oder Winter?`, options: [`Sommer`, `Winter`] },
    ],
    faq: [
      { q: `Wie viele Fragen in einem Quiz?`, a: `10-20 maximal. Mehr, und das Publikum springt ab.` },
      { q: `Kann ich eine 3. Option hinzufügen?`, a: `Dann ist es kein Entweder-oder mehr. Bleib strikt bei 2. Nimm eine normale moomz-Umfrage für 3+.` },
      { q: `Schneller als Instas natives Format?`, a: `Instas natives Entweder-oder zeigt keine Prozentwerte. moomz zeigt Live-%. Wähl nach Bedarf.` },
      { q: `Ideen für Paare?`, a: `Alles, was den Geschmack zeigt: Kaffee/Tee, Serie/Film, Chillen/Ausgehen. Schau auf unsere Paar-Umfrage-Seite für 50 Ideen.` },
    ],
    related: [`would-you-rather-en-de`, `couple-questions-de`, `first-date-en-de`, `instagram-story-poll-de`],
    updatedAt: today,
  },
  {
    slug: `would-you-rather-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🤔`,
    title: `Was-würdest-du-eher-Fragen — 100 Prompts für Partys & Paare`,
    h1: `Was würdest du eher: 100 Fragen für Partys, Dates und Paare`,
    description: `100 Was-würdest-du-eher-Fragen: lustig, philosophisch, Dilemma, hypothetisch. Für Partyspiele, erste Dates und Paare.`,
    intro: `Was würdest du eher: Jede Option ist ein Mini-Albtraum oder ein Mini-Traum. Wähl. Das Format löst die längsten Debatten aller Partyspiele aus. 100 Fragen, sortiert nach Intensität. Plus die Methode, sie ohne peinliche Stille einzusetzen.`,
    sections: [
      {
        h: `Das Format`,
        body: `Du fragst: "Was würdest du eher — X oder Y?" Je radikaler die Optionen, desto härter die Debatte. Sweet Spot: beide Optionen gleich schlecht (oder gleich genial). Zeigt echte Vorlieben.`,
      },
      {
        h: `Stufe 1: lustige Was-würdest-du-eher-Fragen`,
        body: `Sicher für jede Gruppe: "fliegen oder unsichtbar sein?", "die Zukunft kennen oder die Vergangenheit ändern?". 10-Minuten-Debatte, perfekter Eisbrecher zu Beginn eines Abends oder Meetings.`,
      },
      {
        h: `Stufe 2: Dilemma-Fragen`,
        body: `Echte Dilemmata: "1 Jahr ohne Handy oder 1 Monat ohne deinen Hund?", "Vor- oder Nachnamen ändern?", "50 Jahre reich, dann arm, oder reich/arm im Wechsel?". Trifft die Werte. Am besten für enge Freundeskreise.`,
      },
      {
        h: `Stufe 3: Was-würdest-du-eher-Fragen fürs Paar`,
        body: `Mit dem Partner intim: "alles über meine Vergangenheit wissen oder nichts?", "in Berlin ohne Geld leben oder in NYC mit viel?". Tiefer Austausch, ohne die Frage direkt zu stellen.`,
      },
    ],
    polls: [
      { q: `Fliegen oder unsichtbar sein?`, options: [`Fliegen`, `Unsichtbar`] },
      { q: `Zukunft kennen oder Vergangenheit ändern?`, options: [`Zukunft`, `Vergangenheit`] },
      { q: `1 Jahr ohne Handy oder 1 Monat ohne Hund?`, options: [`Handy`, `Hund`] },
      { q: `Vor- oder Nachnamen ändern?`, options: [`Vorname`, `Nachname`] },
      { q: `In Berlin pleite oder in Detroit reich?`, options: [`Berlin pleite`, `Detroit reich`] },
      { q: `50 Jahre erst reich, dann arm — oder im Wechsel?`, options: [`Erst 50 Jahre reich`, `Im Wechsel`] },
      { q: `Alles über den Ex wissen oder nichts?`, options: [`Alles wissen`, `Nichts wissen`] },
      { q: `Gedanken lesen oder teleportieren?`, options: [`Gedanken lesen`, `Teleportieren`] },
      { q: `Jeden Tag Pizza oder nie wieder?`, options: [`Jeden Tag`, `Nie`] },
      { q: `1 Monat ohne Internet oder 1 Woche ohne Strom?`, options: [`Ohne Internet`, `Ohne Strom`] },
    ],
    faq: [
      { q: `Wie viele Was-würdest-du-eher-Fragen pro Party?`, a: `5-10. Mehr wird repetitiv. Verteil sie zwischen anderen Umfragetypen.` },
      { q: `Optionen nicht ausgewogen — schlecht?`, a: `Wenn eine Option klar besser ist, wählen sie 95 %, keine Debatte. Eine gute Frage hat zwei gleich attraktive oder gleich unattraktive Optionen.` },
      { q: `Familientaugliche Version?`, a: `Bleib bei Zauberkräften und trivialen Entscheidungen. Lass ethische Dilemmata weg — die können mit den Schwiegereltern krachen.` },
      { q: `Wie viele Optionen?`, a: `Strikt 2. So funktioniert das Format. Für 3+ nimm eine normale Umfrage.` },
    ],
    related: [`this-or-that-de`, `couple-questions-de`, `party-en-de`, `friends-en-de`],
    updatedAt: today,
  },
  {
    slug: `drama-polls-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🍿`,
    title: `Drama-Umfrage-Ideen — 30 Prompts für TikTok- und Insta-Debatten`,
    h1: `Drama-Umfragen: 30 Prompts als Debatten-Maschine für TikTok`,
    description: `30 Drama-Umfragen: Beziehungs-, Freundschafts-, Familiensituationen. Das Format, das auf TikTok und Insta am meisten Engagement bringt.`,
    intro: `Drama ist das Format mit dem höchsten Engagement auf TikTok und Instagram. Stell eine moralisch zwiespältige Situation vor, gib 3 Urteils-Optionen, lass das Publikum entscheiden. Das moderne Äquivalent zum Schöffendienst. Hier sind 30 Prompts.`,
    sections: [
      {
        h: `Das Drama-Format`,
        body: `Aufbau: (1) Situation in 2-3 Sätzen, (2) moralische Frage ("Wer ist im Unrecht?"), (3) 3 Urteils-Optionen. Je zwiespältiger, desto länger die Debatte. Lass klares Schwarz-Weiß weg — Unsicherheit treibt die Votes.`,
      },
      {
        h: `Beziehungs-Drama`,
        body: `Top-Engagement-Gebiet: Ghosting, der Ex kommt zurück, Verdacht auf Fremdgehen, der Partner geht weg ohne Bescheid. Vorsicht: generisch halten, keine echten Stellvertreter:innen für jemanden im Umfeld (Leak-Gefahr).`,
      },
      {
        h: `Freundschafts-Drama`,
        body: `"Freundin datet deinen Ex — Verrat?", "muss sie der Freundin sagen, dass der Freund fremdgeht?". Genauso fesselnd wie Paar-Drama, mit weniger persönlichem Urteil. Super für gemischte Gruppen.`,
      },
      {
        h: `Teenie- / Schul-Drama`,
        body: `Für Gen Z: Klassendrama, übergriffige Lehrkraft, Petzverhalten. Bei Handlungen bleiben, nicht bei Namen. moomz kann moralische Feinheiten vermitteln.`,
      },
    ],
    polls: [
      { q: `Er hat 2 Monate geghostet, will jetzt zurück. Antworten?`, options: [`Ja`, `Blockieren`, `Ihn warten lassen`] },
      { q: `Freundin datet deinen Ex. Verrat?`, options: [`Absolut`, `Ist ihr Leben`, `Kommt auf die Dauer an`] },
      { q: `Sie hat den Freund einer Freundin auf Tinder gesehen. Sagen?`, options: [`Ja, direkt`, `Nicht ihr Ding`, `Screenshot, abwarten`] },
      { q: `Den Ex zur Party einladen, ohne Bescheid zu geben?`, options: [`Unverzeihlich`, `Egal`, `Wenn der Ex okay damit ist`] },
      { q: `Trennung, verweigert Kontakt mit gemeinsamen Freunden?`, options: [`Legitim`, `Drama`, `Jede:r wie er:sie will`] },
      { q: `Lehrkraft übertreibt es mit Nachsitzen?`, options: [`Beschweren`, `Ihr Recht`, `Kommt drauf an`] },
      { q: `Freundin geht aus, ohne die Gruppe einzuladen?`, options: [`Verrat`, `Ihr Recht`, `Kommt drauf an, mit wem`] },
      { q: `Der besten Freundin den Freund ausspannen — geht das?`, options: [`Niemals`, `Wenn getrennt`, `Wenn's wahre Liebe ist`] },
      { q: `Freund:in lästert hinter deinem Rücken. Zur Rede stellen?`, options: [`Direkt`, `So tun als ob nichts`, `Kontakt abbrechen`] },
      { q: `Auf eine Hochzeit ohne Begleitung gehen?`, options: [`Cool`, `Stressig`, `Wenn ich 5+ Leute kenne`] },
    ],
    faq: [
      { q: `Ist Drama gesund?`, a: `Anonyme Drama-Umfrage = moralische Argumente bauen, gesund. Drama mit Namen + Beleidigungen = Mobbing, das die moomz-Moderation entfernt.` },
      { q: `Werden die Follower voten?`, a: `Ja — das Drama-Format erreicht 3x mehr Engagement als Standard-Umfragen. Auf TikTok/Insta absolute Spitzenklasse.` },
      { q: `Legal?`, a: `Solange keine echten Namen und keine Verleumdung, ja. Bleib hypothetisch.` },
      { q: `Maximale Debatte?`, a: `3 Optionen mit einer Mitte ("kommt drauf an"). Ja/Nein ist weniger gesprächig als Ja/Nein/Kommt-drauf-an.` },
    ],
    related: [`tiktok-poll-de`, `couple-questions-de`, `friends-en-de`, `would-you-rather-en-de`],
    updatedAt: today,
  },
  {
    slug: `icebreaker-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `🧊`,
    title: `Eisbrecher-Umfrage-Fragen — 40 Prompts für jede Gruppe`,
    h1: `Eisbrecher-Umfragen: 40 Fragen, um jedes Gespräch zu starten`,
    description: `40 Eisbrecher-Umfragen für Meetings, erste Dates, neue Gruppen, Klassenzimmer. Das Format, das peinliche Stille in 30 Sekunden killt.`,
    intro: `Peinliche Stille in einem Meeting, bei einem Date, in einer neuen Gruppe — wirf eine Eisbrecher-Umfrage rein. 4 lustige Optionen, 30 Sekunden, alle haben per Vote "geredet". Das Gespräch startet beim Ergebnis neu. Hier sind 40 Prompts.`,
    sections: [
      {
        h: `Wann Eisbrecher-Umfragen Eisbrecher-Fragen schlagen`,
        body: `Eine Frage verlangt Reden. Eine Umfrage verlangt einen Tipp. In einer 8er-Gruppe, in der 3 schüchtern sind, heißt der mündliche Eisbrecher: 5 reden, 3 nicht. Die Umfrage heißt: 8 Leute "reden". Inklusion 100 %.`,
      },
      {
        h: `Setup-Umfragen — Start von Meeting / Event`,
        body: `Beste Eisbrecher: "Wie geht's dir auf einer Skala von 5?", "Morgenenergie: Koffein oder Chill?", "Stimmung dieser Woche: 🔥 oder 😴?". Schnell, lustig, setzt den Ton.`,
      },
      {
        h: `Kennenlern-Umfragen`,
        body: `"Bester Film des Jahres?", "Traumstadt zum Leben?", "Go-to-Comfort-Food?". Zeigt den Geschmack ohne Intimität. Perfekt für neue Teams oder das erste Date.`,
      },
      {
        h: `Fun-Eisbrecher-Umfragen`,
        body: `"Wenn du ein Snack wärst, wärst du…?", "Superkraft: fliegen oder unsichtbar?", "Würdest du 24 Std. ohne WLAN überleben?". Absurde Fragen lösen die Anspannung schneller als ernste.`,
      },
    ],
    polls: [
      { q: `Wie geht's dir heute?`, options: [`🔥 super`, `😊 gut`, `😐 okay`, `😴 müde`] },
      { q: `Morgenenergie?`, options: [`Koffein`, `Workout`, `Chill`, `Keine`] },
      { q: `Bester Film des Jahres?`, options: [`Dune 3`, `Avatar 4`, `Anderer`, `Keinen gesehen`] },
      { q: `Traumstadt?`, options: [`Tokio`, `NYC`, `Paris`, `Bali`] },
      { q: `Comfort Food?`, options: [`Pizza`, `Burger`, `Pasta`, `Sushi`] },
      { q: `Superkraft?`, options: [`Fliegen`, `Unsichtbar`, `Teleportieren`, `Gedanken lesen`] },
      { q: `24 Std. ohne WLAN — überleben?`, options: [`Locker`, `Schwer`, `Heulen`, `Mach ich eh schon`] },
      { q: `Wenn du ein Snack wärst?`, options: [`Chips`, `Schokolade`, `Obst`, `Käse`] },
      { q: `Kaffee oder Tee?`, options: [`Kaffee`, `Tee`, `Matcha`, `Keins`] },
      { q: `Wochenend-Energie?`, options: [`Abenteuer`, `Chill`, `Sozial`, `Solo`] },
    ],
    faq: [
      { q: `Für neue Teams?`, a: `Ja — starte 3 Eisbrecher beim ersten All-Hands. Der Anonym-Modus lässt schüchterne Leute "reden".` },
      { q: `Erste Dates?`, a: `Misch 3-5 Eisbrecher zwischen die Gesprächsabschnitte. Mach kein Quiz daraus.` },
      { q: `Klassenzimmer?`, a: `Ja — zu Schuljahresbeginn "Lieblings-Snack", "Superkraft", "Traumziel" starten. Schafft in 5 Minuten ein Gruppengefühl.` },
      { q: `Online-Meetings?`, a: `Wirf den Link in den Chat. Leute voten während des langweiligen Intros. Die Energie schnellt hoch, sobald die Ergebnisse erscheinen.` },
    ],
    related: [`this-or-that-de`, `coworkers-en-de`, `first-date-en-de`, `team-building-en-de`],
    updatedAt: today,
  },
  {
    slug: `valentines-en-de`,
    locale: `de`,
    category: `ideas`,
    emoji: `💝`,
    title: `Valentinstags-Umfrage-Ideen — 25 Prompts für Paare oder Crushes`,
    h1: `Valentinstags-Umfragen: für Paare, Crushes und Singles`,
    description: `25 Valentinstags-Umfragen: Restaurant, Geschenk, anonymes Geständnis, Anti-Valentinstag für Singles. Für Paare, Crushes und Freundeskreise.`,
    intro: `Valentinstag = 200 WhatsApp-Nachrichten "Was machen wir?". Für Paare: Restaurant, Geschenk, Wahl des Abends. Für Singles: Anti-Valentinstags-Umfragen mit Freunden. Für Crushes: anonymes Geständnis per Umfrage. Hier sind 25 Ideen.`,
    sections: [
      {
        h: `Paar-Umfragen: den Valentinstag organisieren`,
        body: `Befrag deinen Partner: Restaurant, Abend zu Hause, Wochenende, Netflix. Demokratische Entscheidung, kein Druck, etwas vorschlagen zu müssen. Bonus: Bau "Lass mich machen, vertrau mir" als Option ein, um die Überraschung im Rahmen abzubilden.`,
      },
      {
        h: `Single-Umfragen: Anti-Valentinstag`,
        body: `Singles in einer Gruppe: "Was machen wir am 14. Februar?" mit Optionen — Filmabend zu viert, Dinner ohne Männer, Saufabend, jede:r für sich. moomz klärt's, keine Vorschlags-Debatte.`,
      },
      {
        h: `Anonyme Crush-Umfrage`,
        body: `Der Klassiker: Schick deinem Crush eine Umfrage "Was hältst du von mir?" mit 4 lustigen Optionen. Die erstellende Person bleibt auf dem geteilten Link anonym. Perfektes Spiel vor dem Geständnis.`,
      },
      {
        h: `Geschenk-Umfrage`,
        body: `Hängst du zwischen 3 Geschenken fest? Frag die Freunde per anonymer Umfrage. Antwort in 1 Std., kein Stress mit "wird's gefallen?".`,
      },
    ],
    polls: [
      { q: `Valentinstags-Plan?`, options: [`Schickes Restaurant`, `Abend zu Hause`, `Wochenendtrip`, `Netflix`] },
      { q: `Anti-Valentinstag mit Freunden?`, options: [`Filmabend zu viert`, `Dinner`, `Saufen`, `Jede:r für sich`] },
      { q: `Geschenk für ihn?`, options: [`Parfum`, `Klamotten`, `Erlebnis`, `Selbstgekochtes Essen`] },
      { q: `Geschenk für sie?`, options: [`Schmuck`, `Blumen`, `Erlebnis`, `Brief + Selbstgemachtes`] },
      { q: `Valentinstags-Restaurant?`, options: [`Gemütlicher Italiener`, `Brasserie`, `Sushi`, `Cocktailbar`] },
      { q: `Geständnis — Mut dazu?`, options: [`Ja`, `Nein`, `Über eine lustige Umfrage`] },
      { q: `Valentinstag nach 2 Monaten?`, options: [`Ja`, `Zu früh`, `Kleine Geste`] },
      { q: `Valentinstag nach 10 Jahren?`, options: [`Feiern`, `Wie immer`, `Kleines Geschenk`] },
      { q: `Rosen oder andere Blumen?`, options: [`Rote Rosen`, `Pfingstrosen`, `Tulpen`, `Keine Blumen`] },
      { q: `Überraschungsabend?`, options: [`Liebe ich`, `Stresst mich`, `Kommt drauf an`] },
    ],
    faq: [
      { q: `Anonyme Umfrage für einen Crush?`, a: `Ja — moomz identifiziert die erstellende Person nicht auf dem geteilten Link. Du kannst es als Spiel verpacken.` },
      { q: `Können Freunde voten, ohne mich zu identifizieren?`, a: `Ja — im Gruppenchat teilen, alles anonym. Kein "wer hat was gevotet".` },
      { q: `Umfrage, um sich geliebt zu fühlen?`, a: `Starte "Beschreib mich in 1 Wort" mit Freunden. 4 positive Optionen. Schau, was hochkommt, und fühl es.` },
      { q: `Anti-Valentinstag organisieren?`, a: `Befrag deine Single-Freunde. 4 Abend-Optionen. Mehrheit gewinnt. Weniger "Ich will nichts vorschlagen müssen".` },
    ],
    related: [`couple-questions-de`, `first-date-en-de`, `friends-en-de`, `party-en-de`],
    updatedAt: today,
  },
];
