import type { SeoPage } from "./types";

const today = "2026-05-22";

export const ideasPt2: SeoPage[] = [
  {
    slug: `family-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `👨‍👩‍👧`,
    title: `Ideias de Enquete pra Família — 30 Perguntas pra Decidir Sem Briga`,
    h1: `Enquetes em Família: Decidir Juntos Sem Treta`,
    description: `30 enquetes de família pra viagem, refeição, decoração, séries. E o método pra fazer sogra e adolescente votarem sem climão.`,
    intro: `Decisão em família é a mais difícil de todas. Todo mundo tem opinião forte, ninguém quer ceder e a discussão azeda na hora. O moomz neutraliza isso: cada um vota, a maioria ganha, fim de papo. De brinde, ensina a criançada que democracia não é igual a chilique.`,
    sections: [
      {
        h: `Viagem: corta o debate de 3 meses`,
        body: `O clássico: 4 destinos, cada um vota, segue a maioria. A enquete acaba com o "você sempre escolhe". Se a mãe vota A, o pai B e os dois adolescentes votam C e D — todo mundo teve voz, a maioria ganha.`,
      },
      {
        h: `Almoço de domingo`,
        body: `Quem quer o quê no almoço? Em vez dos 30 minutos de "o que vocês querem?", solta uma enquete com 4 opções às 11h. Ao meio-dia, a resposta tá decidida.`,
      },
      {
        h: `Decoração / reforma`,
        body: `Vai repintar? Sofá novo? Faz uma enquete com as opções. A maioria ganha. Se a sogra discordar, é o sistema — a casa é dos filhos, não dela.`,
      },
      {
        h: `Sessão pipoca em família`,
        body: `A batalha de domingo à noite. 4 opções: ação, comédia, drama, documentário. Todo mundo vota, todo mundo assiste. Acabou o "esse eu já vi".`,
      },
    ],
    polls: [
      { q: `Férias de verão?`, options: [`Praia no Nordeste`, `Serra`, `Cidade histórica`, `Camping`] },
      { q: `Almoço de domingo?`, options: [`Restaurante`, `Pedir delivery`, `Cozinhar`, `Cada um se vira`] },
      { q: `Filme hoje à noite?`, options: [`Comédia`, `Ação`, `Animação`, `Drama`] },
      { q: `Cor da sala?`, options: [`Branco gelo`, `Bege`, `Verde água`, `Verde sálvia`] },
      { q: `Chamar a vó no domingo?`, options: [`Sim`, `Não, tô com preguiça`, `Ok, mas rapidinho`] },
      { q: `Pet da família?`, options: [`Cachorro`, `Gato`, `Coelho`, `Nenhum`] },
      { q: `Esporte em família?`, options: [`Pedalar`, `Trilha`, `Futebol`, `Piscina`] },
      { q: `Jantar de aniversário do pai?`, options: [`Boteco`, `Italiano`, `Japonês`, `Em casa`] },
      { q: `Videogame pra criançada?`, options: [`Switch`, `PS5`, `Xbox`, `Nenhum`] },
      { q: `Passeio de fim de semana?`, options: [`Parque`, `Cinema`, `Boliche`, `Ficar em casa`] },
    ],
    faq: [
      { q: `Como evitar o veto da sogra?`, a: `Ela vota como todo mundo. Se for voto vencido toda vez, é porque as escolhas dela não batem com as do resto. É exatamente o ponto da enquete: neutralizar as vozes dominantes.` },
      { q: `Crianças muito novas pra ler?`, a: `Lê as opções pra elas. Elas votam no seu celular. Bem educativo.` },
      { q: `E se der empate?`, a: `Faz um segundo turno entre os dois primeiros. Ou chama uma terceira pessoa pra desempatar.` },
      { q: `E se alguém se recusar a votar?`, a: `Paciência. O resultado é decidido sem essa pessoa. Essa é a regra.` },
    ],
    related: [`birthday-en-pt`, `high-school-en-pt`, `would-you-rather-en-pt`, `this-or-that-pt`],
    updatedAt: today,
  },
  {
    slug: `teens-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🤳`,
    title: `Ideias de Enquete pra Adolescente — 30 Perguntas pra Escola`,
    h1: `Enquetes pra Adolescente: Perguntas Que Realmente Geram Debate`,
    description: `30 enquetes feitas pra adolescentes: treta, escola, paquera, desafios. Solta nos stories do Snap ou nos servidores do Discord.`,
    intro: `Adolescente vê enquete todo dia — stories do Snap, Instagram, grupos. A maioria é básica ("você gosta de mim?"). Aqui vão 30 ideias mais espertas que realmente geram debate sem cair na fofoca pura.`,
    sections: [
      {
        h: `Treta sem crueldade`,
        body: `Treta funciona, mas a enquete deve mirar comportamentos, não pessoas. "Ela deve contar pra amiga que o namorado tá pulando a cerca?" é bem melhor que "a Lea é burra de acreditar nele". Constrói argumento e evita bullying direto.`,
      },
      {
        h: `Enquetes da escola (com respeito)`,
        body: `"Melhor professor do ano" com nomes pode. "Pior professor" arrisca virar perseguição. Fica no positivo: melhor turma, professor mais engraçado, matéria mais útil. Funciona até pro jornal da escola.`,
      },
      {
        h: `Enquetes de paquera`,
        body: `Foco em comportamento: ele curtiu o story dela, respondeu rápido, o que falou pros amigos. Solta no story do Snap pra colher a opinião da escola toda. Mantém casos específicos no anônimo pra não escalar.`,
      },
      {
        h: `Enquetes de desafio`,
        body: `Desafios do TikTok / da vida real: "se inscrever no teatro?", "começar o estilo Y2K?", "marcar a Camille pra ela ver?". As enquetes viram gatilho de desafio em grupo.`,
      },
    ],
    polls: [
      { q: `Contar a verdade pra Lea sobre o namorado?`, options: [`Sim, na lata`, `Não é da nossa conta`, `Guardar o print`] },
      { q: `Melhor professor desse ano?`, options: [`Prof. Silva`, `Profa. Souza`, `Prof. Lima`, `Profa. Costa`] },
      { q: `Pior lugar da escola?`, options: [`Quadra no intervalo`, `Cantina`, `Corredor de manhã`, `Banheiros`] },
      { q: `Quanto tempo até você responder?`, options: [`Na hora`, `1h`, `Só no outro dia`, `Nunca`] },
      { q: `Ele gosta dela de verdade?`, options: [`Sim`, `Só pra aparecer`, `Não, é zoeira`, `A gente vê amanhã`] },
      { q: `Excursão da escola?`, options: [`Praia`, `Cidade histórica`, `Capital`, `Ficar em casa`] },
      { q: `Eletiva no ano que vem?`, options: [`Teatro`, `Esporte`, `Robótica`, `Nenhuma`] },
      { q: `Tendências de 2026?`, options: [`Y2K`, `Coquette`, `Streetwear`, `Vintage anos 90`] },
      { q: `Depois da aula, pra onde?`, options: [`Lanchonete`, `Padaria`, `Minha casa`, `Praça`] },
      { q: `Matar o próximo intervalo?`, options: [`Bora`, `Depende do tempo`, `Não, é meu descanso`] },
    ],
    faq: [
      { q: `É seguro pra adolescente?`, a: `Sim. Sem cadastro, sem dado pessoal. O voto continua anônimo. Pras enquetes de treta, mantém o foco em comportamentos, não em pessoas.` },
      { q: `Dá pra postar no story do Snap?`, a: `Sim — a figurinha de link do Snap aceita links do moomz. Os amigos tocam e votam.` },
      { q: `E o bullying?`, a: `A moderação do moomz remove qualquer enquete que cite uma pessoa + xingamento. A melhor proteção é a cultura: faz perguntas construtivas, não humilhantes.` },
      { q: `Meus pais vão ver?`, a: `Não. A enquete é anônima, os pais não são avisados. Mesmo assim, é esperto conversar com eles se você tem menos de 15.` },
    ],
    related: [`high-school-en-pt`, `snapchat-poll-pt`, `drama-polls-pt`, `instagram-story-poll-pt`],
    updatedAt: today,
  },
  {
    slug: `high-school-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🎒`,
    title: `Ideias de Enquete pro Ensino Médio — 30 Perguntas pra Turma e Grêmio`,
    h1: `Enquetes pro Ensino Médio: Pra Turma, Snap e Grêmio`,
    description: `30 enquetes pro ensino médio: escolha de excursão, tema da formatura, treta da turma, grêmio. Mais o modo anônimo pra assuntos delicados.`,
    intro: `Ensino médio = mais de 30 alunos por turma, vários grupos no Snap, um grêmio que decide as coisas e treta sem parar. O moomz vira a ferramenta democrática pras decisões da turma E o puxador de assunto pros debates de corredor.`,
    sections: [
      {
        h: `Enquetes de turma: decidir em escala`,
        body: `Excursão, filme de fim de ano, tema da viagem, camiseta da turma. Em vez de passar papelzinho no recreio, faz uma enquete no moomz e solta no grupo da turma no Snap. 24h depois você tem a resposta, e até o professor valida só de ler as porcentagens.`,
      },
      {
        h: `Enquetes do grêmio`,
        body: `O grêmio organiza os eventos. Cada um deles: tema da formatura, lugar da festa de integração, candidatos da eleição. Faz uma enquete pra escola toda. Democracia de verdade, bem melhor que riscar no quadro.`,
      },
      {
        h: `Enquetes de treta de corredor`,
        body: `As enquetes que rodam o corredor: casal mais fofo da turma, quem vai vencer na vida, quem vai ficar com quem na formatura. Use com parcimônia — mantém leve e divertido, nunca humilhante.`,
      },
      {
        h: `Enquetes de grupo de estudo`,
        body: `Chegando a época de prova, o moomz organiza tudo: qual capítulo a gente revisa junto, quem fica responsável por qual resumo. Organização coletiva sem ter que ler 30 mensagens espalhadas.`,
      },
    ],
    polls: [
      { q: `Excursão em abril?`, options: [`Museu`, `Sítio histórico`, `Mirante`, `Cinema`] },
      { q: `Tema da formatura?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Sem tema`] },
      { q: `Filme de fim de ano?`, options: [`A Origem`, `Forrest Gump`, `Whiplash`, `O professor escolhe`] },
      { q: `Camiseta da turma?`, options: [`Preta com frase`, `Branca minimalista`, `Colorida`, `Sem camiseta`] },
      { q: `Casal mais fofo?`, options: [`Lea & Lucas`, `Sarah & Téo`, `Cam & Inês`, `Nenhum`] },
      { q: `Pior horário de aula?`, options: [`Segunda 7h`, `Quarta 17h`, `Sexta 17h`, `Terça 16h-18h`] },
      { q: `Festa de integração?`, options: [`Na escola`, `Na casa de alguém`, `Bar pra maiores`, `Sem festa`] },
      { q: `Habilitação no 2º ano?`, options: [`Exatas`, `Biológicas`, `Humanas`, `Linguagens`] },
      { q: `Pior matéria?`, options: [`Matemática`, `História`, `Filosofia`, `Nenhuma, tá tudo bem`] },
      { q: `Foco do grupo de estudo?`, options: [`Matemática`, `Redação`, `História`, `Estudar sozinho`] },
    ],
    faq: [
      { q: `Dá pra usar no grêmio?`, a: `Sim — é a ferramenta certa pra votação da turma toda. Solta o link do moomz no grupo da escola.` },
      { q: `Enquetes de treta anônimas?`, a: `Sim — os votos são anônimos. Mas evita enquetes que mirem uma única pessoa pra humilhar. Moderação do moomz + bom senso.` },
      { q: `O professor pode validar o resultado?`, a: `Sim — mostra a tela com as porcentagens. Mais confiável que cédula de papel.` },
      { q: `Enquetes entre escolas?`, a: `Sim — compartilha o link nos grupos do Snap entre escolas. A enquete funciona enquanto as pessoas tiverem o link.` },
    ],
    related: [`teens-en-pt`, `college-en-pt`, `drama-polls-pt`, `discord-poll-pt`],
    updatedAt: today,
  },
  {
    slug: `college-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🎓`,
    title: `Ideias de Enquete pra Faculdade — 30 Perguntas pra Turma, Atlética e República`,
    h1: `Enquetes pra Faculdade: Pra Turma, Atlética e Treta de República`,
    description: `30 enquetes de faculdade: temas de festa, semana de calouros, grupos de estudo, decisões de república. Feito pra turmas de 200 a 1000 alunos.`,
    intro: `Faculdade = mais de 200 alunos por turma sem jeito nativo de votar coletivamente. O moomz vira a ferramenta democrática da turma. Eventos da atlética, semana de integração, opiniões políticas, grupos de estudo — tudo passa por um link compartilhado.`,
    sections: [
      {
        h: `Enquetes da atlética e do CA`,
        body: `Antes de qualquer evento, faz uma enquete: tema, local, valor da entrada, frase da camiseta. A atlética junta 200 a 500 votos em 48h e a decisão é democrática. Mesma coisa pra eleição de representante de turma.`,
      },
      {
        h: `Enquetes da semana de calouros`,
        body: `O maior evento do ano. O moomz resolve o começo: destino (4 opções), tema, faixa de orçamento, atividades. Até o "quem divide quarto com quem" — útil pra logística.`,
      },
      {
        h: `Enquetes políticas (no anônimo)`,
        body: `Durante greves / assembleias, enquetes anônimas revelam a opinião real. Os grupos mais barulhentos não dominam. O CA pode mostrar o resultado pra estruturar o debate.`,
      },
      {
        h: `Organização de grupo de estudo`,
        body: `Antes das provas finais, faz uma enquete: quem fica com qual resumo, onde rola a sessão de estudo. Dividir tarefas por votação é melhor que 50 mensagens espalhadas no Discord.`,
      },
    ],
    polls: [
      { q: `Destino da semana de calouros?`, options: [`Litoral`, `Serra`, `Interior`, `Outro estado`] },
      { q: `Tema da festa?`, options: [`Y2K`, `James Bond`, `Cosplay`, `Sem tema`] },
      { q: `Preço do evento da atlética?`, options: [`R$ 20`, `R$ 40`, `R$ 60`, `Grátis`] },
      { q: `Aderir à greve amanhã?`, options: [`Sim, com certeza`, `Não, a gente perde aula`, `Decide na assembleia`] },
      { q: `Representante de turma?`, options: [`Lea`, `Lucas`, `Téo`, `Camille`] },
      { q: `Festa quinta ou sexta?`, options: [`Quinta`, `Sexta`, `As duas`, `Nenhuma`] },
      { q: `Destino de intercâmbio ano que vem?`, options: [`Portugal`, `Espanha`, `Canadá`, `Alemanha`] },
      { q: `Pior matéria desse semestre?`, options: [`Estatística`, `Cálculo`, `Marketing`, `História`] },
      { q: `Sessão de estudo em grupo?`, options: [`Bora`, `Não, sozinho rende mais`, `Só pros exercícios`] },
      { q: `Bandejão hoje?`, options: [`Comível`, `Mais ou menos`, `Pulo essa`, `Já pulei`] },
    ],
    faq: [
      { q: `Quantos alunos no máximo?`, a: `Sem limite. 200, 500, 1000 — todos votam ao mesmo tempo.` },
      { q: `Compartilhar numa turma gigante?`, a: `Grupo do Discord / Telegram / WhatsApp. O link curto (5 caracteres) é fácil de passar até falando.` },
      { q: `Enquetes políticas anônimas?`, a: `O anonimato protege quem vota. O resultado revela a opinião real sem expor quem falou o quê.` },
      { q: `Vale como voto em assembleia?`, a: `Juridicamente, não. Mas é um ótimo termômetro antes do debate.` },
    ],
    related: [`high-school-en-pt`, `discord-poll-pt`, `teens-en-pt`, `friends-en-pt`],
    updatedAt: today,
  },
  {
    slug: `classroom-teacher-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🏫`,
    title: `Ideias de Enquete de Sala de Aula pra Professores — 25 Perguntas`,
    h1: `Enquetes de Sala de Aula pra Professores: Votar na Turma Sem Papel`,
    description: `25 enquetes de sala de aula pra professores: nome do mascote, passeio, festa de fim de ano. Ferramenta democrática pro fundamental.`,
    intro: `Professores do fundamental usam tradicionalmente papel ou mão levantada. O moomz deixa você fazer enquete com a turma em 30 segundos: mostra o QR code na lousa digital, os alunos votam nos tablets. Pedagogia de brinde: eles aprendem o que é uma votação de verdade.`,
    sections: [
      {
        h: `Por que fazer enquete na sala`,
        body: `Entre 7 e 12 anos, a criançada entende o que é votar, mas raramente pratica. Uma enquete semanal vira um mini-ritual: nome do mascote da turma, escolha do passeio, tema da festa de fim de ano. Resultado público, discutível, com possibilidade de revotar.`,
      },
      {
        h: `Como montar`,
        body: `Cria a enquete do moomz no celular ou no PC. Projeta a tela na lousa digital. Escreve a URL de 5 caracteres no quadro. Os alunos digitam nos tablets. Vota, resultado ao vivo aparecendo grandão.`,
      },
      {
        h: `Vai além de decisões coletivas`,
        body: `Use enquetes pra avaliação formativa: "qual frase está correta?" com 3 opções. Os votos anônimos revelam a compreensão real melhor que uma prova de papel.`,
      },
      {
        h: `Limites e cuidados`,
        body: `Nenhum dado pessoal é coletado — compatível com a LGPD pra esse uso. Confere a política da sua escola, mas o design anônimo do moomz costuma estar de acordo com as diretrizes da educação.`,
      },
    ],
    polls: [
      { q: `Nome do mascote da turma?`, options: [`Choco`, `Pixel`, `Tornado`, `Biscoito`] },
      { q: `Passeio em maio?`, options: [`Zoológico`, `Museu`, `Parque ecológico`, `Cinema`] },
      { q: `Livro do mês?`, options: [`O Pequeno Príncipe`, `Diário de um Banana`, `Reinações de Narizinho`, `Outro`] },
      { q: `Tema da festa de fim de ano?`, options: [`Circo`, `Espaço`, `Selva`, `História`] },
      { q: `Atividade da sexta à tarde?`, options: [`Desenho`, `Jogo em grupo`, `Leitura`, `Esporte`] },
      { q: `Animal favorito?`, options: [`Cachorro`, `Gato`, `Cavalo`, `Leão`] },
      { q: `Nome do futuro peixinho?`, options: [`Bolhinha`, `Nemo`, `Dourado`, `Batata`] },
      { q: `Cor da camiseta da turma?`, options: [`Vermelho`, `Azul`, `Verde`, `Amarelo`] },
      { q: `Esporte coletivo favorito?`, options: [`Futebol`, `Basquete`, `Handebol`, `Corrida`] },
      { q: `Sobremesa favorita da cantina?`, options: [`Iogurte`, `Maçã`, `Fruta`, `Bolo`] },
    ],
    faq: [
      { q: `É grátis pra professor?`, a: `Sim, totalmente grátis. Não precisa de plano premium pra uso em sala de aula.` },
      { q: `Os alunos precisam de conta?`, a: `Não. Sem cadastro, sem e-mail. Abre o link, vota, pronto.` },
      { q: `Os votos são anônimos?`, a: `Sim. Até você, como professor, só vê as porcentagens, não quem votou no quê. Tranquilizador pros alunos mais tímidos.` },
      { q: `Dá pra integrar com a lousa digital?`, a: `Projeta a página da enquete do moomz em tela cheia. Veja os resultados atualizando em tempo real conforme os alunos votam.` },
    ],
    related: [`teens-en-pt`, `family-en-pt`, `high-school-en-pt`, `college-en-pt`],
    updatedAt: today,
  },
  {
    slug: `coworkers-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `💼`,
    title: `Ideias de Enquete pra Colegas de Trabalho — 30 Perguntas pro Escritório`,
    h1: `Enquetes pra Colegas: Pro Slack, Teams e Home Office`,
    description: `30 enquetes pra colegas de trabalho: restaurante do almoço, local do offsite, café ou chá. Mais o método pra votar pelo Slack ou Teams.`,
    intro: `Decisão de escritório com 8 colegas e 8 opiniões leva uma hora e termina em "a gente vê amanhã". O moomz no canal do Slack: 10 minutos depois, você tem a resposta. De brinde: quebra o gelo, ainda mais no home office onde a pausa pro café nem existe.`,
    sections: [
      {
        h: `Enquetes de decisão`,
        body: `Almoço de sexta, offsite anual, decoração do escritório, máquina de café — moomz, 4 opções, no máximo 24h. Acabou o "eu proponho…" que se perde no barulho do Slack.`,
      },
      {
        h: `Enquetes de cultura`,
        body: `Conhecer os outros sem invadir a intimidade: melhor filme do ano, podcast favorito, time do coração, cidade dos sonhos. O melhor quebra-gelo pra times remotos.`,
      },
      {
        h: `Enquetes de feedback anônimo`,
        body: `O modo anônimo do moomz é ouro pra cultura do time: "reuniões longas demais?", "3 dias de home office tá funcionando?", "o café do escritório é bom o suficiente?". Você recebe a verdade em vez do feedback educado cara a cara.`,
      },
      {
        h: `Enquetes de team building`,
        body: `Antes de qualquer team building: atividade (escape, esporte, gastronomia, criativo), duração, orçamento. Todo mundo participa da decisão, não só o RH. Engajamento lá em cima antes mesmo do evento começar.`,
      },
    ],
    polls: [
      { q: `Almoço de sexta?`, options: [`Italiano`, `Japonês`, `Boteco`, `Hambúrguer`] },
      { q: `Local do offsite anual?`, options: [`Serra`, `Litoral`, `Outro estado`, `Aqui perto`] },
      { q: `3 dias de home office tá bom?`, options: [`Sim, perfeito`, `Quero mais`, `Quero menos`, `100% presencial`] },
      { q: `Reuniões longas demais?`, options: [`Sim, claramente`, `Mais ou menos`, `Não, tá ok`] },
      { q: `Café do escritório — trocar?`, options: [`Sim, trocar`, `Não, tá bom`, `Comprar uma máquina decente`] },
      { q: `Atividade de team building?`, options: [`Escape room`, `Aula de culinária`, `Esporte`, `Bar de coquetel`] },
      { q: `Café virtual toda semana?`, options: [`Sim`, `Não, já chega de tela`, `Só na sexta`] },
      { q: `Horário da reunião semanal?`, options: [`9h`, `10h`, `11h`, `À tarde`] },
      { q: `Ferramenta de projeto?`, options: [`Notion`, `Asana`, `Trello`, `Continuar no Excel`] },
      { q: `Festa de despedida onde?`, options: [`No escritório`, `Bar ao lado`, `Restaurante`, `Sem festa`] },
    ],
    faq: [
      { q: `Dá pra compartilhar no Slack?`, a: `Cola o link do moomz. O Slack mostra uma prévia bonita. Os colegas clicam e votam.` },
      { q: `E no Microsoft Teams?`, a: `Igual — cola o link na conversa ou no canal. A prévia aparece, voto em um clique.` },
      { q: `O RH consegue ver quem votou?`, a: `Não. 100% anônimo, até pra quem criou a enquete. É isso que faz dela uma ferramenta de feedback de verdade.` },
      { q: `Enquetes pra evitar no trabalho?`, a: `Política (quem vota em quem) e religião. Fica no neutro ou positivo pra preservar a segurança psicológica.` },
    ],
    related: [`team-building-en-pt`, `discord-poll-pt`, `family-en-pt`, `birthday-en-pt`],
    updatedAt: today,
  },
  {
    slug: `team-building-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🤝`,
    title: `Ideias de Enquete pra Team Building — 25 Perguntas pro Antes e Durante`,
    h1: `Enquetes pra Team Building: Engajar o Time Antes e Durante`,
    description: `25 enquetes de team building: preparação do evento, quebra-gelo, tomada de decisão, feedback pós-evento. Pra times de 5 a 200 pessoas.`,
    intro: `Team building que funciona é o team building onde as pessoas se sentiram incluídas. O moomz é a ferramenta perfeita: antes, você sonda as preferências (atividade, datas, local). Durante, faz enquetes de animação (quebra-gelo, desafios, eleições). Depois, colhe feedback. Sem app dedicado, só um link.`,
    sections: [
      {
        h: `Fase 1: preparar o team building`,
        body: `4 enquetes seguidas (uma por semana): (1) tipo de atividade, (2) data, (3) local, (4) orçamento. Fecha pela maioria de cada vez. O time se sente parte da decisão, o engajamento sobe antes do evento.`,
      },
      {
        h: `Fase 2: quebra-gelo na abertura do evento`,
        body: `Na abertura, faz 3 enquetes de quiz divertidas: "quem mais fala nas reuniões?", "quem chega sempre adiantado?", "quem traz o melhor lanche?". Anônimo, engraçado, dá o pontapé na dinâmica. As opções são os nomes do time (8 a 15 pessoas).`,
      },
      {
        h: `Fase 3: enquetes de time que revelam decisões`,
        body: `Durante o workshop, uma enquete anônima "qual valor representa o nosso time?" com 4 opções (colaboração, inovação, rigor, gentileza). O resultado vira o ponto de partida da próxima discussão.`,
      },
      {
        h: `Fase 4: feedback pós-evento`,
        body: `No fim: enquete "melhor atividade?" e "quando a gente repete?". 24h depois: "nota do team building de 0 a 5" — anônima, honesta. Melhoria contínua de verdade, não aquele Google Form que ninguém abre.`,
      },
    ],
    polls: [
      { q: `Atividade de team building?`, options: [`Escape room`, `Aula de culinária`, `Esporte`, `Bar de coquetel`, `Workshop criativo`] },
      { q: `Data?`, options: [`Sexta dia 5`, `Sexta dia 12`, `Sábado dia 13`, `Mais pra frente`] },
      { q: `Local?`, options: [`Centro da cidade`, `Bairro afastado`, `Fim de semana fora`, `Sem deslocamento`] },
      { q: `Quem mais fala nas reuniões?`, options: [`Lea`, `Lucas`, `Téo`, `Anônimo`] },
      { q: `Melhor valor do time?`, options: [`Colaboração`, `Inovação`, `Rigor`, `Gentileza`] },
      { q: `Nota do team building?`, options: [`5/5`, `4/5`, `3/5`, `Menos que isso`] },
      { q: `Quando repetir?`, options: [`Em 3 meses`, `Em 6 meses`, `Uma vez por ano`, `Nunca`] },
      { q: `Melhor momento do ano?`, options: [`O offsite`, `Festa de fim de ano`, `Festa junina da firma`, `Nenhum`] },
      { q: `Clima do time?`, options: [`Top`, `Bom`, `Mediano`, `Precisa melhorar`] },
      { q: `Prefere:`, options: [`Atividade física`, `Workshop criativo`, `Almoço em grupo`, `Festa`] },
    ],
    faq: [
      { q: `Máximo de pessoas?`, a: `Sem limite. 5 ou 200, tudo certo.` },
      { q: `Feedback de verdade anônimo?`, a: `Sim. Sem e-mail, sem conta. Os votos ficam salvos sem identificar quem votou. Até quem organiza só vê as porcentagens.` },
      { q: `Os juniores não vão votar contra a opinião do chefe?`, a: `O anonimato é a sua proteção. Reforça isso: "essa enquete é totalmente anônima, vota com sinceridade". E não pergunta na frente de todo mundo — deixa as pessoas votarem no intervalo.` },
      { q: `Time espalhado?`, a: `Perfeito — compartilha o link do moomz no Slack/Teams. Funciona entre fusos, de forma assíncrona se precisar.` },
    ],
    related: [`coworkers-en-pt`, `discord-poll-pt`, `party-en-pt`, `wedding-en-pt`],
    updatedAt: today,
  },
  {
    slug: `this-or-that-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `↔️`,
    title: `Perguntas Isso ou Aquilo — 100 Ideias pra Stories e Encontros`,
    h1: `Isso ou Aquilo: 100 Perguntas pro Insta, Snap e Primeiros Encontros`,
    description: `100 perguntas de isso ou aquilo. O formato de enquete da Geração Z — duas opções, decisão na hora. Use em stories, encontros ou quiz de compatibilidade.`,
    intro: `Isso ou aquilo — duas opções, um toque, pronto. É o formato de enquete com maior taxa de conclusão no story do Insta (60-80%). Perfeito pra quebrar o gelo, pra quiz de compatibilidade e pras correntes virais de story.`,
    sections: [
      {
        h: `Por que isso ou aquilo arrasa`,
        body: `Escolha binária = zero fadiga de decisão. O cérebro decide em 0,3 segundo e parte pra próxima. No story do Insta, é o formato com maior taxa de resposta. Nos primeiros encontros de 2026, é o quebra-gelo número um.`,
      },
      {
        h: `Como usar no moomz`,
        body: `Cria uma enquete no moomz com exatamente 2 opções. Esse é o modo isso ou aquilo. Pra um quiz completo, cria de 5 a 10 enquetes separadas e compartilha cada link numa corrente de stories.`,
      },
      {
        h: `Método da corrente de stories`,
        body: `Solta 5 enquetes de isso ou aquilo em stories seguidos. Os seguidores deslizam, votam em cada uma e te mandam o resultado no direct. Recorde de engajamento. Use a figurinha nativa do Insta pra 2 opções, ou o moomz quando quiser 3+ opções mais pra frente na corrente.`,
      },
      {
        h: `Isso ou aquilo no primeiro encontro`,
        body: `10 perguntas = quebra-gelo perfeito. Vão revezando, sem pressão, e o gosto de cada um aparece. Dica: começa leve (café/chá), vai ficando específico (cachorro/gato, praia/serra) e evita temas delicados no primeiro encontro.`,
      },
    ],
    polls: [
      { q: `Café ou chá?`, options: [`Café`, `Chá`] },
      { q: `Cachorro ou gato?`, options: [`Cachorro`, `Gato`] },
      { q: `Praia ou serra?`, options: [`Praia`, `Serra`] },
      { q: `Dia ou noite?`, options: [`Dia`, `Noite`] },
      { q: `Pizza ou hambúrguer?`, options: [`Pizza`, `Hambúrguer`] },
      { q: `Doce ou salgado?`, options: [`Doce`, `Salgado`] },
      { q: `Ação ou comédia?`, options: [`Ação`, `Comédia`] },
      { q: `iPhone ou Android?`, options: [`iPhone`, `Android`] },
      { q: `Sossego ou balada?`, options: [`Sossego`, `Balada`] },
      { q: `Verão ou inverno?`, options: [`Verão`, `Inverno`] },
    ],
    faq: [
      { q: `Quantas perguntas num quiz?`, a: `No máximo 10 a 20. Passou disso, a galera abandona.` },
      { q: `Posso colocar uma 3ª opção?`, a: `Aí já não é mais isso ou aquilo. Fica firme nas 2. Pra 3+, usa uma enquete normal do moomz.` },
      { q: `É mais rápido que o nativo do Insta?`, a: `O isso ou aquilo nativo do Insta não mostra porcentagens. O moomz mostra a % ao vivo. Escolhe conforme a necessidade.` },
      { q: `Ideias pra casal?`, a: `Todas as perguntas de perfil: café/chá, série/filme, sossego/balada. Veja nossa página de enquetes pra casal com 50 ideias.` },
    ],
    related: [`would-you-rather-en-pt`, `couple-questions-pt`, `first-date-en-pt`, `instagram-story-poll-pt`],
    updatedAt: today,
  },
  {
    slug: `would-you-rather-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🤔`,
    title: `Perguntas O Que Você Prefere — 100 Ideias pra Festas e Casais`,
    h1: `O Que Você Prefere: 100 Perguntas pra Festas, Encontros e Casais`,
    description: `100 perguntas de o que você prefere: engraçadas, filosóficas, dilemas, hipotéticas. Pra jogos de festa, primeiros encontros e casais.`,
    intro: `O que você prefere: cada opção é um mini-pesadelo ou um mini-sonho. Escolha. O formato gera os debates mais longos de qualquer jogo de festa. 100 perguntas, organizadas por intensidade. Mais o método pra usar sem aquele silêncio constrangedor.`,
    sections: [
      {
        h: `O formato`,
        body: `Pergunta: "o que você prefere, X ou Y?". Quanto mais radicais as opções, mais difícil o debate. O ponto ideal: as duas opções igualmente ruins (ou igualmente ótimas). Revela as preferências de verdade.`,
      },
      {
        h: `Nível 1: o que você prefere engraçado`,
        body: `Pra jogar em grupo sem risco: "voar ou ficar invisível?", "saber o futuro ou mudar o passado?". Debate de 10 minutos, quebra-gelo perfeito pro começo da noite ou de uma reunião.`,
      },
      {
        h: `Nível 2: o que você prefere dilema`,
        body: `Dilemas de verdade: "perder o celular por 1 ano ou o cachorro por 1 mês?", "trocar de nome ou de sobrenome?", "50 anos rico e depois pobre, ou rico e pobre alternando?". Mexe com valores. Melhor pra grupos de amigos próximos.`,
      },
      {
        h: `Nível 3: o que você prefere de casal`,
        body: `Com o parceiro, na intimidade: "saber tudo do meu passado ou nada?", "morar em São Paulo sem grana ou em Nova York com muita?". Troca profunda sem precisar fazer a pergunta diretamente.`,
      },
    ],
    polls: [
      { q: `Voar ou ficar invisível?`, options: [`Voar`, `Invisível`] },
      { q: `Saber o futuro ou mudar o passado?`, options: [`Futuro`, `Passado`] },
      { q: `Perder o celular 1 ano ou o cachorro 1 mês?`, options: [`Celular`, `Cachorro`] },
      { q: `Trocar de nome ou de sobrenome?`, options: [`Nome`, `Sobrenome`] },
      { q: `Paris duro ou interior rico?`, options: [`Paris duro`, `Interior rico`] },
      { q: `50 anos rico e depois pobre, ou alternando?`, options: [`50 anos rico primeiro`, `Alternando`] },
      { q: `Saber tudo do ex ou nada?`, options: [`Saber tudo`, `Não saber nada`] },
      { q: `Ler mentes ou se teletransportar?`, options: [`Ler mentes`, `Teletransporte`] },
      { q: `Pizza todo dia ou nunca mais?`, options: [`Todo dia`, `Nunca`] },
      { q: `Sem internet 1 mês ou sem luz 1 semana?`, options: [`Sem internet`, `Sem luz`] },
    ],
    faq: [
      { q: `Quantos "o que você prefere" numa festa?`, a: `De 5 a 10. Mais que isso fica repetitivo. Intercala com outros tipos de enquete.` },
      { q: `As opções não estão equilibradas — é ruim?`, a: `Se uma opção é claramente melhor, 95% escolhem ela, sem debate. Um bom "o que você prefere" tem duas opções igualmente atraentes ou igualmente ruins.` },
      { q: `Versão family-friendly?`, a: `Fica nos superpoderes mágicos e nas escolhas bobinhas. Pula os dilemas éticos — podem dar treta com a sogra.` },
      { q: `Quantas opções?`, a: `Estritamente 2. É o formato. Pra 3+, usa uma enquete normal.` },
    ],
    related: [`this-or-that-pt`, `couple-questions-pt`, `party-en-pt`, `friends-en-pt`],
    updatedAt: today,
  },
  {
    slug: `drama-polls-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🍿`,
    title: `Ideias de Enquete de Treta — 30 Perguntas pra Debates no TikTok e Insta`,
    h1: `Enquetes de Treta: 30 Ideias pra Bombar o Debate no TikTok`,
    description: `30 enquetes de treta: situações de relacionamento, amizade, família. O formato que mais gera engajamento no TikTok e no Insta.`,
    intro: `Treta é o formato de maior engajamento no TikTok e no Instagram. Apresenta uma situação moralmente ambígua, dá 3 opções de veredito e deixa o público decidir. O equivalente moderno de ser jurado. Aqui vão 30 ideias.`,
    sections: [
      {
        h: `O formato treta`,
        body: `Estrutura: (1) a situação em 2 ou 3 frases, (2) a pergunta moral ("quem está errado?"), (3) 3 opções de veredito. Quanto mais ambíguo, mais longo o debate. Pula o preto no branco óbvio — é a incerteza que puxa os votos.`,
      },
      {
        h: `Treta de relacionamento`,
        body: `O terreno de maior engajamento: dar um perdido, ex querendo voltar, suspeita de traição, parceiro saindo sem avisar. Ressalva: mantém genérico, sem ser uma cópia óbvia de alguém próximo (risco de vazar).`,
      },
      {
        h: `Treta de amizade`,
        body: `"Amiga ficando com o seu ex — é traição?", "ela tem que contar pra amiga que o namorado tá pulando a cerca?". Engaja tanto quanto treta de casal e com menos julgamento pessoal. Ótimo pra grupos mistos.`,
      },
      {
        h: `Treta de adolescente / escola`,
        body: `Pra Geração Z: treta de turma, professor passando do ponto, comportamento de dedo-duro. Fica nas ações, não nos nomes. O moomz pode até ensinar nuance moral.`,
      },
    ],
    polls: [
      { q: `Ele sumiu por 2 meses e agora quer voltar. Responde?`, options: [`Sim`, `Bloqueia`, `Faz ele esperar`] },
      { q: `Amiga ficando com o seu ex. É traição?`, options: [`Com certeza`, `É a vida dela`, `Depende de quanto tempo faz`] },
      { q: `Ela viu o namorado da amiga no Tinder. Conta?`, options: [`Sim, na lata`, `Não é da conta dela`, `Guarda o print e espera`] },
      { q: `Convidar o ex pra uma festa sem avisar?`, options: [`Imperdoável`, `Tanto faz`, `Se o ex tiver de boa`] },
      { q: `Terminou e se recusa a ter contato com os amigos em comum?`, options: [`Tem todo o direito`, `É drama`, `Cada um na sua`] },
      { q: `Professor pegando pesado demais na punição?`, options: [`Reclama`, `É o direito dele`, `Depende`] },
      { q: `Amigo saindo sem chamar o grupo?`, options: [`Traição`, `É o direito dele`, `Depende de quem`] },
      { q: `Roubar o namorado da melhor amiga, dá?`, options: [`Nunca`, `Se já terminaram`, `Se for amor de verdade`] },
      { q: `Amigo falando pelas suas costas. Confronta?`, options: [`Na lata`, `Finge que não sabe`, `Corta o contato`] },
      { q: `Ir a um casamento sem acompanhante?`, options: [`De boa`, `Estressante`, `Se eu conhecer 5+ pessoas`] },
    ],
    faq: [
      { q: `Treta é saudável?`, a: `Enquete de treta anônima = construir argumentos morais, é saudável. Treta com nomes + xingamento = perseguição, e a moderação do moomz remove.` },
      { q: `Os seguidores vão votar?`, a: `Sim — o formato treta bate 3x mais engajamento que enquetes normais. No TikTok/Insta, é top de linha.` },
      { q: `É legal?`, a: `Enquanto não tiver nomes reais nem difamação, sim. Fica no hipotético.` },
      { q: `Debate máximo?`, a: `3 opções com um meio-termo ("depende"). Sim/não rende menos conversa que sim/não/depende.` },
    ],
    related: [`tiktok-poll-pt`, `couple-questions-pt`, `friends-en-pt`, `would-you-rather-en-pt`],
    updatedAt: today,
  },
  {
    slug: `icebreaker-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `🧊`,
    title: `Perguntas de Enquete pra Quebrar o Gelo — 40 Ideias pra Qualquer Grupo`,
    h1: `Enquetes Quebra-Gelo: 40 Perguntas pra Começar Qualquer Conversa`,
    description: `40 enquetes quebra-gelo pra reuniões, primeiros encontros, grupos novos, salas de aula. O formato que vence o silêncio constrangedor em 30 segundos.`,
    intro: `Silêncio constrangedor numa reunião, num encontro, num grupo novo — solta uma enquete quebra-gelo. 4 opções divertidas, 30 segundos, e todo mundo já "falou" pelo voto. A conversa recomeça em cima do resultado. Aqui vão 40 ideias.`,
    sections: [
      {
        h: `Quando a enquete quebra-gelo vence a pergunta quebra-gelo`,
        body: `Uma pergunta exige falar. Uma enquete exige um toque. Num grupo de 8 onde 3 são tímidos, o quebra-gelo verbal faz 5 pessoas falarem e 3 ficarem caladas. A enquete faz as 8 "falarem". Inclusão de 100%.`,
      },
      {
        h: `Enquetes de abertura — começo de reunião / evento`,
        body: `Os melhores quebra-gelos: "como você tá, numa escala de 0 a 5?", "energia da manhã: cafeína ou sossego?", "humor da semana: 🔥 ou 😴?". Rápido, divertido, dá o tom.`,
      },
      {
        h: `Enquetes de se conhecer`,
        body: `"Melhor filme do ano?", "cidade dos sonhos pra morar?", "comfort food que nunca falha?". Revela gostos sem invadir a intimidade. Perfeito pra times novos ou primeiro encontro.`,
      },
      {
        h: `Enquetes quebra-gelo divertidas`,
        body: `"Se você fosse um lanche, seria…?", "superpoder: voar ou ficar invisível?", "você sobreviveria 24h sem Wi-Fi?". Perguntas absurdas quebram a tensão mais rápido que as sérias.`,
      },
    ],
    polls: [
      { q: `Como você tá hoje?`, options: [`🔥 ótimo`, `😊 bem`, `😐 mais ou menos`, `😴 cansado`] },
      { q: `Energia da manhã?`, options: [`Cafeína`, `Treino`, `Sossego`, `Nenhuma`] },
      { q: `Melhor filme do ano?`, options: [`Duna 3`, `Avatar 4`, `Outro`, `Não vi nenhum`] },
      { q: `Cidade dos sonhos?`, options: [`Tóquio`, `Nova York`, `Lisboa`, `Bali`] },
      { q: `Comfort food?`, options: [`Pizza`, `Hambúrguer`, `Macarrão`, `Sushi`] },
      { q: `Superpoder?`, options: [`Voar`, `Invisível`, `Teletransporte`, `Ler mentes`] },
      { q: `24h sem Wi-Fi — sobrevive?`, options: [`Fácil`, `Difícil`, `Choro`, `Já faço isso`] },
      { q: `Se você fosse um lanche?`, options: [`Salgadinho`, `Chocolate`, `Fruta`, `Queijo`] },
      { q: `Café ou chá?`, options: [`Café`, `Chá`, `Matchá`, `Nenhum`] },
      { q: `Energia de fim de semana?`, options: [`Aventura`, `Sossego`, `Social`, `Sozinho`] },
    ],
    faq: [
      { q: `Pra times novos?`, a: `Sim — faz 3 quebra-gelos na primeira reunião geral. O modo anônimo deixa os tímidos "falarem".` },
      { q: `Primeiros encontros?`, a: `Mistura de 3 a 5 quebra-gelos entre os momentos de conversa. Não transforma num quiz.` },
      { q: `Salas de aula?`, a: `Sim — no começo do ano, faz "lanche favorito", "superpoder", "destino dos sonhos". Cria vínculo de grupo em 5 minutos.` },
      { q: `Reuniões online?`, a: `Solta o link no chat. As pessoas votam durante a introdução chata. A energia dispara quando o resultado aparece.` },
    ],
    related: [`this-or-that-pt`, `coworkers-en-pt`, `first-date-en-pt`, `team-building-en-pt`],
    updatedAt: today,
  },
  {
    slug: `valentines-en-pt`,
    locale: `pt`,
    category: `ideas`,
    emoji: `💝`,
    title: `Ideias de Enquete pro Dia dos Namorados — 25 Perguntas pra Casais ou Crushes`,
    h1: `Enquetes de Dia dos Namorados: Pra Casais, Crushes e Solteiros`,
    description: `25 enquetes de Dia dos Namorados: restaurante, presente, declaração anônima, anti-Dia dos Namorados pros solteiros. Pra casais, crushes e grupos de amigos.`,
    intro: `Dia dos Namorados = 200 mensagens no WhatsApp "o que a gente vai fazer?". Pra casais: restaurante, presente, escolha do programa. Pra solteiros: enquetes anti-Dia dos Namorados com os amigos. Pra crushes: declaração anônima por enquete. Aqui vão 25 ideias.`,
    sections: [
      {
        h: `Enquetes de casal: organizar o Dia dos Namorados`,
        body: `Faz uma enquete com o parceiro: restaurante, noite em casa, fim de semana, Netflix. Decisão democrática, sem a pressão de ter que propor algo. De brinde: inclui um "deixa comigo, confia" pra encaixar a surpresa dentro das opções.`,
      },
      {
        h: `Enquetes pra solteiros: anti-Dia dos Namorados`,
        body: `Solteiros num grupo: "o que a gente faz no dia 12 de junho?" com opções — noite de filme entre 4, jantar sem homem, rolê de bebida, cada um na sua. O moomz resolve, sem aquele debate de quem propõe.`,
      },
      {
        h: `Enquete anônima pro crush`,
        body: `O clássico: manda pro seu crush uma enquete "o que você acha de mim?" com 4 opções engraçadas. Quem criou continua anônimo no link compartilhado. Jogo perfeito antes da declaração.`,
      },
      {
        h: `Enquete de presente`,
        body: `Travado entre 3 presentes? Pergunta pros amigos do crush por enquete anônima. Resposta em 1h, sem aquele estresse de "será que vai gostar?".`,
      },
    ],
    polls: [
      { q: `Programa de Dia dos Namorados?`, options: [`Restaurante chique`, `Noite em casa`, `Fim de semana fora`, `Netflix`] },
      { q: `Anti-Dia dos Namorados com os amigos?`, options: [`Noite de filme entre 4`, `Jantar`, `Rolê de bebida`, `Cada um na sua`] },
      { q: `Presente pra ele?`, options: [`Perfume`, `Roupa`, `Uma experiência`, `Jantar feito em casa`] },
      { q: `Presente pra ela?`, options: [`Joia`, `Flores`, `Uma experiência`, `Carta + algo artesanal`] },
      { q: `Restaurante de Dia dos Namorados?`, options: [`Italiano intimista`, `Boteco`, `Sushi`, `Bar de coquetel`] },
      { q: `Declaração — encara?`, options: [`Encaro`, `Não`, `Por uma enquete engraçada`] },
      { q: `Dia dos Namorados com 2 meses de namoro?`, options: [`Sim`, `Cedo demais`, `Um gesto pequeno`] },
      { q: `Dia dos Namorados com 10 anos de namoro?`, options: [`Comemora`, `Como sempre`, `Um presentinho`] },
      { q: `Rosas ou outras flores?`, options: [`Rosas vermelhas`, `Peônias`, `Tulipas`, `Sem flores`] },
      { q: `Noite surpresa?`, options: [`Amo`, `Me estressa`, `Depende`] },
    ],
    faq: [
      { q: `Enquete anônima pro crush?`, a: `Sim — o moomz não identifica quem criou no link compartilhado. Você pode apresentar como uma brincadeira.` },
      { q: `Os amigos podem votar sem me identificar?`, a: `Sim — compartilha no grupo, tudo anônimo. Sem "quem votou no quê".` },
      { q: `Enquete pra se sentir amado?`, a: `Faz um "me descreve em 1 palavra" com os amigos. 4 opções positivas. Vê o que aparece e curte o momento.` },
      { q: `Organizar o anti-Dia dos Namorados?`, a: `Faz uma enquete com seus amigos solteiros. 4 opções de programa. A maioria ganha. Menos "não quero ser eu a propor".` },
    ],
    related: [`couple-questions-pt`, `first-date-en-pt`, `friends-en-pt`, `party-en-pt`],
    updatedAt: today,
  },
];
