import type { SeoPage } from "../types";

export const r35: SeoPage[] = [{
  slug: "sister-married-my-ex",
  locale: "en",
  category: "read",
  emoji: "💒",
  title: "My Sister Married My Ex — I Found Out at Their Baby Shower",
  h1: "My sister married my ex behind my back. The baby's name destroyed me.",
  description: "She invited me to a baby shower. She forgot to mention the dad was my ex — and the name in the pink balloons was the one I gave away in pillow talk.",
  intro: "I thought it was a normal Sunday. I walked in with a wrapped onesie and a smile. Six hours later I was sitting on a curb at 1 a.m. holding a half-eaten cupcake and the saddest secret of my life.",
  sections: [
    { h: "The invite that didn't say his name", body: "My sister Lia sent a pastel Canva invite to a 'tiny gender reveal slash baby shower' at her new place in the suburbs. The dad was listed as 'M.' Just M. I assumed she was being cute, hiding the surname until reveal day. I didn't ask. I'd been low-contact with the family for about a year — long enough to miss things, short enough to think I still knew everyone. I bought a little mustard-yellow onesie that said HELLO WORLD. I curled my hair. I practiced being happy for her in the car." },
    { h: "The car in the driveway", body: "I almost didn't go in. There was a black Audi parked sideways across the grass and my body knew it before my brain did. Same scratch on the bumper from the time we hit a curb in Lisbon. Same cracked phone holder on the dash. I told myself a million people drive black Audis. I told myself I was being dramatic. I rang the bell holding the gift bag with two hands like it was protecting me. My niece opened the door. She said: 'Auntie! Uncle M is in the kitchen.' Uncle." },
    { h: "He was wearing the apron I bought him", body: "Marc. My Marc. Wearing the apron that said WORLD'S OKAYEST CHEF that I gave him on his 28th birthday. Stirring a punch bowl. He looked up and his face did something I've never seen a face do — it tried to be five emotions at once and landed on none of them. My sister rushed in from the garden, hands full of pink balloons, and stopped dead. Three seconds of silence. Then she smiled the biggest smile of her life and said 'Surprise! I wanted to tell you in person.' Like that fixed it. Like ANY of that fixed it." },
    { h: "The timeline they fed me on the patio", body: "She pulled me out back. Marc 'gave us space.' She said they bumped into each other at a wedding 'months after' we broke up. She said it was slow. She said she fought it. She said she didn't tell me because she knew I'd 'make it weird,' and now look, she's pregnant and happy and don't I want her to be happy? I did the math in my head. Marc and I broke up in October. Their engagement photo was on her old story from January. She got pregnant in February. Slow, sure. The kind of slow you do at a full sprint." },
    { h: "The pink balloons spelled a name", body: "Then her best friend popped a confetti cannon and the banner unrolled across the patio fence in cursive: WELCOME BABY JUNE. June. JUNE. The name I whispered to Marc in bed in 2022 when we were stupid in love and I told him my grandma's name and my secret pact with myself: if I ever had a daughter, I'd call her June. He'd laughed and said 'June it is, then.' I had never told my sister that name. Not once. Not in any group chat, not at any dinner. Only him. I looked at him across the garden and he wouldn't meet my eyes. He'd given her the name. Or worse — she'd asked." },
    { h: "I didn't scream. I should have", body: "I smiled. I hugged my sister. I took a slice of vanilla cake. I told the aunts how beautiful the decorations were. I posed in a photo where my mother put her arm around me and squeezed and whispered 'be the bigger person, please, for once.' For once. I drank two glasses of pink punch. I waited until everyone was on the lawn doing the diaper raffle. Then I walked out the front door, sat on the curb across the street, and ate a cupcake while my hands shook so hard I dropped the wrapper twice. Marc came out after twenty minutes. He stood three meters away like I was on fire." },
    { h: "What he said on the curb", body: "He said 'I didn't pick the name. She did. She said it just came to her.' He said it like that helped. Like the name landing in her head by magic was better than him saying it out loud. He said he was sorry. He said he didn't know how it happened. He said his therapist told him guilt is just self-pity in a tuxedo. I told him to go back inside. He did. Quickly. My sister never came out. My mom texted me at 11 p.m.: 'You embarrassed her in front of his family. Call tomorrow.' I haven't called. It's been nine days." },
    { h: "What I'm doing now (and not doing)", body: "I haven't blocked them. I keep almost typing the message. I drafted one that just said the name — 'June.' — and deleted it. I drafted one that said everything. Deleted that too. My therapist asked me what outcome I want and I genuinely don't know. I don't want them broken up. I don't want to be at the hospital. I don't want my mom calling me selfish in the family group chat for the fifth Christmas in a row. I want a sister back, and I'm starting to understand I never really had one. The baby comes in June. Of course she does." },
  ],
  polls: [
    { q: "Sister marries your ex without telling you. Verdict?", options: ["Unforgivable, cut contact", "Talk it out, family is family", "Depends how long after the breakup", "I'd go scorched earth"] },
    { q: "Did she steal the name 'June' on purpose?", options: ["100% he told her", "She googled your old captions", "It's a coincidence, calm down", "Doesn't matter, still cursed"] },
    { q: "Would you go to the hospital when the baby is born?", options: ["Yes, the kid is innocent", "No, never", "Only if sister apologizes first", "Send a card, skip the visit"] },
    { q: "Mom said 'be the bigger person.' Mom is...", options: ["Wrong and enabling", "Trying to keep peace", "The real villain here", "Tired, give her grace"] },
    { q: "What do you do at the next family Christmas?", options: ["Don't go", "Go and be civil", "Go and bring a date hotter than Marc", "Host your own dinner without them"] },
  ],
  faq: [
    { q: "Is this story real?", a: "It's posted anonymously on moomz so people can vote without judging the author by name. Whether every detail is exact or smoothed for storytelling, the situation — sibling marries ex, name overlap, mom siding with the favorite — happens way more than you'd think. The comments are full of 'this is literally my cousin.'" },
    { q: "How long after the breakup did they start dating?", a: "By the author's math: roughly three months. Marc and OP broke up in October. The engagement photo surfaced in January. Pregnant by February. 'Slow' is doing a lot of work in that timeline." },
    { q: "Did the ex really give her the baby name?", a: "He swears he didn't. He says it 'just came to her.' The author had only ever told one person on earth that she wanted to name her future daughter June — and that person was stirring punch in her sister's kitchen wearing an apron she bought him." },
    { q: "What did the mom do?", a: "Texted the author at 11 p.m. accusing her of 'embarrassing' the sister in front of the in-laws — for leaving the party quietly without a scene. No apology. No check-in. Just damage control for the golden child. Classic." },
    { q: "Are they still talking?", a: "Nine days of silence at the time of writing. The sister hasn't reached out. The ex hasn't either. The author keeps drafting messages and deleting them. The family group chat is pretending nothing happened, which is its own kind of answer." },
    { q: "What would you actually do in her place?", a: "That's why the polls are there. Some people say cut contact forever, the betrayal is too layered. Others say the baby is innocent and you'll regret missing her childhood. There's no clean answer — vote, see what the internet thinks, and brace for the comments to be unhinged."  },
  ],
  related: [],
  updatedAt: "2026-05-19",
}];
