import type { Locale } from "./i18n";

// Curated Ask.fm-style prompts. Spicy, dare-driven, gossip-bait —
// the kind of question people actually answer because they're juicy.
// 30+ per locale. Used as inspiration chips in the ask composer.
export const ASK_PROMPTS: Record<Locale, string[]> = {
  fr: [
    "Sur qui t'as une vibe en ce moment ?",
    "Dernier crush en date — initiales ?",
    "Le red flag que tu ignores quand même 🚩",
    "Avoue : la dernière fois que t'as menti ?",
    "Le truc le plus embarrassant que t'as fait bourré.e ?",
    "Si tu pouvais voir 1 DM de qui ?",
    "T'as déjà stalk ton ex ce mois-ci ?",
    "Qui tu kiff secrètement dans nos amis ?",
    "Ton plus gros ick chez quelqu'un ?",
    "Ta plus grosse insécurité ?",
    "T'as déjà ghosté quelqu'un ? Pourquoi ?",
    "Décris ta dernière galère en 3 emojis 🫠",
    "Le truc que tu cherches sur Google en secret ?",
    "L'amie/le pote que tu kick si tu pouvais 👀",
    "Ton fantasme inavouable (ouais celui-là) ?",
    "T'as déjà chialé devant une série ? Laquelle ?",
    "Le pire date que t'as eu ?",
    "Drogue préférée : café, scroll ou drama ?",
    "Tu prendrais 10K€ ou 1 an de célébrité ?",
    "Y'a un truc que personne ici ne sait sur toi ?",
    "Si demain c'était la fin du monde, tu textes qui en premier ?",
    "T'as déjà été in love sans le dire ?",
    "L'âge où t'as eu ton 1er chagrin ?",
    "Le compte que tu stalk H24 mais que tu follow pas ?",
    "Mensonge que tu racontes à tes parents ?",
    "Avec qui tu partirais en week-end là, maintenant ?",
    "Truffé.e ou clean : ton historique Insta ?",
    "Tu replongerais avec ton ex pour 1 jour ?",
    "Le pire texto que t'as envoyé ?",
    "Si t'étais invisible 1h, tu fais quoi ?",
    "Ton dernier rêve bizarre ?",
    "Le défaut chez toi que t'assumes pas ?",
  ],
  en: [
    "Who are you crushing on rn?",
    "Last crush — initials only 👀",
    "The red flag you still ignore 🚩",
    "Confess: the last lie you told?",
    "Most embarrassing drunk story?",
    "If you could read 1 DM, whose?",
    "Stalked your ex this month? Be honest.",
    "Who in our friend group do you secretly vibe with?",
    "Biggest ick you have on someone?",
    "Your deepest insecurity?",
    "Ever ghosted someone? Why?",
    "Describe last week in 3 emojis 🫠",
    "What do you google in private?",
    "The friend you'd kick if you could 👀",
    "Most shameful fantasy — spill it.",
    "Last show that made you cry?",
    "Worst date you've been on?",
    "Coffee, scrolling, or drama — which addiction?",
    "$10K or 1 year of fame?",
    "Something no one here knows about you?",
    "End of the world tomorrow — who do you text first?",
    "Ever loved someone in silence?",
    "Age of your first heartbreak?",
    "The account you stalk daily but don't follow?",
    "Lie you still tell your parents?",
    "Who would you ghost a weekend with rn?",
    "Insta search history: messy or clean?",
    "Take back an ex for 1 day?",
    "Worst text you've sent?",
    "Invisible for 1 hour — what are you doing?",
    "Last weird dream you remember?",
    "The flaw about yourself you won't admit?",
  ],
  es: [
    "¿De quién te has encaprichado ahora?",
    "Último crush — iniciales 👀",
    "La red flag que igual ignoras 🚩",
    "Confiesa: la última mentira que dijiste",
    "La vergüenza más grande borracho/a",
    "Si pudieras leer 1 DM, ¿de quién?",
    "¿Has stalkeado a tu ex este mes?",
    "¿A quién del grupo le tienes vibes?",
    "¿El mayor ick que le viste a alguien?",
    "Tu mayor inseguridad",
    "¿Has ghosteado a alguien? ¿Por qué?",
    "Describe tu semana en 3 emojis 🫠",
    "¿Qué buscas en Google en secreto?",
    "El/la amigo/a que sacarías del grupo 👀",
    "Una fantasía que no contarías ni borracho/a",
    "Última serie que te hizo llorar",
    "La peor cita de tu vida",
    "¿Café, scroll o drama? Tu adicción",
    "¿10K€ o 1 año de fama?",
    "Algo que nadie aquí sabe de ti",
    "Fin del mundo mañana — ¿a quién textras primero?",
    "¿Has amado en silencio?",
    "¿Edad de tu primer corazón roto?",
    "La cuenta que stalkeas pero no sigues",
    "La mentira que aún cuentas a tus padres",
    "¿Con quién te irías de finde ya?",
    "Tu historial de IG: ¿caos o limpio?",
    "¿Volverías con tu ex 1 día?",
    "El peor mensaje que has mandado",
    "Invisible 1 hora — ¿qué haces?",
    "El último sueño raro que tuviste",
    "El defecto tuyo que no asumes",
  ],
  it: [
    "Per chi hai una cotta ora?",
    "Ultimo crush — iniziali 👀",
    "La red flag che ignori comunque 🚩",
    "Confessa: l'ultima bugia che hai detto",
    "La cosa più imbarazzante da ubriaco/a",
    "Se potessi leggere 1 DM, di chi?",
    "Hai stalkerato il tuo ex questo mese?",
    "Chi del gruppo ti dà vibes?",
    "L'ick più grosso che hai notato su qualcuno?",
    "La tua insicurezza più profonda",
    "Hai mai ghostato qualcuno? Perché?",
    "Descrivi la settimana in 3 emoji 🫠",
    "Cosa cerchi su Google in segreto?",
    "L'amico/a che cacceresti dal gruppo 👀",
    "Una fantasia che non racconterai mai",
    "Ultima serie che ti ha fatto piangere?",
    "Il peggior appuntamento di sempre?",
    "Caffè, scroll o drama: la tua droga?",
    "10K€ o 1 anno di fama?",
    "Qualcosa che nessuno qui sa di te?",
    "Fine del mondo domani — a chi scrivi per primo?",
    "Hai mai amato in silenzio?",
    "Età del tuo primo dolore d'amore?",
    "L'account che stalkeri ma non segui",
    "La bugia che racconti ancora ai tuoi?",
    "Con chi spariresti un weekend adesso?",
    "Cronologia IG: caos o pulita?",
    "Torneresti col tuo ex per 1 giorno?",
    "Il peggior messaggio che hai mandato?",
    "Invisibile per 1 ora — cosa fai?",
    "L'ultimo sogno strano?",
    "Il difetto che non vuoi ammettere",
  ],
  pt: [
    "Por quem você tá afim agora?",
    "Último crush — só as iniciais 👀",
    "A red flag que você ignora mesmo assim 🚩",
    "Confessa: a última mentira que contou?",
    "A vergonha mais foda bêbado/a?",
    "Se pudesse ler 1 DM, de quem?",
    "Stalkeou seu ex esse mês? Fala a real.",
    "Quem do grupo te dá vibes?",
    "Maior ick que viu em alguém?",
    "Sua insegurança mais profunda?",
    "Já deu ghosting em alguém? Por quê?",
    "Descreve a semana em 3 emojis 🫠",
    "O que você pesquisa no Google escondido?",
    "O/a amigo/a que tirava do grupo 👀",
    "Uma fantasia que nunca contou?",
    "Última série que te fez chorar?",
    "Pior date que já teve?",
    "Café, scroll ou drama — sua adicção?",
    "10K€ ou 1 ano de fama?",
    "Algo que ninguém aqui sabe de você?",
    "Fim do mundo amanhã — quem você texta primeiro?",
    "Já amou em silêncio?",
    "Idade do seu primeiro coração partido?",
    "Conta que você stalkeia mas não segue?",
    "Mentira que ainda conta pros seus pais?",
    "Com quem viajaria um fds agora?",
    "Histórico do IG: caótico ou limpo?",
    "Voltaria com o ex por 1 dia?",
    "Pior mensagem que já mandou?",
    "Invisível por 1h — o que faz?",
    "Último sonho estranho?",
    "Defeito seu que não admite?",
  ],
  de: [
    "Auf wen stehst du gerade?",
    "Letzter Crush — nur Initialen 👀",
    "Die Red Flag, die du ignorierst 🚩",
    "Beichte: deine letzte Lüge?",
    "Peinlichste Story betrunken?",
    "Wenn du 1 DM lesen könntest — von wem?",
    "Hast du diesen Monat deinen/deine Ex gestalkt?",
    "Auf wen aus der Gruppe stehst du heimlich?",
    "Größter Ick, den du an jemand hattest?",
    "Deine tiefste Unsicherheit?",
    "Schon mal jemanden geghostet? Warum?",
    "Beschreib die Woche in 3 Emojis 🫠",
    "Was googelst du heimlich?",
    "Der Freund/die Freundin, den/die du raushauen würdest 👀",
    "Eine Fantasie, die du nie erzählst?",
    "Letzte Serie, bei der du geheult hast?",
    "Das schlimmste Date deines Lebens?",
    "Kaffee, Scrollen oder Drama — deine Sucht?",
    "10.000 € oder 1 Jahr Berühmtheit?",
    "Etwas, das hier niemand über dich weiß?",
    "Weltuntergang morgen — wem schreibst du zuerst?",
    "Hast du jemals heimlich geliebt?",
    "In welchem Alter dein erster Liebeskummer?",
    "Account, den du stalkst aber nicht followst?",
    "Lüge, die du deinen Eltern noch erzählst?",
    "Mit wem würdest du sofort wegfahren?",
    "Insta-Suchverlauf: Chaos oder clean?",
    "Würdest du deinen Ex 1 Tag zurücknehmen?",
    "Die schlimmste Nachricht, die du gesendet hast?",
    "1 Stunde unsichtbar — was machst du?",
    "Letzter komischer Traum?",
    "Schwäche, die du nicht zugibst?",
  ],
  ja: [
    "今、誰に夢中？",
    "最後のクラッシュ、イニシャルだけ教えて 👀",
    "気づいてるのに無視してるレッドフラッグ 🚩",
    "正直に言って — 最後についた嘘は？",
    "酔ってやらかした一番恥ずかしい話",
    "1 件だけ DM 見れるなら誰の？",
    "今月、元カレ/元カノをストーキングした？",
    "友達の中で密かに気になってる人は？",
    "誰かにドン引きした瞬間（ick）",
    "一番のコンプレックス",
    "誰かをゴースティングしたことある？理由は？",
    "今週を絵文字 3 つで 🫠",
    "こっそりググってる検索ワード",
    "正直、グループから外したい人 👀",
    "誰にも言えない妄想",
    "最後に泣いたドラマ／映画",
    "人生最悪のデート",
    "コーヒー・スクロール・ドラマ — 君の依存は？",
    "10 万円 or 1 年間の有名人？",
    "ここの誰も知らない君の秘密",
    "明日世界が終わるなら、最初に連絡する人は？",
    "片想いで終わった恋ある？",
    "初めての失恋は何歳？",
    "フォローしてないけど見にいくアカウント",
    "親にまだついてる嘘",
    "今すぐ週末で消えるなら誰と？",
    "Insta の検索履歴：カオス or キレイ？",
    "元カレ/元カノと 1 日だけ戻る？",
    "今までに送った最悪のメッセージ",
    "1 時間透明人間 — 何する？",
    "最近見た変な夢",
    "認めたくない自分の欠点",
  ],
  zh: [
    "你最近偷偷喜欢谁？",
    "最近的 crush — 只说首字母 👀",
    "你假装没看见的红旗 🚩",
    "坦白：你上次撒的谎是什么？",
    "喝醉时最丢人的事",
    "如果能偷看一条 DM，会是谁的？",
    "这个月有没有偷看前任的动态？",
    "朋友圈里偷偷喜欢谁？",
    "对某人最劝退的瞬间（ick）",
    "你最深的不安全感",
    "你 ghost 过谁？为什么？",
    "用 3 个 emoji 形容这周 🫠",
    "你偷偷搜过的关键词",
    "最想从朋友圈踢掉的人 👀",
    "永远不会说的幻想",
    "最近让你哭的剧",
    "你最糟糕的一次约会",
    "咖啡 / 刷手机 / 八卦 — 你的瘾是哪个？",
    "10000 块还是 1 年成名？",
    "这里没人知道的你的秘密",
    "如果明天世界末日，第一个联系谁？",
    "暗恋过谁却没说？",
    "第一次心碎是几岁？",
    "你天天偷看但不关注的账号",
    "你还在对爸妈撒的谎",
    "现在想和谁立刻去过周末？",
    "你的 IG 搜索记录：混乱还是干净？",
    "愿意和前任复合 1 天吗？",
    "你发过最糟的消息",
    "隐形 1 小时，你会去干嘛？",
    "最近做过的怪梦",
    "你不愿承认的小缺点",
  ],
};

export function getAskPrompts(locale: Locale, count = 8): string[] {
  const pool = ASK_PROMPTS[locale] ?? ASK_PROMPTS.en;
  // Shuffle and pick `count` items.
  const arr = [...pool];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count);
}
