// ~250-word personality blurbs per sign, FR + EN.
// Other locales fall back to EN to keep the file size sane (i18n surface stays
// useful: hub & UI labels are fully localised in _strings.ts).

export type PersonalityLocale = "fr" | "en";

const fr: Record<string, string> = {
  belier:
    "Le Bélier est le bélier de tête, premier signe du zodiaque, gouverné par Mars. On reconnaît un Bélier à sa franchise immédiate, sa vitesse de réaction et son envie d'attaquer la vie de front. C'est l'archétype du leader : si personne ne fait rien, le Bélier passe à l'action — quitte à se brûler. Il aime la compétition pour elle-même, déteste l'attentisme et tolère mal qu'on lui dise quoi faire. Côté cœur, c'est intense, direct, parfois maladroit : le Bélier dit ce qu'il pense au moment où il le pense, et préfère un conflit clair à un non-dit. Son énergie est sa force et sa faille — il s'enflamme vite, s'épuise vite, recommence aussitôt. Il a besoin de défis renouvelés, sinon il s'ennuie. En amitié, il est loyal d'un bloc : tu fais partie de sa team, il se bat pour toi sans poser de questions. Sa faiblesse classique : l'impulsivité. Il signe avant de lire, parle avant de réfléchir, démarre avant de planifier. Avec le temps, il apprend la patience (souvent à la dure) et devient un meneur plus stratégique. Le Bélier qui mature ne perd pas son feu — il apprend juste où mettre l'allumette.",
  taureau:
    "Le Taureau est le signe de la terre concrète, ancré et sensuel, gouverné par Vénus. Il aime ce qui se touche : la bonne nourriture, le tissu doux, la maison stable, le compte en banque sûr. On le caricature en gourmand entêté, mais c'est surtout un bâtisseur patient — il construit sa vie pierre par pierre et ne lâche jamais ce qu'il a posé. La sécurité matérielle n'est pas un caprice : c'est sa façon de respirer. En amour, c'est l'un des signes les plus fidèles du zodiaque ; quand il s'engage, c'est pour de vrai. Mais attention à la jalousie sourde et à l'attachement à la routine : le Taureau peut s'endormir dans le confort. Sa qualité maîtresse est la persévérance — là où d'autres abandonnent, lui reste. Sa faille : la résistance au changement, qui peut virer à l'entêtement pur. Quand il finit par bouger, c'est lent mais irréversible. Sensuel, il aime le plaisir sans culpabilité ; jardinage, cuisine, massage, musique — tout ce qui passe par le corps lui parle. Le Taureau heureux est posé, généreux et drôle. Le Taureau bloqué devient possessif et boude pendant des semaines.",
  gemeaux:
    "Les Gémeaux sont le signe de l'esprit en mouvement, gouvernés par Mercure. Leur cerveau tourne en continu, ils ont besoin de nouveauté, d'échanges, de stimulations. On les voit partout, ils connaissent tout le monde, sautent d'un sujet à l'autre sans transition — et c'est leur force : ils traduisent les mondes entre eux. Curieux insatiables, ils lisent, écoutent, posent des questions, recommencent. La double nature du signe se manifeste par une polyvalence rare mais aussi par une difficulté à se poser : un Gémeaux qui s'ennuie devient pénible, pour lui-même comme pour les autres. En amour, c'est le signe le plus flirteur du zodiaque ; ils ont besoin de jeu mental autant que de désir. Un partenaire qui les ennuie n'a aucune chance. Leur faille classique : la dispersion. Ils commencent dix choses, en finissent deux. Émotionnellement, ils intellectualisent — ce qui peut frustrer les signes d'eau qui cherchent du fond. Leur super-pouvoir : la communication. Ils savent vendre une idée, désamorcer une crise, faire rire un public en trois phrases. Le Gémeaux mature apprend à ralentir et à creuser plutôt qu'à survoler.",
  cancer:
    "Le Cancer est le signe de l'eau familière, gouverné par la Lune. C'est le foyer, la mémoire émotionnelle, le besoin de protéger les siens. Sous une carapace parfois dure se cache une sensibilité énorme : le Cancer ressent les ambiances avant qu'elles n'aient été dites. Cuisine, photos, anniversaires, traditions — il tient la mémoire de la tribu. Loyal jusqu'à l'obsession quand il aime, il peut devenir possessif ou s'enfermer dans la rancune s'il se sent trahi. Sa principale qualité est l'empathie : peu de signes savent aussi bien réconforter, écouter, deviner ce dont on a besoin sans qu'on l'ait demandé. Sa faille : les sautes d'humeur lunaires et la tendance à se replier dans sa coquille au moindre coup. En amour, c'est tout ou rien — il veut un nid, pas une aventure. Côté carrière, on le retrouve souvent dans les métiers de soin, d'éducation, d'art, ou partout où l'on construit dans la durée. Le Cancer mature apprend à protéger sans étouffer, à ouvrir la coquille sans s'oublier. Sa nostalgie est belle quand elle nourrit le présent, toxique quand elle bloque l'avenir.",
  lion:
    "Le Lion est le soleil du zodiaque, gouverné par l'astre solaire lui-même. Il rayonne, il prend de la place, il aime être vu — pas par vanité mais parce qu'il sent qu'il a quelque chose à donner. Né pour mener, créer, performer, il préfère mille fois échouer en grand qu'être moyen en silence. Sa générosité est légendaire : un Lion qui t'a adopté te défendra contre la terre entière. Mais l'ego est le terrain de jeu et le terrain miné du Lion : il a besoin de reconnaissance comme d'oxygène, et la critique sèche le blesse profondément même s'il n'en montre rien. En amour, il aime grand, romanesque, théâtral ; il veut être ton héros et il veut que tu le saches. La fidélité est centrale chez lui — la trahison est impardonnable. Sa faille : l'orgueil et le besoin d'avoir raison. Il peut devenir tyrannique si personne ne lui dit non. Sa qualité maîtresse : le courage. Un Lion sait prendre des risques que d'autres trouvent absurdes. Côté création, c'est souvent un artiste, un entrepreneur, un meneur de scène. Le Lion mature apprend à briller sans écraser, à régner sans dominer.",
  vierge:
    "La Vierge est le signe de l'analyse fine, gouvernée par Mercure dans sa version terre. Là où le Gémeaux disperse, la Vierge ordonne. Elle observe, classe, optimise, corrige. Son cerveau voit le détail que personne d'autre n'a vu — la fissure, l'incohérence, l'erreur dans la facture. C'est précieux et c'est fatigant : pour elle comme pour son entourage. Profondément serviable, la Vierge a besoin d'être utile ; elle se sent vivante quand elle résout, range, soigne. Côté cœur, elle est plus pudique que froide : derrière l'allure réservée, il y a une loyauté énorme et un romantisme discret. Elle exprime l'amour par les actes — un service rendu, une attention pratique, un détail mémorisé. Sa faille classique : l'autocritique. La Vierge se juge avant que les autres ne l'aient fait, ce qui la pousse à exceller mais aussi à se torturer. Le perfectionnisme peut paralyser. Sa qualité maîtresse : la fiabilité. Quand une Vierge dit qu'elle le fait, c'est fait, bien fait, à l'heure. Côté santé, elle est souvent obsédée par le corps, l'hygiène, l'alimentation. La Vierge mature apprend à laisser des choses imparfaites et à recevoir autant qu'elle donne.",
  balance:
    "La Balance est le signe de l'harmonie, gouvernée par Vénus dans sa version air. Elle pèse, compare, cherche l'équilibre — entre les gens, dans une déco, dans une décision. Sa sensibilité au beau est haute : esthétique, vêtements, lieux choisis, manières. On la trouve souvent là où il faut négocier, médier, marier des contraires. C'est le diplomate du zodiaque. En amour, elle déteste être seule et place le couple très haut ; elle est attentive, charmante, soucieuse de plaire — parfois jusqu'à oublier ce qu'elle veut vraiment. Sa faille classique : l'indécision. À force de voir tous les côtés, elle peut rester figée pendant des semaines sur un choix. Sa peur du conflit la pousse à arrondir les angles, parfois au prix de sa propre vérité. Sa qualité maîtresse : l'art de la relation. Personne ne sait comme elle réunir des gens et désamorcer une tension. Côté carrière, on la retrouve dans le droit, le design, la mode, les RH. La Balance mature apprend à choisir même quand le choix est inconfortable, et à dire non sans culpabilité. Quand elle s'aligne sur sa vraie voix, elle devient redoutablement claire — la grâce d'un signe d'air avec la solidité d'une décision assumée.",
  scorpion:
    "Le Scorpion est le signe de l'intensité, gouverné par Pluton. Tout est extrême chez lui : l'amour, la haine, la loyauté, le silence. Il ne fait pas dans la demi-mesure et il sent immédiatement ceux qui en font. Son regard pénètre, sa présence pèse, son intuition lit ce qu'on ne dit pas. C'est le détective émotionnel du zodiaque — rien ne lui échappe, surtout pas l'hypocrisie. En amour, il est fusionnel, possessif, total ; il veut savoir, comprendre, posséder. Quand il aime, c'est pour toujours ou jamais. La trahison est un point de non-retour : le Scorpion pardonne rarement, oublie jamais. Sa faille classique : la jalousie et le besoin de contrôle. Il peut s'enfermer dans la rumination ou la vengeance silencieuse. Sa qualité maîtresse : la transformation. Aucun signe ne sait comme lui mourir à lui-même et renaître — il traverse les crises là où d'autres sombrent. Côté carrière, on le retrouve dans la psychologie, l'enquête, la chirurgie, la finance, tout ce qui demande de fouiller le fond. Le Scorpion mature apprend à canaliser son intensité sans la retourner contre les autres ni contre lui, et à faire confiance malgré la blessure.",
  sagittaire:
    "Le Sagittaire est le signe de l'horizon, gouverné par Jupiter. Il a besoin d'espace, de voyage, d'idées larges, de sens. Optimiste structurel, il croit qu'il y a toujours une issue, toujours mieux à voir derrière la prochaine colline. C'est l'aventurier du zodiaque : géographique (il bouge tout le temps) ou philosophique (il lit, débat, cherche du sens). En amour, il aime la liberté autant que le partenaire ; il veut quelqu'un qui marche à côté, pas qui s'accroche. Franc-parler garanti — il dit la vérité même quand elle blesse, par respect pas par méchanceté. Sa faille classique : l'imprudence et la difficulté à finir ce qu'il commence. Il s'enthousiasme, démarre, puis voit un autre horizon plus brillant. Émotionnellement, il peut paraître insensible parce qu'il fuit la lourdeur. Sa qualité maîtresse : l'élan. Un Sagittaire qui croit à un projet entraîne tout le monde derrière lui — son énergie est contagieuse. Côté carrière, on le retrouve dans l'enseignement, le journalisme, le voyage, l'édition, le sport. Le Sagittaire mature apprend à se poser, à finir, à mesurer l'impact de sa franchise sur les autres. Quand il combine vision large et présence concrète, il devient un mentor naturel.",
  capricorne:
    "Le Capricorne est le signe de la structure, gouverné par Saturne. Sérieux, discipliné, patient, il construit sa vie comme on bâtit une cathédrale — pour qu'elle tienne mille ans. L'ambition n'est pas un gros mot pour lui : c'est l'organisation naturelle de son énergie. Il vise haut, encaisse, recommence, monte. Sous l'allure froide se cache souvent un humour sec très efficace et une loyauté de fond. En amour, il est lent à s'engager mais total quand il y va ; il déteste les démonstrations bruyantes et préfère prouver par les actes. La famille et la stabilité comptent énormément. Sa faille classique : le pessimisme et la difficulté à profiter du présent. Il peut tellement se projeter qu'il oublie de vivre maintenant. Le travail peut devenir une fuite. Sa qualité maîtresse : la résilience. Là où d'autres craquent, le Capricorne tient et finit par arriver. Côté carrière, on le retrouve au sommet — direction, finance, droit, immobilier, tout ce qui demande du long terme et du nerf. Le Capricorne mature apprend à se détendre, à célébrer ses victoires, à accepter l'imperfection et la spontanéité. Quand il s'autorise la légèreté, il devient un pilier rare : sérieux et chaleureux à la fois.",
  verseau:
    "Le Verseau est le signe du futur, gouverné par Uranus. Il pense autrement, voit autrement, refuse autrement. C'est l'inventeur, le rebelle, l'humanitaire, celui qui regarde le système avec une distance étonnée et propose autre chose. Indépendant jusqu'à l'os, il déteste qu'on lui dise quoi faire et qu'on lui demande de rentrer dans une case. En amour, il est ami avant d'être amant — la complicité mentale prime sur la passion brûlante. Il a besoin d'espace et donne le même en retour ; les partenaires qui cherchent du fusionnel se cassent les dents. Sa faille classique : le détachement émotionnel. Il peut intellectualiser ce qu'il devrait ressentir et passer pour froid alors qu'il pense au monde entier. Sa qualité maîtresse : la vision. Un Verseau voit cinq ans avant les autres ce qui va se passer ; ses idées paraissent étranges puis évidentes. Côté carrière, on le retrouve dans la tech, la science, l'art expérimental, l'activisme. Le Verseau mature apprend à descendre dans le corps, à se laisser toucher, à accepter qu'aimer une personne en particulier n'est pas trahir l'humanité en général. Sa singularité est sa contribution.",
  poissons:
    "Les Poissons sont le signe de la fusion, gouvernés par Neptune. C'est le dernier signe du zodiaque, là où les frontières du moi s'effacent — empathie radicale, intuition océanique, sensibilité à tout. Un Poissons ressent ce qui flotte dans une pièce avant que quiconque ait parlé. Artiste, mystique, soignant naturel, il vit beaucoup à l'intérieur et a besoin de temps de solitude pour ne pas se noyer dans les autres. En amour, c'est le grand romantique : il aime fort, idéalise, donne tout. La déception est dévastatrice quand la personne ne tient pas l'image. Sa faille classique : la fuite. Quand la réalité pèse trop, le Poissons s'évade — dans le rêve, l'art, parfois dans des comportements moins sains. Il peut aussi s'oublier dans la relation à l'autre et perdre ses propres contours. Sa qualité maîtresse : la compassion. Personne ne sait comme lui rejoindre quelqu'un dans sa douleur sans la juger. Côté carrière, on le retrouve dans les arts, le soin, le spirituel, la musique, le cinéma. Le Poissons mature apprend à poser des limites tout en gardant la porte ouverte, à transformer sa sensibilité en œuvre plutôt qu'en absorption. Sa magie est réelle quand elle est ancrée.",
};

const en: Record<string, string> = {
  belier:
    "Aries is the headbutting ram, the first sign of the zodiac, ruled by Mars. You recognize an Aries by their immediate frankness, fast reactions, and appetite for charging at life head-on. They are the leader archetype: if no one acts, the Aries goes — even if they burn themselves doing it. They love competition for its own sake, hate waiting, and tolerate being told what to do poorly. In love they are intense, direct, sometimes clumsy: an Aries says what they think the moment they think it, and prefers an open conflict to silence. Their energy is both strength and flaw — they ignite fast, burn out fast, restart immediately. They need fresh challenges or they get bored. In friendship they are blockily loyal: you're on their team, they fight for you, no questions asked. Classic weak spot: impulsivity. They sign before reading, talk before thinking, start before planning. With time they learn patience (often the hard way) and become more strategic leaders. A mature Aries doesn't lose their fire — they just learn where to strike the match.",
  taureau:
    "Taurus is the grounded earth sign, sensual and steady, ruled by Venus. They love what can be touched: good food, soft fabric, a stable home, a healthy bank account. The cliché paints them as stubborn gourmands, but they are above all patient builders — they construct their life brick by brick and never let go of what they've placed. Material security isn't a whim, it's how they breathe. In love, Taurus is one of the most loyal signs in the zodiac; when they commit, it's the real thing. Watch for slow-burning jealousy and a deep attachment to routine: a Taurus can fall asleep inside their comfort zone. Master quality: perseverance — where others quit, Taurus stays. Weak spot: resistance to change that can curdle into pure stubbornness. When they do finally move, it's slow but irreversible. They love pleasure without guilt; gardening, cooking, massage, music — anything that moves through the body speaks to them. A happy Taurus is grounded, generous and funny. A blocked Taurus turns possessive and sulks for weeks.",
  gemeaux:
    "Gemini is the sign of the moving mind, ruled by Mercury. Their brain runs nonstop — they need novelty, exchange, stimulation. They are everywhere, know everyone, jump from topic to topic with no warning, and that's their gift: they translate worlds to each other. Insatiable curiosity drives them to read, listen, ask questions, repeat. The sign's dual nature shows up as remarkable versatility but also as trouble settling: a bored Gemini becomes unbearable, to themselves and others. In love, they are the flirtiest sign of the zodiac; they need mental play as much as desire. A partner who bores them stands no chance. Classic weakness: scatter. They start ten things, finish two. Emotionally, they intellectualize — which can frustrate water signs looking for depth. Their superpower is communication. They sell an idea, defuse a crisis, make a room laugh in three sentences. A mature Gemini learns to slow down and go deep instead of skimming the surface.",
  cancer:
    "Cancer is the sign of familiar water, ruled by the Moon. Home, emotional memory, the urge to protect their people. Under the sometimes hard shell lives a huge sensitivity: Cancer feels the mood in a room before anyone has spoken. Cooking, photos, birthdays, traditions — they hold the tribe's memory. Loyal to the point of obsession when they love, they can also turn possessive or lock themselves in resentment if they feel betrayed. Their main quality is empathy: few signs comfort, listen, and intuit what you need without being asked the way Cancer does. Weak spot: lunar mood swings and the tendency to retreat into the shell at the first blow. In love it's all or nothing — they want a nest, not an adventure. Career-wise you'll find them in caring, teaching, art, or anywhere built over the long haul. A mature Cancer learns to protect without smothering, to open the shell without losing themselves. Their nostalgia is beautiful when it feeds the present, toxic when it blocks the future.",
  lion:
    "Leo is the zodiac's sun, ruled by the solar body itself. They radiate, take up space, love being seen — not from vanity but because they sense they have something to give. Born to lead, create, perform, they will fail big a thousand times before they will be quietly mediocre. Their generosity is legendary: a Leo who adopts you will defend you against the world. But ego is both playground and minefield — they need recognition like oxygen, and dry criticism wounds them deeply even if they hide it. In love they aim big, romantic, theatrical; they want to be your hero and they want you to know it. Loyalty is central — betrayal is unforgivable. Weak spot: pride and the need to be right. They can become tyrannical if no one ever tells them no. Master quality: courage. A Leo takes risks others call absurd. Creatively they're often artists, founders, stage leaders. A mature Leo learns to shine without crushing, to rule without dominating.",
  vierge:
    "Virgo is the sign of fine analysis, ruled by Mercury in its earth aspect. Where Gemini scatters, Virgo orders. They observe, classify, optimize, correct. Their brain spots the detail no one else saw — the crack, the inconsistency, the typo on the invoice. That's precious and exhausting, for them and for everyone around them. Deeply helpful, Virgo needs to be useful; they feel alive when they solve, tidy, repair. In love they are more shy than cold: behind the reserved look sits huge loyalty and quiet romanticism. They show love through acts — a service rendered, a practical attention, a remembered detail. Classic weakness: self-criticism. Virgo judges themselves before others have, which pushes them to excellence but also to self-torture. Perfectionism can paralyze. Master quality: reliability. When a Virgo says they'll do it, it's done, well, on time. Health-wise they're often focused on the body, hygiene, diet. A mature Virgo learns to leave things imperfect and to receive as much as they give.",
  balance:
    "Libra is the sign of harmony, ruled by Venus in its air aspect. They weigh, compare, look for balance — between people, in a room's décor, in a decision. Their sensitivity to beauty runs high: aesthetics, clothing, well-chosen places, manners. You find them wherever negotiation, mediation, or pairing of opposites is required. The zodiac's diplomat. In love, they hate being alone and place the couple very high; they are attentive, charming, eager to please — sometimes to the point of forgetting what they actually want. Classic weakness: indecision. From seeing every side they can stay frozen for weeks over a choice. Fear of conflict pushes them to smooth the edges, sometimes at the cost of their own truth. Master quality: relational art. No one brings people together and defuses tension like Libra. Career-wise you'll find them in law, design, fashion, HR. A mature Libra learns to choose even when uncomfortable, and to say no without guilt. Aligned with their real voice, they become formidably clear — air grace with the solidity of a decision owned.",
  scorpion:
    "Scorpio is the sign of intensity, ruled by Pluto. Everything is extreme with them: love, hate, loyalty, silence. They don't do half-measures and immediately sense those who do. Their gaze penetrates, their presence weighs, their intuition reads what isn't said. The zodiac's emotional detective — nothing escapes them, especially hypocrisy. In love they are fusional, possessive, total; they want to know, understand, possess. When they love, it's forever or never. Betrayal is a point of no return: Scorpio rarely forgives, never forgets. Classic weakness: jealousy and the need for control. They can lock themselves in rumination or silent revenge. Master quality: transformation. No sign dies to themselves and is reborn the way Scorpio does — they cross crises where others drown. Career-wise you'll find them in psychology, investigation, surgery, finance — anything requiring depth. A mature Scorpio learns to channel intensity without turning it on others or themselves, and to trust again despite the wound.",
  sagittaire:
    "Sagittarius is the sign of the horizon, ruled by Jupiter. They need space, travel, big ideas, meaning. Structurally optimistic, they believe there's always a way out, always something better beyond the next hill. The zodiac's adventurer: geographical (always moving) or philosophical (reading, debating, hunting meaning). In love they love freedom as much as the partner; they want someone walking beside them, not clinging. Bluntness guaranteed — they tell the truth even when it hurts, out of respect not malice. Classic weakness: recklessness and trouble finishing what they start. They get excited, begin, then see another brighter horizon. Emotionally they can seem insensitive because they flee heaviness. Master quality: momentum. A Sagittarius believing in a project drags everyone behind them — their energy is contagious. Career-wise they're in teaching, journalism, travel, publishing, sport. A mature Sagittarius learns to settle, finish, and measure the impact of their frankness on others. Combining wide vision with concrete presence, they become a natural mentor.",
  capricorne:
    "Capricorn is the sign of structure, ruled by Saturn. Serious, disciplined, patient, they build their life like a cathedral — to last a thousand years. Ambition isn't a dirty word for them: it's the natural organization of their energy. They aim high, take the hits, restart, climb. Under the cool exterior often lies a very effective dry humor and deep loyalty. In love they are slow to commit but total once they do; they hate loud demonstrations and prove themselves through acts. Family and stability matter enormously. Classic weakness: pessimism and trouble enjoying the present. They project so far ahead they forget to live now. Work can become an escape. Master quality: resilience. Where others crack, Capricorn holds and eventually arrives. Career-wise you'll find them at the top — leadership, finance, law, real estate, anything requiring long horizons and nerve. A mature Capricorn learns to relax, celebrate wins, accept imperfection and spontaneity. When they allow lightness in, they become a rare pillar: serious and warm at once.",
  verseau:
    "Aquarius is the sign of the future, ruled by Uranus. They think differently, see differently, refuse differently. The inventor, the rebel, the humanitarian — the one who looks at the system with surprised distance and proposes something else. Independent to the bone, they hate being told what to do or asked to fit a box. In love they're a friend before a lover — mental complicity trumps burning passion. They need space and give the same in return; partners chasing fusion break their teeth. Classic weakness: emotional detachment. They can intellectualize what they should feel and read as cold while caring about the whole world. Master quality: vision. An Aquarius sees five years before others what's coming; their ideas seem strange then obvious. Career-wise you'll find them in tech, science, experimental art, activism. A mature Aquarius learns to descend into the body, let themselves be moved, accept that loving one person specifically isn't betraying humanity in general. Their singularity is their contribution.",
  poissons:
    "Pisces is the sign of fusion, ruled by Neptune. The last sign of the zodiac, where the borders of self dissolve — radical empathy, oceanic intuition, sensitivity to everything. A Pisces feels what's floating in a room before anyone has spoken. Artist, mystic, natural caregiver, they live a lot inside and need solitude not to drown in others. In love they are the grand romantic: they love hard, idealize, give everything. Disappointment is devastating when the person doesn't hold the image. Classic weakness: escape. When reality weighs too much, Pisces evades — into dream, art, sometimes less healthy patterns. They can also lose themselves in the relationship and forget their own outline. Master quality: compassion. No one meets someone in their pain without judging the way Pisces does. Career-wise you'll find them in the arts, care, the spiritual, music, film. A mature Pisces learns to set boundaries while keeping the door open, to turn sensitivity into work rather than absorption. Their magic is real when it's anchored.",
};

export function getPersonality(slug: string, locale: string): string {
  const dict = locale === "fr" ? fr : en;
  return dict[slug] ?? "";
}
